[Feature] Prettify Json When Saving Response To File
getinsomnia/insomnia pull request #1829
Opened 2019-12-06 13:03 UTC by elemanhillary

Closes [#764](https://github.com/getinsomnia/insomnia/issues/764)

2019-12-11 17:35 UTC, gschier requested changes
Hey @elemanhillary, thanks for taking a crack at this! I've left quite a few comments here so let me know if you have any questions.

I also think we should present an additional dropdown button to save "prettified" response because saving the original un-prettified response is still something that should be possible.

2019-12-11 17:35 UTC, gschier commented on packages/insomnia-app/app/ui/components/response-pane.js
> +        readStream.on('data', data => {
You'll need to handle the case where the `data` event is called multiple times.

2019-12-11 17:35 UTC, gschier commented on packages/insomnia-app/app/ui/components/response-pane.js
> +          const data_ = data.toString();
We should avoid converting to a string unless we know it's JSON (can inspect the `Content-Type` header)

2019-12-11 17:35 UTC, gschier commented on packages/insomnia-app/app/ui/components/response-pane.js
> +          const readStreamContents = JSON.stringify(JSON.parse(data_), null, 2);
We should handle the error here when `parse` fails on invalid JSON.

We should also use Insomnia's custom JSON formatter, which is more flexible than the built-in and preserves more of the original data. You can find examples in the repo if you search for `'insomnia-prettify'`

2019-12-11 17:35 UTC, gschier commented on packages/insomnia-app/app/ui/components/response-pane.js
> +            console.warn('Failed to save response body', err);
Should use the `showError()` helper to show the error to the user.

2019-12-12 07:41 UTC, elemanhillary commented on packages/insomnia-app/app/ui/components/response-pane.js
> +        readStream.on('data', data => {
on it

2019-12-12 07:41 UTC, elemanhillary commented on packages/insomnia-app/app/ui/components/response-pane.js
> +          const data_ = data.toString();
on it

2019-12-12 07:41 UTC, elemanhillary commented on packages/insomnia-app/app/ui/components/response-pane.js
> +          const readStreamContents = JSON.stringify(JSON.parse(data_), null, 2);
on it

2019-12-12 07:41 UTC, elemanhillary commented on packages/insomnia-app/app/ui/components/response-pane.js
> +            console.warn('Failed to save response body', err);
on it

2019-12-12 16:53 UTC, gschier requested changes
Just a couple more comments 🙂

2019-12-12 16:53 UTC, gschier commented on packages/insomnia-app/app/ui/components/response-pane.js
> +      let responseBody = '';
Since this is a string, your logic will force `data` to be converted from a Buffer a string. For binary data, we need to ensure that it remains a Buffer if it's not a string content-type (eg. PDF document, Image, or mp3).

There's some other code that does this over here that can be referenced: https://github.com/Kong/insomnia/blob/c03c52ef90c641143994d03bc2b5a97d67d86c6f/packages/insomnia-app/app/ui/components/viewers/response-multipart.js#L177-L180

2019-12-12 16:53 UTC, gschier commented on packages/insomnia-app/app/ui/components/response-pane.js
> +          to.write(prettify.json(responseBody));
Nice! I think the only thing left to do here is add a check to see if the content type is actually JSON.

There is a `contentType` variable defined above that can be used to see if it contains the substring `json`. If it is not JSON, we should leave it unprocessed.

2019-12-12 17:16 UTC, elemanhillary commented on packages/insomnia-app/app/ui/components/response-pane.js
> +          to.write(prettify.json(responseBody));
i don't know how i forgot that but let me work on it, it's  that i get to work on insomnia when am over worked at my work place

2019-12-12 17:55 UTC, gschier commented on packages/insomnia-app/app/ui/components/response-pane.js
> +          to.write(prettify.json(responseBody));
No rush @elemanhillary, we're just grateful you're contributing 😄 

Also, we're happy to help finish this one if you don't have the time 🤗

2019-12-12 17:57 UTC, gschier approved these changes
Nice, thanks for making those changes so quickly ❤️

2019-12-12 17:57 UTC, merged

2024-01-16 22:23 UTC, robross0606 commented
This should be an option and not done by default.  Saving the response with whitespace can increase the file size considerably.