[Feature] Toggle URL Click Throughs
getinsomnia/insomnia pull request #1845
Opened 2019-12-12 14:51 UTC by elemanhillary

Closes [#1817](https://github.com/Kong/insomnia/issues/1817)

2019-12-12 17:04 UTC, gschier requested changes
Left an initial rounds of comments. Nothing too major except the note about storing the setting in the Settings model instead of React state.

Thanks for taking care of this one! 🤗

2019-12-12 17:04 UTC, gschier commented on packages/insomnia-app/app/ui/components/response-pane.js
> +  disable: boolean,
What do you think about making this setting global to the application instead of local to the response? Having it stored in the React state will not persist across application loads. 

I suggest adding a `disableResponseLinkHandling` property to the `Settings` model and storing it there.

2019-12-12 17:04 UTC, gschier commented on packages/insomnia-app/app/ui/components/response-pane.js
> +          });
Should this be removed? It looks like there changes are from your other PR.

2019-12-12 17:04 UTC, gschier commented on packages/insomnia-app/app/ui/components/response-pane.js
> +    this.setState(prevState => ({
Nice React work here!

2019-12-12 17:04 UTC, gschier commented on packages/insomnia-app/app/ui/components/viewers/response-viewer.js
> +    console.log('URLCLCIC', this.props.urlClickable);
Debug console logs should be removed.

2019-12-12 17:04 UTC, gschier commented on packages/insomnia-app/app/ui/components/viewers/response-viewer.js
> +          urlClickable={urlClickable}
As mentioned above, the `urlClickable` property is not necessary. Links can be done by doing the following instead:

```
onClickLink={urlClickable ? this._handleOpenLink : null}
```

2019-12-17 19:22 UTC, gschier requested changes
Just a few minor comments left. Getting close! 🚀🌟

2019-12-17 19:22 UTC, gschier commented on packages/insomnia-app/app/ui/components/dropdowns/preview-mode-dropdown.js
> +PreviewModeDropdown.propTypes = {
This isn't needed here since this component uses Flow to define it's props at the top of this file.

Sorry for the confusion. Flow was introduced to Insomnia quite far into it's development so many things still use `propTypes` but all the new stuff has migrated to Flow.

2019-12-17 19:22 UTC, gschier commented on packages/insomnia-app/app/models/settings.js
> +    enableUrlClickThrough: false,
Can we change this to be `disableResponsePreviewLink` and default it to `false`? It's usually good to ensure that the default and `undefined` map to the same value.

2019-12-17 19:22 UTC, gschier commented on packages/insomnia-app/app/ui/components/settings/general.js
> +            {this.renderBooleanSetting('Enable URL click through', 'enableUrlClickThrough', '')}
Same here. Can we update the description to read "Disable Response Preview Links"?

2019-12-17 19:22 UTC, gschier commented on packages/insomnia-app/app/ui/components/wrapper.js
> +            settings={settings}
Since the other props here pull values out of settings, can we do the same here and instead pass a `disableResponsePreviewLinks` property to the component?

It makes sense what you did but it's better to be consistent 🙂

2019-12-23 07:05 UTC, elemanhillary commented on packages/insomnia-app/app/models/settings.js
> +    enableUrlClickThrough: false,
which default are we talking about here @gschier

2019-12-23 07:23 UTC, elemanhillary commented on packages/insomnia-app/app/ui/components/dropdowns/preview-mode-dropdown.js
> +PreviewModeDropdown.propTypes = {
i dont see flow's defined props in that file.

2020-01-07 16:03 UTC, gschier approved these changes
Thanks @elemanhillary!

2020-01-07 16:03 UTC, merged

2020-02-06 03:51 UTC, BadPackets commented
Is this available in the current production version of insomnia (7.0.6)?