Enable and disable plugins!
getinsomnia/insomnia pull request #1855
Opened 2019-12-15 10:49 UTC by develohpanda

Closes #1610.

Added the ability to configure a plugin. The only configuration at the moment is to disable, but more can be added in the future. Plugins are installed as enabled by default.

![](http://g.recordit.co/664Dyl0ula.gif)

I figured there would be fewer changes if I update the config settings and reload plugins using existing logic, instead of writing logic to unsubscribe a plugin.

I decided to use a toggle (using [react-switch](https://www.npmjs.com/package/react-switch) instead of checkbox for the UI because a toggle feels more intuitive here. Let me know if you have any suggestions for this!

Changing the state of a plugin involves reloading the plugins (to bind with the app). This means the `onChange` callback is async, and the UI waits for the logic to execute before visually showing the change, causing a ~1 sec UI delay. To overcome this, I extracted a stateful `ToggleSwitch` component which receives the `checked` prop (populated via settings) but also maintains a local `checked` state. The state drives the UI, while an effect runs to ensure the state and prop is kept in sync in case they fall out of sync.

Because changing the toggle triggers a plugin reload, and the current reload button disables while reloading, the toggles follow the same behavior. All toggles will disable when changed until the logic has executed. Champion mouse clickers will only be able to toggle one plugin at a time, no matter how fast they click. 😄 

![image](https://user-images.githubusercontent.com/4312346/70861467-5da57700-1f93-11ea-9624-cdc7dfe1803d.png)

Question: I can't quite figure out how Storybook generates prop types. Had a look at some of the other examples (like `Notice`) but am not sure.

2019-12-15 12:07 UTC, develohpanda commented
@gschier hmmm I've got an error with `React.FC` or `React.FunctionComponent` not being found in the react flow types. Where are these types defined? 😢 

![image](https://user-images.githubusercontent.com/4312346/70862377-6fd9e200-1fa0-11ea-82b4-16d8f9cf5be0.png)

2019-12-17 07:23 UTC, nijikokun commented
From a product perspective, this is looking great, amazing work so far 🎉

2019-12-17 21:16 UTC, gschier commented
> Hey @gschier, hmmm I've got an error with `React.FC` or `React.FunctionComponent` not being found in the react flow types. Where are these types defined? 😢
> 
> ![image](https://user-images.githubusercontent.com/4312346/70862377-6fd9e200-1fa0-11ea-82b4-16d8f9cf5be0.png)

You may have to add a definition in the `flow-typed` folder

2019-12-17 21:19 UTC, gschier commented
On second thought. It might be worth converting that to a Class component. Insomnia doesn't currently have any Hooks related stuff so I propose that we favor consistency over niceness in this case. 

Perhaps we can have a talk later about whether or not introducing Hooks is a good idea and how we could go about it.

2019-12-19 10:01 UTC, develohpanda commented
> Insomnia doesn't currently have any Hooks-related stuff in the codebase and I think it makes sense to favor consistency for now.

Yep agreed, that makes sense. All ready to review now. 😄

I tried to type `react-switch` in `flow-typed` folder, similar to how `react-tabs` is typed, but when consuming in `toggle-switch.js` I kept facing tricky errors like the following. 

> Either  `React.Element` [2] is incompatible with  `React.Portal` [3]. Or property `@@iterator` is missing in  `React.Element` [2] but exists in  `$Iterable

2019-12-20 20:27 UTC, gschier approved these changes
Great execution on this one @develohpanda 😀

2019-12-20 20:27 UTC, gschier commented on packages/insomnia-app/package.json
> +    "react-switch",
Nice! Glad you figured this one out 😄

2019-12-20 20:27 UTC, gschier commented on packages/insomnia-app/app/plugins/index.js
> +  const config: PluginConfig = allConfigs.hasOwnProperty(name)
Nice, I was wondering where you'd chose to setup the default config and this is a great choice.

2019-12-20 20:27 UTC, gschier commented on packages/insomnia-app/app/ui/components/settings/toggle-switch.js
> +    if (this._mounted) {
Was it necessary to have this check here? I know it's in a couple places throughout the codebase but only as a last resort hack.

2019-12-20 20:27 UTC, gschier commented on packages/insomnia-app/app/ui/components/settings/toggle-switch.stories.js
> +import React from 'react';
Thanks for adding this! I was confused at first because I forgot Storybook was part of this project now 😆

2019-12-20 20:27 UTC, gschier commented on packages/insomnia-app/app/ui/css/layout/base.less
> +  &.table--valign-middle td,
Just checking, should this be:

```css
&.table--valign-middle td,
&.table--valign-middle th {
  ...
```

Could also simplify it with nesting:

```css
&.table--valign-middle {
  td, th {
    ...
```

2019-12-20 20:57 UTC, gschier requested changes
Woops, accidentally approved this PR before without realizing I had some comments worth addressing.

2019-12-21 00:43 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/toggle-switch.stories.js
> +import React from 'react';
Storybook is great, I've used it a lot over the past year and was happy to see it added here 💯

OT but we could use [Zeit](https://zeit.co) to host it, as a dev resource that is always available. Useful for component libraries and not crucial for Insomnia but it would be nice!

2019-12-21 00:54 UTC, develohpanda commented on packages/insomnia-app/app/ui/css/layout/base.less
> +  &.table--valign-middle td,
Oh you're right, nice find! 😄 Still getting familiar with CSS selectors

2019-12-21 01:15 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/toggle-switch.js
> +    if (this._mounted) {
I tested a potential edge case to try and produce a memory leak error in console to no avail (which is great!), so I have removed this functionality 😄

2020-01-23 18:25 UTC, gschier submitted a review, later dismissed
Nice work @develohpanda! So excited to get this merged

2020-01-23 18:43 UTC, merged