allow checkboxes input fields in prompt dialog
getinsomnia/insomnia pull request #1980
Opened 2020-03-03 22:20 UTC by superruzafa

This PR allows the Prompt modal dialog to show `<input type="checkbox">` elements.

You only have to call it by setting `inputType` to `checkbox`. You can also set `defaultValue` to `false`/`true` to uncheck/check the checkbox, respectively.

The modal return value will be `true` if the the checkbox was checked and `false` otherwise.

![imagen](https://user-images.githubusercontent.com/231822/75825283-5416f880-5da5-11ea-8c22-34c86f2e7728.png).

2020-03-11 23:21 UTC, develohpanda requested changes
Hi @superruzafa! Thanks for putting up this PR; LGTM! Just one suggestion regarding spacing, and then good to go!

In the future it would be nice to update the `onComplete` callback to accept the true type (`boolean`, `integer`, `string`), but this is good for now. 😃

2020-03-11 23:21 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/prompt-modal.js
> +      );
There are existing checkbox inputs with labels, inside the preferences modal (for example), and it would be awesome to implement this checkbox in a similar fashion to have consistent styling.

<img width="323" alt="image" src="https://user-images.githubusercontent.com/4312346/76472796-ceea9f80-63b3-11ea-8929-838a5bcef305.png">

Code snippet:
https://github.com/Kong/insomnia/blob/327eb5b692afd14e9d499691a4aa8da7f4ebc3d7/packages/insomnia-app/app/ui/components/settings/general.js#L118-L129

2020-03-12 08:36 UTC, superruzafa reviewed
That's exactly what I was looking for :)

2020-03-12 08:36 UTC, superruzafa commented on packages/insomnia-app/app/ui/css/components/forms.less
> +
I'm not a CSS expert.
This could be improved as I observed some baseline misalignment.

2020-03-12 20:27 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/prompt-modal.js
> +      );
Looks good now! 🙌 

I see there's some duplication in the logic here and it would be nice to compress that down a bit.

I see the main difference is with the `className` attribute. If you're familiar with the `classnames` package, one way to do so would be to provide an object parameter where the key is your `className` and the value is a boolean.

Here's an example, would you like to give it a go? ⭐️ 

https://github.com/Kong/insomnia/blob/327eb5b692afd14e9d499691a4aa8da7f4ebc3d7/packages/insomnia-app/app/ui/components/base/dropdown/dropdown-divider.js#L9-L14

2020-03-12 23:11 UTC, superruzafa commented on packages/insomnia-app/app/ui/components/modals/prompt-modal.js
> +      );
Done!

2020-03-12 23:25 UTC, develohpanda approved these changes
Nice one, thanks! 🎉

![](https://media1.giphy.com/media/kiBcwEXegBTACmVOnE/giphy-downsized-medium.gif)

2020-03-12 23:26 UTC, merged