Expose form request body for plugins
getinsomnia/insomnia pull request #2003
Opened 2020-03-18 05:34 UTC by yittg

Support add/set/get the form parameters of the reuqest body, and get/set
the content type of the request.

Noting that file form item adding will be ignored if the mime type is
not multipath form.

Closes #423

2020-03-20 07:52 UTC, yittg commented
cc @gschier

2020-03-23 15:56 UTC, lucashyper commented
Would it be possible to also expose `renderedRequest.body.fileName` in this PR, maybe with `getBodyFileName` and `setBodyFileName`. 
Together with `setMimeType`, plugins will then be able to send files.

2020-03-24 08:18 UTC, yittg commented
@lucashyper 😄 Actually, i missed it. This change should implement them.

2020-04-02 06:36 UTC, yittg commented
@gschier @develohpanda hi, PTAL or help to mention the right people, thanks.

2020-04-02 09:15 UTC, develohpanda requested changes
Hey @yittg! Sorry for the delay, thanks for putting this PR up. Awesome to see that you came back to build a feature, that _you_ requested in the early days! 🔥 

Overall, the code looks good to me. 😄 I've added a couple of comments to your use of conditionals that I feel are worth addressing.

An observation: For clarity and maintainability, conditions are typically easier to follow if they are kept positive (especially negative-or combinations). We could also alias a condition and set the result to a well named variable, to then consume in an if statement in order to make it easier to follow, test and debug.

Speaking of tests, I'd love to see some unit tests for the additional functions you've added! 💯

2020-04-02 09:15 UTC, develohpanda commented on packages/insomnia-app/app/plugins/context/request.js
> +      return true;
This might be clearer to understand without the negative-or conditional 😄 

How about something like the following?

```suggestion
	  const isFile = renderedRequest.body && renderedRequest.body.mimeType === CONTENT_TYPE_FILE;
	  
	  if (isFile) {
	  	renderedRequest.body.fileName = fileName;
	  }
	  return isFile;
```

2020-04-02 09:15 UTC, develohpanda commented on packages/insomnia-app/app/plugins/context/request.js
> +        (!renderedRequest.body || renderedRequest.body.mimeType !== CONTENT_TYPE_FORM_DATA)
Same as above, I'd suggest to avoid the negative-or (or in this case, compress it down to a positive condition, with a single `!` negation) 🎉

2020-04-02 09:15 UTC, develohpanda commented on packages/insomnia-app/app/plugins/context/request.js
> +        }
Another one to do a swap for the negative condition 😄

2020-04-02 09:15 UTC, develohpanda commented on packages/insomnia-app/app/plugins/context/request.js
> +    addFormItem(formItem: any): boolean {
I wonder if this can be typed, instead of `any`?

```suggestion
    addFormItem(formItem: FormItem): boolean {
```

2020-04-02 09:15 UTC, develohpanda commented on packages/insomnia-app/app/common/misc.js
> +type FormItem = {
Good to see 💯 Typing is awesome!

2020-04-02 09:15 UTC, develohpanda commented on packages/insomnia-app/app/plugins/context/request.js
> +      }
A negative condition here is all good, another developer can understand it at a glace 👍

2020-04-03 03:13 UTC, yittg commented on packages/insomnia-app/app/plugins/context/request.js
> +      return true;
thanks, fixed.

2020-04-03 11:57 UTC, yittg commented
@develohpanda PTAnotherL, thanks

2020-04-03 23:35 UTC, gschier commented
Sorry to jump in here at the last minute but I think we should discuss the API design here before moving forward. 

And, just to be clear up front... you did a great job with this PR and we really appreciate your contribution! I just think it's worth putting in more thought up front since it's really hard to change a public API like this later. 💜

---

Okay, let's dive in. To get a feel for what was added in this PR, I'll list the proposed new methods here:

```text
addFileFormItem
addFormItem
addTextFormItem
getFileForm
getMimeType
getTextForm
getUploadFileName
removeFormItem
setFileFormItem
setFormItem
setMimeType
setTextFormItem
setUploadFileName
getFileForm
getMimeType
getTextForm
getUploadFileName
```

My first thought is "that's a lot of methods to handle body logic."  😅I think my biggest concern, however, is making it easy and safe to work with the various body types.

For example, with the proposed API, it's still possible to call `addTextFormItem()` even if the body is not currently a form. I can see this being difficult to debug, as the user will need to add additional logic to check the mimeType. 

Another pain point I see here if you want to switch body types. Currently there is no obvious way to do that with the proposed API. We could add more methods for doing that (eg. `setMultipartFormBody(parameters)` but now the API gets even larger.

You may be able to see where I'm going with this... Essentially, an API design should be clear, understandable, and prevent users from making errors. If this solution provided all of those things, I'd be willing to overlook the added surface area. However, if the user needs to add a bunch of checks/logic anyway, I propose we greatly simplify it to the following:

```js
getBody(): RequestBody
setBody(body: RequestBody): void
```

This essentially puts all responsibility on the plugin developer and also provides a flexible base for us to build on. Later, we can provide additional helper utilities to create and update various body types if needed.

I can imagine a set of body-specific helpers similar to the ones included in the [HTML5 fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Body).

For now, though, I vote to keep things as simple as possible.

Thoughts @develohpanda @yittg?

2020-04-03 23:35 UTC, gschier requested changes
Sorry to jump in here at the last minute but I think we should discuss the API design here before moving forward. 

And, just to be clear up front... you did a great job with this PR and we really appreciate your contribution! I just think it's worth putting in more thought up front since it's really hard to change a public API like this later. 💜

---

Okay, let's dive in. To get a feel for what was added in this PR, I'll list the proposed new methods here:

```text
addFileFormItem
addFormItem
addTextFormItem
getFileForm
getMimeType
getTextForm
getUploadFileName
removeFormItem
setFileFormItem
setFormItem
setMimeType
setTextFormItem
setUploadFileName
getFileForm
getMimeType
getTextForm
getUploadFileName
```

My first thought is "that's a lot of methods to handle body logic."  😅I think my biggest concern, however, is making it easy and safe to work with the various body types.

For example, with the proposed API, it's still possible to call `addTextFormItem()` even if the body is not currently a form. I can see this being difficult to debug, as the user will need to add additional logic to check the mimeType. 

Another pain point I see here if you want to switch body types. Currently there is no obvious way to do that with the proposed API. We could add more methods for doing that (eg. `setMultipartFormBody(parameters)` but now the API gets even larger.

You may be able to see where I'm going with this... Essentially, an API design should be clear, understandable, and prevent users from making errors. If this solution provided all of those things, I'd be willing to overlook the added surface area. However, if the user needs to add a bunch of checks/logic anyway, I propose we greatly simplify it to the following:

```js
getBody(): RequestBody
setBody(body: RequestBody): void
```

This essentially puts all responsibility on the plugin developer and also provides a flexible base for us to build on. Later, we can provide additional helper utilities to create and update various body types if needed.

I can imagine a set of body-specific helpers similar to the ones included in the [HTML5 fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Body).

For now, though, I vote to keep things as simple as possible.

Thoughts @develohpanda @yittg?

2020-04-04 00:11 UTC, yittg commented
@gschier, I'm ok about the single simple API, just one thing should we mark the existed body text APIs as deprecated?

2020-04-04 09:45 UTC, yittg commented
Another question: should we update the content type header automatically if set body with different mimeType?

2020-04-06 00:35 UTC, develohpanda commented
Agree with the explanation Greg gave with what an API design should achieve and how this change to the API ensures simplicity, especially given the potential this has to grow. Thanks for your time and effort, @yittg! 💯 

> Should we mark the existing body text APIs as deprecated?

That one feels like a body-specific helper that Greg mentioned, so perhaps we need to find a better place to put it. Since helpers don't belong in the core API, my vote is to mark the existing one as deprecated and direct users to the `setBody` API.

Also an internal note, we should make sure to update the plugin API [docs](https://support.insomnia.rest/article/26-plugins#context.request).

> Should we update the content type header automatically if set body with different mimeType?

Kind of on the edge - I feel that we should given the Insomnia client already updates the header automatically, but that also means we need to be clear in docs about the additional automatic change this API may make, therefore adding complexity to the API. I'll defer to @gschier for this one! 👍

2020-04-06 01:06 UTC, yittg commented
> should we update the content type header automatically if set body with different mimeType?


@develohpanda  @gschier prefer to not do this implicitly, and just point out the potential issue in the document.

2020-04-06 21:35 UTC, gschier commented
I agree with not changing the header implicitly in this API. Again, it's easier to add functionality later than paint ourselves into an API corner before necessary 👍 

And, also yes on marking the old `(get|set)BodyText()` as deprecated. We don't have a great system for doing that currently, but we just deprecated our first method last week which can be used as an example (I'm also open to suggestions if you have a better way to mark something deprecated). https://github.com/Kong/insomnia/blob/develop/packages/insomnia-app/app/plugins/context/app.js#L103-L113

2020-04-06 23:15 UTC, yittg commented
That's great,  I'll fix it soon.

2020-04-07 01:27 UTC, yittg commented
Have marked the deprecated api.
However, i didn't find the source code of the document to update,    🤣

2020-04-07 02:15 UTC, develohpanda approved these changes
> I didn't find the source code of the document to update

Don't think that's in source code 😄

2020-04-07 18:41 UTC, gschier commented
Ya, the docs are hosted on HelpScout so we'll have to update them after the PR is merged 👍

2020-04-07 23:24 UTC, yittg commented
So then? Let's merge it? :)

2020-04-10 11:39 UTC, yittg commented
@gschier @develohpanda anything more needed?

2020-04-23 18:44 UTC, gschier approved these changes
Looks great @yittg! Thanks for taking care of this and being accepting to changes/feedback 🙂💜

2020-04-23 18:44 UTC, merged

2020-04-23 23:17 UTC, yittg commented
@gschier @develohpanda Thanks. Pleasure to contribute to the tool I use everyday, :)