Extend Certificates with Windows Cert Store + Custom CA bundles
getinsomnia/insomnia pull request #2020
Opened 2020-04-01 07:45 UTC by develohpanda

Continuing with #1804 😄 

Tasks remaining from original PR:
- [ ] Unit tests (add/fix)
- [ ] Investigate extracting some logic from `network.js` to clean-up code (seems okay to me)
- [ ] From #675: _Since Curl retrieve the base CA bundle from the OS on Mac, it's unclear whether or not setting CURLOPT_CAINFO will override this bundle entirely or add to it. This needs to be tested._

UX to be advised but here's an attempt. Alternatively, instead of hiding the custom file-picker we can always show it and only enable when relevant.

Credit to @coolhome for picking this up, I'm just getting it across the line! 🔥 

Closes #675, closes #1432.

2020-04-06 22:26 UTC, gschier requested changes
Getting close! Looked at it with some fresh eyes and jotted down some thoughts.

2020-04-06 22:26 UTC, gschier commented on packages/insomnia-app/app/models/settings.js
> +  caBundle: string,
Should this be a union type? `'' | 'windowsCertStore' | 'userProvided'`

2020-04-06 22:26 UTC, gschier commented on packages/insomnia-app/app/models/settings.js
> +  caBundle: string,
Also, what are your thoughts on combining these into an Object property, since they're very closely related?

2020-04-06 22:26 UTC, gschier commented on packages/insomnia-app/app/ui/components/settings/general.js
> +    const userProvidedValue = 'userProvided';
+1 for enum for this

2020-04-06 22:26 UTC, gschier commented on packages/insomnia-app/app/ui/components/settings/general.js
> +        <h3>Certificate Authority</h3>
This header seems a bit too specific to encompass the Validate Certificates setting. Can we rename it to Certificates instead?

Also, in the future note, it might be nice to separate the `SSL_VERIFYHOST` and `SSL_VERIFYPEER` options into their own settings for more control. Right now, we're setting both on libcurl from a single setting.

2020-04-06 22:26 UTC, gschier commented on packages/insomnia-app/app/ui/components/settings/general.js
> +              Select Certificate Bundle
Can we remove the `Select` prefix from these two labels?  💄

2020-04-10 12:58 UTC, coolhome commented on packages/insomnia-app/app/network/network.js
> +              caFile = folder + '/roots.pem';
According to win-ca documentation `onsave` will have `undefined` passed if it failed to save certificate to disk.

I wonder if we should check this and reject the promise or maybe at least log message?

2020-04-13 00:51 UTC, develohpanda commented on packages/insomnia-app/app/models/settings.js
> +  caBundle: string,
Hmm, I like the idea of it, also would want to pull `validateSSL` into that object property typed as `CertSettings` or something.

We would have to make the update settings functions a little smarter to work with updating nested properties (eg. `certSettings.caBundlePath`). I did something similar for the plugin settings (which right now only has enable/disable)

2020-04-13 01:01 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/general.js
> +        <h3>Certificate Authority</h3>
Would be good to do that, though I think it needs some more thought about when that user setting should kick in during consumption (in `network.js`).

2020-04-13 01:08 UTC, develohpanda commented on packages/insomnia-app/app/network/network.js
> +              caFile = folder + '/roots.pem';
Noted, I'll need to play with this on Windows to see what the UX is like. Thanks! 😄

2020-04-27 23:02 UTC, gschier commented on packages/insomnia-app/app/models/settings.js
> +  caBundle: string,
Ya, we could hold off for now as it's not a huge deal 👍

2020-05-18 21:05 UTC, develohpanda commented on packages/insomnia-app/app/network/network.js
> +              caFile = folder + '/roots.pem';
Rejecting the promise will stop the request as a whole.

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/4312346/82259435-ac769300-99af-11ea-83f3-666885be4089.png">

I've resorted to providing a nicer message in console log and not setting the CAINFO flag.

2020-05-18 22:22 UTC, develohpanda commented
Hi @coolhome! Would you have any capacity to help test and validate this PR? I didn't get very far with smoke-testing, as I'm unfamiliar with how to quickly setup a backend and CA bundle that would allow for testing this manually. 😄

Aside from some unit testing to lock down the new functionality, this is ready to roll.

2020-07-05 19:36 UTC, coolhome commented
@develohpanda I have been trying to create a working build to transfer to my work machine for testing. In the process I have discovered that `win-ca` with the current setup for insomnia are not compatible. It works when you run start but on a packaged version we get the following error:
![image](https://user-images.githubusercontent.com/700740/86540561-5a90ba80-bed4-11ea-880b-70b7a2ab69c8.png)

Upon investigation I found the path `win-ca` is trying to execute a program to receive the windows certificate but fails because it has the path to the asar and not the unpacked location where the `roots.exe` exists.

![image](https://user-images.githubusercontent.com/700740/86540681-25d13300-bed5-11ea-9f35-9f15069eaae6.png)

The file does exists here tho:
![image](https://user-images.githubusercontent.com/700740/86540693-400b1100-bed5-11ea-8cfa-749f777d177f.png)


Switching the import statement to this at least gets the app to bootup but now the error displays in the http response box.
```js
import winCa from 'win-ca/api';
```

ref: https://github.com/ukoloff/win-ca#entry-points

May need to do more research if this is correct. I also tried the fallback which is electron compatible but that also gave the same error.

2020-07-05 23:49 UTC, coolhome commented
In `win-ca` there is a line to get the `roots.exe` location using a relative path off `__dirname`. In this case the `__dirname` resolves to `resources/app.asar/roots.exe`. ASAR is like a zip to my understanding. We are obviously unable to extract the executable and run from a package. Good news is the package was put in the ASAR unpacked at `resources\app.asar.unpacked\node_modules\win-ca\lib\roots.exe`

Setting webpack `node.__dirname` to `false` (current value)
 -> Error: `. spawn .\roots.exe ENOENT`
 -> Code:
```js
// __dirname is ".\"
 bin = path.join(__dirname, 'roots.exe');
```

Setting webpack `node.__dirname` to `true` 
 -> Error: `. spawnSync ..\node_modules\win-ca\lib\roots.exe ENOENT`
 -> Code:
```js
// __dirname is "..\node_modules\win-ca\lib\"

 bin = path.join(__dirname, 'roots.exe');
```

When this is true we are pretty close. Unfortunately we are in ASAR when this codes executed so it does not know the path should have `resources\app.asar.unpacked\` prepended to the path.


So enabling [`node.__dirname`](https://webpack.js.org/configuration/node/#node__dirname) to preserve nodejs module paths but we still have a problem. I think I will need to see the possibilities of switching `win-ca` to use [`electron-util`]([https://github.com/sindresorhus/electron-util](https://github.com/sindresorhus/electron-util)) over [`is-electron`]([https://github.com/cheton/is-electron](https://github.com/cheton/is-electron)). This new package will allow us to know if `win-ca` is in a electron, detect if its in a ASAR, and use the correct path.

2020-07-06 08:16 UTC, develohpanda commented
Thanks for the help @coolhome, a couple of people have requested this so hoping to get it in soon! 🤗 

I found the `win-ca` documentation stating it has been adapted to work within an Electron app and support ASAR, with an example: https://github.com/ukoloff/win-ca#electron; suppose this doesn't work for our case.

I wonder if it could be related to our webpack configuration rather than `win-ca` specifically. @gschier does this behavior ring any bells with any other dependencies that have given issues during packaging?

2020-07-08 18:59 UTC, gschier commented
Unfortunately, I don't know off the top of my head why it _wouldn't_ be working. However, we _have_ worked-around a similar problem before.

We bundle `yarn` inside the app to download and install plugins, and had to list it in `extraResources` in the `electron-builder` config to force it to live outside the `asar` package. If you search the codebase for `yarn-standalone.js` you can perhaps follow a similar pattern to get it working.

2020-08-28 01:07 UTC, develohpanda commented
Hi @coolhome! I've pushed a commit that marks `roots.exe` as per Greg mentioned, and was able to package, run the app and make a simple HTTP request.

The error you saw, did you see that on first launching the packaged app or when running a request?

Quick note, that you'll need to update the fallback [here](https://github.com/Kong/insomnia/blob/develop/packages/insomnia-app/scripts/getBuildContext.js#L34) to the current build version (`2020.4.0-beta.4`), in order to build locally. (Working on this to improve it, slowly 😄)

2020-12-06 18:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/insomnia?pullRequest=2020) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/insomnia?pullRequest=2020) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/insomnia?pullRequest=2020) it.</sub>

2021-03-18 05:06 UTC, closed without merging

2021-03-18 05:06 UTC, develohpanda commented
Closed in favor of #3203