fix: Escape key in editble field closing modals
getinsomnia/insomnia pull request #2039
Opened 2020-04-16 19:57 UTC by baleeds

This PR will:
- Fix an issue where pressing escape in an editable field closed the containing modal
- Fix an issue where pressing escape in an editable field would save the current value, instead of discarding

Closes #2029

2020-04-21 02:05 UTC, gschier requested changes
Thanks so much for taking care of this! Just one comment of the removal of the `blur` logic.

2020-04-21 02:05 UTC, gschier commented on packages/insomnia-app/app/ui/components/base/editable.js
> +      if (this._input) {
I might be missing something but don't we want to have `this._input.blur()` here still?

2020-04-21 02:38 UTC, baleeds commented on packages/insomnia-app/app/ui/components/base/editable.js
> +      if (this._input) {
It's possible!  I removed it because the text input is unmounted when `editing` becomes false, so in my mind the blur state is irrelevant.

What would be the reason it's needed?

2020-04-22 19:28 UTC, gschier approved these changes
Thanks for taking care of this!

2020-04-22 19:28 UTC, gschier commented on packages/insomnia-app/app/ui/components/base/editable.js
> +      if (this._input) {
I think the blur is there so the `onBlur` handler gets called, which actually just calls `_handleEditEnd` anyway.

I think I see why you made this change now. Currently, pressing `escape` blurs the input but still saves the value. With your change, the value will be reverted to the original. I like it!

2020-04-22 19:28 UTC, merged