Handle non-string types in filterHeaders()
getinsomnia/insomnia pull request #2099
Opened 2020-04-30 22:20 UTC by gschier

This is a small fix for a bug report that was submitted to support. I'm not sure how it happened, but somehow the user ended up with a request header with a non-string name.

2020-04-30 23:28 UTC, develohpanda requested changes
Nice! 

Small note about empty string checks that have disappeared

2020-04-30 23:28 UTC, develohpanda commented on packages/insomnia-app/app/common/misc.js
> +    if (!h || !(typeof h.name === 'string')) {
Should the `!h.name` check still exist? That would exclude an empty string (considering the previous behavior looks like it excludes empty strings).

Also, TIL you can effectively filter and map at the same time. This implementation is cool although not immediately obvious (and it would also implicitly filter out a header if `h.name` is an empty string)

2020-04-30 23:28 UTC, develohpanda commented on packages/insomnia-app/app/common/__tests__/misc.test.js
> +    expect(misc.filterHeaders([{ name: 'good', value: 'valid' }], 123)).toEqual([]);
Yay more tests

2020-04-30 23:28 UTC, develohpanda commented on packages/insomnia-app/app/common/misc.js
> +  if (!Array.isArray(headers) || !(typeof name === 'string')) {
Should the `!name` check also still exist? 🤔 

![image](https://user-images.githubusercontent.com/4312346/80768390-668f9180-8b9e-11ea-8c0b-52e99ab3bb52.png)

2020-05-01 22:47 UTC, gschier commented on packages/insomnia-app/app/common/misc.js
> +    if (!h || !(typeof h.name === 'string')) {
Hmm, ya I think so. I _did_ think about it a bit while changing it but I think I agree now that it should be kept. A header with no name is essentially a non-existing header.

2020-05-02 04:01 UTC, develohpanda approved these changes
LGTM! 😄

2020-05-02 18:19 UTC, merged