Storybook Sidebar Provisioning & WIP Implementation
getinsomnia/insomnia pull request #2125
Opened 2020-05-06 12:34 UTC by sonicyeti

This PR encompasses the following:

1. Implementing the latest round of SVGs per Figma design specs
2. Rolling in updated & expanded base CSS vars in both core & storybook (preview head)
3. Adding Storybook > Figma design preview add-on (seen in screenshot)
4. Adding Framer animation package (see animation below)
5. Migrating **WIP** sidebar from Studio (see in screenshot)

![Screen Shot 2020-05-06 at 8 28 17 AM](https://user-images.githubusercontent.com/52717970/81176992-f99c4300-8f73-11ea-9a38-9744776e2a5b.png)

![2020-05-06 08 33 20](https://user-images.githubusercontent.com/52717970/81177226-513aae80-8f74-11ea-8228-2ea4f742f777.gif)

2020-05-06 17:48 UTC, gschier commented
Some interaction feedback:

When playing the Sidebar component, I kept clicking the + icon to try and expand the sections. I never even thought to click on the rest of the item. 

I think these might help:

- Add a hover state to each item
- Add `cursor: default` since it's currently showing the caret
- Make the whole thing clickable instead of just the label

Thoughts @sonicyeti @jitachi?

2020-05-06 17:55 UTC, sonicyeti commented
> Some interaction feedback:
> 
> When playing the Sidebar component, I kept clicking the + icon to try and expand the sections. I never even thought to click on the rest of the item.
> 
> I think these might help:
> 
> * Add a hover state to each item
> * Add `cursor: default` since it's currently showing the caret
> * Make the whole thing clickable instead of just the label
> 
> Thoughts @sonicyeti @jitachi?

The plus icon threw me for a loop as well. I would never expect a plus icon to do anything other than expand an accordion style piece of UI but low-and-behold Jitachi showed me how Figma's UI worked and its pretty slick. Same concept (check out the export panel). Title is hot for expand/contract while the plus sign adds an export preference line. This pattern can also be seen in VS Code but I forgot where.

2020-05-07 20:04 UTC, gschier requested changes
A few comments! Looking pretty good though

2020-05-07 20:04 UTC, gschier commented on packages/insomnia-app/app/ui/css/constants/dimensions.less
> +  --spacing-xxxxl: calc(var(--font-size) * 4);
We talked about this briefly in the past, but I think the new `spacing` should entirely replace `padding` vars since they will be used for the same purpose (padding and margin).

I think we have to options:

1. Replace and update padding vars with these values, and continue using `padding` as the name
2. Delete the `padding` vars and update all usages to reference the new `spacing` ones

For the purpose of keeping this PR _small_, my vote would be to No. 1

2020-05-07 20:04 UTC, gschier commented on packages/insomnia-components/components/sidebar.js
> +  min-height: 1100px;
Hmm, these styles seem like they should be controlled by the place the component is being consumed (App or Story), not by the component itself.

For example, `min-height: 1100px` will break if we render this in the app with a window shorter than `1100px`

2020-05-07 20:04 UTC, gschier commented on packages/insomnia-components/components/sidebar.js
> +      {/*
Delete comment

2020-05-07 20:09 UTC, gschier commented on packages/insomnia-components/.storybook/preview-head.html
> +    --color-text: #404040;
For now, can we use theme colors for these instead, until we update the theme system to support Jitachi's new variables?

With the current system, this would be the values:

- border: `var(--hl-md)`
- sidebar: `var(--color-bg)`
- text: `var(--color-font)`

2020-05-07 20:09 UTC, gschier commented on packages/insomnia-components/components/sidebar.js
> +    <StyledSidebar>
This should have `className="theme--sidebar"` so that `--color-bg` uses the sidebar scope from the theme.

2020-05-08 13:58 UTC, sonicyeti commented on packages/insomnia-app/app/ui/css/constants/dimensions.less
> +  --spacing-xxxxl: calc(var(--font-size) * 4);
Let me break this PR up. I agree 100% with your first point and don't feel like we should cut corners for the sake of the PR being too big. Given the actual sidebar in this PR is only located in SB, I'll remove these changes from "dimensions.less" all together since they aren't directly needed. I was trying to provision for the next step, in which case they will be needed but lets address this now before moving forward.

2020-05-08 14:03 UTC, sonicyeti commented on packages/insomnia-app/app/ui/css/constants/dimensions.less
> +  --spacing-xxxxl: calc(var(--font-size) * 4);
Ok reverted dimension back.

2020-05-08 14:10 UTC, sonicyeti commented on packages/insomnia-components/components/sidebar.js
> +  min-height: 1100px;
Yep, for sure not driven by a fixed value like this. I literally just needed a way for forcibly increase the height given SB has no parent element with a fixed height. I'll work around this though now before re-review!

2020-05-08 14:13 UTC, sonicyeti commented on packages/insomnia-components/.storybook/preview-head.html
> +    --color-text: #404040;
Sounds good.

2020-05-08 18:30 UTC, gschier requested changes
Second pass complete 🥳

2020-05-08 18:30 UTC, gschier commented on packages/insomnia-components/.storybook/preview-head.html
> +    --color-text: var(--color-font);
Oh, woops. I meant to use these vars directly in the component CSS. If we merge this, the component won't work in the app, since `--color-border` etc won't be defined there yet.

2020-05-08 18:30 UTC, gschier commented on packages/insomnia-components/components/sidebar.js
> +    background-color: var(--hl-xs);
Indent?

2020-05-08 18:30 UTC, gschier commented on packages/insomnia-components/.storybook/preview-head.html
> +    --color-text: var(--color-font);
Also just realized that the other news vars in this file also won't be present in the app yet.

2020-05-08 18:30 UTC, gschier commented on packages/insomnia-components/components/sidebar.js
> +  background-color: #fafafa;
Should be `var(--color-bg)`, which will pull the bg color from the theme `sidebar: {}` scope.

2020-05-08 18:30 UTC, gschier commented on packages/insomnia-components/components/sidebar.js
> +    fill: #737373;
Should use a theme color here. `--hl-md` perhaps?

2020-05-08 18:30 UTC, gschier commented on packages/insomnia-components/components/sidebar.js
> +  min-width: 88%;
I have a feeling this relative width might cause a problem when resizing the sidebar?

2020-05-08 18:30 UTC, gschier commented on packages/insomnia-components/components/sidebar.js
> +  .inline-icon {
Not used anywhere

2020-05-08 18:30 UTC, gschier commented on packages/insomnia-components/components/sidebar.js
> +              <SvgIcon icon={IconEnum.search} />
Hmm, the search seems to have a BG color for some reason
 
![image](https://user-images.githubusercontent.com/587576/81436785-e679a680-911e-11ea-9970-851fa64ddc14.png)

2020-05-08 18:30 UTC, gschier commented on packages/insomnia-components/components/sidebar.js
> +            initial={{ height: visible3 ? '0px' : '45px' }}
This hardcoded px value makes me uneasy. Is there a way we can do this that doesn't involve fixed sizing? Perhaps by animating `transform: scaleY(0);` to `transform: scaleY(1);` and defining the height in CSS using a line-height var. Making this change will also prove useful once we have an <Input> component that controls its own height.

2020-05-11 13:02 UTC, sonicyeti commented on packages/insomnia-components/components/sidebar.js
> +  min-width: 88%;
Pulled it out for now, will refine once we get it in. Renders too skinny for and would rather fix once I get it in the actual environment.

2020-05-13 22:00 UTC, gschier requested changes
A few comments but we're really close now!

2020-05-13 22:00 UTC, gschier commented on packages/insomnia-components/components/sidebar.js
> +  }
Random bracket leftover

2020-05-13 22:00 UTC, gschier commented on packages/insomnia-app/app/ui/css/constants/dimensions.less
> +  --font-weight-bold: 700;
For the purposes of this PR, can we remove these new variables for now and stick with the currently-existing ones? 

ie. use `--padding-*` instead of spacing, `calc(font-size-*, x)` instead of line height, and hardcode font-weight. 

I think it makes sense to do a separate sweep to update all the variables in both the app and components library at once.

2020-05-13 22:00 UTC, gschier commented on packages/insomnia-components/components/tooltip.js
> +  className?: string,
We talked about passing the color in as a prop like we do with <Button> here. What made you decide against that?

2020-05-14 12:02 UTC, sonicyeti commented on packages/insomnia-components/components/sidebar.js
> +  }
Thanks for the catch!

2020-05-14 17:32 UTC, gschier commented on packages/insomnia-components/components/tooltip.js
> +  className?: string,
Woops! Somehow I thought this was the <Notice> component.

2020-05-14 17:34 UTC, gschier approved these changes
We made it! 🥳 

![](https://media3.giphy.com/media/BkJcfyoWYYQXi8Uofu/giphy.gif)

2020-05-14 18:00 UTC, merged