Wrap SwaggerUI component with an error boundry that can invalidate
getinsomnia/insomnia pull request #2131
Opened 2020-05-07 01:13 UTC by develohpanda

Current:
- Currently, the error boundary shows one error and doesn't re-attempt a render until the page is navigated to again, for instance. 
- Swagger UI can be inconsistent with its errors, for instance #2094. Because this is not a component controlled by us, there may be other unknown bugs that exist as well.

This PR introduces an `ErrorBoundary` around the SwaggerUI component, and it also allows an `ErrorBoundry` to be invalidated.

Invalidation is controlled via a changing prop, which triggers a component update, and a life-cycle hook that decides whether the error should be cleared and a re-render attempted.

Demo:
![2020-05-07 13 05 07](https://user-images.githubusercontent.com/4312346/81243295-8a9e1780-9063-11ea-8735-0ab67466f7f2.gif)

2020-05-07 01:33 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-design.js
> +              </ErrorBoundary>
This is the primary change in this file... the rest are from linting 😢

2020-05-07 01:33 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/error-boundary.js
> +    this.setState(clearState);
There will not be a double render when `setState` is called from `componentWillRecieveProps` 😄

2020-05-07 01:33 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/error-boundary.js
> +  invalidateWith?: object,
The value of this prop isn't used directly by the error boundary, but it triggers a component update when bound to a text field (such as the spec object in wrapper-design)

2020-05-07 01:33 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-design.js
> +                  spec={swaggerUiSpec || {}}
Is parsing the apiSpec necessary? We _can_ send the original contents (`activeApiSpec.contents`) directly to SwaggerUI, and it handles the error case fixed by this PR correctly, however we have no control over the error it shows.

With the following code change, SwaggerUI shows this in the preview
```suggestion
                  spec={activeApiSpec.contents}
```
![image](https://user-images.githubusercontent.com/4312346/81244695-35640500-9067-11ea-9859-777e3e7a9198.png)

2020-05-07 01:34 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-design.js
> +                  </div>
@nijikokun how's this for an error message to show in place of the preview when SwaggerUI throws a fatal error?

2020-05-07 19:32 UTC, gschier requested changes
A few comments but nothing too major! Will be nice to get this in 😄

2020-05-07 19:32 UTC, gschier commented on packages/insomnia-app/app/ui/components/error-boundary.js
> +  invalidateWith?: object,
Can we force this to be a string? Object comparison in JS isn't great, as it matches by reference, not by shape.

2020-05-07 19:32 UTC, gschier commented on packages/insomnia-app/app/ui/components/error-boundary.js
> +    const clearState = { error: null, info: null };
This object comparison with `this.state` seems like it could be brittle, as it won't compare the properties themselves. We should probably be checking both `error` and `info` explicitly to ensure our code is robust.

```
> { error: null, info: null } === { error: null, info: null }
false
```

2020-05-07 19:32 UTC, gschier commented on packages/insomnia-app/app/ui/components/wrapper-design.js
> +                  </div>
What do you think about removing the "If it doesn't..." sentence?

2020-05-07 19:46 UTC, gschier commented on packages/insomnia-app/app/ui/components/wrapper-design.js
> +                  spec={swaggerUiSpec || {}}
If it works, I'm fine with passing it straight through

2020-05-07 21:33 UTC, gschier commented on packages/insomnia-app/app/ui/components/settings/plugins.js
> +        <div key={} className="text-right">
🤔

2020-05-07 21:33 UTC, gschier commented on packages/insomnia-app/app/ui/components/error-boundary.js
> +    this.setState({ error: null, info: null });
I feel like we should be checking if the invalidation key changed here. I know your current solution works, but it's hard to follow what's happening without adding a ton of comments. I suggest something a bit more descriptive and explicit.

```suggestion
    const invalidationKeyChanged = nextProps.invalidateWith !== this.props.invalidateWith;
    const isErrored = error !== null || info !== null;
    const shouldResetError = invalidationKeyChanged && isErrored;
    
    if (shouldResetError) {
        this.setState({ error: null, info: null });
    }
```

2020-05-07 22:23 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/plugins.js
> +        <div key={} className="text-right">
🙈

2020-05-08 18:13 UTC, gschier requested changes
Almost there! Just one comment on `renderError` behavior.

2020-05-08 18:13 UTC, gschier commented on packages/insomnia-app/app/ui/components/error-boundary.js
> +      );
Optional chaining is nice in many cases but this one seems like adds more complexity than it saves. This code will also render the fallback if `renderError(error)` returns a falsey value, which seems like confusing behavior. 

```suggestion
      return (
        renderError ? renderError(error) : (
          <div className={errorClassName || null}>Render Failure: {error.message}</div>
        )
      );
```

2020-05-11 21:19 UTC, sonicyeti approved these changes
Nice!

2020-05-12 21:45 UTC, gschier approved these changes
Woo!

2020-05-12 22:05 UTC, merged