Bug/kubernetes name not sluggified
getinsomnia/insomnia pull request #2136
Opened 2020-05-08 03:18 UTC by develohpanda

Closes #2102 - bug reports and examples in the issue.

All of the following items are fixed via TDD, with breaking tests written before fixing.

Resolves several small bugs:
- name is not sluggified
- `path: null` is invalid under an ingress document, so path should be left off
- original annotations object gets modified, resulting in all ingress documents having the same annotations. Ideally it should deep-clone, but the object is only one level deep so it is likely sufficient to duplicate via `{...annotations}`.

2020-05-08 18:07 UTC, gschier reviewed
Just a small comment. Looks good otherwise!

2020-05-08 18:07 UTC, gschier commented on packages/openapi-2-kong/src/kubernetes/index.js
> +  const fullPath = urlJoin(serverBasePath, specificPath, specificPath ? '' : '.*');
Were any tests updated to handle this `.*` suffix change?

2020-05-08 19:19 UTC, develohpanda commented on packages/openapi-2-kong/src/kubernetes/index.js
> +  const fullPath = urlJoin(serverBasePath, specificPath, specificPath ? '' : '.*');
Yip there are existing tests for this. Figured to keep the url join steps together instead of separated. No behaviour change here.

2020-05-13 23:29 UTC, gschier requested changes
One. Comment. Left!

![](https://media2.giphy.com/media/Qaxd5XpgDWMso/giphy.gif)

2020-05-13 23:29 UTC, gschier commented on packages/openapi-2-kong/src/common.js
> +  const name = typeof rawName === 'string' ? rawName : defaultName;
Can we break up this logic? All the ternaries, optional chaining, and `||`s make it difficult to follow.

![](https://media1.giphy.com/media/WNJdVoZw7gcXt5c7d4/giphy.gif)

2020-05-13 23:29 UTC, gschier commented on packages/openapi-2-kong/src/kubernetes/index.js
> +  const fullPath = urlJoin(serverBasePath, specificPath, specificPath ? '' : '.*');
Oh, I see. The part I missed was on line 232 below. I didn't realize you had move the `.*` logic from there to here.

2020-05-14 17:58 UTC, gschier approved these changes

2020-05-14 20:27 UTC, merged