Honor variable defaults from servers declaration during OpenAPI3 import
getinsomnia/insomnia pull request #2151
Opened 2020-05-11 01:18 UTC by develohpanda

This PR adds functionality to honor variable defaults from the servers declaration during an OpenAPI3 spec import.

The `openapi-2-kong` package already does this, the functionality is simply adapted for `insomnia-importers`.

- If the scheme is a variable, and no default is provided, then it will default to `http`.
- Any other variables that have no default provided remain unchanged (therefore showing existing behavior). More thought is needed around handling unknown variables.

<details>
<summary>Example spec</summary>

```yaml
openapi: 3.0.2
info:
  description: This API is for administrating files and file storages.
  license:
    name: Some license
  title: File and Storage API
  version: 0.1.0
servers:
  - description: Devserver
    url: '{protocol}://{host}:{port}/{basePath}'
    variables:
      port:
        default: 8080
      host:
        default: localhost
      basePath:
        default: filemanagement
paths:
  /files:
    get:
      operationId: find_files
```
</details>

![image](https://user-images.githubusercontent.com/4312346/81515715-7cb10500-9389-11ea-8031-80d06dc701ba.png)

Closes #1640 

### Gripes:
- We should try to add flow into `insomnia-importers`
- It would be nice to be able to reuse the `resolveUrlVariables` implementation (and therefore, tests) between `openapi-2-kong` and `insomnia-importers`. How could we do that? Is a separate package needed to do this resolution?

2020-05-14 00:01 UTC, gschier requested changes

2020-05-14 00:01 UTC, gschier commented on packages/insomnia-importers/src/importers/openapi3.js
> +function getDefaultServerUrl(api) {
Curious why you used a different approach than `openapi-2-kong` does. Is it so you could replace vars with a default value if they don't have one defined? If so, can we make sure the fixture defined handles the case where there is no default?

https://github.com/Kong/insomnia/blob/d6998ad6843a73dd191f1142a997581c60c12ad0/packages/openapi-2-kong/src/common.js#L121

2020-05-14 02:39 UTC, develohpanda commented on packages/insomnia-importers/src/importers/openapi3.js
> +function getDefaultServerUrl(api) {
Wasn't aware of `fillServerVariables`. I used the same as what the k4k8s generation uses: https://github.com/Kong/insomnia/blob/d6998ad6843a73dd191f1142a997581c60c12ad0/packages/openapi-2-kong/src/kubernetes/variables.js#L13-L33.

Key difference is k4k8s converts variables with no default to `.*`, while `fillServerVariables` throws an error if the default doesn't exist.

The implementation I did for the openapi3 importer has one subtle difference, in that if a variable default does not exist, it simply skips it.

Eg. with the example service `api.insomnia.rest/{var}/test` where `var` is not defaulted
- `fillServerVariables` -> error
- `k4k8s` -> `api.insomnia.rest/.*/test`
- this file -> `api.insomnia.rest/{var}/test`

2020-05-14 02:58 UTC, develohpanda commented on packages/insomnia-importers/src/importers/openapi3.js
> +function getDefaultServerUrl(api) {
> It would be nice to be able to reuse the resolveVariables implementation (and therefore, tests) between openapi-2-kong and insomnia-importers. How could we do that? Is a separate package needed to achieve this reuse?

Looks like there are three (not two) similar implementations spread between `insomnia-importers` and `openapi-2-kong` - is it possible to have one implementation be used across the packages?

2020-08-05 05:06 UTC, develohpanda commented on packages/insomnia-importers/src/importers/openapi3.js
> +function getDefaultServerUrl(api) {
There are two approaches to fill server variables in `openapi-2-kong`:
1. iterates over `server.variables`, throws if default missing, and replaces items in the url
2. iterates over variables in the url, searches for a default in `server.variables`, defaults if missing

I used a hybrid approach for the openapi3 importer, for several reasons:
- To successfully parse the URL, we need a valid, resolved URL, and smart defaults are much more involved,
- A truly valid OpenAPI spec should have variable defaults defined for a server url
- `o2k` (kubernetes) can handle missing defaults (as per the requirements) using `.*` fallback

The openapi3 importer honors variable defaults, but if a variable exists in the URL and is missing in `server.variables`, an error is thrown and presented to the user.

2020-08-06 11:10 UTC, DMarby approved these changes

2020-08-06 19:19 UTC, gschier approved these changes
![](https://media2.giphy.com/media/VbnUQpnihPSIgIXuZv/giphy-downsized-medium.gif)

2020-08-06 20:13 UTC, merged