WIP - Fix GitLab sync
getinsomnia/insomnia pull request #2162
Opened 2020-05-12 20:50 UTC by develohpanda

2020-05-13 23:53 UTC, gschier requested changes
A few comments. I like the way this was implemented though 👍

2020-05-13 23:53 UTC, gschier commented on packages/insomnia-app/app/common/documentation.js
> +}
Nice 👍

2020-05-13 23:53 UTC, gschier commented on packages/insomnia-app/app/models/git-repository.js
> +export function create(patch: $Shape<GitRepository> = {}): Promise<GitRepository> {
Yay for `$Shape`

2020-05-13 23:53 UTC, gschier commented on packages/insomnia-app/app/sync/git/git-vcs.js
> +  async fetch(singleBranch: boolean, depth: number | null, creds: GitCredentials): Promise<void> {
Even though `null` is part of the `GitCredentials` type, I think it still makes sense to denote this arg as optional. Perhaps we should remove `null` from the type and define it explicitly where the type is used?

2020-05-13 23:53 UTC, gschier commented on packages/insomnia-app/app/sync/git/git-vcs.js
> +import type { GitCredentials } from '../../models/git-repository';
The app already imports and knows about this Git helper, so importing from models effectively creates a circular dependency between the git logic and the app logic. I would prefer to see either the type definition moved into here, or have it duplicated in both places.

Since the Git logic is very isolated and specific, it makes sense for it to be treated more as a standalone library and thus not need to know how or where it's being used. Perhaps we could even move it to a separate Lerna package to draw a more clear separation in the future. _Note: The analytics tracking does technically violate this already, but you can't win 'em all 🤷_

2020-05-13 23:53 UTC, gschier commented on packages/insomnia-app/app/ui/components/modals/error-modal.js
> +            <details>
Nice use of HTML5!

2020-05-13 23:53 UTC, gschier commented on packages/insomnia-app/app/ui/components/modals/git-repository-settings-modal.js
> +                    placeholder="Username"
Nitpick: Generally placeholder should be an example value, ideally different from the label. Perhaps `MyUser` or something generic.

2020-05-14 03:18 UTC, develohpanda commented on packages/insomnia-app/app/sync/git/git-vcs.js
> +import type { GitCredentials } from '../../models/git-repository';
I'd prefer to move the type definition into this git helper, and import into models, rather than duplicate. IMO type definitions should have one source of truth.

Extracting a separate package would be nice for future too 👍

2020-05-14 03:39 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/help-link.js
>        </Link>
No usages of `HelpLink` so I removed the component
![image](https://user-images.githubusercontent.com/4312346/81889990-f4d13200-95f8-11ea-9bdc-b585d078bac0.png)

2020-05-14 23:18 UTC, gschier approved these changes

2020-05-14 23:18 UTC, gschier commented on packages/insomnia-app/app/common/documentation.js
> +export const docsGitSync = insomniaDocs('/article/96-git-sync');
Woah, this is really nice ⚡

2020-05-14 23:18 UTC, gschier commented on packages/insomnia-app/app/ui/components/modals/index.js
> +export function showError(config: ErrorModalOptions) {
😄

2020-05-15 02:11 UTC, merged