WIP - git sync failures on Windows - change root directory from / to .
getinsomnia/insomnia pull request #2194
Opened 2020-05-19 05:51 UTC by develohpanda

This approach sets `.` as the base directory, instead of `/`. Windows cannot handle the double slash route (eg //.insomnia/ApiSpec/) that gets created by using / as the base dir, but both Windows and macOS seem to handle `./.insomnia/ApiSpec/` just fine.

Further notes in the linked issue. Closes #2153

2020-05-25 06:03 UTC, develohpanda commented
Sigh; I'm working through commit logic not working correctly on Windows, and it seems `isomorphic-git` has hard-coded the usage of the `posix` separator (`/`) - https://github.com/isomorphic-git/isomorphic-git/blob/c2cd5cb8c4f69163de535e026f9e6e09cef29dc6/src/api/status.js#L172.

This logic is used when getting filestatus. Reverted this back to draft.

2020-05-27 23:41 UTC, gschier requested changes
Looks good! A few comments but all minor 😄

2020-05-27 23:41 UTC, gschier commented on packages/insomnia-app/app/sync/git/__mocks__/path.js
> +module.exports = exportObj;
Woah, very nice! Was there a technical reason for not using ES6-style import/exports here?

2020-05-27 23:41 UTC, gschier commented on packages/insomnia-app/app/sync/git/__tests__/git-vcs.test.js
> +describe.each(['win32', 'posix'])('Git-VCS using path.%s', type => {
Dang, I didn't even know `describe.each` existed 😃

2020-05-27 23:41 UTC, gschier commented on packages/insomnia-app/app/sync/git/ne-db-plugin.js
> +    const pathSep = path.sep === path.win32.sep ? '\\\\' : '/';
Should we comment what we're doing here?

2020-05-27 23:41 UTC, gschier commented on packages/insomnia-app/app/sync/git/ne-db-plugin.js
> +    const pathSep = path.sep === path.win32.sep ? '\\\\' : '/';
Also, took me a while to understand why it was 4 backslashes instead of 2. Is it because we have to escape the JS string, then also the RegExp? `\\\\` > `\\` > `\`

2020-05-27 23:41 UTC, gschier commented on packages/insomnia-app/app/sync/git/ne-db-plugin.js
> +    filePath = filePath.replace(this._cloneDirRegExp, '');
Nice, this seems like a great place for this.

2020-05-27 23:41 UTC, gschier commented on packages/insomnia-app/app/ui/components/modals/git-repository-settings-modal.js
> -      inputs.token = typeof creds.token === 'string' ? creds.token : '';
Was token removed here on purpose?

2020-05-27 23:41 UTC, gschier commented on packages/insomnia-app/app/ui/components/wrapper-home.js
> +            } = this.props;
Nice catch

2020-05-28 00:38 UTC, develohpanda commented on packages/insomnia-app/app/sync/git/__mocks__/path.js
> +module.exports = exportObj;
If you try to import the module being mocked (importing `path` in `__mocks__/path.js`), then jest gets stuck in an infinite loop. Using `jest.requireActual` bypasses that.

The export is tricky... The test setup logic (to prepare the database) calls into `mkdirp`, which uses a CommonJS import (`require('path')`) and it fails to import `path` module correctly if the mock is setup with es6-style exports.

![image](https://user-images.githubusercontent.com/4312346/83085301-adaa6d00-a0df-11ea-8304-66cdd6b5690e.png)

In all the testing I've done with mocks, I've never been able to get ES6-style mocks working properly, and most of the examples use `module.exports` so haven't given too much more thought into this since the first time I ached over it 😅 If you have any other ideas on how to solve it, that'd be super useful!

2020-05-28 00:43 UTC, develohpanda commented on packages/insomnia-app/app/sync/git/ne-db-plugin.js
> +    filePath = filePath.replace(this._cloneDirRegExp, '');
It _is_ trivial given what `cloneDir` is set to, but following the general pattern in the rest of this PR to remove all hard-coding to do with file-paths in git (and be independent of what `cloneDir` is set to), I thought this solution would be more stable.

2020-05-28 00:58 UTC, develohpanda commented on packages/insomnia-app/app/sync/git/ne-db-plugin.js
> +    const pathSep = path.sep === path.win32.sep ? '\\\\' : '/';
Added a comment to explain this. It _is_ to escape both the JS string and RegExp. 👍

2020-05-28 17:19 UTC, gschier approved these changes
Happy to finally get this fix in!

![](https://media2.giphy.com/media/l3vR670UdfqBiH0fS/giphy.gif)

2020-05-28 18:13 UTC, merged