Default to rendered request URL when name is not present
getinsomnia/insomnia pull request #2230
Opened 2020-06-01 04:18 UTC by jodyheavener

Closes #1505

This PR implements the ability to use a Request's URL as its sidebar "name" in lieu of a defined value.

When creating a new request the initial value remains "My Request", but the placeholder is now "Your request URL":

<img width="1023" alt="Screen Shot 2020-05-31 at 11 55 51 PM" src="https://user-images.githubusercontent.com/6392049/83375038-9ac3c100-a39b-11ea-8301-9694f75b0b2b.png">

Similarly, the Request settings displays the current URL (when available) as the placeholder:

<img width="1024" alt="Screen Shot 2020-06-01 at 12 04 00 AM" src="https://user-images.githubusercontent.com/6392049/83375095-c9419c00-a39b-11ea-9cbc-8f9c32edb2a4.png">

The name in the sidebar automatically updates as you change the URL in the Request pane:

![Update as you type](https://user-images.githubusercontent.com/6392049/83375133-e1b1b680-a39b-11ea-935c-f452ce31dd68.gif)

It supports environment variables:

<img width="1023" alt="Screen Shot 2020-06-01 at 12 00 03 AM" src="https://user-images.githubusercontent.com/6392049/83375195-11f95500-a39c-11ea-9eb0-eb3f74ef6a09.png">

And template tags (within reason)...

A Prompt template tag does not have a value until request time, so it yields nothing:

<img width="1023" alt="Screen Shot 2020-06-01 at 12 02 03 AM" src="https://user-images.githubusercontent.com/6392049/83375216-263d5200-a39c-11ea-8556-1e0c8281ec2e.png">

Dynamically generated string template tags, such as Hashes, Timestamps, and UUIDs, render once and don't change (so a timestamp, for example, may not accurately represent the request's name):

<img width="1022" alt="Screen Shot 2020-06-01 at 12 02 23 AM" src="https://user-images.githubusercontent.com/6392049/83375245-40773000-a39c-11ea-9a85-2b161f9521e7.png">

And finally, if there's an error with a template tag or environment variable we fall back to the raw, un-rendered URL:

<img width="1023" alt="Screen Shot 2020-06-01 at 12 00 31 AM" src="https://user-images.githubusercontent.com/6392049/83375447-e5920880-a39c-11ea-92ef-cd277a571f5f.png">

---

This could probably use some tests, but I can't seem to find any integration or component-level tests (maybe I'm just blind) - if you have suggestions for testing I'll be happy to add them.

2020-06-01 13:43 UTC, jodyheavener reviewed
Little self-review.

2020-06-01 13:43 UTC, jodyheavener commented on packages/insomnia-app/app/ui/components/base/editable.js
> +    const value = this._input.value.trim() || this.props.fallback;
I think this should be undone. This is assigning the fallback value _to_ the name instead of allowing the fallback to be used at render time.

2020-06-01 13:43 UTC, jodyheavener commented on packages/insomnia-app/app/ui/components/sidebar/sidebar-request-row.js
> +  async _setRenderedUrl(props) {
Consider throttling this. We probably don't need to update for _every_ keystroke, and it might reduce the likelihood of seeing the unparsed value rendered in the sidebar if you're hand-typing an env var.

2020-06-01 13:43 UTC, jodyheavener commented on packages/insomnia-app/app/ui/components/modals/request-create-modal.js
> +      this._input.placeholder = 'Your request URL';
Hmmmm. Mixing "My" and "Your"...

2020-06-02 22:21 UTC, gschier requested changes
This is a really awesome improvement, thanks for doing it! I just have a few minor comments before we can merge 😁

2020-06-02 22:21 UTC, gschier commented on packages/insomnia-app/app/ui/components/modals/request-create-modal.js
> +      this._input.placeholder = 'Your request URL';
It's usually recommended to set placeholder as an example of a valid value. I would prefer using "My Request" for both placeholder and value.

2020-06-02 22:21 UTC, gschier commented on packages/insomnia-app/app/ui/components/sidebar/sidebar-request-row.js
> +                  fallback={this.state.renderedUrl}
We should probably show something when both name and URL are blank

2020-06-02 22:21 UTC, gschier commented on packages/insomnia-app/app/ui/components/sidebar/sidebar-request-row.js
> +  async _setRenderedUrl(props) {
Yes, debouncing it seems like a good idea. 

Here's a good example to follow:
https://github.com/Kong/insomnia/blob/819f4b9cf57f433378cb9620ca671e51db365067/packages/insomnia-app/app/ui/components/rendered-query-string.js#L17-L22

2020-06-03 00:36 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/request-create-modal.js
> +      this._input.placeholder = 'Your request URL';
A thought I had was to somehow mark the name as optional, eg the placeholder set as "My Request (optional)" and the value unset.

Then the sidebar can decide for itself whether to show the name, the URL, or a placeholder (while there is no name and no url). 😄

2020-06-05 00:07 UTC, jodyheavener commented
@gschier updated to reflect your feedback. Notably:

A _truly_ empty request name now displays an "Empty" label, which looks slightly visually different than a valid name/URL value:

<img width="1331" alt="Screen Shot 2020-06-04 at 7 58 31 PM" src="https://user-images.githubusercontent.com/6392049/83822242-7c610c80-a69e-11ea-88ab-63a88b4097a2.png">

And, the New Request modal now has a helper label next to "Name" that indicates the default will be your request URL (cc @develohpanda):

<img width="1330" alt="Screen Shot 2020-06-04 at 8 05 32 PM" src="https://user-images.githubusercontent.com/6392049/83822369-cf3ac400-a69e-11ea-95fe-e6f18f6b3fd4.png">

2020-06-16 18:09 UTC, gschier approved these changes
Nice work on the empty state! I'm excited to get this in

![](https://media0.giphy.com/media/l2JHRhAtnJSDNJ2py/giphy.gif)

2020-06-30 20:53 UTC, merged