Unit Testing POC
getinsomnia/insomnia pull request #2232
Opened 2020-06-01 23:47 UTC by gschier

2020-06-11 23:39 UTC, develohpanda reviewed
Looks great! I've added a couple of comments that may be worth addressing now, but most are improvements for future.

2020-06-11 23:39 UTC, develohpanda commented on packages/insomnia-testing/src/generate/__tests__/index.test.js
> +// @flow
Should this be called `fixtures.test.js` to match with the other fixture tests?

2020-06-11 23:39 UTC, develohpanda commented on packages/insomnia-testing/src/generate/__tests__/index.test.js
> +    if (prefix.startsWith('skip')) {
Nice

2020-06-11 23:39 UTC, develohpanda commented on packages/insomnia-testing/src/generate/index.js
> +}
This feels better placed as a testing utility rather than exported from this package / production code

2020-06-11 23:39 UTC, develohpanda commented on packages/insomnia-testing/src/generate/index.js
> +}
I think the logic could be greatly simplified by replacing the indenting logic with prettier (or something more lightweight). This way it just becomes a few `.map` calls, plus the formatting can be made optional given it is typically going to be read by a machine.

Thoughts?

2020-06-11 23:39 UTC, develohpanda commented on packages/insomnia-testing/src/generate/index.js
> +export async function generate(suites: Array<Suite>): Promise<string> {
Don't think this needs to be `async`

```suggestion
export function generate(suites: Array<Suite>): string {
```

2020-06-11 23:39 UTC, develohpanda commented on packages/insomnia-testing/src/run/index.js
> +    const m = new Mocha({
Naming 😛 When reviewing a change to this file where the assignment `const m = new Mocha` is not shown, it'll be a tricky diff.

```suggestion
    const mocha = new Mocha({
```

2020-06-11 23:39 UTC, develohpanda commented on packages/insomnia-testing/src/run/insomnia.js
> +};
I'm a little torn about re-declaring these types, when we already have the types defined in the core application.

In future once we have extracted logic out of `insomnia-app`, it would be nice to not redefine the types here and maintain the single source of truth.

Same with the types in `openapi-2-kong`

2020-06-11 23:39 UTC, develohpanda commented on packages/insomnia-testing/src/run/reporter.js
> + * NOTE: This is a straight copy of the default Mocha JSON reporter, except
Is that source on github? Useful to add a permalink to this comment.

Also maybe mark what has been changed in this file explicitly. The comment here says stdout logging has been removed, _but where from and what replaced it_? 😄

2020-06-11 23:39 UTC, develohpanda commented on packages/insomnia-testing/webpack.config.js
> +    // import the test file because it lives outside the bundle.
👍

Could even go to the extent of writing a unit test to check this because it is a fairly critical issue if this setting is changed.

2020-06-11 23:39 UTC, develohpanda requested changes
Oops, clicked the wrong button before 😞

2020-06-11 23:44 UTC, sonicyeti commented on packages/insomnia-testing/flow-typed/axios.js
> +// @flow
Can we centralize our 3rd party module export declarations? I feel like we have batches of these sprinkled around.

2020-06-11 23:45 UTC, sonicyeti approved these changes
Excited that you've broken ground on this so quickly, can't wait to see how the UI manifests around this.

2020-06-11 23:48 UTC, develohpanda commented on packages/insomnia-testing/flow-typed/axios.js
> +// @flow
Maybe we could Script our Type management

😉

2020-06-16 17:35 UTC, gschier commented on packages/insomnia-testing/src/generate/index.js
> +}
I'm inclined to take the simple route for now. Prettier is a fairly large dependency and users may not like their code being reformatted from under them.

2020-06-16 17:40 UTC, gschier commented on packages/insomnia-testing/src/generate/index.js
> +}
If we needed to do something more complicated than indent, I might agree. However, the indent code here seems simple enough, has solid tests, and doesn't seem like it'll need to change much over time. I usually prefer in-house code over external dependencies for things of this nature.

2020-06-16 17:44 UTC, gschier commented on packages/insomnia-testing/src/run/insomnia.js
> +};
I'm not quite sure what the best thing for this is at the moment. Sometimes it's good to have libraries define their own types because it reduces coupling. I think, if it ends up that the testing package needs to know that Insomnia exists, sharing types could make sense. However, if we can have the testing package only have to care about things inside itself, I think it makes more sense to define it's own types (they may even be slightly different than the ones in Insomnia).

2020-06-16 17:48 UTC, gschier commented on packages/insomnia-testing/webpack.config.js
> +    // import the test file because it lives outside the bundle.
Do you have a suggestion for this? It would require building the Webpack library for the test to use. Perhaps we could have some integration tests that run the production bundle.

2020-06-16 20:41 UTC, develohpanda commented on packages/insomnia-testing/src/generate/index.js
> +}
> I usually prefer in-house code over external dependencies for things of this nature

Curious to dig into this one. But sounds good to leave as-is for this PR, for the reasons you gave. 👍

2020-06-16 20:55 UTC, develohpanda commented on packages/insomnia-testing/webpack.config.js
> +    // import the test file because it lives outside the bundle.
A MVP test that will _break_ when `mocha` is removed from externals. Something as simple as:

```js
import config from 'webpack.config.js'
...
expect(config.externals.mocha).toBe('mocha');
```

2020-06-16 21:54 UTC, develohpanda approved these changes
![](https://media2.giphy.com/media/11sBLVxNs7v6WA/giphy.gif)

2020-06-18 00:14 UTC, develohpanda commented on packages/insomnia-testing/webpack.config.js
> +    // import the test file because it lives outside the bundle.
Added https://github.com/Kong/insomnia/blob/b1f30cdb20e79c183aff1fde463f7f4ea6d02926/packages/insomnia-testing/src/__tests__/integration.test.js#L12-L16

2020-06-18 00:21 UTC, merged