Fixes #2208: Displays nicer error message given empty input when installing plugins
getinsomnia/insomnia pull request #2238
Opened 2020-06-02 19:08 UTC by nicholasraphael

Closes #2208 

This PR implements a nicer error message when handling empty input when clicking install plugin. It points the user to https://insomnia.rest/plugins/ to get the package names

Previous:
![image](https://user-images.githubusercontent.com/10778130/83559405-86d6a700-a4e2-11ea-9c87-926224f07bc5.png)

With this PR:

<img width="777" alt="Screenshot 2020-06-02 15 00 17" src="https://user-images.githubusercontent.com/10778130/83559438-948c2c80-a4e2-11ea-9da6-632baccdbeac.png">

2020-06-02 21:05 UTC, develohpanda reviewed
Hi @nicholasraphael! Thanks for working on this. 🤗 

My only bit of feedback would be, that we still need to indicate that plugin installation failed, and then perhaps direct them to the plugin hub.

How about something like:
> Failed to install "[plugin-name]", there may be an issue with the plugin itself. You can discover and install plugins from the [Plugin Hub](https://insomnia.rest/plugins/).

@nijikokun any thoughts on wording?

2020-06-02 22:06 UTC, nicholasraphael commented
@develohpanda Okay that sounds good thank you. I'll wait on input from @nijikokun before making any further changes.

2020-06-02 22:50 UTC, nijikokun commented
Awesome work so far! 

> Failed to install "[plugin-name]", there may be an issue with the plugin itself. You can discover and install plugins from the [Plugin Hub](https://insomnia.rest/plugins/).

This looks really good, just a few adjustments:

> **Failed to install "[plugin-name]"**
>
> There may be an issue with the plugin itself, as a note you can discover and install plugins from the [Plugin Hub](https://insomnia.rest/plugins/).
> <details>
> <summary>Additional Information</summary>
> <code>[error output]</code>
> </details>

❤️

2020-06-03 02:43 UTC, nicholasraphael commented
@nijikokun just want to know if the 'Additional Information' dropdown is a priority. I feel like it would require more code additions/changes than anticipated.

2020-06-03 03:35 UTC, develohpanda commented
> If the 'Additional Information' dropdown is a priority.

Not a priority 😄 

> I feel like it would require more code additions/changes than anticipated.

If you would like to try it, it should be fairly quick. It would involve storing the entire Error object (instead of just the error message) in State, and default that property in state to be `null` instead of `''`.

As for the collapsible component, you could use the `<details>` [HTML5 tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details). Here's an example of where that is used: https://github.com/Kong/insomnia/blob/819f4b9cf57f433378cb9620ca671e51db365067/packages/insomnia-app/app/ui/components/modals/error-modal.js#L66-L73

2020-06-03 14:31 UTC, nicholasraphael commented
@develohpanda Thanks for the help. I have gone with the changes suggested let me know if it's good. 

<img width="775" alt="Screenshot 2020-06-03 10 28 47" src="https://user-images.githubusercontent.com/10778130/83649534-4e3bd980-a585-11ea-93bc-323ed1ca352d.png">

2020-06-03 22:46 UTC, develohpanda requested changes
Nice one! Almost there, a couple of small changes.

Namely, I don't see the need to have two items in state to represent an error; so we can remove `installPluginErrMsg` and simply put that message in the `render` itself. 😄

2020-06-03 22:46 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/plugins.js
> +  error: Object,
This can be typed explicitly :)

```suggestion
  error: Error | null,
```

2020-06-03 22:46 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/plugins.js
> +              <b>{installPluginErrMsg}</b>
Since we can remove this from state, it can simply be:

```suggestion
              <b>Failed to install "{npmPluginValue}"</b>
```

2020-06-03 22:46 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/plugins.js
> +                  <code>{error.stack || error}</code>
I suggest changing this to just show `error.message`, which was the previous behavior (where `error.message` was added to state and rendered on the UI).

```suggestion
                  <code>{error.message}</code>
```

2020-06-03 22:46 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/plugins.js
> +      newState.error = err;
We should only need to store `error` on state, and can move the text "Failed to install..." directly into the `render()` function

```suggestion
      newState.error = err;
```

2020-06-04 13:55 UTC, nicholasraphael commented on packages/insomnia-app/app/ui/components/settings/plugins.js
> +      newState.error = err;
Okay! I originally added this new state because when using `npmPluginValue` in `render()` when the `error` is displayed and user types the text changing is reflected in the error.

2020-06-06 01:01 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/plugins.js
> +      newState.error = err;
Oh I see! Makes sense. In that case this is fine. 🤗

2020-06-06 01:10 UTC, develohpanda approved these changes
Looks good, thanks for doing this!

I will make some minor spacing adjustments once this is merged, but the functionality is great. 💯

2020-06-06 01:11 UTC, merged