Feature: Show Dev Tools with hotkeys
getinsomnia/insomnia pull request #2309
Opened 2020-06-18 16:55 UTC by nicholasraphael

Closes #2157 

We want to allow users to show Dev Tools with ⌘⌥I (or ⌃⇧I) like all the browsers do, and many Electron apps.

2020-06-18 17:37 UTC, gschier requested changes
Thanks for taking this one on @nicholasraphael! 

The solution here is actually much simpler than you might expect. In `window-utils.js` you will notice the menu item for toggling devtools. There are actually two in there: one in the Developer menu (which has an "accelerator" and is only shown when building from source) and one in the View menu (which doesn't have a hotkey). We should be able to add the Accelerator to the item in the View menu and remove the menu item from the Develop menu.

Let me know if that makes sense! ⚡

2020-06-21 03:43 UTC, nicholasraphael commented
@gschier Thanks for the help 😄! Let me know if this is looking good.

2020-06-23 23:55 UTC, gschier requested changes
One comment but looks good after that's addressed!

2020-06-23 23:55 UTC, gschier commented on packages/insomnia-app/app/common/hotkeys.js
> +  SHOW_DEVTOOLS: defineHotKey('showDevTools', 'Show Developer Tools'),
We don't actually need the edits you made to this file, since we don't currently have a way to configure hotkeys for actions in the app titlebar.

2020-06-25 17:37 UTC, nicholasraphael commented on packages/insomnia-app/app/common/hotkeys.js
> +  SHOW_DEVTOOLS: defineHotKey('showDevTools', 'Show Developer Tools'),
Removed the edits

2020-06-25 22:34 UTC, gschier approved these changes
Nice, thanks for this! 

![](https://media3.giphy.com/media/nXxOjZrbnbRxS/giphy.gif)

2020-06-29 18:48 UTC, merged