Add unit testing to CLI, configurable Mocha reporter
getinsomnia/insomnia pull request #2311
Opened 2020-06-19 04:42 UTC by develohpanda

New command: `inso test run --reporter progress --bail`

- Add support for various Mocha reporters (only supports single reporter for now, can support multiple in future with [mocha-multi-reporters](https://www.npmjs.com/package/mocha-multi-reporters)).
- Add support for `--bail` Mocha flag

<img width="934" alt="image" src="https://user-images.githubusercontent.com/4312346/85097454-afcd9a80-b24b-11ea-95a7-26cf4fbd0888.png">

> Note: currently fails with the reference error, resolved in a separate branch

Todo:
- [ ] Exit code 1 if any test failures
- [ ] Unit tests

2020-06-25 22:43 UTC, gschier requested changes
A few minor comments but it looks pretty much good to go!

2020-06-25 22:43 UTC, gschier commented on packages/insomnia-cli/src/commands/run-tests.js
> +    return;
Should be exiting with error code here right?

2020-06-25 22:43 UTC, gschier commented on packages/insomnia-testing/src/run/index.js
> +        mocha.reporter(Mocha.reporters.Dot);
`reporter()` accepts a string too instead of a constructor so this switch may not be necessary. I'm fine with the explicitness if you want to leave it, though.

2020-06-25 22:43 UTC, gschier commented on packages/insomnia-testing/src/run/index.js
> +      resolve(runner.testResults || { stats: runner.stats });
I wonder if we should have two separate `runTest` functions. One for running tests that return a JS object and one that outputs to `stdout`. I think that would clean of some of the logic in here like this part. If it's not the `js` runner, we don't really need to return anything.

2020-06-26 00:19 UTC, develohpanda commented on packages/insomnia-testing/src/run/index.js
> +      resolve(runner.testResults || { stats: runner.stats });
We _do_ need to return stats, so that `inso` can exit with an appropriate exit code (#2318 does this). We could also use https://www.npmjs.com/package/mocha-multi-reporters to always use the JS reporter, in addition to whatever the user specifies (although I didn't test it).

2020-06-26 00:19 UTC, develohpanda commented on packages/insomnia-testing/src/run/index.js
> +        mocha.reporter(Mocha.reporters.Dot);
Oh 😆 removing the switch would be ideal, so I will clean this up (in a separate PR)

2020-06-26 00:20 UTC, develohpanda commented on packages/insomnia-cli/src/commands/run-tests.js
> +    return;
Yah, done so in #2318 <3

2020-06-26 00:32 UTC, gschier commented on packages/insomnia-testing/src/run/index.js
> +      resolve(runner.testResults || { stats: runner.stats });
Oh I see. So the reporter prints to the console as it runs but the stats are the only way to detect whether it passed or failed? 

My hesitation here is that `runTests()` returns an object with more than just a stats field. Since these two cases return different shapes, it may make sense to have another function that simply returns stats (or even a boolean if that's all we need).

2020-06-26 00:32 UTC, gschier commented on packages/insomnia-cli/src/commands/run-tests.js
> +    return;
Nice!

2020-06-26 00:39 UTC, develohpanda commented on packages/insomnia-testing/src/run/index.js
> +      resolve(runner.testResults || { stats: runner.stats });
> The stats are the only way to detect whether it passed or failed?
To my knowledge, that's correct. The `stats` property is populated by each reporter.

I agree about separating the functions. One is solely for the JS reporter (and does not allow for overriding the reporter, used by insomnia-app), while the other function has a configurable mocha reporter. Will make the change.

2020-06-29 18:50 UTC, gschier commented on packages/insomnia-testing/src/run/index.js
> +
Nice refactor!

2020-06-29 18:57 UTC, gschier approved these changes
Looks good after we get those conflicts resolved 🥳

2020-06-29 21:54 UTC, merged