Update test fixtures and support sendRequest() callback
getinsomnia/insomnia pull request #2325
Opened 2020-06-26 00:09 UTC by gschier

This PR adds a `sendRequest` callback to the `insomnia-testing` package to enable the ability to use the app's native networking library to handle requests. It's still rough but should be a good starting point until we have a better understanding of the requirements.

2020-06-26 00:12 UTC, gschier commented on packages/insomnia-testing/src/generate/index.js
> +  lines.push(`const { expect } = chai;`);
This is not cool. Since the tests are being run inside a Jest environment, it wasn't complaining that `expect()` did not exist as a global. Once I tried using it in the app, it didn't exist. In the future, I think it would be better to somehow run the tests in a sub-process or something, so no global state is shared.

2020-06-26 06:48 UTC, develohpanda requested changes
> This PR also changes runTests() to accept stringified source code instead of a file path.

I agree with this, but I've made two points further down that I think are worth discussing before merging.

Nice work pulling in `insomnia` networking magic. Is there anything extra we need to think about when trying to get these tests to run through CLI?

2020-06-26 06:48 UTC, develohpanda commented on packages/insomnia-testing/src/generate/index.js
> +  lines.push(`const { expect } = chai;`);
Explains why tests also failed when running from CLI. Worth nothing this as a TODO in the code itself and/or creating a card on the kanban board

2020-06-26 06:48 UTC, develohpanda commented on packages/insomnia-testing/src/generate/index.js
> +  });
What was the reason for this change? 🤔

2020-06-26 06:48 UTC, develohpanda commented on packages/insomnia-testing/src/run/index.js
> +}
Two notes about this:
1. we should generate to a folder in the tempdir (like most other applications),
2. we should make sure to delete the file after generation. It might be good to have the option to keep the file as well, maybe? 👇 From CLI #2318 
https://github.com/Kong/insomnia/blob/c593b396a8c9a9526ae1f4d0c82788c3b91478ef/packages/insomnia-cli/src/cli.js#L43 https://github.com/Kong/insomnia/blob/c593b396a8c9a9526ae1f4d0c82788c3b91478ef/packages/insomnia-cli/src/commands/run-tests.js#L33-L44

2020-06-26 06:48 UTC, develohpanda commented on packages/insomnia-testing/src/run/index.js
>  // @flow
We're going to have some conflicts with this file 😢 lets cross that bridge when we get to it

2020-06-26 06:48 UTC, develohpanda commented on packages/insomnia-testing/src/run/insomnia.js
> +  sendRequest?: (requestId: string) => Promise<$Shape<Response>>,
Yay `$Shape<T>` 🎉

2020-06-26 20:41 UTC, gschier commented on packages/insomnia-testing/src/generate/index.js
> +  });
Ya, you get a big angry warning when using the `fs.promises` API in our current version of Node 
![image](https://user-images.githubusercontent.com/587576/85899350-c2e3eb80-b7b2-11ea-8810-65ec870b75ff.png)

2020-06-26 20:45 UTC, gschier commented on packages/insomnia-testing/src/run/index.js
> +}
I like keeping the temp file around because it provides the ability to debug if you get an exception that includes a stack trace. Since the files are so small, it doesn't seem like a big deal to keep the files around until the OS cleans them up. 

I would side on not deleting them unless there is a good reason to do so but am not super adamant on it. Thoughts?

2020-06-26 20:46 UTC, gschier commented on packages/insomnia-testing/src/run/index.js
> +}
A agree with the folder thing, though. Will address that one.

2020-06-27 03:17 UTC, develohpanda commented on packages/insomnia-testing/src/generate/index.js
> +  });
Oh I see 🤔 I thought git-sync was using `fs.promises`, but I now see the elusive workaround (and future proofing 😉)

https://github.com/Kong/insomnia/blob/1c46b95ac90b16cc099ad8657ace91398eba149c/packages/insomnia-app/app/sync/git/fs-plugin.js#L61

`mem-db.js` in the CLI currently uses `fs.promise`, I suppose that needs to be updated? Thought I haven't seen this warning.

2020-06-27 03:20 UTC, develohpanda commented on packages/insomnia-testing/src/run/index.js
> +}
My thought are to:
1. Delete by default,
2. Keep file if there are any test failures (this can be configurable if need be)
3. Allow a `--keep-file` override to keep the file _always_ if you so desire.

But mainly, point 1 - deleting by default. Only in exceptional cases should you want/need to look at the file.

2020-06-29 17:34 UTC, gschier commented on packages/insomnia-testing/src/run/index.js
> +}
Added the deletion logic and sub folder 😄

2020-06-29 17:35 UTC, gschier commented on packages/insomnia-testing/src/generate/index.js
> +  });
Perhaps Node doesn't show those types of warnings. I'm not sure

2020-06-29 17:40 UTC, merged