Design sidebar
getinsomnia/insomnia pull request #2328
Opened 2020-06-26 20:05 UTC by sonicyeti

Initial PR covering the integration of the latest sidebar design into both SB and the application.

2020-06-27 03:01 UTC, develohpanda requested changes
Had a play around in the storybook and it looks amazing. I have added some notes regarding the implementation side of it. The rest are open for discussion, however we should address index as keys in _this_ PR.

2020-06-27 03:01 UTC, develohpanda commented on packages/insomnia-components/components/sidebar.js
> +  const toggleInfoSec = () => setInfoSec(!infoSec);
Quick note: these callbacks will always create a new instance every time, causing the child components to update unnecessarily due to a prop change, even though most of the `toggle` callbacks will remain unchanged.

I suggest the `useCallback` [hook ](https://reactjs.org/docs/hooks-reference.html#usecallback) to set these, which returns a memoized callback if the dependencies (in this case, `infoSec` and `setInfoSec`) don't change. It's a little more verbose, but you can write your own hook to wrap that logic, eg:

```js
const useToggle = (state, set) => React.useCallback(() => set(!state), [set, state]);
```

Resulting in 
```suggestion
  const toggleInfoSec = useToggle(infoSec, setInfoSec);
```

2020-06-27 03:01 UTC, develohpanda commented on packages/insomnia-components/components/sidebar.js
>  }
Is suggest to break this component down in several ways:
1. By each logical section. Components like `<SidebarServers servers={props.spec.servers} />`. Each component can then contain it's respective state and dispatch values, isolated.
2. By the styled components, and the children you expect inside each styled component. A good example would be `StyledFilter` (see comment below).
3. As a nice to have, basic stories for each `<Sidebar* />` component in addition to the all-in-one.

I think you've done an amazing job with how it visually looks. With this breakdown, it will be much easier to unit test, debug and review, and will remove a lot of the code duplication.

Thoughts?

2020-06-27 03:01 UTC, develohpanda commented on packages/insomnia-components/components/sidebar.js
> +            </StyledFilter>
Sections like this are duplicated a lot, with the only difference being the value (`schemasFilter` vs `headerFilter`) and the `onChange` handle. Perfect candidate for a component.

The `StyledFilter` is a filter component with only styling. A `SidebarFilter` can be made, which contains a `StyledFilter`, as well as the actual filtering logic and children.

This way, when composing the sidebar itself, adding a filter will be a one-liner:
```
<SidebarFilter filter={headerFilter} onChange={setHeaderFilter} />
<SidebarFilter filter={schemasFilter} onChange={setSchemaFilter} />
```

2020-06-27 03:01 UTC, develohpanda commented on packages/insomnia-components/components/sidebar.js
> +              <React.Fragment key={index}>
Index as key is a [cause for concern]( https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318), we should definitely look to fix this. Some other instances of it in this components too.

ES Lint should have picked it up, [this rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-array-index-key.md) may not be enabled.

2020-06-27 03:01 UTC, develohpanda commented on packages/insomnia-components/components/sidebar.js
> +            <Dropdown renderButton={({ open }) => <SvgIcon icon={IconEnum.ellipsesCircle} />}>
I believe this syntax will result in this drop-down component and it's children updating on every render. The inline function will mean a new instance is sent every time. Definitely a candidate to declare the a button component outside the component, and consume it here. Also, looks like the `open` prop isn't being used so I have removed it. Eg:
```
const DropdownElipsis = () => <SvgIcon icon={IconEnum.ellipsesCircle} />;
```

```suggestion
            <Dropdown renderButton={DropdownElipsis}>
```

2020-06-27 03:01 UTC, develohpanda commented on packages/insomnia-components/components/sidebar.js
> +  const [serverFilter, setServerFilter] = useState('');
I wonder if the state declarations might benefit from `useReducer` instead of `useState`. Easier to test, and less verbose.

2020-06-29 19:04 UTC, gschier requested changes
@develohpanda did a great job reviewing this! I just had one other comment about adding a click handler so we can hook up the click-to-scroll later.

2020-06-29 19:04 UTC, gschier commented on packages/insomnia-components/components/sidebar.js
> +  jsonData: Object,
We're going to need some sort of event handlers here. I suggest an `onClick` to start that returns an array containing the path to the object that was clicked. 

```js
onClick: (specPath: Array<string | number>) => void,
```

For example, clicking on an operation (request) might call the `onClick` handler with `[ 'paths', '/foo', 'get' ]`

2020-06-29 19:18 UTC, sonicyeti commented on packages/insomnia-components/components/sidebar.js
>  }
This sounds great, will start breaking these down now. Originally the plan was one item type to rule them all but we switched it mid-way where we have things like methods grouped/tucked under paths & results. The above will be much easier to work with.

2020-07-13 08:39 UTC, develohpanda requested changes
Nice one, it's looking at lot more concise, and it's nice to see some separation of concerns where the logic for rendering the requests is scoped, and the logic for rendering servers is scoped, etc.

A little more to go, many of the review comments added to one component apply to other components as well. There is a fair bit of functionality we can still abstract away and extract into reusable components, for readability and making the consumption of each component easier.

2020-07-13 08:39 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/spec-editor/spec-editor-sidebar.js
> +const jsyaml = require('js-yaml');
Interesting, is this not able to use ES6 imports?

2020-07-13 08:39 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/spec-editor/spec-editor-sidebar.js
> +
Can be removed

2020-07-13 08:39 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/spec-editor/spec-editor-sidebar.js
> +    }
Curious about this - could you please elaborate on why we need jsyaml given we only call it if the content type is _not_ yaml?

2020-07-13 08:39 UTC, develohpanda commented on packages/insomnia-app/app/ui/css/components/spec-editor-sidebar.less
> +  /*
Should the commented lines be removed altogether?

2020-07-13 08:39 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-filter.js
> +    {children}
Do any consumers of `SidebarFilter` currently set `children`? If not, we should remove this prop.

2020-07-13 08:39 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-header.js
> +  children?: React.Node,
- Given we are in a header component, the `headerTitle` prop can simply be `title`
- Is it possible to type the `toggleSection` and `toggleFilter` props more explicitly than `Function`? How about something like `toggleSection: () => void`
- A prop simply named `section` doesn't convey what it represents - I suggest something more explicit like bodyVisible/sectionVisible/sectionExpanded etc.

2020-07-13 08:39 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar.js
> +  );
Can be removed in favor of `useToggle` in `react-use`. All of the state declarations in this file can simplify, see usage in `SidebarSection`.

2020-07-13 08:39 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar.js
> +    <StyledSidebar className="theme--sidebar">
Feels a little strange to use a styled component and also a theme class - what is the reason for using both?

2020-07-13 08:39 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar.js
> +// @flow
Worth renaming this file to `index.js` given it's in the `sidebar` folder

2020-07-13 08:39 UTC, develohpanda commented on package.json
> +    "react-use": "^15.3.2"
Doesn't need to be in the root `package.json`

2020-07-13 08:39 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-header.js
> +      {!children && (
```suggestion
      {children || (
```

2020-07-13 08:39 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar.js
> +  className?: string,
`className` prop is not used

2020-07-13 08:39 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar.js
> +  }
None of these elements exist directly in this component; they exist in child components - I suggest these styles be moved closer to where they are used.

2020-07-13 08:39 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-servers.js
> +};
This on click handler, and the element it is linked to, is duplicated through each sidebar section component. Did you want to make a stab at extracting it to a component and reusing? 😄

2020-07-13 08:39 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-servers.js
> +          {server.url.includes(filter) && (
It would be nice to have a placeholder in the empty state (eg. "no results"), which would require a small refactor here. The empty state could also be handled by the `SidebarSection`, so lets discuss some ideas on how to go about doing that.

Currently, this is what the empty state looks like. 

<img width="404" alt="image" src="https://user-images.githubusercontent.com/4312346/87275847-2603ab00-c533-11ea-92b0-f1167276a694.png">

2020-07-13 08:39 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-servers.js
> +              <div></div>
Rogue empty div? Same with the other components

2020-07-13 08:39 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-security.js
> +          {scheme.toLowerCase().includes(filter) && (
Filtering should be case-insensitive (same with the other components)

<img width="401" alt="image" src="https://user-images.githubusercontent.com/4312346/87276208-fb662200-c533-11ea-868d-c41143f6dabe.png">

<img width="399" alt="image" src="https://user-images.githubusercontent.com/4312346/87276230-04ef8a00-c534-11ea-80d0-c3b959b21cd0.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/4312346/87276257-13d63c80-c534-11ea-8b58-7a27d8607dd8.png">
(no results)

2020-07-13 08:39 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-info.js
> +export default class SidebarInfo extends React.Component<Props> {
Can be a function component, the code comment does not apply to this component

2020-07-13 08:39 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-item.js
> +export default SidebarItem;
This component is just a proxy into `StyledItem`, but that means places `SidebarItem` is consumed, there is an empty div to consume the first grid column.

In order to consume `SidebarItem`, one shouldn't need to consider how the `SidebarItem` is styled, so with that in mind, lets discus some ways to abstract that away. 😄 

Same goes for the `SidebarBlockItem`.

2020-07-13 08:39 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-info.js
> +        )}
Destructuring props, and extracting a reusable component in this file would make this really concise 😄

2020-07-13 08:39 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-panel.js
> +  parent: boolean,
What does `parent` represent? I suggest to name the prop according to what it controls in _this_ component. What this prop is linked to, is the responsibility of the consumer. 😄

2020-07-13 08:39 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-requests.js
> +      {Object.keys(this.props.requests).map((requestName, value) => (
This component can again be broken down, for readability if not for reuse. 👍

2020-07-13 08:39 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-requests.js
> +                        className="method-post"
Should this className be hard-coded? Feels like it should be linked to the request method 🤔

2020-07-13 08:39 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-paths.js
> +          {path[0].includes(filter) && (
`path[0]` and `path[1]` are difficult to understand, given they are typed as `any`.

I suggest settings the required array items to named variables and consuming those.

`const [foo, bar] = path;`

2020-07-14 20:13 UTC, sonicyeti commented on packages/insomnia-components/components/sidebar/sidebar-panel.js
> +  parent: boolean,
Parent wrapper visibility, yeah this could be much clearer.

2020-07-15 14:16 UTC, sonicyeti commented on packages/insomnia-components/components/sidebar/sidebar.js
> +    <StyledSidebar className="theme--sidebar">
This is to pickup our inline styling back on preview-head.html, where we essentially dump all CSS variables from core theming. Not an ideal solution and temporary until we centralize all shared styling variables.

2020-07-15 16:01 UTC, sonicyeti commented on packages/insomnia-components/components/sidebar/sidebar.js
> +  }
I was able to move them all except svg, which spans header, section, panels and items. Header & section are flat from a DOM perspective due to the header being the target to hide/show panels while persisting visibly.

2020-07-15 16:02 UTC, sonicyeti commented on packages/insomnia-components/components/sidebar/sidebar-servers.js
> +};
Yeah, this was the start of the separate path reveal to the app's code editor wrapper class. This will not be present next round!

2020-07-21 02:10 UTC, develohpanda approved these changes
Couple of things worth addressing, either in this PR or a separate one, otherwise good to go. 👍

2020-07-21 02:10 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-info.js
> +    <SidebarPanel childrenVisible={props.childrenVisible}>
Since all of the children in `SidebarPanel` (title, description, version, license.name) are conditional, if _none_ of them are present an empty panel would render.

What happens/should happen in that case? Should we be rendering `null` (ie. nothing) or an empty `SidebarPanel`?

2020-07-21 02:10 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-panel.js
> +  childrenVisible: boolean,
🔥

2020-07-21 02:10 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar.stories.js
> +      url: 'https://dev.kongonghq.com/v1',
😆

2020-07-21 02:10 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-requests.js
> +          <React.Fragment key={requestName}>
I suggest destructing the request data up here.

```js
const {description, content} = this.props.requests[requestName];
...
<Tooltip message={description} ... />
...
{Object.keys(content).map(format => (
    ...
    {Object.keys(content[format].examples).map(requestExample => (...))}
    ...
  )
}
```

2020-07-21 02:10 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-responses.js
> +              <SidebarItem>
This can be simplified now

```suggestion
        {filteredValues.map(response => (
          <SidebarItem key={response}>
```

2020-07-21 02:10 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-schemas.js
> +              <SidebarItem>
```suggestion
        {filteredValues.map(schema => (
          <SidebarItem key={schema}>
```

2020-07-21 02:10 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-paths.js
> +            {route.includes(filter.toLocaleLowerCase()) && (
This check should be in the filter above on line 29 and not here, I think?

2020-07-21 02:10 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-section.js
> +          <StyledNoResults>No results found for "{filterValue}"...</StyledNoResults>
👍

2020-07-21 12:34 UTC, sonicyeti commented on packages/insomnia-components/components/sidebar/sidebar-info.js
> +    <SidebarPanel childrenVisible={props.childrenVisible}>
Great point, I'm going to back some overarching checks for top level sections into sidebar itself to we don't have empty panels.

2020-07-21 14:42 UTC, sonicyeti commented on packages/insomnia-components/components/sidebar/sidebar-requests.js
> +          <React.Fragment key={requestName}>
So much cleaner

2020-07-21 22:12 UTC, develohpanda approved these changes
Nice one 👍

2020-07-21 22:12 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-section.js
> +  }, [bodyVisible, toggleFilterVisible]);
Nice! I had to research about the difference between `useEffect` and `useLayoutEffect`, [TIL](https://daveceddia.com/useeffect-vs-uselayouteffect/)! 🤗

2020-07-21 22:12 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-filter.js
> +  const filterField = React.createRef();
There is a `useRef` hook to use here in place of `React.createRef()`. Although I don't know the difference between them, would favor `useRef` to stay with hooks.

It would also be nice to achieve this without using a ref altogether, but I'm not totally sure what the solution might be right now (maintaining the value as state), so not going to suggest removing the ref yet. 😄

2020-07-21 22:17 UTC, gschier approved these changes

2020-07-22 13:13 UTC, merged