fix: prettify graphql based on user indentation size
getinsomnia/insomnia pull request #2344
Opened 2020-07-04 18:17 UTC by arjunkesava

Closes #2301 

By default, graphql comes with a default 2 space indentation.
If the user had a different tab space setting, then we should apply the indentation

2020-07-15 01:59 UTC, develohpanda requested changes
Thanks for the PR! I cloned locally and did some testing, and unfortunately it's not quite working as expected.

- [ ] Indent is only applied to the first level of nesting, not all levels
- [ ] If indent is set to 2, it clears the textbox
- [ ] Indent does not respect the `indent with tab` setting

🎉 

![2020-07-15 13 50 36](https://user-images.githubusercontent.com/4312346/87494252-a09f0880-c6a2-11ea-8e1b-1b2de65c8649.gif)

2020-07-15 01:59 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/body/graph-ql-editor.js
> +    const indentationSpace = Array(indentSize).join(' ');
This means the indent doesn't respect the `indent with tabs` setting and always applies space instead of tabs.

![image](https://user-images.githubusercontent.com/4312346/87494420-0ee3cb00-c6a3-11ea-83f0-96cc149391dd.png)

2020-07-15 17:45 UTC, gschier commented on packages/insomnia-app/app/ui/components/editors/body/graph-ql-editor.js
> +  }
This indentation strategy seems like there could be some edge-cases. For example, what happens if the user has `\n  ` in the query itself?

```graphql
mutation {
  addUser(bio: "this could have a newline \\n  some more stuff") {
    ...
  }
}
```

I think, ideally, we swap out for a different formatting strategy rather than try to patch it after the fact. There's also another downside of the `print(parse(` strategy we're using now, which is that any comments are discarded. Switching the formatter we use would also fix this problem.

2020-08-06 19:17 UTC, gschier commented
Thanks for the effort on this, but we're going to close this one as there isn't a reliable way to implement this using the existing formatter.

2020-08-06 19:17 UTC, closed without merging