Upgrade Electron
getinsomnia/insomnia pull request #2403
Opened 2020-07-14 00:03 UTC by gschier

Closes #2369 

## To-Do

- [x] Bump Electron version to 8
- [x] Update NPM config (`.npmrc`, etc) to target builds for new Electron version
- [ ] Identify and fix breaking Electron API changes (see below)
- [x] Switch from `font-manager` back to `font-scanner` as it was first to support Node 12
- [ ] Lots and lots of QA for anything that touches the Electron APIs
- [ ] QA Snap build, as apparently it works a lot better with newer versions of Electron
- [ ] **[ON HOLD]** Upgrade to Electron 9 once `node-libcurl` adds prebuilt binaries for it. We can help with this task if necessary

## Electron-Related Tasks

- [x] Specify `nodeIntegration: true` when creating `BrowserWindow`
- [ ] Re-do single-instance API to accommodate breaking changes

2020-07-27 08:00 UTC, develohpanda requested changes
Looking great 👍 Big effort!

Question regarding the file selection dialog responses, which now return a `{canceled, <result>}` object. Should we be validating the `result`? All appropriate uses check for the `canceled` property, but only some check for the `result`.

One really minor (but important) comment change suggested, otherwise good to go.

2020-07-27 08:00 UTC, develohpanda commented on .github/workflows/release-core.yml
> +          node-version: 12
I suggest we do something like this, to ensure workflows and local dev all depend on the exact same version of node (patch as well), defined in `.nvmrc`. Could do the same for `.npmrc` as well.

https://github.com/actions/setup-node/issues/32#issuecomment-525791142

Would help with reducing the number of `package-lock.json` changes.

2020-07-27 08:00 UTC, develohpanda commented on packages/insomnia-app/app/network/o-auth-2/misc.js
> -    // Force user-agent for GitHub until we update Chromium version. Note, we don't do this for
🎉

2020-07-27 08:00 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/base/file-input-button.js
> +    if (canceled && filePaths.length) {
Should this be the following?

```suggestion
    if (canceled || !filePaths.length) {
```

The two are not the same 🤔

2020-07-27 08:00 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/request-create-modal.js
> +                  <span className="txt-sm faint italic space-left">
Woah! Sneaked in during a recent PR.

2020-07-27 08:00 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/request-url-bar.js
> +    if (canceled) {
Should we be checking for `filePaths.length` here as well, similar to a previous comment?

```suggestion
    if (canceled || !filePaths.length) {
```

2020-07-27 08:00 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/viewers/response-multipart.js
> +    fs.writeFile(filePath, part.value, err => {
Are we able to use the `fs.promises` API for this now?

2020-07-27 08:00 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/viewers/response-web-view.js
> +    // NOTE: We *should* be setting the base URL like this, but there is a bug
```suggestion
    // NOTE: We *should* be setting the base URL by specifying the baseURLForDataURL option, but there is a bug
```

I had to read a few times to understand "this" was referring to the example at the end of the comment, not referring to the code above.

2020-07-27 08:00 UTC, develohpanda commented on packages/insomnia-app/app/ui/containers/app.js
> +      // NOTE: An error will be thrown if defaultPath is supplied but not a String
Should we check for `typeof defaultPath === 'string'`, in that case?

2020-07-27 08:00 UTC, develohpanda commented on packages/insomnia-app/scripts/build.js
> +    console.log('[build] Node v12.x.x is required to build');
👍 Nice, I would have missed this.

2020-07-27 08:00 UTC, develohpanda commented on packages/insomnia-app/webpack/webpack.config.development.babel.js
> -  },
Ahhh, `contentBase: '/'` is a fix for this warning suppression.

I remember facing these warnings, but the source-maps still loaded, so it was very confusing. Awesome to get to the bottom of it. 👍

2020-07-27 17:41 UTC, gschier commented on packages/insomnia-app/scripts/build.js
> +    console.log('[build] Node v12.x.x is required to build');
Hehe, hard to miss when it prevents the build from working 😆

2020-07-27 17:43 UTC, gschier commented on packages/insomnia-app/app/ui/containers/app.js
> +      // NOTE: An error will be thrown if defaultPath is supplied but not a String
LocalStorage always returns strings or `null`
https://developer.mozilla.org/en-US/docs/Web/API/Storage/getItem

2020-07-27 18:04 UTC, gschier commented on packages/insomnia-app/app/ui/components/viewers/response-multipart.js
> +    fs.writeFile(filePath, part.value, err => {
Yep! Looks like no errors are logged when using it now 😄

2020-07-27 18:06 UTC, gschier commented on packages/insomnia-app/app/ui/components/base/file-input-button.js
> +    if (canceled && filePaths.length) {
The Electron docs say the array will be empty if `canceled` is `true` so I don't think there's a need to check the length. I'll just remove it

2020-07-27 18:06 UTC, gschier commented on packages/insomnia-app/app/ui/components/base/file-input-button.js
> +    if (canceled && filePaths.length) {
Also, good catch! I definitely tested that change after making it but must have done a breaking refactor right afterwards without realizing.

2020-07-28 00:23 UTC, develohpanda approved these changes
Awesome, nice to be consistent with the file checking 😄 and yay for using `.nvmrc` in github actions. That's one less manual step (of remembering to change the node version in actions!)

2020-07-28 05:18 UTC, merged