[WIP] Support config file for inso
getinsomnia/insomnia pull request #2420
Opened 2020-07-16 00:14 UTC by develohpanda

2020-07-23 03:53 UTC, develohpanda commented on packages/insomnia-inso/src/util.js
> -export function getAllOptions<T>(cmd: Object): T {
Extracted to `get-options.js` because it is a little more complex now

2020-07-23 03:53 UTC, develohpanda commented on packages/insomnia-inso/src/__tests__/get-options.test.js
> +jest.unmock('cosmiconfig');
We need to explicitly unmock `cosmiconfig` to use the real module in order to test loading and merging correctly.

Using fixtures feels more understandable, than mocking the responses, and the `cosmiconfig` implementation itself moved away from mocks for the same reason.

2020-07-23 22:00 UTC, gschier submitted a review, later dismissed
Implementation looks good!

My only concern is potential config collisions, since everything in `settings` is flat. What happens if you have two commands with a `type` flag? To me, it seems like the only things in `settings` should be truly global.

2020-07-23 22:00 UTC, gschier commented on packages/insomnia-inso/src/get-options.js
> +    const results = configFile ? explorer.load(configFile) : explorer.search();
This is neat

2020-07-23 23:36 UTC, DMarby requested changes
This is great 🎉 
Just a few minor nitpicks

2020-07-23 23:36 UTC, DMarby commented on packages/insomnia-inso/src/__tests__/__snapshots__/inso-snapshot.test.js.snap
> +  -w, --workingDir <dir>  set working directory
Is the reason these went from kebab-case to camelCase so that they work well as keys in yaml/json?
I don't really mind either way, just curious :)

I guess we need to update the documentation in the README and such as well, since I think this would be a breaking change?

2020-07-23 23:36 UTC, DMarby commented on packages/insomnia-inso/src/cli.js
> +      // console.log(`> > inso ${scriptArgs.join(' ')}`);
Is this meant to be commented out?

2020-07-27 04:17 UTC, develohpanda commented on packages/insomnia-inso/src/__tests__/__snapshots__/inso-snapshot.test.js.snap
> +  -w, --workingDir <dir>  set working directory
Yep, that's the reason for switching from kebab to camel. I prefer kebab for a CLI though :(

2020-07-27 04:20 UTC, develohpanda commented on packages/insomnia-inso/src/cli.js
> +      // console.log(`> > inso ${scriptArgs.join(' ')}`);
Yep, I've left it out because piping commands seem to include this text 🤔 But also I feel like printing the command being run is misleading because it doesn't add in any flags extracted from the config file.

2020-07-27 04:25 UTC, develohpanda commented
> My only concern is potential config collisions, since everything in `settings` is flat. What happens if you have two commands with a `type` flag?

They will use the global, or use any overrides given in the command/script.

> To me, it seems like the only things in `settings` should be truly global.

Yeah, potentially. I would explicitly be ignoring any non-global options, rather than adding functionality to _support_ non-global options. It feels like it's okay to leave that up to the user but I'm not too pressed either way. Would you suggest to explicitly exclude any non-global options?

2020-07-27 13:05 UTC, DMarby commented on packages/insomnia-inso/src/cli.js
> +      // console.log(`> > inso ${scriptArgs.join(' ')}`);
Sounds fair enough!

2020-07-27 14:06 UTC, DMarby approved these changes

2020-07-27 21:29 UTC, gschier commented
> Would you suggest to explicitly exclude any non-global options?

That would be my preference, at least to start – especially since we don't know for sure that it will be useful. We can always add support for non-global options later if there's demand.

If we do end up adding command-specific settings, this would be my first approach:

```yaml
settings:
  ci: false
  command1:
    foo: bar
  command2:
    foo: baz
scripts:
  example1: inso command1 ...
  example2: inso command2 ...
  # ...
```

It's a bit more verbose but also a bit more readable, as it's clear which settings relate to which commands.

2020-07-28 00:47 UTC, develohpanda commented
> That would be my preference, at least to start – especially since we don't know for sure that it will be useful. We can always add support for non-global options later if there's demand.

That's fair, I agree - will update.

I considered command specific settings (similar to `.babelrc` and their NODE_ENV specific settings), but that was definitely scope creep. The flat structure we get for free, but I'll limit it.

2020-07-28 06:48 UTC, develohpanda commented on packages/insomnia-inso/src/cli.js
> +      // console.log(`> > inso ${scriptArgs.join(' ')}`);
I've added the console log back, given flags specific to a command don't exist in the config file any more :)

2020-07-28 09:27 UTC, DMarby approved these changes

2020-07-28 21:57 UTC, gschier approved these changes
![](https://media3.giphy.com/media/26gQth8MdtUhjtUD6/giphy.gif)

2020-07-28 23:47 UTC, merged