Add logs
getinsomnia/insomnia pull request #2432
Opened 2020-07-23 07:37 UTC by develohpanda

2020-07-24 12:38 UTC, DMarby approved these changes
Very nice 🎉

2020-07-24 18:40 UTC, gschier requested changes
Just a minor comment on simplifying the error handling logic.

2020-07-24 18:40 UTC, gschier commented on packages/insomnia-app/app/sync/git/git-vcs.js
> +  errors?: string[],
Nit: we usually use `Array<string>` in this codebase 🔍

2020-07-24 18:40 UTC, gschier commented on packages/insomnia-app/app/sync/git/git-vcs.js
> +    git.plugins.set('emitter', emitter);
Woah, that's a convenient hook.

2020-07-24 18:40 UTC, gschier commented on packages/insomnia-app/app/ui/components/dropdowns/git-sync-dropdown.js
> +      if (response.errors?.length) {
So only git-specific errors throw exceptions? Network errors return error responses?

2020-07-24 18:40 UTC, gschier commented on packages/insomnia-app/app/ui/components/dropdowns/git-sync-dropdown.js
> +      if (response.errors?.length) {
I wonder if it would simplify things if we checked `response.errors` inside `vcs.push()` and threw an error from there. Then the caller would only have to `try/catch` and not forget to check the errors array.

2020-07-27 01:35 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/dropdowns/git-sync-dropdown.js
> +      if (response.errors?.length) {
Git hooks that fail (on the server) are returned in the responses array, because the network request succeeded, but the git operation was rejected. Authentication issues are thrown as exceptions, because the network request is rejected.

This is how isomorphic-git is choosing to return the various responses anyway. I agree, checking the error within the vcs class is better than outside. I'll update this to make it nicer to consume.

2020-07-27 01:45 UTC, develohpanda commented on packages/insomnia-app/app/sync/git/git-vcs.js
> +  errors?: string[],
Oops, this was a straight copy-paste from the bundled Typescript declaration file in the `isomorphic-git` module.

I would expect code-style preferences to be governed by ES Lint rules (because nobody should need to think about them), so for this I will add:
- [array-style-simple-type](https://github.com/gajus/eslint-plugin-flowtype#array-style-simple-type)
- [array-style-complex-type](https://github.com/gajus/eslint-plugin-flowtype#array-style-complex-type)

2020-07-27 03:04 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/error-modal.js
> +                <code className="wide">{error.stack || error}</code>
I have a growing preference for `styled-components`. The changes in this file are meaningless unless the reviewer knows what CSS classes exist in the code-base and what they do.

2020-07-27 13:04 UTC, DMarby approved these changes

2020-07-27 21:33 UTC, gschier commented on packages/insomnia-app/app/sync/git/git-vcs.js
> +  errors?: string[],
Oh nice! That's a great addition 👍 🌟

2020-07-27 21:55 UTC, gschier commented on packages/insomnia-app/app/ui/components/modals/error-modal.js
> +                <code className="wide">{error.stack || error}</code>
I'm curious how `styled-components` might help. I haven't yet come across a solution for CSS utility classes for styled-components but I'm picturing something like MaterialUI's [`<Box>`](https://material-ui.com/components/box/#box) component that can modify (or wrap) the styles of its children. It would be quite a bit more verbose, however, and still requires us to learn/remember utility names.

I'm still a big fan of utility classes but you're right that they can be messy. Especially ours, which are home-grown and inconsistently named. If the main problem is documentation/standardization, perhaps [TailwindCSS](https://tailwindcss.com/docs/width/#app) would be a good substitute.

---

Zooming back out a bit, for components that use a lot of utility helpers like this, it might make sense to factor the styles out into a component-specific `.less` file. Or, is this maybe what you mean when you mention using `styled-components`, essentially giving the whole component it's own stylesheet?

2020-07-27 21:55 UTC, gschier approved these changes

2020-07-27 23:44 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/error-modal.js
> +                <code className="wide">{error.stack || error}</code>
> If the main problem is documentation/standardization

And discoverability. To figure out I need to use `wide`, I did a global search for "width: 100%", and found an appropriate class that has that, that I can use. Definitely not a nice approach, and much, much less manageable for anything more complex. Tailwind, Bootstrap, etc - they all solve this case.

> It might make sense to factor the styles out into a component-specific `.less` file

Instead of this, I'd favor styled-components. With the `.less` approach, if a style is changed, as a reviewer (and sometimes as a developer) you don't know where it's used. And if an element has a new class added to it (like in this PR), a reviewer doesn't know what _css_ styles are being added.

My preference for this particular fix would be to _not_ used styled-components, but use a utility from Tailwind or Bootstrap (documented, discoverable), but I think the `styled-component` route is faster in this codebase.

2020-07-27 23:48 UTC, merged

2020-07-27 23:52 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/error-modal.js
> +                <code className="wide">{error.stack || error}</code>
Also note - there's nothing stopping us from using the best of both worlds.

Any really specific/custom CSS can be handled with styled-components, while utilities used for layout.

Just need to think carefully about how to integrate insomnia's theming system with tailwind/boostrap.

```js
const AnimatedFilter = styled.div`...`;

<AnimatedFilter className="d-flex w-100" />
```

2020-07-28 17:13 UTC, sonicyeti commented on packages/insomnia-app/app/ui/components/modals/error-modal.js
> +                <code className="wide">{error.stack || error}</code>
I think we could benefit from hugely from simplifying the theme system's variables to cover colors, fonts and base unit values. We then leverage bootstrap for layout and utility classes. From there, we leverage styled components to compose each individual component.

The styled component would extend bootstrap's utility classes as needed via SC's attrs capability while theming & branding cohesion would be driven via variables similar to what we have now, only greatly pruned down as mentioned above. Bootstrap would essentially be picking up a lot of what is currently being handled by our theming system while exposing a ton of other helpful utility classes.

An example component might look like:

    const MyCustomThing: React.Component<{}> = 
     styled.div.attrs({
        // Extending From Bootstrap core CSS utils
        className='d-inline-flex p2'
      })`
      
      // From Theming System
      color: var(--color-surprise);
      background-color: var(--color-bg);
      font-size: var(--font-size-sm);
      
      // From Hi-Fi design specs > figma
      Custom...
    }`;
  .
`

2020-07-28 20:53 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/error-modal.js
> +                <code className="wide">{error.stack || error}</code>
This is a nice approach, I didn't know about `styled.div.attrs`. I think we can also fairly easily configure bootstrap to be aware of our theme variables without having to explicitly set them.