Sidebar code mirror interactions
getinsomnia/insomnia pull request #2433
Opened 2020-07-23 14:36 UTC by sonicyeti

This PR covers:

- When a user clicks on an item in the sidebar, the editor will select and scroll to the position within the spec.
- Fixed overflow scrolling issue
- Incorporation of yaml-source-map to expose line and column numbers for specs

Example:
![2020-07-23 10 34 50](https://user-images.githubusercontent.com/52717970/88299402-4fa99880-ccd0-11ea-84ba-30e9e7716299.gif)

2020-07-23 17:00 UTC, gschier submitted a review, later dismissed
A few higher-level comments right off the bat! Nothing too major, though.

![](https://media1.giphy.com/media/10t57cXgo7x5kI/giphy.gif)

2020-07-23 17:00 UTC, gschier commented on package.json
> +  }
Should be in `packages/insomnia-app/package.json`

2020-07-23 17:00 UTC, gschier commented on packages/insomnia-app/app/ui/components/spec-editor/spec-editor-sidebar.js
> +    };
Would be good to move this all into a component method (since this component is a class)

2020-07-23 17:00 UTC, gschier commented on packages/insomnia-app/app/ui/components/codemirror/code-editor.js
> +      this.codeMirror.scrollIntoView({ line: lineStart, char: chStart }, 400);
Is this supposed to be here?

2020-07-23 17:00 UTC, gschier commented on packages/insomnia-app/app/ui/css/components/sidebar.less
> +
This Less file is for the old sidebar. I think this style would better fit in `spec-editor.less`.

2020-07-23 17:00 UTC, gschier commented on packages/insomnia-app/app/ui/components/spec-editor/spec-editor-sidebar.js
> +  onClick: (path: any) => any,
It looks like this prop isn't being used by anything.

2020-07-23 17:00 UTC, gschier commented on packages/insomnia-app/app/ui/components/spec-editor/spec-editor-sidebar.js
>  import * as React from 'react';
It looks like there is a bunch of methods in this class that can now be deleted 💣

2020-07-23 17:00 UTC, gschier commented on packages/insomnia-components/components/sidebar/index.js
> +  onClick: Function,
Can we increase the specificity on these `onClick` type definitions? Should be something like `onClick: (section: string, path: Array<string>) => void`

2020-07-23 17:07 UTC, sonicyeti commented on packages/insomnia-app/app/ui/components/codemirror/code-editor.js
> +      this.codeMirror.scrollIntoView({ line: lineStart, char: chStart }, 400);
Yeah, scrollIntoView allows for the passing of the margin as a visual buffer (in this case 400) but alone, it doesn't set selection. setSelection has no option for margin but does achieve the actual base positioning.

2020-07-27 04:14 UTC, develohpanda requested changes
I love the changes in storybook! 🔥

Couple of comments, but generally looking good. 😄

2020-07-27 04:14 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/spec-editor/spec-editor-sidebar.js
> +    const scrollPosition = {
`sourceMap`, `specMap`, `itemPath` and `scrollPosition` are all, only used by the `_handleItemClick` function. This means we're regenerating the YAML sourcemap on _every_ render, but only consuming it when an item is clicked. We're also re-declaring the `_handleItemClick` function on every render (every change of the spec).

Is this necessary? I think it's worth exploring solutions that make the `render` function leaner and more efficient.

2020-07-27 04:14 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/spec-editor/spec-editor-sidebar.js
> +    const _handleItemClick = (section, item) => {
Please add typing to this function definition. For example:

`const _handleItemClick = (section: string, item: Array<string>): void => {`

2020-07-27 04:14 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/spec-editor/spec-editor-sidebar.js
>        <div className="spec-editor-sidebar">
I suggest using a `styled-component` here and keeping the styles close to where the are being consumed, especially given the CSS for this is simply
```less
.spec-editor-sidebar {
  overflow: hidden;
  overflow-y: auto;
}
```

2020-07-27 04:14 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/spec-editor/spec-editor-sidebar.js
> +      scrollPosition.end.col = 200;
Any specific reason for this being a hard-coded 200?

2020-07-27 04:14 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-headers.js
> +              <span onClick={() => this.props.onClick('components', ['headers', header])}>
I highly encourage destructing `this.props` where-ever appropriate, because React components are verbose enough as it is.

```js
const {headers, onClick} = this.props;
```

2020-07-27 04:14 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-info.js
> +      {license && license.name && (
```suggestion
      {license?.name && (
```

[Optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) is a friend 🤗

2020-07-27 04:14 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/spec-editor/spec-editor-sidebar.js
> +    const _handleItemClick = (section, item) => {
Looking at the usages of this, I feel like it might be worthwhile using  js [`rest parameters`](https://scotch.io/bar-talk/javascripts-three-dots-spread-vs-rest-operators543#toc-rest-parameters) here.

```js
const _handleItemClick = (...itemPath: Array<string>): void => {
	const isServersSection = itemPath[0] === 'servers;
	...
}
```

Fewer array operations make it more efficient - this replaces three array creations and one `push.apply`, in favor of a single `...itemPath` and indexed access.

2020-07-27 04:14 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar.stories.js
> +      <div style={{ display: 'block', margin: '0px 0px 20px 0px' }}>Target: {targetPath}</div>
This is cool 👍

2020-07-27 15:24 UTC, sonicyeti commented on packages/insomnia-app/app/ui/components/spec-editor/spec-editor-sidebar.js
> +      scrollPosition.end.col = 200;
On the yaml source map we get back the entire node's start and ending column position rather than just the intended single line item's ending so I'm manually passing 200 which it will shrink from when rendering the selection.

2020-07-27 15:44 UTC, sonicyeti commented on packages/insomnia-components/components/sidebar/sidebar-info.js
> +      {license && license.name && (
Tried enabling in flow via esproposal.optional_chaining=enable within components and restarted flow server but no luck. It has already been enabled in app. Not sure why it isn't happy here, I'll circle back on this.

2020-07-28 07:09 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-info.js
> +      {license && license.name && (
You might need to install `@babel/plugin-proposal-optional-chaining` and add that to `.babelrc`.

https://github.com/Kong/insomnia/blob/93c91ebdbed9dc635056c920686913722fd19965/packages/insomnia-app/.babelrc#L14

2020-07-29 00:47 UTC, develohpanda requested changes
🔥

2020-07-29 00:47 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/spec-editor/spec-editor-sidebar.js
> +      const mappedPosition = this._mapPosition([itemPath[0]].concat(...itemPath[1]));
Just the comment here we discussed about triggering this callback with `onClick('components', 'parameters', parameter)` instead of `onClick('components', ['parameters', parameter])`, and moving the this._scrollToPosition inside the class method so we can remove this callback being created during render 😄

2020-07-29 20:41 UTC, develohpanda approved these changes
Nice! Excited for this one 😁🔥

2020-07-30 20:50 UTC, gschier reviewed
A few comments

2020-07-30 20:50 UTC, gschier commented on packages/insomnia-app/app/ui/components/codemirror/code-editor.js
> +    const selectionFocusPos = remote.getCurrentWindow().getSize()[1] / 2 - 100;
Seems a bit strange to pull in `electron` as a dependency for this purpose. Should be able to get away with `window.innerHeight`.

2020-07-30 20:50 UTC, gschier commented on packages/insomnia-app/app/ui/components/codemirror/code-editor.js
> +      this.codeMirror.scrollIntoView(
I think a some other parts of the app call this method as well. It might be safer (and easier to understand) to add a new method to scroll to the position (`scrollToSelection(...)`), then call them both from outside.

2020-07-30 20:50 UTC, gschier commented on packages/insomnia-app/app/ui/components/spec-editor/spec-editor-sidebar.js
> +      itemPath.push.apply(itemPath, item);
Can also do this with `const itemPath = [section, item...]`

2020-07-30 20:50 UTC, gschier commented on packages/insomnia-components/components/sidebar/index.js
> +  const paths = Object.entries(props.jsonData.paths || {});
Should probably be checking to see if the type of `paths` is an object here. You'll get some weird results if `paths` is a string, for example.

2020-07-30 20:50 UTC, gschier commented on packages/insomnia-components/components/sidebar/index.js
> +  const paths = Object.entries(props.jsonData.paths || {});
Same with `components` and the rest

2020-07-30 21:05 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/spec-editor/spec-editor-sidebar.js
> +      itemPath.push.apply(itemPath, item);
I think you may have been reviewing an old version of this file? This logic has been switched in favor of rest parameters.

https://github.com/Kong/insomnia/blob/cccad719c73be4060f5073b6d8a9e0218a1e8823/packages/insomnia-app/app/ui/components/spec-editor/spec-editor-sidebar.js#L46-L72

2020-07-31 17:11 UTC, sonicyeti commented on packages/insomnia-app/app/ui/components/codemirror/code-editor.js
> +    const selectionFocusPos = remote.getCurrentWindow().getSize()[1] / 2 - 100;
Hah, I forget sometimes that we are in a browser ; ) thanks!

2020-08-03 09:21 UTC, develohpanda requested changes
Comment regarding type definitions

2020-08-03 09:21 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/index.js
> +  } = props.jsonData.components || {};
Hmm, not a fan of typing like this, it makes the code unnecessarily complex.

These types should be defined with the `Props` definition.

```js
type Props = {
	jsonData: {
		servers?: Object,
		info?: Object,
		paths?: Object,
		components?: {
			requestBodies?: Object,
		    responses?: Object,
		    parameters?: Object,
		    headers?: Object,
		    schemas?: Object,
		    securitySchemes?: Object,
		}
	}
}
```

2020-08-03 12:39 UTC, develohpanda approved these changes
Yay! 😊🤗

2020-08-03 17:57 UTC, merged

2020-08-03 20:45 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-headers.js
> +    if (Object.prototype.toString.call(headers) !== '[object Object]') {
🤔 Is there a particular reason we didn't just use `typeof` here?

2020-08-03 20:45 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-paths.js
> +    if (Object.prototype.toString.call(paths) !== '[object Array]') {
Same here, is there a particular reason for not using `Array.isArray(paths)`?