Checking format to offset line number if spec string is JSON parsable.
getinsomnia/insomnia pull request #2467
Opened 2020-07-30 16:25 UTC by sonicyeti

Spec type is YAML regardless of content format but when mapping, if the content format is JSON the scroll line number is offset. This fixes that by checking if the spec contents are parsable as JSON.

2020-07-30 21:02 UTC, develohpanda reviewed
Going to wait on this review until https://github.com/Kong/insomnia/pull/2433 is merged I think; there are changes here that are also in the other PR?

2020-08-05 04:01 UTC, develohpanda requested changes
Couple of minor comments 😄 Looks good though!

2020-08-05 04:01 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/spec-editor/spec-editor-sidebar.js
> +  componentDidMount() {
Since this only runs on mount, if I start with a blank spec (which will be treated as YAML), but then start typing in JSON, will it be treated correctly?

I don't think we need to change it, given the immediate impact would be the click to scroll is one line off, and it'll be fixed for every future navigation to the design tab. Just want to understand the impact of it treating a spec as YAML when it is, in-fact JSON.

I don't think changing to `componentDidUpdate` is the solution either, since `JSON.parse` will run and likely throw an exception on _every_ update 😬

2020-08-05 04:01 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/spec-editor/spec-editor-sidebar.js
> +  _IsSpecContentJson(str: string) {
I don't think this method is used anymore 😄

2020-08-05 04:01 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/spec-editor/spec-editor-sidebar.js
> +      : (scrollPosition.start.line += itemMappedPosition.start.line - 1);
Just to make this one a little less jarring

```js
scrollPosition.start.line += itemMappedPosition.start.line;

if (isServersSection) {
	scrollPosition.start.line -= 1;
}
```

2020-08-05 18:34 UTC, sonicyeti commented on packages/insomnia-app/app/ui/components/spec-editor/spec-editor-sidebar.js
> +  componentDidMount() {
Great point. In testing, it is thrown off by 1 line if starting fresh via default YAML and you author in JSON. This brings up another question. What if I decided to shift from JSON to YAML at any time on any existing spec, the same occurs. I'm wondering if we start detecting format as a standard, in general, before rendering anything.

2020-08-06 01:29 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/spec-editor/spec-editor-sidebar.js
> +  componentDidMount() {
In both cases, if you close the document and reopen, it will be fixed - so I don't think we need to do it any more frequently than on mount, but just something to keep in mind.

The cost of checking format on _every render_ isn't worth it, especially since the alternative is just being one line out, and only until the document is reopened. @nijikokun thoughts?

2020-08-06 01:31 UTC, develohpanda approved these changes

2020-08-06 01:31 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/spec-editor/spec-editor-sidebar.js
> +    if (!isServersSection) {
🤣 see how I was confused by the previous implementation and suggested `if(isServersSection)`, when it should have been `if(!isServersSection)`. This is much clearer.

2020-08-06 18:39 UTC, nijikokun commented on packages/insomnia-app/app/ui/components/spec-editor/spec-editor-sidebar.js
> +  componentDidMount() {
Good point, let's punt on it, in the future we should have the user declare types.

2020-08-06 18:39 UTC, merged