Replace textarea with code editor for response raw viewer
getinsomnia/insomnia pull request #2475
Opened 2020-08-01 07:06 UTC by aszx87410

This PR should Closes #2397 

After look into this issue, I found that it's not actually "crash" but freeze. When we set large text to textarea, somehow it blocks the main thread so nothing works until text is loaded. 

I think we should not use textarea in this scenario because it's not for large text. We can replace textarea with code editor to avoid this issue because loading large chunk of text already handled by codemirror.

Below are some pdf files to reproduce the issue:

1. https://github.com/tpn/pdfs/raw/master/A%20Comparison%20of%20Programming%20Languages%20in%20Economics%20(16-Jun-2014).pdf 206kb
2. https://eloquentjavascript.net/Eloquent_JavaScript.pdf 2.2MB ( be careful to use this because it will freeze the current app for a long time)

After switching to code editor it works fine. Please let me know if there is any problems, thanks!

2020-08-03 06:04 UTC, develohpanda requested changes
Nice, I like this. Code-mirror doing what it's good at, efficiently.

It seems like code-mirror is doing something to render raw JSON response nicely. This is only a rendering difference though, as I don't see any white-space when copy-pasting the content into VS Code.

Top is v2020.3.3, bottom is this PR.

![image](https://user-images.githubusercontent.com/4312346/89148650-95a70c00-d5ae-11ea-8a3f-ad4200d7a029.png)

So two things to try and address for this PR:
- [ ] Are we able to disable anything extra that code-mirror (or our code-editor component) is doing, in order to allow the raw response to be truly raw? 💥 
- [ ] It would be awesome to bring the CSS spacing from the text-area implementation to the code-mirror implementation. You'll notice in the screenshot above they are slightly different on all four sides. 💄

2020-08-03 06:30 UTC, develohpanda commented
Raised https://github.com/Kong/insomnia/issues/2478 as a related issue

2020-08-03 16:37 UTC, aszx87410 commented
Fortunately it seems that it's all styling issue. I made some changes in this commit: https://github.com/Kong/insomnia/pull/2475/commits/887de23f36d62673cdcebfd94deb96d258147749

We need to restyle codemirrow so I added a new class called `raw-editor`.  Although we can pass `raw-editor` as className to CodeEditor, I still introduce a new props called `raw` because we may need this raw editor somewhere else in the future. Moreover, we can also disable some functionalities in the CodeEditor component by looking at `raw` props. Passing this props is like: "Hey, I want this editor behave like a real raw viewer", the meaning is quite different compare to just passing a className.

Left one is PR while right is the original textarea, it looks pretty much the same!

![螢幕快照 2020-08-04 上午12 17 23](https://user-images.githubusercontent.com/2755720/89205493-69a97c00-d5ea-11ea-9694-5197473c6b2d.png)

2020-08-04 03:37 UTC, develohpanda approved these changes
> Although we can pass `raw-editor` as className to CodeEditor, I still introduce a new props called `raw`

I'm in favor of `raw` being a prop rather than passing the `raw-editor` class as a prop, however I don't think padding should be a part of `raw-editor`; see comment below.

Other than this minor change, looks good to me!

2020-08-04 03:37 UTC, develohpanda commented on packages/insomnia-app/app/ui/css/editor/raw-editor.less
> +    padding: var(--padding-md);
I'm on the fence about specifying padding here, versus sending a `className="pad"` prop into `CodeEditor` from `ResponseRaw`.

Spacing is a concern of the consumer, while `word-break`/`line-height` are a concern of the `CodeEditor` showing raw content correctly, as controlled by the `raw` prop.

For this reason I suggest removing padding from the `raw-editor` style and sending it as a prop from `ResponseRaw`. What are your thoughts?

2020-08-04 03:38 UTC, develohpanda requested changes
Oops, one comment that is worth addressing. Clicked the wrong button! 😄

2020-08-04 04:27 UTC, aszx87410 commented on packages/insomnia-app/app/ui/css/editor/raw-editor.less
> +    padding: var(--padding-md);
At first I tried to send className prop to `CodeEditor` but it doesn't work, so I have to restyle this way. The problem is, the HTML structure of the code mirrow. We have limited control by adding class class in the wrapper because of the structure under the hood. Below is the screenshot for sending `className="pad"` prop:

<img width="515" alt="截圖 2020-08-04 下午12 17 53" src="https://user-images.githubusercontent.com/2755720/89252772-4e238d00-d64d-11ea-9fc1-b266fadb6082.png">

The UI is different from original textarea, for example, the scrollbar is not at the right position, and also an unexpected gap on the top of the container. I have looked into this and found that we need to add padding in CSS to restyle, instead of sending a class name to the container.

2020-08-04 04:32 UTC, aszx87410 commented on packages/insomnia-app/app/ui/css/editor/raw-editor.less
> +    padding: var(--padding-md);
I pushed a new commit to merge the style into `general.less`

2020-08-04 04:37 UTC, develohpanda approved these changes
Nice one, thanks for working through this! I see what you mean regarding padding, and why it needs to exist on the `CodeMirror-*` classes rather than higher up. 🎉

LGTM 💯

2020-08-04 11:10 UTC, DMarby approved these changes
This is awesome, thanks for taking the time to implement this! 🎉

2020-08-04 12:10 UTC, sonicyeti approved these changes
Super solid, LGTM!

2020-08-04 19:17 UTC, merged