Copy info to clipboard
getinsomnia/insomnia pull request #2480
Opened 2020-08-03 14:14 UTC by Innoxious

Closes #2097 

Adds a button in the message box which will write system + insomnia details into the users clipboard.
![image](https://user-images.githubusercontent.com/5837038/89192092-f9a1f280-d5f7-11ea-93de-a4cf9387ad5a.png)
![copyInfoToClipboard](https://user-images.githubusercontent.com/5837038/89191917-b778b100-d5f7-11ea-9be7-43d95baab7d3.gif)

2020-08-03 21:13 UTC, develohpanda approved these changes
![](https://media1.giphy.com/media/13V60VgE2ED7oc/giphy.gif)

Looking awesome 🔥

2020-08-03 21:13 UTC, develohpanda commented on packages/insomnia-app/app/main/window-utils.js
> +          buttons: ['Copy to clipboard', 'OK'],
Ooooo this is cool, TIL 😮

2020-08-03 21:18 UTC, develohpanda requested changes
Small change I just noticed! 🤗

2020-08-03 21:18 UTC, develohpanda commented on packages/insomnia-app/app/main/window-utils.js
> +          'Version ' + getAppVersion(),
Might be good to the long app name here, so it shows in the snippet pasted into GH.

```suggestion
          `Version ${getAppLongName()} ${getAppVersion()}`,
```

2020-08-03 21:23 UTC, develohpanda commented on packages/insomnia-app/app/main/window-utils.js
> +    const os = require('os');
Oh this can also move to the imports at the top of the file 😄

2020-08-03 21:31 UTC, develohpanda commented
I looked back at #760, seems that the About screen doesn't exist for macOS because Electron gives it for free under `Insomnia Designer > About Insomnia Designer`.

![image](https://user-images.githubusercontent.com/4312346/89229117-f6792780-d634-11ea-8f7f-f6386559af3f.png)

VS Code also being electron, pops open a similar dialog with the `About Visual Studio Code` menu item, and has copy logic in it, so likely we need to extend whatever is setting the about page for macOS.

![image](https://user-images.githubusercontent.com/4312346/89229226-288a8980-d635-11ea-9af8-22dba6fc532e.png)

2020-08-05 21:37 UTC, Innoxious commented
@john-vuong pls help for mac

2020-08-07 08:02 UTC, john-vuong commented
There is no way to configure the macOS provided `[About](https://developer.apple.com/documentation/appkit/nsapplication/aboutpaneloptionkey)` menu item to how we want.

vscode uses the `showMessageBox` to show the About dialog like we have.

2020-08-10 03:56 UTC, develohpanda requested changes
LGTM, almost there! A couple of minor comments. 🎉

2020-08-10 03:56 UTC, develohpanda commented on packages/insomnia-app/app/main/window-utils.js
> +  const aboutMsgOptions = {
It would be nice to add `cancelId` and `defaultId` - see the [electron docs](https://www.electronjs.org/docs/api/dialog#dialogshowmessageboxbrowserwindow-options) about what they represent and see the [VS Code implementation](https://github.com/microsoft/vscode/blob/d890a22dc21fed13cf5a9eed81780d700f6e4f32/src/vs/workbench/services/dialogs/electron-browser/dialogService.ts#L254-L255) as inspiration.

2020-08-10 03:56 UTC, develohpanda commented on packages/insomnia-app/app/main/window-utils.js
> +          buttons: ['Copy to clipboard', 'OK'],
Looking at the [electron docs](https://www.electronjs.org/docs/api/dialog#dialogshowmessageboxbrowserwindow-options), setting `noLink: true` will stop the "Copy to clipboard" showing up as a full width button. Can also rename to just "Copy", like the macOS one above.

I noticed this while looking at how VS Code is [handling their buttons](https://github.com/microsoft/vscode/blob/d890a22dc21fed13cf5a9eed81780d700f6e4f32/src/vs/workbench/services/dialogs/electron-browser/dialogService.ts#L252-L253).

Just handle macOS and Windows for now, once it works for those I'll clone and test on Linux to see how the buttons array should be configured for that. AFAIK there are slight variations in ordering.

2020-08-10 20:58 UTC, nijikokun commented
Amazing addition, thank you for the PR @Innoxious  👏

2020-08-10 21:13 UTC, develohpanda approved these changes
Solid 👍 I'll make a small change later on to make things less verbose and reuse the click handler but the functionality looks good! 💯

2020-08-10 21:14 UTC, merged