Unit testing test output
getinsomnia/insomnia pull request #2533
Opened 2020-08-20 12:38 UTC by sonicyeti

This PR covers the creation of a list group & supporting list group item specifically for the the purpose of our unit testing right rail which is responsible for test result display:

**Before:**
![Screen Shot 2020-08-20 at 8 18 50 AM](https://user-images.githubusercontent.com/52717970/90769710-acdc3e00-e2be-11ea-8e3d-a7a0b4a25ef4.png)

**After:**
![Screen Shot 2020-08-20 at 8 23 44 AM](https://user-images.githubusercontent.com/52717970/90769718-b1085b80-e2be-11ea-8223-51b8edc8fdf7.png)

**Supporting Story:**
![Screen Shot 2020-08-20 at 8 26 13 AM](https://user-images.githubusercontent.com/52717970/90769806-d4cba180-e2be-11ea-821b-62fa5a4f09a8.png)

2020-08-20 21:25 UTC, develohpanda reviewed
Couple of notes :)

2020-08-20 21:25 UTC, develohpanda commented on packages/insomnia-components/components/list-group-item.js
> +// TODO: Create a collection of visual badges within our component system.
We have tags (like packages/insomnia-app/app/ui/components/tags/method-tag.js). Is that similar?

2020-08-20 21:25 UTC, develohpanda commented on packages/insomnia-components/components/list-group-item.js
> +class ListGroupItem extends React.PureComponent<Props> {
This is named as a really generic component, but it's actually _very_ specific to test results. It almost doesn't need to be within `insomnia-components`, but at the very least I would name it more specifically and/or separate what is needed for a `ListGroupItem` (eg expand/collapse) vs what is needed for a `TestResultItem`

2020-08-20 21:25 UTC, develohpanda commented on packages/insomnia-components/components/list-group-item.js
> +  .itemToggler {
Could we please remove any direct classes from a styled-component in favor of a standalone styled-component? See `notice-table` for an example.

You can also [extend styles](https://styled-components.com/docs/basics#extending-styles) if need be

2020-08-20 21:25 UTC, develohpanda commented on packages/insomnia-components/components/list-group-item.js
> +    return (
Great candidate for a functional component 😄

2020-08-20 21:25 UTC, develohpanda commented on packages/insomnia-components/components/list-group.js
> +class ListGroup extends React.PureComponent<Props> {
Great candidate for a functional component 😄

2020-08-20 21:25 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-unit-test.js
> +                  )}
This logic can (and should, IMO), be inside a `TestResultListItem` component.

2020-08-20 21:59 UTC, sonicyeti commented on packages/insomnia-components/components/list-group-item.js
> +// TODO: Create a collection of visual badges within our component system.
Similar in theory but the design is very far off and more appropriate for accent type usages (currently). My hope is that we can craft a nice array of badges similar to other frameworks.

2020-08-21 13:56 UTC, DMarby requested changes

2020-08-21 13:56 UTC, DMarby commented on packages/insomnia-components/components/list-group.stories.js
> +        time="602ms"
Nitpick, but imo it looks kind of strange to have the unit directly after the number, I think adding a space to make it `602 ms` would make more sense, same for all the other items.

2020-08-21 13:56 UTC, DMarby commented on packages/insomnia-components/components/list-group-item.js
> +            TODO: Add show/hide toggle support in the future.
Imo it's nice to avoid leaving comments/commented code like this as much as possible, if we want something to be done in the future, we should open an issue for it to have it properly tracked instead.

Not sure what the common approach is in this codebase however, but that's my two cents.

2020-08-21 13:56 UTC, DMarby commented on packages/insomnia-components/components/list-group-item.js
> +            <span>{time}</span>
Since this is just outputting the raw input, currently, we already have two different results here:
- The storybook has strings in the format of `100ms`
- The actual UI has integers, resulting in just `100`

I think it would be better to just always pass in milliseconds or a duration type or such to the component, and have the presentation formatting be done by the component itself, this way it's always consistent.
With presentation formatting I mean either doing something like `%d ms` which is equivalent to what we had before this change, or by using a library that rounds up to seconds/minutes/etc.

2020-08-22 06:04 UTC, develohpanda commented on packages/insomnia-components/components/list-group-item.js
> +            <span>{time}</span>
To add to that, I suggest naming the prop as `timeMilliseconds` or `timeMs`. Almost everything else in JS operates with ms, so lets stick with that convention, both with naming and with logic.

2020-08-27 14:16 UTC, DMarby approved these changes

2020-08-27 20:07 UTC, develohpanda requested changes
Almost there!! A couple of minor notes 😄

2020-08-27 20:07 UTC, develohpanda commented on packages/insomnia-components/components/list-group/list-group.stories.js
> +);
Epic!

2020-08-27 20:07 UTC, develohpanda commented on packages/insomnia-components/components/list-group/unit-test-result-badge.js
> +  result?: String,
I suggest changing this prop to be more explicit

```suggestion
  failed?: boolean,
```

2020-08-27 20:07 UTC, develohpanda commented on packages/insomnia-components/components/list-group/unit-test-result-item.js
> +        <UnitTestResultBadge result={item.err.message} />
Then updating this usage:

```suggestion
        <UnitTestResultBadge failed={!!item.err.message} />
```

2020-08-27 20:07 UTC, develohpanda commented on packages/insomnia-components/components/list-group/unit-test-result-item.js
> +export { UnitTestResultItem, UnitTestResultBadge, UnitTestResultTimeStamp, SvgIcon };
Do all of these still need to be exported? I would think we only need to export `UnitTestResultItem` now.

If all do need to be exported, careful about re-exporting `SvgIcon`

2020-08-27 20:07 UTC, develohpanda commented on packages/insomnia-components/components/list-group/unit-test-result-timestamp.js
> +  children?: React.Node,
`children` prop can be removed now 😄

2020-08-27 20:07 UTC, develohpanda commented on packages/insomnia-components/index.js
> +import * as unitTestResultItem from './components/list-group/unit-test-result-item';
After updating the exports from `unit-test-result-item`, we should be able to change this back to follow the same pattern as the other exports.

2020-08-27 20:42 UTC, sonicyeti commented on packages/insomnia-components/components/list-group/unit-test-result-item.js
> +export { UnitTestResultItem, UnitTestResultBadge, UnitTestResultTimeStamp, SvgIcon };
Thanks for the catch!

2020-08-27 21:32 UTC, develohpanda approved these changes

2020-08-27 22:09 UTC, merged