Editor toggling, visual design spec. integration, various stylistic tweaks
getinsomnia/insomnia pull request #2598
Opened 2020-09-10 14:25 UTC by sonicyeti

This PR covers the incorporation of accordion style functionality for unit tests including: 

- Unit tests can now be toggled to expand or collapse
- A single unit test's max height caps at around the 20 line mark, where scrolling takes over to preserve real estate
- The unit test header has been brought closer to alignment with the original design specification
- Unit Test is now a list group item type from a component standpoint
- Swapping play and delete iconography positioning
- Resolution for multiple Code Mirror instances introducing lag

**Screenshot:**
![Screen Shot 2020-09-10 at 10 00 43 AM](https://user-images.githubusercontent.com/52717970/92743135-4773ee00-f34e-11ea-8448-3437f9660f02.png)

**Demo:**
![2020-09-10 10 19 42](https://user-images.githubusercontent.com/52717970/92744796-cae20f00-f34f-11ea-9755-d60a603003c3.gif)

Closes #2562
Fixes INS-85
Fixes INS-48
Fixes INS-52

2020-09-10 19:16 UTC, DMarby approved these changes

2020-09-11 04:57 UTC, develohpanda requested changes
Nicely done 😄 

I've made a couple of comments, but one overarching one is to do with defining Props for components. Because props are the interface between a component and it's consumer, we should try to be as explicit as possible with the prop type definitions, rather than generic `Function`, `Object`, etc. It will only help us when we come to look at or consume the same component in a few months time.

I will add that there are many components currently that do not define their prop types clearly; those components were likely created before a typing methodology was introduced. Even though we are currently using Flow right now, when we eventually look to move towards TS, the flow type definitions will be useful. 😄

2020-09-11 04:57 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/unit-test-selection.js
> +  selectableRequests: Object,
It would be great if we could type these more explicitly.

For example, just from looking at the usage in the component
```suggestion
  onChange: () => void,
  selectedRequestId?: string,
  selectableRequests: Array<{name: string, request: { _id: string }}>,
```

2020-09-11 04:57 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/unit-test-selection.js
> +export default function UnitTestSelection({ onChange, unitTest, selectableRequests }: Props) {
Suggestion to rename component as `UnitTestRequestSelector`, as this is specific to selecting requests 😄

2020-09-11 04:57 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-unit-test.js
> +        }
I like that you extracted `UnitTestItem` and `UnitTestSelection` out into standalone components 👍 

We can avoid having to pass `<UnitTestSelection />` as a prop into `UnitTestItem`; instead, we can simply pass the onChange handler as a prop, for instance, `onRequestSelectionChanged={this._handleSetActiveRequest.bind(this, unitTest)}`.

Then, `UnitTestItem` becomes

```js
function UnitTestItem(props) {
  ...
  <UnitTestSelection onChange={props.onRequestSelectionChanged} ... />
  ...
}
```
instead of
```js
function UnitTestItem(props) {
  ...
  {props.testSelection}
  ...
}
```

This way UnitTestSelection can be moved into insomnia-components!

2020-09-11 04:57 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-unit-test.js
> +        onRunTest={() => this._handleRunTest(unitTest)}
Passing arrow functions as props mean a new function is instantiated on each render. A newly instantiated function, even if it has the same implementation, is unique. Because it is unique, React will tell `UnitTestItem` to update, because a prop has changed, when in-fact it hasn't. Try use the `.bind` syntax within class components 😄

2020-09-11 04:57 UTC, develohpanda commented on packages/insomnia-components/components/list-group/list-group.stories.js
> +        <UnitTestItem item={test} key={i}>
Index as keys hehe. Doesn't really matter here, but good to get into the practice of it. I suggest to use `test._id` as the key

2020-09-11 04:57 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-unit-test.js
> +        }>
Same as above, but less trivial because `Editable` isn't in `insomnia-components`. _But_, it would be a great idea to pull `Editable` into the component library, and other usages can be updated later on.

2020-09-11 04:57 UTC, develohpanda commented on packages/insomnia-components/components/list-group/unit-test-item.js
> +  const [collapse, toggleCollapse] = React.useState(false);
We can use the `useToggle` hook from `react-use`, like in the new sidebar hehe

2020-09-11 04:57 UTC, develohpanda commented on packages/insomnia-components/components/list-group/unit-test-item.js
> +        </Button>
Does this icon need to exist inside a disabled `Button`? I'm guessing it's for consistent spacing

2020-09-11 13:02 UTC, sonicyeti commented on packages/insomnia-components/components/list-group/unit-test-item.js
> +        </Button>
Exactly. Disabled happened to match the design spec while reducing custom styling overhead.

2020-09-14 18:33 UTC, DMarby commented on packages/insomnia-app/app/ui/components/wrapper-unit-test.js
> +    console.log(selectableRequests);
I think this is a leftover debug statement?

2020-09-14 18:34 UTC, sonicyeti commented on packages/insomnia-app/app/ui/components/wrapper-unit-test.js
> +    console.log(selectableRequests);
Thanks for the catch, pulling it now!

2020-09-15 03:32 UTC, develohpanda approved these changes
A couple of minor notes, good to merge after they are addressed. 👍

2020-09-15 03:32 UTC, develohpanda commented on packages/insomnia-components/components/list-group/list-group.stories.js
> +            CodeMirror instance.
👌

2020-09-15 03:32 UTC, develohpanda commented on packages/insomnia-components/components/list-group/list-group.stories.js
> +        <UnitTestResultItem item={test} key={test._id} />
👌

2020-09-15 03:32 UTC, develohpanda commented on packages/insomnia-components/components/list-group/unit-test-item.js
> +  }, [toggle]);
I think this can be removed in favor of just using `onClick={toggle}`

The `React.useCallback` would be useful if you were to do `onClick={() => { toggle() }}`, because the `() => {}` syntax creates a new function. 🙂

2020-09-15 03:32 UTC, develohpanda commented on packages/insomnia-components/components/list-group/unit-test-item.js
> +  onChange: () => void,
It's not immediately clear what this change handler is for - changing the test body, title, request, etc?

Similar to the other event handles (`onDeleteTest`, `onRunTest`), I suggest naming this explicitly like `onSetActiveRequest`, for example.

`onChange` on it's own is fine for a generic component like `Editable`, though. Contextual 😄

2020-09-15 03:32 UTC, develohpanda commented on packages/insomnia-components/components/list-group/unit-test-item.js
> +  onRunTest?: () => void,
I'd like to double check but I don't think these callbacks should be optional, right?

2020-09-15 03:32 UTC, develohpanda commented on packages/insomnia-components/components/list-group/unit-test-item.js
> -  .form-control {
Yay, happy to see this move into what uses it specifically. 😄

2020-09-15 03:32 UTC, develohpanda commented on packages/insomnia-components/components/list-group/unit-test-item.js
> -          animate={{ height: collapse ? '100%' : '0px' }}>
Was the removal of animation intentional?

2020-09-15 03:32 UTC, develohpanda commented on packages/insomnia-components/index.js
> +export const UnitTestRequestSelector = _UnitTestRequestSelector;
We can get away with not exporting this selector from insomnia-components since it's more of an internal component. Keen for your thoughts on this however - what stuff is exported from the library and what is not.

2020-09-15 14:46 UTC, sonicyeti commented on packages/insomnia-components/index.js
> +export const UnitTestRequestSelector = _UnitTestRequestSelector;
100% agreed, I didn't realize that this export serves the sole purpose of exposing it for usage in app. I thought it was necessary for bundling deps which the UT result item needs. I'll yank it!

2020-09-15 15:15 UTC, sonicyeti commented on packages/insomnia-components/components/list-group/unit-test-item.js
> -          animate={{ height: collapse ? '100%' : '0px' }}>
I pulled this because while we can slide-reveal the CM instance, when collapsed, it no longer exists in the DOM and looks quite janky when attempting to slide-hide and wanted to avoid having a toggle collapsed callback tied to the tween duration just for the sake of animating the exit of the CM instance.

2020-09-15 16:26 UTC, merged

2020-09-15 20:36 UTC, develohpanda commented on packages/insomnia-components/components/list-group/unit-test-item.js
> -          animate={{ height: collapse ? '100%' : '0px' }}>
Fair enough, we can alter it depending on feedback. Either way seems fine