Sidebar method styling & click regions
getinsomnia/insomnia pull request #2632
Opened 2020-09-17 14:32 UTC by sonicyeti

This PR covers the method badge design integration into the application along with the fixing of sidebar item click region inconsistencies.

- Theme support
- Subtle hover animation and alpha shift
- Fixed legacy alignment & spacing issues
- Address less than intuitive click target inconsistencies with the rest of the sidebar

Static screenshot and hover animation below:
![2020-09-17 10 29 43](https://user-images.githubusercontent.com/52717970/93485171-c75f0280-f8d0-11ea-8c9b-7d2251810529.gif)

![Screen Shot 2020-09-17 at 10 21 21 AM](https://user-images.githubusercontent.com/52717970/93484571-10fb1d80-f8d0-11ea-8920-aadfafa855d0.png)

FIXES INS-31
FIXES INS-76

2020-09-17 19:56 UTC, develohpanda requested changes
One important note about the new component - `SidebarMethodBadge` - and the way it is consumed. I encourage you to design towards exporting _components_ instead of _stylesheets as components_. 🤗

2020-09-17 19:56 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-panel.js
> -  .method {
👍

2020-09-17 19:56 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-method-badge.js
> +`;
Looking at the two usages below, I propose an update to this component.

```js
// sidebar-badge.js

type Props = {	
	onClick: () => void,
	label?: string,
	method?: 'get' | 'post' | ... | 'put',
}

export const SidebarBadge = (props: Props) => { ... };
```

Where:
- if `method` _is not_ provided, some default color is applied
- if `label` _is_ provided, it is overwritten, otherwise is the `method`
- if both `method` and `label` are not provided, returns null

Consumed as:
```js
	<SidebarBadge onClick={...} method="get" />
	<SidebarBadge onClick={...} label="cat" />
```

Doesn't have to be _exactly_ this - this can also be split into two components, but notice how this approach abstracts the need for a user to know the inner styling of `SidebarBadge` in order to use it.

After redoing this component, you can also create stories in Storybook.

2020-09-18 13:02 UTC, DMarby approved these changes

2020-09-21 16:01 UTC, DMarby requested changes

2020-09-21 16:01 UTC, DMarby commented on packages/insomnia-components/components/sidebar/sidebar-badge.js
> +    | 'parameters'
Should "parameters" be duplicated here?

2020-09-21 17:25 UTC, DMarby approved these changes

2020-09-21 17:27 UTC, sonicyeti commented on packages/insomnia-components/components/sidebar/sidebar-method-badge.js
> +`;
Got it, coming along although I opted to make the onClick optional as well in the event we need a visual only badge for something. Pinged you on a flow related issue.

2020-09-21 21:11 UTC, develohpanda reviewed
Nicely done 👏 I've made a couple of comments, but you're on the right path!

2020-09-21 21:11 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-requests.js
> +                          }></SidebarBadge>
Can be self closing

```suggestion
                          } />
```

2020-09-21 21:11 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-requests.js
> +                          key={requestExample}
👍

2020-09-21 21:11 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-badge.js
> +const SidebarBadge = ({ onClick = () => {}, method = 'post', label = method }: Props) => {
The `onClick` prop isn't used anywhere - it needs to be sent to the `<StyledBadge>` right?

2020-09-21 21:11 UTC, develohpanda commented on packages/insomnia-components/components/sidebar/sidebar-badge.js
> +export default SidebarBadge;
Keen to see some Storybook stories for this new component 😄

2020-09-22 13:19 UTC, DMarby approved these changes

2020-09-22 21:56 UTC, develohpanda approved these changes
Nice! 💯

2020-09-22 23:36 UTC, merged