Add PKCE support
getinsomnia/insomnia pull request #2652
Opened 2020-09-22 13:19 UTC by DASPRiD

This is a small change to support PKCE with authentication code authorization.

Closes #1653
Closes #2154

2020-10-12 12:11 UTC, develohpanda commented
Thanks for the PR @DASPRiD! Could you please take a look at the breaking tests? Please mark as ready to review again once fixed up. Thanks!

2020-10-13 05:42 UTC, develohpanda requested changes
Apologies for the delayed review! Thank you for working through this feature, I'm looking forward to get it in. 😄

A couple of questions and one minor change, but otherwise LGTM. 👏

2020-10-13 05:42 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/auth/o-auth-2-auth.js
> +              title={authentication.usePkce ? 'Disable PKCE' : 'Enable PKCE'}>
Strange, it seems the `Button` component doesn't use the `title` prop for anything.

It might have been removed accidentally because there are a lot of instances that provide the `title` prop. No need to change this line, we should fix button to consume it. 😄

2020-10-13 05:42 UTC, develohpanda commented on packages/insomnia-app/app/network/o-auth-2/grant-authorization-code.js
> +    .replace(/=/g, '');
Could you please explain why these replacements need to happen - is it something specific with OAuth 2, or something else that I'm missing?

If there are any docs, it would be great to add as a comment in the code, for anyone looking at it later on.

2020-10-13 05:42 UTC, develohpanda commented on packages/insomnia-app/app/network/o-auth-2/grant-authorization-code.js
> +    params.push({ name: c.P_CODE_CHALLENGE_METHOD, value: 'S256' });
Does `S256` need to be a hard-coded constant in `o-auth-2/constants.js`, or be defined closer to the hash type (`crypto.createHash('sha256')`) to indicate that the two are related?

(I assume they are related)

2020-10-13 05:42 UTC, develohpanda commented on packages/insomnia-app/app/network/o-auth-2/grant-authorization-code.js
> +  return string
We absolutely should not be using reserved keywords as variable names, very strange that ES Lint didn't complain 🤔 Even if it works, it can be a little confusing.

```suggestion
function _base64UrlEncode(str: string): string {
  return str
```

2020-10-13 10:25 UTC, DASPRiD commented on packages/insomnia-app/app/network/o-auth-2/grant-authorization-code.js
> +    .replace(/=/g, '');
Base64-URL encoding is defined by the PKCE RFC:
https://tools.ietf.org/html/rfc7636#section-4.2

2020-10-13 10:26 UTC, DASPRiD commented on packages/insomnia-app/app/network/o-auth-2/grant-authorization-code.js
> +    params.push({ name: c.P_CODE_CHALLENGE_METHOD, value: 'S256' });
Not really. There's only S256 and plain, and plain **must not** be used when the client does support sha256 hashing, according to the RFC. See also:

https://tools.ietf.org/html/rfc7636#section-4.2

2020-10-13 10:47 UTC, develohpanda commented on packages/insomnia-app/app/network/o-auth-2/grant-authorization-code.js
> +    .replace(/=/g, '');
👍 thanks for that

```suggestion
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=/g, '');
    
    // The characters + / = are reserved for PKCE as per the RFC,
    // so we replace them with unreserved characters
    // Docs: https://tools.ietf.org/html/rfc7636#section-4.2
```

2020-10-13 10:47 UTC, develohpanda commented on packages/insomnia-app/app/network/o-auth-2/grant-authorization-code.js
> +    params.push({ name: c.P_CODE_CHALLENGE_METHOD, value: 'S256' });
Noted, thanks!

2020-10-13 10:49 UTC, develohpanda approved these changes
LGTM

2020-10-13 11:51 UTC, DASPRiD commented
> LGTM

Your suggested change broke prettier D:

2020-10-13 12:13 UTC, DASPRiD commented
Fixed the prettier report. For some reason the MacOS build is failing now, but that seems to be build server related… *shrugs*

2020-10-13 12:50 UTC, develohpanda commented
> Fixed the prettier report. For some reason the MacOS build is failing now, but that seems to be build server related… *shrugs*

No probs, I'll have a look at what's breaking there, should be fine though.

2020-10-15 15:06 UTC, DMarby approved these changes

2020-10-20 07:58 UTC, merged

2021-02-11 16:01 UTC, et1975 commented
Can anyone confirm if this impl works with Azure AD?