Basic auth e2e test
getinsomnia/insomnia pull request #2671
Opened 2020-09-28 08:04 UTC by develohpanda

This is a follow-up to https://github.com/Kong/insomnia/pull/2642#pullrequestreview-495945646.

20 runs successful 👍 

<img width="734" alt="image" src="https://user-images.githubusercontent.com/4312346/94406078-f8430f80-01cd-11eb-9c8c-a44ad6f33bb9.png">

2020-09-28 08:25 UTC, jgiovaresco reviewed
👏 
It is a nice way to test the app, quite easy to review one everything is in place.

We may need to split `debug.js` file in the future because it will become huge as we will write more tests. Maybe we could extract authentication related functions (`clickBasicAuth`, `clickRequestAuthDropdown`...) in a dedicated file ?

2020-09-28 08:25 UTC, jgiovaresco commented on packages/insomnia-app/app/ui/components/request-pane.js
> +            <Tab id="auth-dropdown-tab" tabIndex="-1">
I don't understand why we had an id here ? I was expecting to see a selector using it in tests but I didn't find it ?
Is it a standard rule ? 

2020-09-28 08:30 UTC, develohpanda commented
> We may need to split `debug.js` file in the future because it will become huge as we will write more tests

Yep, I think it's worth breaking down by the three panes - sidebar, request, response - which can then be broken down further for specific things (eg auth). Step by step. 😄

2020-09-28 08:32 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/request-pane.js
> +            <Tab id="auth-dropdown-tab" tabIndex="-1">
Ah, nice catch. This isn't used because `id` is not a property that the react-tabs Tab component uses. There isn't a way (from what I could see) to set a unique id, so the test is just using the generated one for now.

I think it's worth creating a tab selection helper, to allow you to click according to the tab _contents_.

2020-09-29 05:27 UTC, DMarby requested changes

2020-09-29 05:27 UTC, DMarby commented on packages/insomnia-smoke-test/modules/debug.js
> +  await app.client.$('button#use-iso-8859-1').then(e => e.click());
It doesn't feel super obvious to me that a helper method for entering basic auth would select a non-standard encoding option.

If we want to test this encoding, perhaps we should make this parameter and test both cases?

2020-09-30 13:49 UTC, DMarby approved these changes

2020-12-07 05:07 UTC, develohpanda commented on packages/insomnia-smoke-test/server/index.js
> +  setTimeout(next, 500);
We can experiment with reducing this `500ms` delay until it is no longer than necessary. As it stands, I think it's fine. Longest test (this one) is `16s` and it tests every aspect of basic auth

2020-12-07 10:31 UTC, DMarby approved these changes

2020-12-07 20:12 UTC, merged