Added nested keys check after root keys check for environment editor.
getinsomnia/insomnia pull request #2685
Opened 2020-10-02 08:32 UTC by johnhorsema

Closes #2684

2020-10-02 09:26 UTC, develohpanda reviewed
Nice first attempt 👏 

After #2601, keys themselves can contain spaces, so after calling `getNestedKeys`, splitting on a single space won't quite work as intended. Additionally, `getNestedKeys` will iterate over all keys first, and then check each, one by one. This needs to be made much more efficient in that as soon as a key that does not follow the regex rule is detected, the algorithm stops.

Remember, the example linked in the issue is an _example_, from which a new solution needs to be derived for the `environment-editor` specifically. 😄 Let me know if you'd like further direction here, but I'll let you improve the approach with this feedback in mind.

Lastly, please add some screenshots for what the user will see when adding a nested key which does not follow the rules, as well as some unit tests in `environment-editor.test.js`.

2020-10-02 18:15 UTC, johnhorsema commented
> Lastly, please add some screenshots for what the user will see when adding a nested key which does not follow the rules, as well as some unit tests in `environment-editor.test.js`.

Screenshots
![001](https://user-images.githubusercontent.com/10090182/94956127-3453d880-051e-11eb-90f8-59a34f669866.png)
![002](https://user-images.githubusercontent.com/10090182/94956147-3ddd4080-051e-11eb-895a-59b225d08693.png)
![003](https://user-images.githubusercontent.com/10090182/94956162-45044e80-051e-11eb-9736-d56537462217.png)

2020-10-05 04:36 UTC, johnhorsema commented
@develohpanda please have a look at my latest PR, thanks

2020-10-07 01:21 UTC, develohpanda requested changes
Making some progress 👏 a couple of comments, particularly with the efficiency and clarity of the recursive function.

2020-10-07 01:21 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/environment-editor.js
> +  }
The check for root keys (and subsequent error message) needs to be removed from the `ensureKeyIsValid` function and moved into here.

https://github.com/Kong/insomnia/blob/0d522a69a7efe8d5296b4d91791d1aedd851619b/packages/insomnia-app/app/ui/components/editors/environment-editor.js#L18-L20

2020-10-07 01:21 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/environment-editor.js
> +      result = checkNestedKeys(obj[key], result, false);
I don't quite understand why result is passed into the recursive call here. Does it need to be a parameter of `checkNestedKeys` at all?

2020-10-07 01:21 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/environment-editor.js
> +): boolean {
The return type is incorrect, here and in the comment above. It should be `string | null`.

2020-10-07 01:21 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/environment-editor.js
> +      }
Running a function, checking the result, and then running the function again is quite an inefficient workflow.

But, you can simplify it using [short-circuit evaluation](https://codeburst.io/javascript-what-is-short-circuit-evaluation-ff22b2f5608c):

```js
result = ensureRootKeyIsValid(key) || ensureKeyIsValid(key);
```

2020-10-07 01:21 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/environment-editor.js
> +}
I think this overall function (`checkNestedKeys`) can be simplified a fair bit. Root vs non-root keys aren't two different cases.

The only conditional statement inside `if (isRoot)` needs to be `ensureRootKeyIsValid`, because `ensureKeyIsValid` needs to be applied to _all_ keys. See if you can simplify this a little bit. 😄

2020-10-07 01:28 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/environment-editor.js
> +    if (typeof obj[key] === 'object' && obj.hasOwnProperty(key)) {
Do objects and arrays need to be treated differently? Note that in the following environment, the first `$val.id` is valid, but `$in.valid` is invalid.

```json
{
  "arr": [
    "$val.id",
    {
      "$in.valid": 1
    }
  ]
}
```

You might need to use `const typeOfObj = Object.prototype.toString.call(obj);` to differentiate between an array and an object.

2020-10-15 13:52 UTC, johnhorsema commented on packages/insomnia-app/app/ui/components/editors/environment-editor.js
> +): boolean {
You're right.

2020-10-15 13:53 UTC, johnhorsema commented on packages/insomnia-app/app/ui/components/editors/environment-editor.js
> +      }
It's refactored to just have `ensureKeyIsValid`.

2020-10-15 13:53 UTC, johnhorsema commented on packages/insomnia-app/app/ui/components/editors/environment-editor.js
> +      result = checkNestedKeys(obj[key], result, false);
Removed and replaced with a local variable in the function.

2020-10-15 13:54 UTC, johnhorsema commented on packages/insomnia-app/app/ui/components/editors/environment-editor.js
> +  }
Part of refactoring to single `ensureKeyIsValid`.

2020-10-15 14:24 UTC, johnhorsema commented on packages/insomnia-app/app/ui/components/editors/environment-editor.js
> +    if (typeof obj[key] === 'object' && obj.hasOwnProperty(key)) {
No changes needed here. The check `typeof obj[key]` will return `object` for both objects and arrays.
So `environmentObj["arr"]` will still pass the condition and be checked for subsequent valid keys in its nested members.

Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof

2020-10-15 14:32 UTC, johnhorsema commented on packages/insomnia-app/app/ui/components/editors/environment-editor.js
> +}
Sure. I've refactored the `ensureKeyIsValid` to incorporate root key checking.

2020-10-17 03:38 UTC, johnhorsema commented
@develohpanda please have a look at my latest PR, thanks

2020-10-22 05:32 UTC, develohpanda commented
@johnhorsema Thanks! Don't worry, I haven't missed it, just been quite busy. I will re-review when I get a chance to. 🤗

2020-11-19 03:56 UTC, develohpanda requested changes
Sorry about the delay, I finally had a chance to review this. I'm generally happy with it, did some testing locally and it seems to be working nicely.

I've added a couple of comments that are worth addressing, please! 🙂

2020-11-19 03:56 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/environment-editor.js
> +  return result;
It should be safe to simply exit without a null check, since `checkNestedKeys` has a return type that includes `null`. In addition, further down, there is a check to only set an error if an error is returned, so we don't need to double-up checks.

Also, it feels as though the `obj.hasOwnProperty(key)` check is obsolete, because `typeof obj[key]` returns `undefined` if the key is not present. The second condition will never be reached.

```suggestion
  for (const key in obj) {
    // Nested keys
    if (typeof obj[key] === 'object') {
      return checkNestedKeys(obj[key], false);
    } else {
      return ensureKeyIsValid(key, isRoot);
    }
  }
```

2020-11-19 03:56 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/environment-editor.js
> +export const ensureKeyIsValid = (key: string, isRoot: boolean = false): string | null => {
Is there a particular reason you chose to set `isRoot` to default false here, but default true in `checkNestedKeys`?

It feels unnecessarily complex and I would prefer to remove the defaults altogether.

2020-11-19 03:56 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/__tests__/environment-editor.test.js
>  });
I noticed there are no tests for `checkNestedKeys`; could you please add some permutations for that?

2020-12-06 18:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/insomnia?pullRequest=2685) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/insomnia?pullRequest=2685) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/insomnia?pullRequest=2685) it.</sub>

2021-09-07 06:15 UTC, develohpanda approved these changes
QA'd with the following environment (and by changing it round): https://www.loom.com/share/1fa103f7ce0141c286da62dad146e147.

The rules are defined in https://github.com/Kong/insomnia/issues/2684.

```json
{
  "base-url": "https://api.insomnia.rest",
  "nested": {
    "path-with-hyphens": "/path-with-hyphen"
  },
  "ar-ray": [
    "/first",
    {
      "second": "second"
    },
    {
      "third": "third"
    }
  ]
}
```

Thanks for working through this, apologies for the mega delays; we're working through the older PRs.

2021-09-10 19:04 UTC, dimitropoulos approved these changes
works great.  I really appreciate all the tests, too!

2021-09-10 19:25 UTC, merged