Add logic to cancelRequest to remember requestId
getinsomnia/insomnia pull request #2696
Opened 2020-10-06 21:25 UTC by selamanse

Closes #2690

I replaced the inner network.js variable cancelRequestFunction with a Map that remembers the requestId of the given cancelFunction.

Also the ui now uses cancelRequestById with the actual requestId to cancel the specific request.

I tested package insomnia-app locally via ui with the express based test-server that was proposed by the issue description (very helpful and precise by the way).

I also ran all tests with `npm test` locally from repository root...all seem fine.

I am unsure about ui or module tests. Is there something I should add?

2020-10-06 21:38 UTC, develohpanda approved these changes
I'm really impressed, brilliant work 👏 

> I am unsure about ui or module tests. Is there something I should add?

Currently there are no UI tests (this is WIP as I'd like to add them too).

Some tests could potentially be added for the `cancelRequestById` function in `network.test.js` though. Looks like there are only tests for `_actuallySend`, which sets up the cancellation logic, so we might be able to add a few test cases to also cancel.

Give that a go, and if it's non-trivial to add tests for cancellation then I'll merge this in as-is. Looks pretty good to me!

2020-10-06 21:38 UTC, develohpanda commented on packages/insomnia-app/app/network/network.js
> +      return cancelRequestFunction();
It's surprising there is nothing that clears the `cancelRequestFunction`, it just relies on the UI to hide the button so the function cannot be called.

I wonder if after invoking the function, we should clear it on the map (set it back to null).

2020-10-06 21:56 UTC, develohpanda requested changes
Small change about clearing the cancel function once a request completes or is cancelled, to avoid a memory leak 😄

2020-10-06 22:42 UTC, selamanse commented on packages/insomnia-app/app/network/network.js
> +      return cancelRequestFunction();
I agree, I fixed it and added a simple test.

2020-10-07 00:25 UTC, develohpanda commented on packages/insomnia-app/app/network/network.js
> +      return cancelRequestFunction();
Just had a look at the change; it will only clear on canceling a request but we should also clear when a request completes or fails. Looking at the code, all the exist paths lead to the [`respond()`](https://github.com/Kong/insomnia/blob/fa64e6b5e896c2d043499b6b937e1a8f616d5346/packages/insomnia-app/app/network/network.js#L147-L151) helper function (including cancellation), so you might be able to clear in one convenient location.

Also, I think the tests in the current state are a false positive - they're only checking whether the property has been cleared rather than the request cancelled. When a request is cancelled, the promise returned from the network call to `_actuallySend()` [should resolve with a statusMessage of `Cancelled`](https://github.com/Kong/insomnia/blob/fa64e6b5e896c2d043499b6b937e1a8f616d5346/packages/insomnia-app/app/network/network.js#L228-L238).

`node-libcurl` is being automatically mocked [here](https://github.com/Kong/insomnia/blob/develop/packages/insomnia-app/app/__mocks__/node-libcurl.js). You should be able to extend that, adding things necessary to configuring your unit test. Note: any changes you make to the mock should only impact your test, not the other tests.

2020-10-08 09:46 UTC, selamanse commented on packages/insomnia-app/app/network/network.js
> +      return cancelRequestFunction();
@develohpanda  ...sorry took me a while, I struggled a little with the understanding of the response() helper and the promises but now I think I have a solution that cleans up corresponding cancellation Function of a request at every respond invocation.
Also changed the test expectancy as you suggested.

2020-10-08 10:25 UTC, develohpanda reviewed
Your update to the unit test was exactly what I had in mind, nice work!

A couple of comments, almost there 🤗

2020-10-08 10:25 UTC, develohpanda commented on packages/insomnia-app/app/network/network.js
> +        }
This `finally` block won't be reached when the respond function exits on line 174, as part of the `if (noPlugins)` condition. Is that excluded intentionally?

If unintentional, I'd be inclined to suggest running this clearing logic straight after storing the timeline, on line 157, using `renderedRequest._id` as the request id.

A few more quick notes about this code-block:
- Could you please extract this clearing logic in a standalone function, like `clearCancelFunctionForId` (doesn't need to be exported, though)
- I think it's safe to remove the log message from here while clearing (as long as we keep the one you added when actually trying to cancel)

2020-10-08 10:25 UTC, develohpanda commented on packages/insomnia-app/app/network/network.js
> +  console.log(`WARN: cancelFunction for ${requestId} not found.`);
Small suggestion to update the error message here, nice observation to add it in 😄 

```suggestion
  console.log(`[network] Failed to cancel req=${requestId} because cancel function not found`);
```

2020-10-08 10:25 UTC, develohpanda commented on packages/insomnia-app/app/network/__tests__/network.test.js
> +    expect(response2.statusMessage).toBe('OK');
Awesome update to this test, it looks great 🎉

How do you feel about adding a `hasCancelFunctionForId` function?
```js
export function hasCancelFunctionForId(requestId) {
	return cancelRequestFunctionMap.hasOwnProperty(requestId);
}
``` 

We can then use it to validate at the end of this test that the cancel functions have been cleared for both requests.

2020-10-08 10:48 UTC, selamanse commented on packages/insomnia-app/app/network/__tests__/network.test.js
> +    expect(response2.statusMessage).toBe('OK');
Had the same idea, but wasn't sure about it until you mentioned it. I think its helpful.

2020-10-08 10:49 UTC, develohpanda commented on packages/insomnia-app/app/network/__tests__/network.test.js
> +    expect(response2.statusMessage).toBe('OK');
We're on the same page 👏

2020-10-08 15:50 UTC, develohpanda approved these changes
Nicely done 💯

2020-10-08 17:16 UTC, develohpanda commented
I did some manual testing:
- cancelled requests
- successful requests
- failed requests (invalid url)

Cancel functions didn't persist longer than necessary. So excited to merge this!

2020-10-08 17:17 UTC, merged

2020-10-08 19:59 UTC, selamanse commented
@develohpanda thanks for reviewing and advising. I appreciated this.

2020-10-08 20:10 UTC, develohpanda commented
Credit where credit is due, @DMarby noticed the memory leak, and you did a great job with fixing it up.

I was certainly impressed with your refined unit test as well! 🥇