Fix color picker display when updating an environment color
getinsomnia/insomnia pull request #2711
Opened 2020-10-11 16:18 UTC by jgiovaresco

> For environments where you want to change the color, you have to unset, then you're back to the previous
> issue. Trying to change without brings the menu up for a second, then it disappears.

I've noticed that for any reason calling `await this._load(this.state.workspace)` just after appending the
input element to the body is fixing the display of the color picker.
Instead of calling `this.load` directly, I've removed the condition check to update the environment color even
if it is already set.

Closes #2647

2020-10-19 20:36 UTC, develohpanda approved these changes, later dismissed
Seems alright but I'd like to know how it was working before the Electron update or if the logic here changed recently.

2020-10-19 20:36 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/workspace-environments-edit-modal.js
> -    }
How was this previously working at all? This logic says that once the environment color is set, it can't be set again until it's cleared, right?

2020-10-19 20:45 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/workspace-environments-edit-modal.js
> -    }
Ah, this line is only for defaulting the color if one doesn't exist - there is an event handler further down that handles the actual input change.

2020-10-19 21:00 UTC, develohpanda reviewed
> I've noticed that for any reason calling `await this._load(this.state.workspace)` just after appending the input element to the body is fixing the display of the color picker.

I'm guessing that adding an await to _something_ after appending the input element, is allowing some background process to complete.

I doesn't feel like forcibly updating the environment color each time we prompt for a new color is fixing the root cause.

I was able to get the same fix working by delaying the element click using `setTimeout(() => el.click(), 50);`, so needs further investigation to determine and fix the root cause, _or_ use this timeout approach.

2020-10-21 00:22 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/workspace-environments-edit-modal.js
>      el.click();
I hope I'm not missing something, but we shouldn't need to DOM manipulation this way, if the `input` tag is being rendered directly as part of this component. It should be achievable just in React itself, right?

2020-10-21 05:45 UTC, jgiovaresco commented on packages/insomnia-app/app/ui/components/modals/workspace-environments-edit-modal.js
>      el.click();
Good catch... I didn't think about that... 🤦 

Using React helps because we don't need to clean the listener to keep #811 fixed.

2020-10-22 04:26 UTC, develohpanda requested changes
Thanks for updating the description and adding in a gif. Almost there!

2020-10-22 04:26 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/workspace-environments-edit-modal.js
> +    el.value = color;
Is there anything stopping you from setting the value on the input itself, using `activeEnvironment.color`?

You can also refer to the input using `ref` in order to programmatically click it.

There should be no need for `document.querySelector` with the changes you've made, just need to take it one step further.

2020-10-22 04:26 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/workspace-environments-edit-modal.js
> +  }
This event handler can be simplified...

```suggestion
  _handleInputColorChange(e: SyntheticEvent<HTMLInputElement>) {
      this._handleChangeEnvironmentColor(this._getActiveEnvironment(), event.target && event.target.value);
  }
```

Then on the input itself, consumed as:
```js
<input
  ...
  type="color"
  onInput={this._handleInputColorChange}
/>
```

2020-10-22 04:26 UTC, develohpanda commented on packages/insomnia-app/app/ui/css/layout/base.less
> +.hidden-item {
Can this just be `hidden`, or does that clash with something else?

2020-10-22 06:06 UTC, jgiovaresco commented on packages/insomnia-app/app/ui/components/modals/workspace-environments-edit-modal.js
> +  }
> input is fired on the <input> element every time the color changes. The change event is fired when the user dismisses the color picker. In both cases, you can determine the new value of the element by looking at its value.
[source](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color)

I've tried to use `onChange` and we keep the same behavior 🤔 
![2647-onChange-event](https://user-images.githubusercontent.com/4171593/96831463-6da4a780-143d-11eb-8a9f-d239c76eb26e.gif)

Therefore we can change the event 🤷

2020-10-22 06:13 UTC, jgiovaresco commented on packages/insomnia-app/app/ui/css/layout/base.less
> +.hidden-item {
My IDE has found a `hidden` class. But after a closer look, this class belongs to `swagger-ui-react` dependency. Therefore I should be able to rename it ;)

2020-10-23 01:41 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/workspace-environments-edit-modal.js
> +    this.environmentColorInputRef.click();
Last one! It's usually good to check that the ref is not falsey before using it

```suggestion
    this.environmentColorInputRef && this.environmentColorInputRef.click();
```

I don't know if optional chaining is currently enabled, but you could also do something like

```suggestion
    this.environmentColorInputRef?.click();
```

2020-10-23 05:21 UTC, develohpanda approved these changes
Nicely done 👏

2020-10-23 16:07 UTC, DMarby approved these changes

2020-10-27 07:02 UTC, merged