WIP -- fix(insomnia-designer): Add resizing for Design Preview and Testing Results panes
getinsomnia/insomnia pull request #2712
Opened 2020-10-11 20:07 UTC by simplywondrous

> 🚨 Currently a work in progress!

## Context
This PR closes #2583 

## Changes
- Removed wrapper grid div that encompassed middle and right panes and replaced with Fragment tag
  - Structure now matches the Debug tab
  - Passed refs down to both middle and right panes via `TestsPane` and `ResultsPane` classes in order to reuse the existing resize logic (which has a class component ref, then calls `findDOMNode` on that ref, and finally gets `offsetWidth` off of the dom node)
- Some CSS changes

## Questions / Comments
There are three ways I'm thinking of for cleaning this up -
1. Forwarding the refs with the wrapper (that wraps the two panes) with `forwardRef` instead of creating classes. Doesn't seem like `forwardRef` is used anywhere, and React has a [note to component library maintainers](https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers) about introducing it. This is an app and not a component library I guess, but asking to be sure!

2. Keep the grid wrapper, slap the refs directly onto the dom elements themselves, and modify the resize logic to be
```
      const requestPane =
        this._requestPane instanceof HTMLElement
          ? this._requestPane
          : ReactDOM.findDOMNode(this._requestPane);
      const responsePane =
        this._responsePane instanceof HTMLElement
          ? this._responsePane
          : ReactDOM.findDOMNode(this._responsePane);
```
so that we get correct `offsetWidth` values from request and response panes, regardless of if the ref is an element or component
(I am currently stuck with this one. The ref element is correct, but the offsetWidth value isn't updated as I drag - if you have any ideas for what might be the issue?)

3. Change the wrapper to a flexbox, which handles resizing easier than a grid layout

## TODO
- Make request / response pane var names generic
- Apply same logic to Design tab

2020-10-11 20:25 UTC, simplywondrous commented
For question / option #2 - here's what `renderPageBody` looks like:

```js
renderPageBody() {
  ...
  return (
    <div className="unit-tests layout-body--sidebar">
      <section ref={handleSetRequestPaneRef} className="unit-tests__tests">...</section>
      <div className="drag drag--pane-test">...</div>
      <section className="unit-tests__results results-pane" ref={handleSetResponsePaneRef}>
         {this.renderResults()}
      </section>
    </div>
  );
}
```

2020-10-12 10:43 UTC, develohpanda commented
All in all, a nice approach you've followed 👏 Code looks good!

Note: if none of the following options are viable in the short term, the current changes (and those anticipated for `WrapperDesign`) are still great! I have some really minor notes but we can address those once the PR is ready with the desired direction.

**To answer your questions**

> Forwarding the refs with the wrapper (that wraps the two panes) with `forwardRef` instead of creating classes.

I'm not too concerned about the warnings for library maintainers with this particular case as _we_ are the only consumers of the components. How do you envision `forwardRef` being set up? To my understanding, `forwardRef` works with a single ref, but we have multiple to pass around (sidebar, request, response panes).

Alternatively the new class components can also be simple(r) function components. New components might be unnecessary altogether too, if you get refs on dom elements working.

> slap the refs directly onto the dom elements themselves

I'm not sure why this wouldn't be working... could it be that you need to use `this._requestPane.current` when accessing a ref in the absence of `findDOMNode`? Maybe it needs to be gently sent as a prop, instead of being _slapped_ on the element? Elements have feelings too! 😢 

If you can't get it working for this PR, it can be scoped to a standalone PR given it might need some additional work, but it would be good to remove `findDOMNode` (unless absolutely necessary) as it is now discouraged. Looks like the pane dragging logic was written in 2016, so is probably well outdated with current React practices. 🤣 

> Change the wrapper to a flexbox, which handles resizing easier than a grid layout

While this would be pretty awesome, my gut feel is that it might be a lot of work. CSS Grid is quite central to the layout and it's variations. Flexbox would definitely be a step forwards but might be too much to tackle in this PR?
 
**Some additional observations**

I was looking at how the drag pane was set up for the sidebar, because it seems to be working across all views (design, debug, test) in the current state. It looks like `PageLayout` has `renderPageSidebar` and `renderPageBody` as props, and sets up the sidebar dragging logic in there.

I wonder if it's worth investigating whether `renderPageBody` can be updated to `renderPaneOne` and `renderPaneTwo`, and any className props, and the dragging logic for the entire layout all be set up in one common location.

This doesn't really _change_ the approach, just moves the logic somewhere else, and prevents . It would require some further updates in the Wrapper components, but at first sight it doesn't look too tricky.

2020-10-12 21:31 UTC, simplywondrous commented
It's only a guess, but after thinking about it some more, maybe if the ref is a dom element since the element itself isn't changing on drag no update is triggered, whereas when the ref is on a class component (that then finds a dom element) when the pane gets resized something is updated and the changes propagate down to the component, which then updates?

Looking it up, seems the best way to forward multiple refs is to make the ref an object with refs. That being said, if we had `PaneOne` and `PaneTwo` then we wouldn't need to forward multiple, so that seems to be the way to go. 

It'd make the most sense if the dragging logic were all in one place like `PageLayout`. I haven't looked at how the functions in `app.js` (including the drag logic) make it into `PageLayout`, but I think for this PR I'll try to separate `renderPageBody` into `renderPaneOne` and `renderPaneTwo` and consolidate the styling, along with adding resizing between the two panes. Then removing findDOMNode and seeing if the drag logic can be moved to PageLayout can be follow-up issues.

2020-10-13 03:53 UTC, develohpanda commented
My understanding of `ReactDOM.findDOMNode` is that if invoked with a ref attached to a _component_, it returns the first dom element rendered by the component, and so should be the same as just putting a ref on the dom element itself (as recommended). Neither the element nor the component is updated (as far as I can tell) because `paneWidth` and `paneHeight` are consumed higher up the tree in `PageLayout`. Needs some more research but I wonder if `findDOMNode` is loading the _latest_ dom to before finding the node, which would have been updated with the row/column sizing applied in [`PageLayout`](https://github.com/Kong/insomnia/blob/81ad8ba2c89196ec2fefe088a9d2e860279d12a0/packages/insomnia-app/app/ui/components/page-layout.js#L60-L63). What a pickle!

> for this PR I'll try to separate `renderPageBody` into `renderPaneOne` and `renderPaneTwo` and consolidate the styling, along with adding resizing between the two panes.

This sounds good 👍 I can't think of any (great) reasons _not_ to split `renderPageBody` - in the case where only one of the panes is used (preview hidden in the design tab), one of the render props can just be optional, and drag handlers can be applied as required within `PageLayout`.

> Then removing `findDOMNode` and seeing if the drag logic can be moved to PageLayout can be follow-up issues.

I agree, it seems non-trivial, but also non-critical so it can be tackled as a standalone PR.

2020-10-14 17:27 UTC, simplywondrous commented
Ohhh I see - so if `findDOMNode` is loading the latest dom and then finding the node, it'd get the updated offset, whereas when we're simply looking at the current ref element's offset, that doesn't get updated so stays the same.

Right now I'm working on hiding `PaneTwo` when hiding the preview in the design tab, and have a question.
Currently, `render` in `PageLayout` includes (with some code omitted)
```js
return {renderPaneTwo && <div> ... renderPaneTwo()</div>}
```
and in `WrapperDesign`, `renderPaneTwo={this.renderPreview}` is passed to `PageLayout`, with
```js
renderPreview = () => { return !previewHidden && <div /> }
``` 

Since we're passing it a function, `renderPaneTwo` is always `true` even when `renderPaneTwo()` returns `false`. To fix this, my first thought is to call `renderPreview` in `WrapperDesign` and pass the returned value to `renderPaneTwo`:

```js
const preview = renderPreview()
<PageLayout renderPaneTwo={preview} />
```

This would prevent dynamically generating the content of `PaneTwo` in `PageLayout`, though. Then `preview` from the example above would be statically passed in. I'm _pretty sure_ this would cause edge case issues of some sort, but am not quite skilled enough to give examples, so could be I have concepts mixed up :pensive:. Maybe if `renderPreview` called a handler that relied on variables set in `PageLayout`, which later changed?

If there are no issues, would it be a good idea to change just `renderPageTwo` to take in JSX, while keeping the rest, such as `renderPaneOne`, the same?

Second thought is, in `PageLayout` I could do
```js
const preview = renderPaneTwo()
{preview && <div />}
```
and I think then the content would still be dynamically generated upon component render. Would this be okay or is there a better way to go about hiding the second pane?

2020-10-14 21:00 UTC, develohpanda commented
There are a few different options I can think of, and no one is better than the other at first sight. The options you've given are both good too. 

I'll pull this code later today and see what's up, AFK for the next few hours! 😊

2020-10-14 21:03 UTC, simplywondrous commented
I very much appreciate your responsiveness, but it says your status is "on vacation" so please enjoy it! This is certainly not something that can't wait a few days!

2020-10-15 08:22 UTC, develohpanda commented
> 
> 
> I very much appreciate your responsiveness, but it says your status is "on vacation" so please enjoy it! This is certainly not something that can't wait a few days!

I picked a good week to take off, middle of the busiest open-source month 😅 just making sure the wheels keep turning, but I'll dip away for the last few days!

I noticed `WrapperHome` is yet another variation of the grid which will need to be considered here. This is the documents home page when you hit the "Documents" link on the top left. Note: with this PR in the current state, the homepage doesn't show anything.

> If there are no issues, would it be a good idea to change just `renderPaneTwo` to take a JSX element instead of a function, while keeping the rest, such as `renderPaneOne`, the same?

Because the render functions don't actually have any arguments, I don't think there's a specific case for them to be functions over just `React.Element` or `React.Node`. If you change this it _should_ behave like for like. The header has props that behave this way (used in all Wrapper components as well): https://github.com/Kong/insomnia/blob/4fc8b21827b7b0222b67ef0f2756458d7007a6b0/packages/insomnia-components/components/header.js#L5-L10

2020-10-15 09:16 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-design.js
> -            })}>
> To get hiding the preview (in `WrapperDesign`) to trigger a style change in its parent component (`PageLayout`) would require the parent passing down a show/hide handler of some sort to `PaneTwo` to then call, right?

Don't think so - looks like the size changes from hiding the preview are all just controlled by the `grid-template-columns` CSS property.

I think you're missing this highlight div and classes, though.

Previously in `WrapperDesign`, the parent div in the body contains these classes: `spec-editor layout-body--sidebar theme--pane`, but these no-longer exist on the DOM after splitting the body into the panes. You will probably need to send a `pageBodyClassName` (for example) prop into `PageLayout`, and wrap `paneOne` and `paneTwo` in a div, applying those classes.

```js
// in page-layout.js
<div className={pageBodyClassName}>
	{paneOne && <ErrorBoundary>...</ErrorBoundary>}
	{/* horizontal drag pane */}
	{/* vertical drag pane */}
	{paneTwo && <ErrorBoundary>...</ErrorBoundary>}
</div>
```

2020-10-15 09:16 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-unit-test.js
> -      <div className="unit-tests layout-body--sidebar theme--pane">
`<div className="unit-tests layout-body--sidebar theme--pane">` is missing as well (see previous comment) 😄

2020-10-16 06:49 UTC, simplywondrous commented on packages/insomnia-app/app/ui/components/wrapper-design.js
> -            })}>
Thank you, yes it is `grid-template-columns` and it required only a slight change to `const gridColumns` in `PageLayout` to accomplish hiding the preview!

While both design and test tabs had a parent div around both panes, debug doesn't, and by changing from `renderPageBody` to `renderPaneX` a lot of the styling in `unit-tests.less` and `spec-editor.less` can be removed (currently unused, has been duplicated elsewhere, or is now covered by pane one / two styles).

2020-10-16 07:08 UTC, simplywondrous commented
Pushed a couple more changes and updated the PR body! Still have a couple todos, but please let me know if the logic looks okay, and if I'm missing something not in the todos!

2020-10-19 04:05 UTC, simplywondrous commented on packages/insomnia-app/app/ui/css/components/unit-tests.less
> +    overflow-y: auto; // TODO - Jasmine do we want it auto or hidden?
Which `overflow-y` is correct?

2020-10-19 04:06 UTC, simplywondrous commented on packages/insomnia-app/app/ui/components/page-layout.js
> +                <div className="drag drag--pane-vertical">
Is this in the correct position? Visually, where is the vertical drag bar in the app?

2020-10-19 04:21 UTC, simplywondrous commented on packages/insomnia-app/app/ui/css/components/spec-editor.less
> -  }
I didn't find anywhere where these styles were used - not missing anything, I hope?

2020-10-19 04:22 UTC, simplywondrous commented on packages/insomnia-app/app/ui/css/components/unit-tests.less
> -    }
Same for these styles here - not missing anything, I hope?

2020-10-20 05:34 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-design.js
> -            })}>
Oooh interesting, I'm all for removing redundant code 🔥

2020-10-20 05:37 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/page-layout.js
> +                <div className="drag drag--pane-vertical">
There is a setting in preferences to toggle vertical and horizontal display

![image](https://user-images.githubusercontent.com/4312346/96544491-2a461e00-1303-11eb-93f1-4ae8825fe7a1.png)

The vertical drag bar shows up in between the two panes when displayed vertically

![image](https://user-images.githubusercontent.com/4312346/96544561-4b0e7380-1303-11eb-9789-7365f42a2a85.png)

Does that answer your question?

2020-10-20 05:40 UTC, develohpanda commented on packages/insomnia-app/app/ui/css/components/spec-editor.less
> -  }
Entirely possible they are redundant, but I suggest removing these unused styles (and the ones in `unit-tests.less`) in a standalone PR to keep it scoped down.

2020-10-20 05:45 UTC, develohpanda commented on packages/insomnia-app/app/ui/css/components/unit-tests.less
> +    overflow-y: auto; // TODO - Jasmine do we want it auto or hidden?
Oh good find! `auto` will always be overridden by `hidden` because of `!important`...

![image](https://user-images.githubusercontent.com/4312346/96545138-48f8e480-1304-11eb-8c4e-5c32199671aa.png)

2020-10-20 05:47 UTC, develohpanda commented on packages/insomnia-app/app/ui/css/components/unit-tests.less
> -    }
A lot of this styling was moved into the component library (`insomnia-components`), using `styled-components`. This are most likely residual styles, nice find!

2020-10-20 06:07 UTC, develohpanda reviewed
> Consolidated CSS styling, mostly removing styles previously unused or now unused after these changes

One note about styles, in favor of keeping the scope of this PR small. If styles were previously unused, move to a separate PR. If styles are now unused after these changes, keep in this PR. 😄 

Looks to be on the right path! I'm not so familiar with the CSS classes and where they are used upfront, but as long as the end result is correct, I'm not _too_ concerned about the changes made there.

Also, it is possible to create [custom themes](https://support.insomnia.rest/article/26-plugins#themes) via Insomnia plugins. I don't _think_ any of the changes you have made should impact theming, but it would be worth comparing the live application with your PR, to ensure theme support hasn't changed.

2020-10-20 06:07 UTC, develohpanda commented on packages/insomnia-app/app/ui/css/components/pane.less
> -    border-left: 1px solid var(--hl-md);
I'm guessing this was moved from here into `.pane-one` and `.pane-two`?

2020-10-20 06:07 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/response-pane.js
> +        <div className={paneClasses}>
Curious, is there a specific reason for switching from `section` to `div` tags?

2020-10-20 19:22 UTC, simplywondrous commented on packages/insomnia-app/app/ui/components/response-pane.js
> +        <div className={paneClasses}>
Before there were more changes to this file, but I ended up reverting them afterwards. I kept these 'cause they match the other tabs, where PaneOne and PaneTwo render their children in `section` tags and the children themselves are `div` elements. Should I change these back?

2020-10-20 19:23 UTC, simplywondrous commented on packages/insomnia-app/app/ui/css/components/pane.less
> -    border-left: 1px solid var(--hl-md);
Yep!

2020-10-20 20:02 UTC, simplywondrous commented on packages/insomnia-app/app/ui/components/page-layout.js
> +                <div className="drag drag--pane-vertical">
Yes, and seems vertical dragging for Debug is working fine so I'll leave it where it is now!

2020-10-20 20:05 UTC, simplywondrous commented
Aww shucks, I even tried out a bunch of different themes but I guess not the first one! It was missing two properties - it should be good now!

I'll keep the CSS changes as is in this PR and open another new PR with just the previously unused styles, if that one can be merged in first?

And thanks for the compliment, it means a lot!

2020-10-22 04:33 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/response-pane.js
> +        <div className={paneClasses}>
Hmm I don't immediately see any issue with them, would you mind investigating whether there are any CSS styles impacted by this change? If not, I'm okay with leaving them as is, for consistency. Good catch!

2020-10-22 05:26 UTC, develohpanda requested changes
Looks really good! Just some minor feedback that would be worth addressing, but nothing blocking. 🤗 

> Aww shucks, I even tried out a bunch of different themes but I guess not the first one! It was missing two properties - it should be good now!

I cloned and tested again, and the already broken theme is slightly less broken now (and matches the live application) so that's good to see!

Lastly, could you also please add a gif to the PR description of the final feature, for documentation purposes because this is a UI/UX related change? Thanks!

2020-10-22 05:26 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/page-layout.js
> +            )}
> For cases where panes aren't desired, `renderPageBody` is still available (such as for `WrapperHome`)

These two elements look very similar. If the `sidebar` and `paneTwo` don't exist (you already cater for it), isn't `paneOne` the same as `pageBody`, given `paneOne` will take up the space that is available? 😄

It looks like `WrapperHome` _does_ apply `theme--pane` as well, so it feels fine to use `PaneOne`, if I'm not missing anything.

I think what you've done for _this_ PR, by keeping `renderPageBody` for `WrapperHome`, is good, keeping in scope for the issue being resolved! 🎉 Although, it feels like `renderPageBody` is now also redundant and can be removed in a subsequent PR.

2020-10-22 05:26 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/page-layout.js
> +}
This can just be a single `Pane` component that takes in a prop to switch between the `pane-one` and `pane-two` classes. The `ref` for each pane will still be unique, because two instances of the same class component would end up on the tree. 🤓

2020-10-22 05:26 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-design.js
> +  renderEditor = (): React.Node => {
Would prefer regular function syntax (prefixed with `_` for private functions) here to keep consistent with the rest of the class methods 😄 same with `renderPreview` below and some other instances in this PR. There's probably an ES Lint rule to govern this that we should enable...

```suggestion
  _renderEditor(): React.Node {
```

2020-10-22 05:26 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-design.js
> +        <div id="swagger-ui-wrapper">
Always keep in mind to exit logic as early as possible (the previous implementation should have been better too).

While this is compact and correct, if the preview is hidden, we can avoid the `parseApiSpec` step altogether, because we will never show the result! With the refactoring you've done, this is now possible (easily). 😄 

`null` is a valid `React.Node`, so with that, we can do the following as the first step of `renderPreview()`

```js
if (previewHidden) {
  return null;
}
// everything else
```

2020-10-22 05:26 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-design.js
> +        renderPaneTwo={this.renderPreview}
So much cleaner. So much easier to understand the layout at a glance. 😍 

![](https://media4.giphy.com/media/3o8doT9BL7dgtolp7O/giphy.gif)

2020-10-22 05:26 UTC, develohpanda commented on packages/insomnia-app/app/ui/css/components/spec-editor.less
>  .spec-editor {
I think you can get rid of this class altogether and just use `tall`.

(We're exploring tailwind to use some standard CSS helpers, rather than using custom ones like this. 😎)

https://github.com/Kong/insomnia/blob/bd4ed35dab63a91b55384fe7c36029589e6cc7ae/packages/insomnia-app/app/ui/css/layout/base.less#L352-L354

2020-10-22 05:29 UTC, develohpanda commented
...also, a net change of +1 so far? Epic!

<img width="147" alt="image" src="https://user-images.githubusercontent.com/4312346/96828638-80969680-1494-11eb-91a6-39237ac7bd6a.png">

2020-10-24 22:39 UTC, simplywondrous commented on packages/insomnia-app/app/ui/components/page-layout.js
> +            )}
I used `PaneOne` at first, but that has `pane-one` styles that account for a sidebar, with `grid-column-start: 4` and `border-left: 1px solid var(--hl-md)`. My thought is, it could be passed in with `position="0"` with `pane-zero` styles in a follow-up PR?

2020-10-27 05:27 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/page-layout.js
> +            )}
Hmmm I see... that could work! To me, the three render props in `PageLayout` are the source of truth, and depending on their presence or absence, the layout adjusts.

We can probably remove the `pane-*` CSS classes altogether by using `styled-components`, where the styles can [change depending on props](https://styled-components.com/docs/basics#adapting-based-on-props), but I'm not too stubborn on which solution to use. Feel free to give that a go in another PR if you'd like!

2020-10-27 06:19 UTC, develohpanda approved these changes
QA:
- [x] horizontal resizing panes work on all tabs
- [x] vertical resizing panes work on all tabs
- [x] automatic/forced vertical layout works 🤯 
- [x] designer homepage correctly wraps and scrolls with multiple documents
- [x] view -> toggle sidebar (to hide sidebar) works on all tabs
- [x] after navigating around, I don't see any additional errors or warnings in the console window
- [x] can send requests (E2E tests)

Nicely done! I think there ended up being some overlap with #2713, because this PR handles vertical layout automatically, but this PR would be my preferred direction. I did find another bug (#2787) that might already be fixed by #2713, though.

LGTM, thank you for working through the various iterations, and putting your time into it! I'm looking forward to merge it in. 💯

2020-10-27 19:48 UTC, simplywondrous commented on packages/insomnia-app/app/ui/components/page-layout.js
> +            )}
I wasn't quite sure how to create a PR that goes against this repo when the branch itself is against my forked repo's branch - opening a PR against `Kong:develop` from `simplywondrous:fix/pane-update` included all of the changes from `simplywondrous:develop`. Do you know of a good way to do so? In the future, instead of forking should I clone and branch instead?

In the meanwhile, the PR is [here](https://github.com/simplywondrous/insomnia/pull/1).

2020-10-27 23:39 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/page-layout.js
> +            )}
Nested branches and forks can become tricky, so what you've done is fine. Once this PR is merged, you can create another PR into `Kong:develop` from `simplywondrous:fix/pane-update` for the additional changes, and I'll review those changes in that PR to keep conversation in one place.

> instead of forking should I clone and branch instead?
Clone and branch won't work as OSS contributors don't have push permissions to this repo, so working through forks is the best approach.

2020-11-02 12:45 UTC, DMarby requested changes

2020-11-02 12:45 UTC, DMarby commented on packages/insomnia-app/app/ui/components/page-layout.js
> +                <Pane position="one" ref={handleSetRequestPaneRef}>
Since we set the ref here, but also set it on `RequestPane` in wrapper-debug as we did previously, I think the ref will be overwritten?
It should probably only be set in one of the two places?

2020-11-02 12:45 UTC, DMarby commented on packages/insomnia-app/app/ui/components/page-layout.js
> +                  <Pane position="two" ref={handleSetResponsePaneRef}>
Same here regarding setting the ref both here and in wrapper-debug

2020-11-02 12:45 UTC, DMarby commented on packages/insomnia-app/app/ui/components/wrapper-design.js
>      let swaggerUiSpec;
I think this can be removed now, since it was moved up into _renderPreview?

2020-11-06 04:59 UTC, develohpanda commented
Let me know if you need any help to resolve the conflicts here! There was some refactoring in #2799, and looking at that PR might help. The changes in the conflicting files were mostly copy-paste so it should not be too tricky. 🤞

2020-11-07 23:49 UTC, simplywondrous commented on packages/insomnia-app/app/ui/components/wrapper-design.js
>      let swaggerUiSpec;
It's still used on line #274 of this file, for `{previewHidden ? 'Preview: Off' : 'Preview: On'}` in the header

2020-11-08 00:00 UTC, simplywondrous commented on packages/insomnia-app/app/ui/components/page-layout.js
> +                <Pane position="one" ref={handleSetRequestPaneRef}>
Removed that ref in wrapper-debug!

2020-11-08 00:01 UTC, simplywondrous commented on packages/insomnia-app/app/ui/components/page-layout.js
> +                  <Pane position="two" ref={handleSetResponsePaneRef}>
Removed that ref in wrapper-debug!

2020-11-08 00:22 UTC, simplywondrous commented
Merged and updated :)

2020-11-09 01:43 UTC, develohpanda commented
Merge looks good! Any future conflicts should only be prop changes to `GrpcRequestPane` and `GrpcResponsePane`. Unfortunately there is another piece of work in progress that touches this code, but all of the foundational work is in place and I don't anticipate any more major conflicts.

2020-11-09 10:44 UTC, DMarby commented on packages/insomnia-app/app/ui/components/wrapper-design.js
>      let swaggerUiSpec;
Sorry, to clarify, I meant that the `swaggerUiSpec` part here in `render()` can be removed unless I'm mistaken:
```
    let swaggerUiSpec;
    try {
      swaggerUiSpec = parseApiSpec(activeApiSpec.contents).contents;
    } catch (err) {}

    if (!swaggerUiSpec) {
      swaggerUiSpec = {};
    }
```

You moved that up to `_renderPreview` function where it's now used, but it's still defined here in `render()` as well, even tho it's not used there anymore.

2020-11-09 10:50 UTC, DMarby requested changes
There's still some dead code in the `render()` function of WrapperDesign, but as long as that gets removed this looks good to go: https://github.com/Kong/insomnia/pull/2712#discussion_r519712832

Thanks for implementing this @simplywondrous!

2020-11-13 01:19 UTC, simplywondrous commented on packages/insomnia-app/app/ui/components/wrapper-design.js
>      let swaggerUiSpec;
Ahh gotcha, removed!

2020-11-13 02:00 UTC, develohpanda requested changes
Just keeping an eye on merge conflict resolution and noticed some props need to be sent through 👀 should be a quick one

gRPC work is 90% complete so there will not be any more conflicts 🤞

2020-11-13 02:00 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-debug.js
> -              />
I think this snippet was lost after the last merge 😄 The `<GrpcResponsePane />` tag has been moved across to `_renderResponsePane()`, just need to put these three props on it!

2020-11-13 05:29 UTC, simplywondrous commented on packages/insomnia-app/app/ui/components/wrapper-debug.js
> -              />
Oh! I looked at the last four commits but can't find where I accidentally merged that out... would you happen to know what happened? In any case, adding it back in now!

2020-11-13 05:51 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-debug.js
> -              />
No stress, it was bound to be a tricky one and very evident during QA. Here's what _I think_ happened.

This particular change with the props was lost as part of the last merge commit [`0332327` (#2712)](https://github.com/Kong/insomnia/pull/2712/commits/0332327837bf978f6b8a0325819849d2cbeffce7), but you won't see it when viewing that individual commit.

Each commit in git is a _change since the previous commit_, right? For this branch, the previous commit is [`9037d8d` (#2712)](https://github.com/Kong/insomnia/pull/2712/commits/9037d8d93f146484e987ec7065cbdd579708bfca), and that commit didn't have these props, because these props were introduced in a very recent commit on develop.

However! When comparing the whole PR against develop we can see that the props are lost.

It's a bit easier to draw a commit tree to explain, but I hope that makes sense? 😆 When you last merged with develop and resolved conflicts, I think it should have shown the conflict, but because `wrapper-debug` had a **lot** of lines moved around. Even looking at this PR alone, `wrapper-debug` has a lot of stuff moved around, but few functional changed. It would have been difficult to spot while resolving conflicts, and your IDE probably wouldn't have helped either...

2020-11-13 05:54 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-debug.js
> -              />
You could probably experiment as well if you want 🤓 create a new branch from [`9037d8d` (#2712)](https://github.com/Kong/insomnia/pull/2712/commits/9037d8d93f146484e987ec7065cbdd579708bfca) and try merge develop into it, you can double check the conflicts to see if that change was there.

2020-11-13 05:55 UTC, develohpanda approved these changes
🎉

2020-11-13 18:06 UTC, DMarby approved these changes
:shipit:

2020-11-14 04:27 UTC, simplywondrous commented on packages/insomnia-app/app/ui/components/wrapper-debug.js
> -              />
Ohh I see I see. Thanks for the explanation! Checking out that commit and then trying to merge, I see where the conflict was. 

Hmm... other than good tests and QA, is there a good way to detect merge errors like that one? I guess while it seems hard to trace within the branch, it'd be more trivial to trace the PR as the culprit if it were merged in with the error.

2020-11-16 10:04 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-debug.js
> -              />
That's a great question! Unit and integration tests would definitely help, but unless there's really high test coverage in the impacted areas it's hard to rely entirely on them. Unfortunately I don't think there's one great solution for safely resolving large conflicts, and it feels more difficult in an open-source project.

In my experience, with any large refactor (in terms of lines/files in particular), I've found that it's best to do it in a tightly scoped piece of work, and get that merged into the main branch fairly quickly. For example, if a feature requires some groundwork refactoring, do the refactoring first and ensure there is _no functional change_ to the existing code, merge that in, and then build the feature on top. This way it's easier to review and validate the refactor and feature separately. The longer a valid refactor stays in a child branch, the more likely it is there will be a difficult conflict to resolve. This isn't always possible, but I opt for it when it _is_ possible.

Additionally, when you as a developer know that you work is likely to conflict with someone else's work, and it's going to be difficult to avoid a conflict, it's good to communicate that early and stay on the lookout. In previous roles I've paired up with a team-mate when it comes to resolving the conflict, as each party has a good understanding of each side of the conflict, so it's easier to resolve correctly. This is definitely more challenging to co-ordinate in the open-source world, where as a maintainer I'm trying to keep up with OS PRs that might conflict, and also internal work that might benefit from or conflict with OS PRs, but in a completely asynchronous manner.

My goal with this PR was to hopefully merge it in _before_ starting with the gRPC work as I was anticipating some conflicts, but timing/deadlines didn't quite align. Even viewing the diff of this PR, because of the number of lines changed in `wrapper-debug`, I would have missed that the props on the `GrpcResponePane` were lost... I only picked it up because I was explicitly looking for it, given that was my side of the conflict. Pseudo pair-programming! 😄

We try to QA each PR before merging it, but even if this slipped through the cracks, like you said tracing it back to this PR would have been quite easy as a reactive measure (have a look at [`git bisect`](https://www.metaltoad.com/blog/beginners-guide-git-bisect-process-elimination)). What I've described above are some preventative measures.

2020-11-18 14:24 UTC, simplywondrous commented
Is this PR waiting for another review? Otherwise can it be merged in?

2020-11-18 23:06 UTC, develohpanda commented
We've held off on merging OS PRs for the last week or so, pushing for a big release. Now that 2020.5 is on the horizon, we'll start merging OS PRs again. No more reviews needed, this PR is good to go. 😄

2020-11-19 00:13 UTC, merged

2021-01-15 06:01 UTC, roqueemir reviewed
> @