Allow Autocomplete to be properly registered as a Shortcut
getinsomnia/insomnia pull request #2726
Opened 2020-10-15 15:14 UTC by thewheat

- Closes #1633
- Currently we display "Show Autocomplete" under the list of customizable keyboard shortcuts **but in actual testing it does not work**
![image](https://user-images.githubusercontent.com/892961/96149290-b8a15500-0f3b-11eb-8903-424740a88d9c.png)
- The shortcut is currently hardcoded in the `autocomplete.js`
- 

**Current issue**
- If you modify the shortcut you need to reload Insomnia for it to register (still trying to find a way for this but open for guidance on this 😃)

2020-10-15 15:16 UTC, thewheat commented on packages/insomnia-app/app/ui/components/codemirror/extensions/autocomplete.js
> +    };
Docs on CodeMirror's keymap https://codemirror.net/doc/manual.html#keymaps

2020-10-16 17:44 UTC, nijikokun commented
We might need a little piece of text or notice that a reload is required. cc @erickrico

2020-10-17 13:49 UTC, thewheat commented
@nijikokun I could definitely look into that route in this (or in another PR if this PR is something we'd want to merge first) 👍
I did some digging and wasn't able to find anything helpful to trigger a shortcut refresh in CodeMirror. So having a message may be an easier and quicker win for now

2020-10-24 09:26 UTC, thewheat commented
I've dug around a bit but haven't been able to find a good way to refresh the shortcuts on update but in testing further it looks like a full reload isn't necessary, we just need to select a new request and it works

![image](https://user-images.githubusercontent.com/892961/97078256-8b306780-161d-11eb-8009-55fd54b4ad52.png)

If we were to display a message, how best should we do it? Tried mocking up this up in the settings section and it looks a bit odd if just add to the description
![image](https://user-images.githubusercontent.com/892961/97078269-b31fcb00-161d-11eb-9c3e-f771bfa8fd9f.png)

Perhaps the displaying of the message could be worked on in another PR? I'll set this PR as ready for review and if we want all the changes in this PR I'll be happy to make the change with some guidance on how best proceed 👍

2020-10-24 13:49 UTC, develohpanda commented
Hi @thewheat! Sorry about the delay. There are a lot of PRs to get through and I haven't had a chance to work through them all yet. 😢 

> If you modify the shortcut you need to reload Insomnia for it to register (still trying to find a way for this but open for guidance on this 😃)

There is a `uniquenessKey` applied to the root component of the app to trigger a force refresh of the UI without the need to reload the app. You should be able to do something with altering this at an appropriate time. See the usages of `forceRefreshCounter` inside the file below.

https://github.com/Kong/insomnia/blob/543dc2df99ed602b002f532da7a937c92a3ffc61/packages/insomnia-app/app/ui/containers/app.js#L1283

2020-10-27 01:02 UTC, thewheat commented
No worries @develohpanda ! Thanks for the tip there, I'll try do some digging this weekend 👍

2020-12-06 18:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/insomnia?pullRequest=2726) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/insomnia?pullRequest=2726) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/insomnia?pullRequest=2726) it.</sub>

2021-02-14 04:19 UTC, thewheat commented
Took a long while for me to get back to this 😅 Digging around I saw that there was a method to refresh the wrapper

https://github.com/Kong/insomnia/blob/e9fb34490ac4d118c0374d356133f41d3e498cd6/packages/insomnia-app/app/ui/components/wrapper.js#L495-L497

But using that didn't work. There was another method (shown below) that adds a 100ms delay before the refresh and that successfully got it working! 🎉  So dediced to refactor that logic into its own method to be called in the existing location and in the new code when shortcuts are updated

https://github.com/Kong/insomnia/blob/e9fb34490ac4d118c0374d356133f41d3e498cd6/packages/insomnia-app/app/ui/components/wrapper.js#L227-L236

If there was another way to approach this do let me know!

**Demo**
![gif2](https://user-images.githubusercontent.com/892961/107868343-bbe32800-6ebe-11eb-8a5e-7e12114f7b74.gif)

2021-02-15 23:37 UTC, develohpanda requested changes
Really great work, and no worries about the delay 🙂 

Looks good to me overall! There's only one blocker in my review, and that is to `await` the model update before triggering a refresh. The remaining items are just observations where I think it might be useful to add some code comments. 🤗

2021-02-15 23:37 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/settings-modal.js
> +    this.props.handleUpdateKeyBindings();
Model updates are asynchronous and because the callback depends on keybindings having updated correctly, I think we need to `await` the model update now to avoid race conditions.

2021-02-15 23:37 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper.js
> +              handleUpdateKeyBindings={this._forceRequestPaneRefreshAfterDelay}
Seems like an OK solution to me given the current state 👍🏽

2021-02-15 23:37 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/codemirror/extensions/autocomplete.js
> +    for (const keyComb of keyCombs) {
This is some awesome voodoo!!

Could you please add a small comment here about what this for-loop is doing to the `keymap` object, for anybody venturing here in the future?

2021-02-15 23:37 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/codemirror/extensions/autocomplete.js
> +      const meta = keyComb.meta ? 'Cmd-' : '';
I think this should only happen if we're on a mac, otherwise default back to ctrl 🤔 thoughts? https://github.com/Kong/insomnia/blob/c4babfc129c737eb46f1f92e2992c72dfae34bfa/packages/insomnia-app/app/ui/components/keydown-binder.js#L25

2021-02-15 23:37 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/codemirror/extensions/autocomplete.js
> +      const key = `${shift}${meta}${ctrl}${alt}${keyname}`;
There's a snippet in the documentation above where it talks about the keymap being in the expected order, otherwise `normalizeKeyMap` should be used.

I think it might be worth adding a comment that the key order used here is significant (and to not change it), and maybe link to the docs?

> When a map contains multi-stoke bindings **or** keys with modifiers that are not specified in the default order (`Shift-Cmd-Ctrl-Alt`), you must call `CodeMirror.normalizeKeyMap` on it before it can be used. This function takes a keymap and modifies it to normalize modifier order and properly recognize multi-stroke bindings. It will return the keymap itself.

2021-02-26 08:23 UTC, thewheat commented on packages/insomnia-app/app/ui/components/codemirror/extensions/autocomplete.js
> +      const meta = keyComb.meta ? 'Cmd-' : '';
This is actually on purpose
- We shouldn't map it to `Ctrl` as there is already `keyComb.ctrl`. The `keyComb` object indicates the full raw shortcut. So for Windows the meta key should map to `Win` and I guess on Linux it maps to `Meta`
- The `meta` variable is used to create the `key` value (line 157). `key` is then fed into CodeMirror whose docs says supports `Ctrl`, `Shift`, `Alt`, `Cmd`

![image](https://user-images.githubusercontent.com/892961/109271417-745b8500-784a-11eb-8e08-31facc1da53a.png)

Tested a couple in Windows and registering `Cmd` in Codemirror does work to recognize the `Win` key. [Test file here](https://gist.github.com/thewheat/d852b807a3b92cb7c37f6ab82f6d1e6d)
![image](https://user-images.githubusercontent.com/892961/109274461-7fb0af80-784e-11eb-9acc-c7605c224540.png)

2021-02-26 08:23 UTC, thewheat commented on packages/insomnia-app/app/ui/components/codemirror/extensions/autocomplete.js
> +    for (const keyComb of keyCombs) {
Sure thing!

2021-02-26 08:25 UTC, thewheat commented on packages/insomnia-app/app/ui/components/codemirror/extensions/autocomplete.js
> +      const key = `${shift}${meta}${ctrl}${alt}${keyname}`;
Ah good call. Definitely will add it!

2021-02-26 08:30 UTC, thewheat commented on packages/insomnia-app/app/ui/components/modals/settings-modal.js
> +    this.props.handleUpdateKeyBindings();
Thanks for this. I just realised after updating to the latest code base, that the refreshing mechanism I used doesn't work correctly anymore (even with using `await models.settings.update(this.props.settings, { hotKeyRegistry });` 😞

- CodeEditor instances (the URL and the response body) do not get rerendered when `forceRefreshKey` is set to a new value. 
- They will only get rerendred when there are any changes in them

Any idea how to force them to rerender to pick up changes? 

![image](https://user-images.githubusercontent.com/892961/109275524-d23e9b80-784f-11eb-8ec0-2f92155098d9.png)

2021-03-01 04:51 UTC, thewheat commented on packages/insomnia-app/app/ui/components/modals/settings-modal.js
> +    this.props.handleUpdateKeyBindings();
Hopefully these screenshots and GIF can help demonstrate the current issue

**Comparing old code base and new code base behaviours of CodeEditor rendering**
- [test code for old code base](https://github.com/thewheat/insomnia/tree/fix-autocomplete-shortcut-old-version-oct-27)
- [test code for new code base](https://github.com/thewheat/insomnia/tree/fix-autocomplete-shortcut-debug)
![image](https://user-images.githubusercontent.com/892961/109452401-9c392b80-7a8a-11eb-8638-8de4eb54b0ee.png)

**New code base only rerenders CodeEditor when updating contents**
![change_content_rerenders](https://user-images.githubusercontent.com/892961/109452635-297c8000-7a8b-11eb-80de-678bdd48bf1a.png)

**Demo of shortcuts not working until contents are changed**
![Shortcuts dont work until contents change](https://user-images.githubusercontent.com/892961/109452673-42853100-7a8b-11eb-90fe-e5ce0d24c167.gif)

2021-03-01 06:36 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/settings-modal.js
> +    this.props.handleUpdateKeyBindings();
Wow, amazing investigation! I'm not totally surprised at this because a _lot_ has changed since Oct 27th (we introduced gRPC, for starters!). I can think of a few changes which may have caused this behavior (have a look inside `page-layout.js`), but I will dig deeper when I get a chance to code-review in detail.

2021-09-15 09:06 UTC, develohpanda approved these changes
I pushed a few commits to replace the `_forceRequestPaneRefreshAfterDelay` approach. While testing I had noticed that the code-editor would briefly lose focus while typing immediately after changing a keyboard shortcut.

Instead I replaced the delay and force refresh approach by connecting the code-editor to `settings.hotKeyRegistry` in redux. I tested this a bit and it seems to be working well! Please have a look at the last few commits that add this!

![2021-09-15 20 51 12](https://user-images.githubusercontent.com/4312346/133404794-328e1b55-8986-42a8-8753-7001b2dfe0f0.gif)

2021-09-15 13:01 UTC, merged