Adds sorting to Documentation Browser - Closes #2720
getinsomnia/insomnia pull request #2732
Opened 2020-10-16 19:01 UTC by tomprats

Really simple addition to sort list of graphql queries. Really helps in apps with a large number. Right now they're shown in a seemingly random order. Still might be better to have a full search (since ctrl-f doesn't seem to work), but this is a good start either way.

My original change was just:

```
+     {Object.keys(fields).map(key => {
-     {Object.keys(fields).sort().map(key => {
```

But eslint didn't like that. It's auto-fix did something like:

```
{Object.keys(fields)
  .sort()
  .map(key => {
    ...
```

Which indented most of the file a whole lot, so I wasn't sure if it was worth the large change log or if a variable was the better option. Let me know what you'd prefer and I can update it!

2020-10-28 09:17 UTC, develohpanda approved these changes
Thanks @tomprats! This looks good to me.

2020-10-28 12:38 UTC, DMarby requested changes

2020-10-28 12:38 UTC, DMarby commented on packages/insomnia-app/app/ui/components/graph-ql-explorer/graph-ql-explorer-type.js
> +    const fieldKeys = Object.keys(fields).sort();
```suggestion
    const fieldKeys = Object.keys(fields).sort((a, b) => a.localeCompare(b));
```

I think it would be more appropriate to use `localeCompare` here, since we're comparing names. This will ensure that non-ascii characters and such are handled correctly.

2020-10-30 16:02 UTC, tomprats commented
Thanks for checking it out! I used the Github buttons to incorporate your change and get it up to date with develop. Let me know if there's anything else

2020-10-30 16:35 UTC, DMarby approved these changes
Looks good, thank you for implementing this @tomprats!

After talking to @nijikokun, I have unlinked the #2732 issue from this PR so that it will remain open after this is merged, as we'd still like to have sorting implemented in the future as well.

2020-11-17 16:52 UTC, tomprats commented
@DMarby Any next steps I can do to get this merged? Would really love to have this functionality!

2020-11-17 19:48 UTC, develohpanda commented
Hi @tomprats, we've been pushing for an already large release and have halted merging open source PRs until then. Once the next release is out, we'll get through the remaining PRs and potentially do a patch release after. 😊

2020-11-17 20:18 UTC, tomprats commented
Sounds good! I appreciate your time

2020-11-19 00:33 UTC, develohpanda commented
Netlify failure can be ignored, we need to investigate why it's occasionally failing, but your PR didn't break anything there. 😄

2020-11-19 00:34 UTC, merged