Allow prompt values to be clear
getinsomnia/insomnia pull request #2736
Opened 2020-10-17 16:48 UTC by jgiovaresco

Should Closes #1456

I'm trying to implement what Greg describes in this [comment](https://github.com/Kong/insomnia/issues/1456#issuecomment-524422705): add a way to define actions in template tag.

I've managed to implement it, some screenshot of the TagEditor

With 1 action
<img width="836" alt="Screenshot 2020-10-17 at 18 45 44" src="https://user-images.githubusercontent.com/4171593/96348472-4babcd80-10a9-11eb-9ac0-63fa3edd920d.png">

With more actions
<img width="833" alt="Screenshot 2020-10-17 at 18 47 24" src="https://user-images.githubusercontent.com/4171593/96348478-54040880-10a9-11eb-85e5-8f607003dee9.png">

However, I'm blocking on how we can provide some context to the action callbacks. 🤔 

To solve issue #1456, I would need a reference on `context.store` at least but, I can't find a way to do that 😞 

@develohpanda @nijikokun @DMarby, would you have some time to take a look at this 🙏  ?

2020-10-20 06:41 UTC, develohpanda commented
> However, I'm blocking on how we can provide some context to the action callbacks.

My guess is to investigate how the `helperContext` is built (when needed) for running the template tag, and do something similar for the action button.

https://github.com/Kong/insomnia/blob/27d588168457679f9e28463d43c7119b3c2f58b6/packages/insomnia-app/app/templating/base-extension.js#L130

I suggest only exposing the `store` context for now, but it should be built in the standard way that allows other contexts' to be added, should they be required.

2020-10-22 05:45 UTC, jgiovaresco commented
@develohpanda

I've managed to provide a context to the action callback. I had to look deeper on how plugins & nunjunks tags are working but it was interesting :)
I'm wondering if I should create a PR that will add only the feature "Define actions buttons on a template tag" and another that will fix the original issue? Or I keep this one 🤔

2020-11-27 02:58 UTC, develohpanda requested changes
> I've managed to provide a context to the action callback. I had to look deeper on how plugins & nunjunks tags are working but it was interesting :)

💯 

> I'm wondering if I should create a PR that will add only the feature "Define actions buttons on a template tag" and another that will fix the original issue? Or I keep this one 🤔

Am I understanding correctly that in order to create another PR to fix the original issue, you will only need to move the changes in `plugins/insomnia-plugin-prompt/index.js`? If that's the case, I think what you've done here is fine. In order to fix the original issue, the plugin API needed to be extended so this is all related.

2020-11-27 02:58 UTC, develohpanda commented on packages/insomnia-app/app/plugins/context/store.js
> +export type PluginStore = {
👍

2020-11-27 02:58 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/templating/tag-editor.js
> +    return action.run(helperContext);
I suggest after running an action we also refresh the preview. In your original gif, after you clear the prompt, the preview still shows the old value and it looks as though nothing happened.

2020-11-27 02:58 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/templating/tag-editor.js
> +        key={index}
We need to [avoid index as keys](https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318). You should be able to use the `name` as the key, given we can safely assume actions in a particular plugin will always have unique names.

2020-11-27 02:58 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/templating/tag-editor.js
> +        {actions.map((action, index) => this.renderAction(action, index))}
Can be simplified 😄 

```suggestion
        {actions.map(this.renderAction)}
```

2020-11-27 02:58 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/templating/tag-editor.js
> +        {activeTagDefinition && this.renderActions(activeTagDefinition.actions)}
I think this should avoid rendering an empty `form-row` if no actions exist, as such you can either do it here or inside `this.renderActions`.

```suggestion
        {activeTagDefinition?.actions?.length && this.renderActions(activeTagDefinition.actions)}
```

2020-11-27 02:58 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/templating/tag-editor.js
> +    });
Doesn't look like plugin is used any longer?

```suggestion
    const activeTemplateTag = templateTags.find(({ templateTag }) => {
      return templateTag.name === this.state.activeTagData.name;
    });
```

2020-11-27 03:04 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/templating/tag-editor.js
> +  renderActions(actions = []) {
It might be good to label the buttons row with "Actions", similar to how the "Title" and "Label" appear, so that we have a title for the section. Looking at the screenshots, it looks a little out of place.

2020-11-27 06:54 UTC, jgiovaresco commented on packages/insomnia-app/app/ui/components/templating/tag-editor.js
> +        key={index}
🤦  
A great developer explained that to me during a tech interview I had recently :p

2020-11-27 08:07 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/templating/tag-editor.js
> +        key={index}
You did this PR beforehand, and I just noticed now while reviewing 😆

2020-11-30 02:03 UTC, develohpanda approved these changes
LGTM 👍

2020-11-30 16:58 UTC, DMarby approved these changes

2020-11-30 16:58 UTC, DMarby commented on packages/insomnia-app/app/plugins/context/store.js
> +  getItem(string): Promise<boolean | null>,
This signature doesn't seem to match the function

```suggestion
  getItem(string): Promise<string | null>,
```

2020-11-30 16:59 UTC, DMarby requested changes
Looks good other then the mismatching type definition 👍

2020-11-30 17:26 UTC, jgiovaresco commented on packages/insomnia-app/app/plugins/context/store.js
> +  getItem(string): Promise<boolean | null>,
good catch 😅

2020-11-30 17:49 UTC, DMarby approved these changes

2020-11-30 23:15 UTC, merged

2020-11-30 23:15 UTC, develohpanda commented
Docs have been updated: https://support.insomnia.rest/article/26-plugins#template-tags

2020-12-01 00:35 UTC, scottmmmm commented
Amazing! My issue got fixed!

2020-12-01 00:41 UTC, develohpanda commented
Thanks for reporting it initially, @scottmmmm! We do have a release planned for this week, unfortunately this PR won't make it in. There will likely be a patch release early 2021 with this included!