Fix Copy as CURL with Multipart
getinsomnia/insomnia pull request #2740
Opened 2020-10-19 06:04 UTC by jgiovaresco

The issue was located in the `exportHar` function. It was not handled `file` param correctly.
For this type of file, the `value` attribute is empty, therefore we should take instead the `fileName`

`Generate code` feature was also impacted by the issue

Closes #2282

**Before**

```
curl --request POST \
  --url http://localhost:3000/multipart \
  --header 'Content-Type: multipart/form-data' \
  --header 'content-type: multipart/form-data; boundary=---011000010111000001101001' \
  --form my_file=\
  --form my_field=my_value
```

**After**

```
curl --request POST \
  --url http://localhost:3000/multipart \
  --header 'Content-Type: multipart/form-data' \
  --header 'content-type: multipart/form-data; boundary=---011000010111000001101001' \
  --form my_file=/Users/jgiovaresco/Documents/Untitled \
  --form my_field=my_value
```

2020-10-19 15:55 UTC, nijikokun commented
Awesome change, I assume this works for multi-file as well?

2020-10-20 06:11 UTC, jgiovaresco commented
> Awesome change, I assume this works for multi-file as well?

You are assuming right ;)
I've updated the unit test to be sure. 😅 

```
curl --request POST \
  --url http://localhost:3000/multipart \
  --header 'Content-Type: multipart/form-data' \
  --header 'content-type: multipart/form-data; boundary=---011000010111000001101001' \
  --form my_file=/Users/jgiovaresco/Documents/Untitled \
  --form my_field=my_value \
  --form my_second_file=/Users/jgiovaresco/Documents/AFTER.gif
```

2020-10-21 20:51 UTC, reynolek approved these changes
This change makes sense to me.

2020-11-19 00:44 UTC, develohpanda approved these changes
LGTM, sorry for the delay in getting to this!

2020-11-20 17:43 UTC, DMarby requested changes

2020-11-20 17:43 UTC, DMarby commented on packages/insomnia-app/app/common/har.js
> +          value: param.fileName,
While this now correctly includes the path in the generated curl command, it doesn't actually work correctly when you run it, as curl needs a file path to be prepended with `@` in order for it to read it.

If we set `fileName` instead of `value`, httpsnippet will do so:
https://github.com/Kong/httpsnippet/blob/dc08d8338a5e27caa3bdddb0131c3ed8eb92080c/src/targets/shell/curl.js#L48-L52

```suggestion
          fileName: param.fileName,
```

2020-11-21 08:39 UTC, jgiovaresco commented on packages/insomnia-app/app/common/har.js
> +          value: param.fileName,
Arf good catch I should have took a look at httpsnippet 🤦

2020-11-23 13:29 UTC, DMarby approved these changes
LGTM, thanks for fixing this @jgiovaresco!

2020-11-24 01:33 UTC, merged