Modal prompt to select protofile
getinsomnia/insomnia pull request #2756
Opened 2020-10-21 04:19 UTC by develohpanda

WIP

2020-10-21 05:00 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/proto-files-modal.js
> +const ProtoFileListItem = (props: {
Extract this component (and a new component - `ProtoFileList`) into `ui`.

2020-10-22 12:23 UTC, DMarby requested changes

2020-10-22 12:23 UTC, DMarby commented on packages/insomnia-app/app/ui/components/modals/proto-files-modal.js
> +  onSave?: string => Promise<void>,
I don't think that `onSave` should be an optional parameter here.
There's currently no case where we wouldn't want to persist a change in this modal, and not passing this would lead to the Save button just not doing anything, which is confusing.

2020-10-22 19:04 UTC, DMarby approved these changes
Awesome 🎉

2020-10-22 19:14 UTC, merged