Add specification linting for files
getinsomnia/insomnia pull request #2773
Opened 2020-10-24 04:12 UTC by joemirizio

Closes #2769

Adds support for linting a local specification file (e.g. `inso lint spec ./spec.yaml`).

#### Lint steps
1. Try to load from db
2. Try to load from file. The file path is resolved in the same way as `generate config`.
3. Trace log if the file path is blank or the file is not found and return `false`
4. Log linting results and return success

2020-10-28 14:53 UTC, joemirizio commented
@develohpanda no rush on the review, but would you consider adding the `hacktoberfest-accepted` label to this PR before the Oct 31st deadline?

2020-10-28 20:53 UTC, develohpanda commented
Hey @joemirizio! Because this repo is opted-in to Hacktoberfest, as long as we don't mark this PR as spam (which it isn't), it will count as a contribution. On you Hacktoberfest dashboard, it should mature after 14 days (which is the time they give to maintainers to mark as spam).

2020-10-28 21:23 UTC, joemirizio commented
Based on the [FAQ](https://hacktoberfest.digitalocean.com/faq) and the [update](https://hacktoberfest.digitalocean.com/hacktoberfest-update), I think PR's need to merged/approved by Nov 1st or `hacktoberfest-accepted` labeled. My dashboard lists it as "Pending" and does not show it maturing.

> Pull requests in repositories with the ‘hacktoberfest’ topic will also need to be merged, approved by a maintainer, or labeled as ‘hacktoberfest-accepted’ in order to qualify. The deadline for completions, merging, labeling, and approving is November 1.

2020-10-28 21:26 UTC, develohpanda requested changes
Nice work, some minor feedback!

2020-10-28 21:26 UTC, develohpanda commented on packages/insomnia-inso/src/commands/lint-specification.js
> +      logger.trace(`Reading specification from file \`${fileName}\``);
Please update this trace to the following

```suggestion
      logger.trace(`Linting specification from file \`${fileName}\``);
```

2020-10-28 21:26 UTC, develohpanda commented on packages/insomnia-inso/src/commands/lint-specification.js
> +        throw new InsoError('Specification not found.');
Please update this error message to the following, or something similar:
```suggestion
        throw new InsoError(`Failed to read "${fileName}"`, e);
```

2020-10-28 21:26 UTC, develohpanda commented on packages/insomnia-inso/src/commands/lint-specification.js
> +    }
Controlling flow through exceptions is generally discouraged as it is inefficient and difficult to follow. Re-throwing an external (such as a file read exception) with `InsoError` is useful because it provides additional context, but throwing an exception in this `else` block is avoidable.

You can simply log and exit:

```suggestion
    } else {
      logger.fatal(`Specification not found.`);
      return false;
    }
```

2020-10-28 21:26 UTC, develohpanda commented on packages/insomnia-inso/src/commands/__tests__/lint-specification.test.js
> +      '.insomnia/ApiSpec/spc_46c5a4a40e83445a9bd9d9758b86c16c.yml',
This should be a standard OpenAPI yaml file (for all tests you have introduced), rather than the database file in a `.insomnia` folder. The contents are different. 

Please save the following file at `src/commands/__fixtures__/openapi-spec.yaml` and use that:
```yaml
openapi: '3.0.2'
info:
  title: Sample Spec
  version: '1.2'
servers:
  - url: https://200.insomnia.rest
tags:
  - name: Folder
paths:
  /global:
    get:
      tags:
        - Folder
      responses:
        '200':
          description: OK
  /override:
    get:
      responses:
        '200':
          description: OK
```

2020-10-28 21:26 UTC, develohpanda commented on packages/insomnia-inso/src/commands/__tests__/lint-specification.test.js
> +  });
👏

2020-10-28 21:26 UTC, develohpanda commented on packages/insomnia-inso/src/commands/__tests__/lint-specification.test.js
> +        workingDir: 'src/db/__fixtures__/git-repo',
There is a visual false positive here (even though there is technically nothing wrong) - the `workingDir` and `directory` are identical.

To be clearer, I suggest setting the `workingDir` to some other directory entirely, so it's easy to see at a glance that `workingDir` is ignored.

2020-10-28 21:30 UTC, develohpanda commented
> Based on the [FAQ](https://hacktoberfest.digitalocean.com/faq) and the [update](https://hacktoberfest.digitalocean.com/hacktoberfest-update), I think PR's need to merged/approved by Nov 1st or `hacktoberfest-accepted` labeled. My dashboard lists it as "Pending" and does not show it maturing.
> 
> > Pull requests in repositories with the ‘hacktoberfest’ topic will also need to be merged, approved by a maintainer, or labeled as ‘hacktoberfest-accepted’ in order to qualify. The deadline for completions, merging, labeling, and approving is November 1.

Oh, this requirement for opted-in repos is news to me... No worries, I'll run through PRs today and add the appropriate label. I read this from the FAQ a few days ago and gathered a different understanding 😞 

![image](https://user-images.githubusercontent.com/4312346/97498671-7a8f4100-19d1-11eb-983a-9361d0409ebf.png)

**Thanks for letting me know!**

2020-10-29 00:34 UTC, joemirizio commented on packages/insomnia-inso/src/commands/lint-specification.js
> +    }
Gotcha! I know some prefer using a single error state handling block and didn't think it was too much control flow manipulation, but I can certainly change.

2020-10-29 00:35 UTC, joemirizio commented on packages/insomnia-inso/src/commands/__tests__/lint-specification.test.js
> +      '.insomnia/ApiSpec/spc_46c5a4a40e83445a9bd9d9758b86c16c.yml',
OH! Completely didn't realize it should have been another type of file. Thanks!

2020-10-29 00:36 UTC, joemirizio commented on packages/insomnia-inso/src/commands/__tests__/lint-specification.test.js
> +        workingDir: 'src/db/__fixtures__/git-repo',
Sure thing - I was trying to make it congruent with the other tests, but I can definitely see how this can be confusing.

2020-10-29 01:04 UTC, joemirizio commented
Ah I think my rebase messed up the review comment linking, but I was able to address everything.


> **Thanks for letting me know!**

Absolutely! The rules this year got a little confusing, but I appreciate you applying the label across the project. I use Insomnia all the time and I'm glad I could contribute!

2020-10-29 02:20 UTC, develohpanda commented on packages/insomnia-inso/src/commands/lint-specification.js
> +    }
Ya fair enough! In this case it's easy enough to see because the `throw` and `catch` are so close, but usually that isn't the case. My preference is to keep the catch block only for genuine errors, and exit if we know we can exit.

2020-11-19 04:21 UTC, develohpanda approved these changes
Sorry about the delay! Looks good to me, did some QA locally as well :)

2020-11-20 18:11 UTC, DMarby approved these changes
LGTM!

2020-11-24 02:44 UTC, merged