Setting same sidebar item sorting for the Edit tag request dropdown
getinsomnia/insomnia pull request #2777
Opened 2020-10-24 21:34 UTC by antoine29

This PR is adding a method to get the same item sorting as is in the request left sideBar, for the tag requests dropdown. For the item sorting I'm using the same sorting criteria found in this [selector code](https://github.com/Kong/insomnia/blob/af6a9b6a78a46402bc254e709b31d8dfa9e4b314/packages/insomnia-app/app/ui/redux/selectors.js#L165-L175).
And as you can see if the sidebar item sorting is rearranged, the change will be reflected in the tag requests dropdown too.
![tagReqsSorted](https://user-images.githubusercontent.com/28495651/97093769-d6964600-161c-11eb-8998-829e907a1a30.gif)
This would close #2745

2020-10-27 14:22 UTC, cobwebsonsale commented on packages/insomnia-app/app/ui/components/templating/tag-editor.js
> +      .concat(requestGroups.filter(requestGroup => requestGroup.parentId === parentId))
*nit* since concat happens every time and both the arrays are filtered in the same way, we could send a combined array of `docs` instead.

2020-10-27 14:22 UTC, cobwebsonsale commented on packages/insomnia-app/app/ui/components/templating/tag-editor.js
> +    const sortedReqs = this.sortDocs(requests, requestGroups, this.props.workspace._id);
Sorting the requests in render method causes this to get triggered multiple times. `_refreshModels` updates the `allDocs` state variable. That may be a better place to update the order. Something like:
```
allDocs[models.request.type] = this.sortDocs(allDocs[models.request.type] || [], allDocs[models.requestGroup.type] || [], this.props.workspace._id);
```

`_refreshModels` is called just once per times popup is shown.
<img width="469" alt="Screenshot 2020-10-27 at 7 46 45 PM" src="https://user-images.githubusercontent.com/1848127/97314513-cf29a380-188d-11eb-8a20-bfc92e7df3e6.png">

2020-10-27 14:22 UTC, cobwebsonsale commented on packages/insomnia-app/app/ui/components/templating/tag-editor.js
> +          sortedDocs = sortedDocs.concat(this.sortDocs(requests, requestGroups, doc._id));
Yep, this does it. Nice! :)

2020-10-28 01:29 UTC, antoine29 commented on packages/insomnia-app/app/ui/components/templating/tag-editor.js
> +    const sortedReqs = this.sortDocs(requests, requestGroups, this.props.workspace._id);
You're right. So I moved the sorting logic into the refresh method

2020-10-28 01:30 UTC, antoine29 commented on packages/insomnia-app/app/ui/components/templating/tag-editor.js
> +          sortedDocs = sortedDocs.concat(this.sortDocs(requests, requestGroups, doc._id));
thank you :D

2020-11-01 06:58 UTC, cobwebsonsale commented on packages/insomnia-app/app/ui/components/templating/tag-editor.js
> +  _sortRequests(requests: Array<any>, parentId: string) {
You can use types to specify that this is an array of Requests and RequestGroups. Like suggested [here](https://github.com/Kong/insomnia/pull/2738#discussion_r513076716).

2020-11-02 18:37 UTC, antoine29 commented on packages/insomnia-app/app/ui/components/templating/tag-editor.js
> +  _sortRequests(requests: Array<any>, parentId: string) {
types added :D

2020-11-27 01:45 UTC, develohpanda requested changes
Overall looks good, I've got some minor suggestions. 🙂

Sorry about the delay in getting to this, I've been really bogged down for a while!

2020-11-27 01:45 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/templating/tag-editor.js
> +  _sortRequests(requests: Array<models.request.type | models.requestGroup.type>, parentId: string) {
You can import the type directly and use it. `models.request.type` is actually just a string 😆 

```js
import type { Request } from '../../../models/request';
import type { RequestGroup } from '../../../models/requestGroup';
...
_sortRequests(models: Array<Request | RequestGroup>, parentId: string) { 
```

Also, it seems that using `models` instead of `requests` seems more appropriate here for the parameter, since an item in the array can actually be a `Request` or a `RequestGroup`. By extension, when iterating through the array it would also change to `models.filter(model => ...)`

2020-11-27 01:45 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/templating/tag-editor.js
> +      .map(request => {
Nit picking, but this should likely be a `.forEach` rather than `.map` since we don't use the result for anything.

2020-11-27 01:45 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/templating/tag-editor.js
> +        if (request.type === models.requestGroup.type)
I've created some helpers in `packages/insomnia-app/app/models/helpers/is-model.js` to make these a little less verbose. It would then change to:

```js
if (isRequest(model)) { }
if (isRequestGroup(model)) { }
```

2020-11-27 01:45 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/templating/tag-editor.js
> +      })
#2738 is almost complete and it creates a `metaSortKeySort` helper, linked below. Ideally that is used here, so once that PR is merged in we can update this.

https://github.com/cobwebsonsale/insomnia/blob/bca044f74d8bf437b6775ac5a9cf4c9f5f52ba3d/packages/insomnia-app/app/common/sorting.js#L92-L98

Then, this code would just become:
```suggestion
      .sort(metaSortKeySort)
```

2020-11-27 01:47 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/templating/tag-editor.js
> +  _sortRequests(requests: Array<any>, parentId: string) {
😆 we picked up on the same thing

https://github.com/Kong/insomnia/pull/2777#discussion_r531306885

2020-12-06 18:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/insomnia?pullRequest=2777) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/insomnia?pullRequest=2777) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/insomnia?pullRequest=2777) it.</sub>

2020-12-16 01:52 UTC, antoine29 commented on packages/insomnia-app/app/ui/components/templating/tag-editor.js
> +      })
Sorry for the delay, l lost sight of this PR hehe. Anyways I added the required changes :D

2020-12-16 03:21 UTC, develohpanda approved these changes
Nice! Looks awesome now 👏🏽 Thanks for working through it

2020-12-16 10:13 UTC, DMarby approved these changes

2020-12-16 22:03 UTC, merged