Allow sidebar to show grpc requests
getinsomnia/insomnia pull request #2786
Opened 2020-10-27 02:43 UTC by develohpanda

2020-10-27 13:02 UTC, sonicyeti commented on packages/insomnia-app/app/ui/components/tags/grpc-tag.js
> +    <div className={`tag tag--no-bg tag--small method-grpc`}>
Any chance we could go with the #5ac5c5 value found on the visual accent items on the gRPC site itself? If not, all good. I'm thinking longer term when we have actual gRPC badges in play.

2020-10-27 13:04 UTC, sonicyeti approved these changes
Awesome, only feedback would be on the color of the tag. The gRPC site leverages 5ac5c5 for accents. This would naturally lend well to a unique badge down the road for other scenarios.

2020-10-27 16:42 UTC, DMarby commented on packages/insomnia-app/app/ui/components/tags/grpc-tag.js
> +    <div className={`tag tag--no-bg tag--small method-grpc`}>
Agreed that this would be a nice change.
Perhaps we should also change it in the modal dropdown for creating a request to match then as well?

2020-10-27 17:45 UTC, DMarby requested changes
Some notes from testing:
- The generate as code button should be hidden for gRPC requests as httpsnippet/none of our targets currently supports this
- Same with copy as curl
- Settings can be accessed, but are showing a lot of options that doesn't exist for gRPC, so this needs to be remedied by either adjusting the settings modal, or not allowing access to request settings, or such.
- Moving/copying between workspaces seems to be working, but this will need to be re-tested once #2785 is using GrpcRequestMeta instead of RequestMeta
- Pinning also seems to work since it's using RequestMeta, but again, this needs to be re-tested once it's using GrpcRequestMeta correctly.
- Duplicate and Delete also seems to work, but again, will need to be re-tested to ensure that GrpcRequestMeta is correctly used/cleaned up.

Please address the above issues either in this PR, or by creating linear tickets for them so that they don't get lost.

2020-10-27 17:45 UTC, DMarby commented on packages/insomnia-app/app/ui/redux/helpers.js
> +export const shouldIgnoreChildrenOf = ({ type }: SidebarModels): boolean =>
Since this and the one below are sidebar specific due to being tied to the SidebarModels type, I'd like to see them either have less generic names, or for this file to be renamed to sidebar-helpers.js or similar. 

Generally, organizing things under generic names such as "helper", "util", et al. rather then organizing them by what they do/something more specific, is not a great practice.

2020-10-27 22:00 UTC, develohpanda commented
Nice QA @DMarby! As I was running through it I was happy to see how much of it we get for free.

> Please address the above issues either in this PR, or by creating linear tickets for them so that they don't get lost.

Most of these have linear tickets, and there are some I missed during the initial task creation, which I will now create (namely, removing the items that don't apply to gRPC). They will be fixed in a separate PR, though. This PR makes no changes to the context menu of a request, because there were enough changes required to simply show a gRPC request in the sidebar.

2020-10-27 22:01 UTC, develohpanda commented on packages/insomnia-app/app/ui/redux/helpers.js
> +export const shouldIgnoreChildrenOf = ({ type }: SidebarModels): boolean =>
I'll see if I can pull the entire selector (where these are used) into a separate file. I separated them into this because I wanted to test them, but also didn't want to export them out of the main `selectors.js` file, but I agree in hindsight that I could have named the file better.

2020-10-27 23:18 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/tags/grpc-tag.js
> +    <div className={`tag tag--no-bg tag--small method-grpc`}>
Yes they would all update, as I made sure to source the color from one location `method-grpc`. I will update, I have only been working through functional work and not exact pixels and colors.

2020-10-27 23:19 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/tags/grpc-tag.js
> +    <div className={`tag tag--no-bg tag--small method-grpc`}>
I did take the current yellow from the mocks, but it is not exactly what is in Figma

2020-10-28 04:37 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/tags/grpc-tag.js
> +    <div className={`tag tag--no-bg tag--small method-grpc`}>
#5ac5c5
![image](https://user-images.githubusercontent.com/4312346/97391217-9815c980-1943-11eb-8023-95bbfd59b4d1.png)
![image](https://user-images.githubusercontent.com/4312346/97391421-0f4b5d80-1944-11eb-84bb-8db1efe93dce.png)

#ffbf2f (from Figma)
![image](https://user-images.githubusercontent.com/4312346/97391472-25591e00-1944-11eb-8bc1-b9233c1440a7.png)
![image](https://user-images.githubusercontent.com/4312346/97391482-2c802c00-1944-11eb-92d9-42fc9a7f0509.png)

I have opted to take the color from Figma (#ffbf2f), instead of changing it from the mocks.

2020-10-28 11:42 UTC, DMarby commented on packages/insomnia-app/app/ui/components/tags/grpc-tag.js
> +    <div className={`tag tag--no-bg tag--small method-grpc`}>
@nijikokun Do you have any input on this?

2020-10-28 11:47 UTC, DMarby approved these changes

2020-10-28 22:25 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/tags/grpc-tag.js
> +    <div className={`tag tag--no-bg tag--small method-grpc`}>
I added a card in Linear with a link to this conversation so it is not skipped 🙂 INS-266

2020-10-28 22:44 UTC, merged

2020-11-10 00:45 UTC, sonicyeti commented on packages/insomnia-app/app/ui/components/tags/grpc-tag.js
> +    <div className={`tag tag--no-bg tag--small method-grpc`}>
This should be in, I'm seeing it in your latest branch. Opted for #2FA3A3 to prevent washout on lighter colors vs. the actual hex on the gRPC site.