Allow users to delete synced workspaces from the API
getinsomnia/insomnia pull request #2795
Opened 2020-10-29 17:01 UTC by DMarby

This allows users to remove synced projects from the API, by adding a new item to the sync dropdown menu.

![2020-10-29 17 57 00](https://user-images.githubusercontent.com/174626/97606938-a1209c80-1a10-11eb-8a4a-937559b6d73c.gif)

@nijikokun I know you had some thoughts around the wording/messaging, so I put in a basic placeholder, wasn't sure of a good way to communicate that the workspace will be deleted from the API, but not locally.
Please look it over and let me know what wording you'd prefer.

Fixes INS-236

2020-10-29 17:57 UTC, nijikokun approved these changes

2020-11-02 00:52 UTC, develohpanda requested changes
Code review was good. The testing steps outlined were also good, just found an edge case while doing some exploration.

If you create a workspace with a name that ends or begins with any amount of white-space, the delete modal message trims the white-space even though it is required for confirmation. How would you suggest to handle this case considering the state of data in local and server databases?

In the following screenshot, the workspace name starts and ends with three spaces, but typing the name as prompted does not match, and the delete button is disabled.
![image](https://user-images.githubusercontent.com/4312346/97820088-51dcb380-1d11-11eb-989f-b1831d6e49d5.png)

I know that the intention is to have users type out the workspace name and the pattern is fairly common, however GitHub/Azure (as examples that I have seen) allow you to select and copy the text. Our modal prevents text selection.

![image](https://user-images.githubusercontent.com/4312346/97820143-9cf6c680-1d11-11eb-864f-4cf5dc7f5910.png)

The only time where I feel allowing text selection might be useful for Insomnia in particular, is where the workspace contains special characters. In theory you could go down the rename and delete route, so I'm open to other options if you want to keep text selection disabled. cc: @nijikokun / @erickrico

2020-11-02 14:10 UTC, DMarby commented
Good catch! I was testing with trailing whitespace to ensure the validation was correct, but hadn't thought about the way it was being displayed.

I've corrected the CSS to not collapse whitespaces, so that's it properly displays when you have more then one whitespace somewhere in the name: 
![image](https://user-images.githubusercontent.com/174626/97873560-1beefd80-1d18-11eb-8ecd-a14d64bfac08.png)

As for being able to select, I don't think there's a good reason to disallow it, so I've gone ahead and made that change as well:
![image](https://user-images.githubusercontent.com/174626/97877105-04664380-1d1d-11eb-95b1-16d4bee3b944.png)

2020-11-02 15:28 UTC, sonicyeti approved these changes

2020-11-02 23:59 UTC, develohpanda approved these changes
Looks great!

2020-11-02 23:59 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/sync-delete-modal.js
> +            Please type <strong style={{ whiteSpace: 'pre-wrap' }}>{workspace.name}</strong> to
Nitpicking here, but I'd suggest to put the workspaceName node into a component/variable and reuse it so styles are defined in one place for any future changes

```js
const workspaceName = <strong>...</strong>;

// ...permanently delete the{' '}{workspaceName}{' '}workspace remotely..
```

2020-11-03 13:45 UTC, DMarby commented on packages/insomnia-app/app/ui/components/modals/sync-delete-modal.js
> +            Please type <strong style={{ whiteSpace: 'pre-wrap' }}>{workspace.name}</strong> to
Updated 👍

2020-11-05 22:40 UTC, develohpanda commented
Actually, thinking about this one - are you able to achieve a similar result using the `PromptModal` that already exists? It contains input validation.

I ask because the UI pattern here is very different to all other modals, and preference would be to keep consistent, unless this is a conscious decision cc: @erickrico

2020-11-06 11:04 UTC, DMarby commented
Using a different UI pattern here was a conscious decision made by @nijikokun, as this is a high-impact operation, and none of the existing patterns fitted that well.

I looked at using the PromptModal initially, but it doesn't support text above the input field other than a small label, doesn't provide proper feedback as to when or why a validation is failing, and uses our standard model footer to right-align the submit button (and provides no way to change the state/disable it), which creates a disconnect between the input field and the button that is unwanted for this pattern.

While it would've been possible to modify it to also support this pattern, adding further complexity and special-casing to the PromptModel for this use-case did not feel ideal, which is why I opted to make this a separate component instead.

2020-11-09 22:33 UTC, nijikokun approved these changes
@DMarby looks good to me :+1:

2020-11-09 22:56 UTC, merged