Ut sidebar design integration
getinsomnia/insomnia pull request #2796
Opened 2020-10-29 18:01 UTC by sonicyeti

This PR covers integration of the latest unit testing design sidebar. 

**Features include:**
- Unit tests grouped by their associated testing suite
- Filtering on test suites
- Executing and deleting of test suites within the sidebar
- Collapsing & expanding of suites
- Adding test suites
- Adding individual tests to a suite contextually
- Overall visual design integration

UI Demonstration:

![2020-10-29 13 59 55](https://user-images.githubusercontent.com/52717970/97613519-2bf09f80-19ef-11eb-95d2-474458c2daad.gif)

Fixes INS-121
Fixes INS-258

2020-10-30 14:09 UTC, DMarby requested changes
This is awesome, looks really good visually!

Wasn't really able to run through testing of this as I wasn't able to create any new test suites, so will QA it again in the next round of review.

2020-10-30 14:09 UTC, DMarby commented on packages/insomnia-components/components/sidebar/sidebar-unit-testing.js
> +      }
I think this could be simplified a bit, with something along the lines of this:
```suggestion
      return !filter || suite.name.toLowerCase().includes(filter.toLowerCase())
```

2020-10-30 14:09 UTC, DMarby commented on packages/insomnia-app/app/ui/components/wrapper-unit-test.js
> +    models.unitTest.all().then(res => {
If we're sticking with this approach instead of Redux, I think this should be able to just call `getUnitTests()`?

2020-10-30 14:09 UTC, DMarby commented on packages/insomnia-app/app/ui/components/wrapper-unit-test.js
> +          {unitTests.length > 0 && (
I don't think this conditional is correct, as it currently makes it impossible to create a test-suite in an empty project, as the sidebar is just blank.

2020-10-30 14:09 UTC, DMarby commented on packages/insomnia-app/app/ui/components/wrapper-unit-test.js
> +  async _handleSetActiveUnitTestSuite(e, unitTestSuite: UnitTestSuite): Promise<void> {
Not sure if I understand this change, as far as I can tell this function is identical to `_handleSetActiveSuite` below, and the below function does not seem to get called anywhere?

Not sure if this breaks `_handleCreateTestSuite` as well, since that does not have the event included when calling this function?

2020-10-30 14:09 UTC, DMarby commented on packages/insomnia-app/app/ui/components/wrapper.js
> +  allUnitTests: Array<UnitTest>,
As far as I can tell, this doesn't seem to be used by anything?

2020-10-30 14:09 UTC, DMarby commented on packages/insomnia-components/components/sidebar/sidebar-unit-test-suite-item.js
> +    _id: string,
Would it be possible to use an existing type for this, or define one somewhere, so that this definition doesn't have to be redefined here and for every handler below as it is currently?

Same thing for the SidebarUnitTesting component.

2020-10-30 14:09 UTC, DMarby commented on packages/insomnia-components/components/sidebar/sidebar-unit-testing.js
> +  if (unitTestSuites === null) {
I don't think this is correct, as it will make it impossible to create test suites in an empty workspace.

2020-10-30 14:09 UTC, DMarby commented on packages/insomnia-components/components/sidebar/sidebar-unit-test-suite-item.js
> +        {unitTests.length !== 0 &&
I don't think the .length check is needed here, as `.filter` should work fine on an empty array?

2020-10-30 14:09 UTC, DMarby commented on packages/insomnia-app/app/ui/components/wrapper-unit-test.js
> +    unitTests: models.unitTest.all(),
I think it might be better to get these from Redux instead of directly from the database, doing so would mean that there's no need for a refresh function like `getUnitTests`.

You should be able to create a selector similar to `selectActiveUnitTestSuites`, but for getting all tests belonging to the current workspace:
https://github.com/Kong/insomnia/blob/develop/packages/insomnia-app/app/ui/redux/selectors.js#L307-L313

And use that in app.js to add it to our wrapper props:
https://github.com/Kong/insomnia/blob/develop/packages/insomnia-app/app/ui/containers/app.js#L1377

Then you'll be able to access them from `this.props.wrapperProps`, same as how we access activeUnitTests/activeUnitTestSuite in this file.


---

If we do prefer sticking with grabbing them from the database, I'd prefer if we were to fetch just the unittests belonging to this workspace, instead of all the ones in the database.

2020-10-30 14:09 UTC, DMarby commented on packages/insomnia-components/components/sidebar/sidebar-unit-test-suite-item.js
> +            <span onClick={onExecuteSuiteClick}>
Do we need to handle the case where tests are already running here, as we were doing previously using the `testsRunning` state property?

2020-11-16 13:43 UTC, sonicyeti commented on packages/insomnia-app/app/ui/components/wrapper-unit-test.js
> +          {unitTests.length > 0 && (
I think perhaps that was via the old UI. Here, even if we have an empty spec, we can still create a suite (and tests) on it. 

![2020-11-16 08 41 54](https://user-images.githubusercontent.com/52717970/99259253-b99dfe80-27e7-11eb-901a-3de1002571b4.gif)

2020-11-16 16:17 UTC, sonicyeti commented on packages/insomnia-components/components/sidebar/sidebar-unit-test-suite-item.js
> +            <span onClick={onExecuteSuiteClick}>
Thanks for the catch! Initially we hadn't planned for actions on the left rail suites for this first pass. Converted them to buttons and now checking to disable accordingly!

2020-11-16 16:39 UTC, sonicyeti commented on packages/insomnia-components/components/sidebar/sidebar-unit-testing.js
> +  if (unitTestSuites === null) {
Add suite is part of the UT header component so we can still add them but it did make me realize that we shouldn't actually show the filter input if suites haven't been created, fixed that.

2020-11-16 17:09 UTC, DMarby commented on packages/insomnia-app/app/ui/components/wrapper-unit-test.js
> +          {unitTests.length > 0 && (
Sorry, but no, this logic is wrong and needs to be removed.
It works for you since you're pulling *all unit-tests* rather then the ones for just the workspace, but when you have an instance of Designer with no workspaces with unit-tests, this makes the sidebar not render at all:

![image](https://user-images.githubusercontent.com/174626/99284627-c564e180-2836-11eb-8c60-afaa0bc4472e.png)

2020-11-16 17:11 UTC, DMarby commented on packages/insomnia-components/components/sidebar/sidebar-unit-testing.js
> +  if (unitTestSuites === null) {
Returning here will make the UT header component not render, as it's included further down, so this logic is unfortunately still incorrect.

2020-11-16 17:24 UTC, sonicyeti commented on packages/insomnia-app/app/ui/components/wrapper-unit-test.js
> +          {unitTests.length > 0 && (
Ah gotcha, hadn't tested this without tests across all workspaces. Yep, will fix now!

2020-11-16 17:35 UTC, sonicyeti commented on packages/insomnia-components/components/sidebar/sidebar-unit-testing.js
> +  if (unitTestSuites === null) {
Yanked it entirely.

2020-11-25 14:48 UTC, closed without merging