Fix for random UI crash #2805
getinsomnia/insomnia pull request #2840
Opened 2020-11-16 15:14 UTC by MrSnix

After some analysis i found out the main problem it's related to the `from.line` which has an `undefined` value in some situations (which i was not able to reproduce). `foldOptions.widget(from, to)` is called internally by CodeMirror when you want to fold code inside the editor itself. This makes React crash when the "Send" button is pressed because the CodeMirror state is not consistent due to invalid folding triggering an infinite setState.

I was thinking about simply return and do not execute any folding on the editor but it will create another inconsistency due to CodeMirror attaching an eventListener on an invalid point. So maybe throwing an error could be the best option.
At the least CodeMirror won't make the app crash when it's not able to retrieve from which line the folding happens and won't attach eventListener on invalid point.

This my proposal for a fix, it closes #2805

Any feedback?

2020-11-16 22:52 UTC, develohpanda requested changes
Thanks for investigating a submitting a PR! 🎉 

I think that instead of throwing an error, we simply return `'\u2194'` (the current fallback, see line 330) if either `from` or `to` are falsey, and allow CodeMirror to handle it internally. The event listener would likely be created regardless, because this code doesn't actually do any folding, it only provides the text content. There will be an arrow in the gutter (see below) to fold/unfold regardless.

![image](https://user-images.githubusercontent.com/4312346/99318184-17a41200-28cc-11eb-8600-6ea0ceaab0e3.png)

2020-11-16 23:55 UTC, develohpanda requested changes
Nice 😄 a few more changes please!

2020-11-16 23:55 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/codemirror/code-editor.js
> +        if (!from.line || !to.line) return '\u2194';
Unfortunately, if `from` or `to` are undefined, this will throw an error. This will need to be changed to:

```suggestion
        // Prevent retrieving an invalid content if undefined
        if (!from?.line || !to?.line) return '\u2194';
```

2020-11-16 23:55 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/codemirror/code-editor.js
>          if (prevLine.lastIndexOf('[') > prevLine.lastIndexOf('{')) {
The initial reported error was that `lastIndexOf` could not be found on `prevLine`, so there needs to be another check here to make sure to exit if `prevLine` is undefined.

2020-11-17 02:08 UTC, develohpanda approved these changes
🎉 LGTM, thanks for the PR

2020-11-20 17:11 UTC, DMarby approved these changes
Looks good, thanks for investigating and fixing this!

2020-11-24 04:40 UTC, merged