Hide the active workspace when moving a folder (#2849)
getinsomnia/insomnia pull request #2853
Opened 2020-11-20 06:25 UTC by gravyboat

Closes #2849

Before:
![before](https://user-images.githubusercontent.com/1396878/99766472-0880b800-2ab6-11eb-9f4a-932452e3bf64.PNG)

After:
![after](https://user-images.githubusercontent.com/1396878/99766487-0d456c00-2ab6-11eb-8f30-68ad494c1e8d.PNG)

This uses a `flatMap` which should have minimal impact on performance. I didn't see any tests for this specific component. If I missed them let me know and I can add some.

2020-11-24 05:09 UTC, develohpanda requested changes
Thanks for the PR! A couple of comments. 🎉

2020-11-24 05:09 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/move-request-group-modal.js
> +                  )}
I'm guessing you didn't go down the `workspaces.filter(...).map(...)` route to avoid iterating through the array twice: 👏.

Is there a particular reason to use `flatMap` over `map`, though? If you use a `map`, you can simply return `null` in place of an empty array in the conditional.

2020-11-24 05:09 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/move-request-group-modal.js
> +  workspace: Workspace,
Please change this prop to be `activeWorkspace` to be clearer about what it represents. 🙂

2020-11-24 07:40 UTC, gravyboat commented on packages/insomnia-app/app/ui/components/modals/move-request-group-modal.js
> +  workspace: Workspace,
I considered this when making the PR but wasn't sure since it was labeled `workspace` in other instances, thanks for the clarification.

2020-11-24 08:05 UTC, gravyboat commented on packages/insomnia-app/app/ui/components/modals/move-request-group-modal.js
> +                  )}
> Is there a particular reason to use `flatMap` over `map`, though?

Not really other than personal preference. I don't like using null when I can avoid it and since it's already an array of workspaces here it seems more clear to provide an array. Performance wise it's nearly identical:
![flatmap_v_map](https://user-images.githubusercontent.com/1396878/100065476-ad6a0080-2de8-11eb-8675-324a25515ede.PNG)

2020-11-24 10:34 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/move-request-group-modal.js
> +  workspace: Workspace,
Oh, you're right, it is labeled simply `workspace` in other places. I don't know why... since it loses context. I'm not too concerned, but I think keeping context about what the workspace represents is useful for this particular case! 👍

2020-11-24 10:43 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/move-request-group-modal.js
> +                  )}
That's good to know! I don't really have a preference, I'm on board with avoiding null where possible, and I can see cases where `flatMap` will certainly be safer.

I feel that for the sake of consistency in this code-base (only one instance of `flatMap`), and the fact that React knows exactly what to do with a `null`, it might be better to stick with `map`. 🙂 

Btw, what did you use to get that performance snapshot? Looks useful!

2020-11-24 18:54 UTC, gravyboat commented on packages/insomnia-app/app/ui/components/modals/move-request-group-modal.js
> +  workspace: Workspace,
Agreed!

2020-11-24 19:08 UTC, gravyboat commented on packages/insomnia-app/app/ui/components/modals/move-request-group-modal.js
> +                  )}
Good point about React knowing what to do with `null` for the conditional rendering. I didn't check to see if `flatMap` had been used elsewhere in the project and this being the only instance would be annoying for maintenance. I've updated the PR with this change. If things look good after that I'll squash the 3 commits in to one.

> Btw, what did you use to get that performance snapshot? Looks useful!

It's https://jsbench.me, I wouldn't use it for anything large, but it's great for testing in these sorts of scenarios.

2020-11-24 19:45 UTC, develohpanda approved these changes
Nicely done! 💯

2020-11-24 19:46 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/move-request-group-modal.js
> +                  )}
We squash and merge PRs through GH, so no need to squash into a single commit 😊

2020-11-25 14:46 UTC, DMarby approved these changes

2020-11-25 19:00 UTC, gravyboat commented
Did a quick merge in of the develop branch to get back up to date since I wasn't sure if you prefer that or a rebase since it will be squashed any way.

2020-11-25 19:17 UTC, merged