Yarn warnings wrongly treated as errors
getinsomnia/insomnia pull request #2861
Opened 2020-11-23 22:31 UTC by MrSnix

Changes:

0. Modified if condition from `if (stderr)` to `if (stderr && !isFalsePositive(stderr))`
1. Added function `isFalsePositive(std_err)` which takes std as input, split it using `\r?\n` and run `isDeprecatedDependencies(str)` on each line.
2. Added function `isDeprecatedDependencies(str)` which checks if a given message is a plain warning, 
it's commented to better explains what it does.

Feedbacks ?

It resolves #2836

2020-11-24 05:45 UTC, develohpanda requested changes
Nice update from the previous PR, and useful comments 🙂 

I've outlined a bunch of questions/comments below, let me know how you get on or if you have any questions!

2020-11-24 05:45 UTC, develohpanda commented on packages/insomnia-app/app/plugins/install.js
> +  // Split into array and remove falsy values (null, undefined, 0, -0, NaN, "", false)
```suggestion
  // Split on line breaks and remove falsy values (null, undefined, 0, -0, NaN, "", false)
```

2020-11-24 05:45 UTC, develohpanda commented on packages/insomnia-app/app/plugins/install.js
> +  // arr.find() stops and return the first match which is not a deprecated dependency warning
```suggestion
  // arr.find() stops and return the first match which is not a deprecated dependency warning. If there are any other warnings/errors, we should exit as normal.
```

2020-11-24 05:45 UTC, develohpanda commented on packages/insomnia-app/app/plugins/install.js
> +  const regex = /(?<keyword>warning)(?<dependencies>[^>:].+[>:])(?<issue>.+)/gm;
1. Because `isDeprecatedDependencies` can be called multiple times as part of `arr.find()`, we shouldn't re-create this regex every time. _I think_, if you declare it outside the function and remove the `global, g` flag from the end of it, you should have the same result.

2. Given you're using the `multi-line, m` flag, do you need to split `stderr` on new lines as well? And conversely, if you are splitting on new lines, the regex doesn't need the multi-line flag?

I _think_ there's some scope for improvement here with splitting into individual lines, and the flags used on the regex.

2020-11-24 05:45 UTC, develohpanda commented on packages/insomnia-app/app/plugins/install.js
> +function isFalsePositive(stderr) {
Could you please export this function and add some unit tests for it? Place the tests in `packages/insomnia-app/app/plugins/__tests__/install.test.js`.

2020-11-24 05:45 UTC, develohpanda commented on packages/insomnia-app/app/plugins/install.js
> +  let result = false;
I suggest avoiding `let` where possible.

In this case, you can just `return true` or `return false` where needed, instead of setting this variable.

2020-11-24 05:45 UTC, develohpanda commented on packages/insomnia-app/app/plugins/install.js
> +  if (arr.find(e => !isDeprecatedDependencies(e))) isFalsePositive = false;
I think it might be useful to atleast print _all_ deprecation warnings to the console, so we don't swallow them altogether.

2020-11-24 05:45 UTC, develohpanda commented on packages/insomnia-app/app/plugins/install.js
> +    message.includes('upgrade your dependencies')
Could this be included as part of the regex?

2020-11-24 05:45 UTC, develohpanda commented on packages/insomnia-app/app/plugins/install.js
> +  const message = regex.exec(str)[3];
Since you're using named capture groups (very nice, they make the regex somewhat understandable), you can access the result using names as well.

![image](https://user-images.githubusercontent.com/4312346/100053106-371adc00-2e84-11eb-81d7-2d24781ef0d1.png)

2020-11-24 11:04 UTC, MrSnix commented on packages/insomnia-app/app/plugins/install.js
> +    message.includes('upgrade your dependencies')
I keep suggesting to leave this out from the regex.
I think regex should be used to match only the general layout of the message rather than the content.
I feel like it could be messy, but i leave the choice to you. Let me know.

2020-11-24 13:34 UTC, MrSnix commented
**Changes**:

0. The regex now is compiled outside the function as global variable
1. I removed the flags `/gm` from regex
2. Modified comments as requested
3. Warning are now displayed with console.log() (we won't hide them)
4. Using the dot notation to refers to regex groups
5. Created `install.test.js` with some tests which validate the exported `isDeprecatedDependencies(str)`

Feedbacks ?

2020-11-26 23:48 UTC, develohpanda requested changes
Nice tests; just need to think about naming tests the same way one would think about function names. 🙂

2020-11-26 23:48 UTC, develohpanda commented on packages/insomnia-app/app/plugins/install.js
> +function isFalsePositive(stderr) {
Instead of naming this function `isFalsePositive` I suggest `containsOnlyDeprecationWarnings` for clarity.

This also needs some tests:
1. `should return true when all lines in stderr are deprecation warnings`
2. `should return false when stderr contains a deprecation warning and an error`

2020-11-26 23:48 UTC, develohpanda commented on packages/insomnia-app/app/__tests__/install.test.js
> +    });
These can be combined into one test named `should not match when the message is falsey`

2020-11-26 23:48 UTC, develohpanda commented on packages/insomnia-app/app/__tests__/install.test.js
> +    it('valid-warning-0', () => {
```suggestion
    it('should match with multiple nested dependencies', () => {
```

2020-11-26 23:48 UTC, develohpanda commented on packages/insomnia-app/app/__tests__/install.test.js
> +    it('valid-warning-1', () => {
```suggestion
    it('should match with one nested dependency', () => {
```

2020-11-26 23:48 UTC, develohpanda commented on packages/insomnia-app/app/__tests__/install.test.js
> +    it('invalid-warning', () => {
```suggestion
    it('should not match with an unrelated warning', () => {
```

2020-11-26 23:48 UTC, develohpanda commented on packages/insomnia-app/app/__tests__/install.test.js
> +    it('invalid-error', () => {
```suggestion
    it('should not match with an unrelated error', () => {
```

2020-11-26 23:48 UTC, develohpanda commented on packages/insomnia-app/app/plugins/install.js
> +  warnings.forEach(e => console.log(e));
We tend to scope console messages, so I propose the following change. Could you please add a screenshot for messages in the console after you try to install your plugin?

```suggestion
  warnings.forEach(e => console.log('[plugins] deprecation warning during installation: ', e));
```

2020-11-26 23:48 UTC, develohpanda commented on packages/insomnia-app/app/plugins/install.js
> +  const warnings = arr.filter(e => isDeprecatedDependencies(e));
These filters can be combined to reduce the number of times we iterate through the array

```suggestion
  const arr = stderr.split(/\r?\n/);
  // Retrieve all matching deprecated dependency warning
  const warnings = arr.filter(e => e && isDeprecatedDependencies(e));
```

2020-11-27 00:49 UTC, MrSnix commented
**Changes**:

0. `isFalsePositive` has been renamed to `containsOnlyDeprecationWarnings`
1. As requested tests have been provided for `containsOnlyDeprecationWarnings`
2. As requested some tests have been unified
3. Tests now have meaningful names
4. As requested output on console has been modified
5. Array iteration has been reduced
6. There is no sixth item in this list

Feedbacks ?

2020-11-27 01:04 UTC, MrSnix commented on packages/insomnia-app/app/plugins/install.js
> +  const warnings = arr.filter(e => isDeprecatedDependencies(e));
I cannot do that otherwise the algorithm mismatch the array length and the function returns `false` when it shouldn't.
- **If i do not apply** the last filter, `arr` will contain [msg, null] and `warnings` [msg] and it's mismatched.
- **If i do apply** the last filter, arr will contain [msg] and warnings [msg] and it's a match.

2020-11-27 01:09 UTC, MrSnix commented on packages/insomnia-app/app/plugins/install.js
> +  warnings.forEach(e => console.log(e));
![image](https://user-images.githubusercontent.com/20780192/100400092-88c69080-3055-11eb-9d99-711d8714dfc5.png)
**Here is it**

2020-11-27 01:13 UTC, develohpanda commented on packages/insomnia-app/app/plugins/install.js
> +  const warnings = arr.filter(e => isDeprecatedDependencies(e));
Ah, that makes sense! 👍

2020-11-27 01:16 UTC, develohpanda commented on packages/insomnia-app/app/plugins/install.js
> +  warnings.forEach(e => console.log(e));
Thanks! We should probably change that to `console.warn` instead of `console.log` so it applies colors accordingly. But looks good!

2020-11-27 01:20 UTC, develohpanda approved these changes
LGTM 🎉 tested locally with `insomnia-plugin-pdf-report` (has a warning) and `insomnia-plugin-faker` (has no warning).

One note about changing `console.log` to `console.warn` but rest is good!

2020-11-30 16:10 UTC, DMarby approved these changes

2020-11-30 23:38 UTC, merged

2020-12-15 08:12 UTC, ThomasP1988 commented
Hi everyone, I'm using Insomnia v2020.5.2 and i still have this issue:

Error: Yarn error warning insomnia-plugin-aws-cognito-iam > @aws-amplify/auth > amazon-cognito-identity-js > buffer@4.9.1: This version of 'buffer' is out-of-date. You must update to v4.9.2 or newer
warning "insomnia-plugin-aws-cognito-iam > @aws-amplify/auth > @aws-amplify/core > @aws-sdk/client-cognito-identity > @aws-sdk/middleware-retry > react-native-get-random-values@1.5.0" has unmet peer dependency "react-native@>=0.56".

    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:103518:16
    at ChildProcess.exithandler (child_process.js:295:7)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:223:5)
    at Pipe.<anonymous> (net.js:664:12)

Wasn't it suppose to be fix in the last release?

2020-12-15 08:16 UTC, develohpanda commented
Hi @ThomasP1988, this was merged but not released with 2020.5.2. It will be included with the next release, likely early 2021.

2020-12-15 08:31 UTC, ThomasP1988 commented
Ok thank you, I will wait until there then

2021-03-15 21:00 UTC, nickroberts commented
Still having an issue with this. I'm on the latest, 2021.1.1.

2021-03-15 21:15 UTC, MrSnix commented
This happens because **the check was made really strict on purpose**.

It passes only if the message is shaped as follows: 

[Message format]
_Yarn warnings [dependencies-list]: 
"The following x is **no longer maintained** and **not recommended for usage**, 
please **upgrade your dependencies**."_

From the fix:
```js
    message.includes('no longer maintained') &&
    message.includes('not recommended for usage') &&
    message.includes('upgrade your dependencies')
```

**I could make it less strict** but there were some concerns that could lead to false positives.

2021-03-28 23:48 UTC, develohpanda commented
@nickroberts looking closer at the error you've got, this is actually an issue with a package Insomnia maintains being consumed by an external plugin. This should be addressed by an open dependabot ticket and I'll look to get that through soon, you can track it in #3245.

A longer term solution for handling yarn responses is still useful, but the plugin installation can be resolved faster with the dependabot PR for now.