Add OS dark mode support
getinsomnia/insomnia pull request #2868
Opened 2020-11-24 22:22 UTC by flostellbrink

Just discovered insomnia and I love it, especially the themes and plugins!

One thing I missed was the theme updating when I switch my OS to dark mode.
So I went ahead and added that. Maybe you'll find it useful too.

Not sure how well this works outside of Windows 10, but I am guessing electron should make it work.

![image](https://user-images.githubusercontent.com/2600682/100157586-10bc6700-2eab-11eb-8921-29e40c8803a0.png)

Figuring out what is a light and what is a dark theme is just based on the background color.
I know that's not ideal, but it seems to work pretty well.
I think there should be some way for themes to override that if they want.

Please feel free to change the default themes, I just picked them arbitrarily.

2020-12-05 18:52 UTC, flostellbrink commented
Hey @develohpanda, did you get a chance to look at this already?

2020-12-05 21:31 UTC, develohpanda commented
> Hey @develohpanda, did you get a chance to look at this already?

Hi @flostellbrink! Unfortunately not yet 😞 I've been a little pressed for time given the number of (awesome) PRs and pushing for a big release last week. I'll be sure to run through it in the coming or the following week! 🤗

2020-12-06 18:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/insomnia?pullRequest=2868) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/insomnia?pullRequest=2868) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/insomnia?pullRequest=2868) it.</sub>

2020-12-16 04:58 UTC, develohpanda reviewed
This is an awesome PR and I'm pretty excited to get it in! 🎉

Generally it looks good to me. I'd like to propose a few small changes to the Themes tab interface, in order to allow a user to use any theme for any color scheme, instead of us separating light and dark themes.

I'll get some feedback from our designer @erickrico around a nicer interface in the Themes tab, for selecting the light/dark theme when auto-detection is enabled. That will require some refactoring so I haven't reviewed the files I anticipate to change.

2020-12-16 04:58 UTC, develohpanda commented on packages/insomnia-app/app/plugins/misc.js
> +}
I think we can avoid this heuristic entirely and allow _any_ theme to be the default for light or dark schemes.

For example, in VS Code, when specifying the preferred light theme, the user can still choose a dark theme.

![image](https://user-images.githubusercontent.com/4312346/102303695-a33eba80-3fc0-11eb-8401-14480c6235a7.png)

2020-12-16 04:58 UTC, develohpanda commented on packages/insomnia-app/app/plugins/misc.js
> +export async function applyColorScheme(settings: Settings): Promise<IColorTheme | null> {
Looks like this function doesn't return anything

```suggestion
export async function applyColorScheme(settings: Settings): Promise<void> {
```

2020-12-16 04:58 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/theme.js
>            value={theme.theme.name}
The `value` prop is usually send to the `onClick` handler, but since the handler parameter is no longer used the `value` prop itself can be removed.

2020-12-17 00:44 UTC, develohpanda commented
Hi @flostellbrink! Firstly, I've just tested this on macOS and it seems to detect the color scheme as expected 👏🏽 

I had a chat with our PM and designer, and we think it might be good to follow the VS Code approach for now. This would involve not splitting the theme listing into light and dark, but instead allowing for light/dark selection through two drop-downs, which show all themes and default to those in app config.

Most of the work you have done is still applicable, there will just be a few changes in the themes tab itself.

Here's a quick mock-up just with the HTML, pulling elements from the General settings tab.

![image](https://user-images.githubusercontent.com/4312346/102423464-f28ef480-406d-11eb-9985-26487071cf2f.png)

2020-12-17 08:18 UTC, flostellbrink commented
@develohpanda Thanks for the feedback and for finding a nice UI solution!

Gonna get back to you on the weekend :)

2020-12-24 16:24 UTC, flostellbrink commented
Heey, sorry for the delay.
Hope these changes address the issues you brought up.

Also got the new look in:
![image](https://user-images.githubusercontent.com/2600682/103098841-8b90b300-460c-11eb-88c6-a4fc54208ac5.png)

Hope this does the trick. Happy Holidays!

2021-01-11 00:35 UTC, develohpanda requested changes
Awesome! I've just got some minor comments, namely to convert the object maps to switch/if-else statements.

I was doing some testing locally and noticed that when the "use OS color scheme" box is checked, clicking on the themes above doesn't do anything but still changes the selection. We could disable the click handler entirely, and not show the selected 'default' theme, essentially making it read-only. What would you expect to happen, or do you have any other ideas for that case?

![2021-01-11 13 32 30](https://user-images.githubusercontent.com/4312346/104139633-cd459a00-5411-11eb-85f8-668480883642.gif)


Happy belated holidays to you too! Sorry for the delay, I was on vacation. 😄

2021-01-11 00:35 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/theme.js
> +    }[scheme];
Interesting approach! I suggest using `if...else` or a `switch` statement instead of a map, especially considering this code could run frequently and object maps have memory implications and a map doesn't seem necessary here. Is there a particular reason you chose to use a map?

2021-01-11 00:35 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/theme.js
> +        {row.map(theme => this.renderTheme(theme))}
Can be simplified to the previous implementation 🙂 

```suggestion
        {row.map(this.renderTheme)}
```

2021-01-11 00:35 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/theme.js
> +          {this.renderThemeSelect('dark')}
Nice reuse 💯

2021-01-11 00:35 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/settings-modal.js
> +    }[colorScheme];
Same as a previous comment, using a `switch` should be a little more efficient and easier to skim read. 😄

2021-01-11 00:35 UTC, develohpanda commented on packages/insomnia-app/app/ui/containers/app.js
> +      .addListener(async () => themes.applyColorScheme(this.props.settings));
I'm unfamiliar here, do you need to add a listener for `prefers-color-scheme: light` as well?

2021-01-11 00:35 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/theme.js
> +        <div className="themes">{this.renderThemeRows('default')}</div>
```suggestion
        <div className="themes">{this.renderThemeRows()}</div>
```

Argument is now redundant 😄

2021-02-13 21:01 UTC, flostellbrink commented on packages/insomnia-app/app/ui/containers/app.js
> +      .addListener(async () => themes.applyColorScheme(this.props.settings));
Listening to just one of them seems to do the trick and is what other people have been doing too, I think^^

2021-02-13 21:08 UTC, flostellbrink commented on packages/insomnia-app/app/ui/components/settings/theme.js
> +    }[scheme];
Well I personally like things to be const whenever possible.
The switch alternative to that is to put it into a function that can return a value.
But I am happy to make that mutable and assign it in a switch if you think that makes it more readable.

I am not gonna benchmark this, but I think that it really doesn't make much of a performance difference at all.

2021-02-13 21:08 UTC, flostellbrink commented on packages/insomnia-app/app/ui/components/modals/settings-modal.js
> +    }[colorScheme];
Sure

2021-02-13 21:34 UTC, flostellbrink commented
Heey @develohpanda! Sorry for the delay.
I went ahead and implemented the suggested changes.

You're right, its confusing to change the default theme when it is not enabled.
Disabling those buttons seems like a good enough solution 👍 

Gonan fix those conflicts real quick.

2021-02-13 22:20 UTC, flostellbrink commented
Okay, had to rebase, it was getting a bit messy. Quite a lot has happened since last time.

2021-02-15 23:43 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/theme.js
> +    }[scheme];
> The switch alternative to that is to put it into a function that can return a value.

I think this is a suitable alternative! It is a bit more readable than the map, for this use case 🤗

2021-02-15 23:50 UTC, flostellbrink commented on packages/insomnia-app/app/ui/components/settings/theme.js
> +    }[scheme];
Oh yeah you're right.
I was thinking about the self invoke lambda style.
But it would have been perfectly reasonable to just have this as a normal named function.

Worked around it with a ternary, hope that's okay too.

2021-02-15 23:52 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/theme.js
> +    }[scheme];
A hundred ways to solve the same problem 😂 ternary is fine too, there will only ever be light-dark mode lol

2021-02-16 02:13 UTC, develohpanda reviewed
No worries about the delay, thanks for making those updates! It's looking great, almost there 💯

2021-02-16 02:13 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/settings-modal.js
> +        patch = { theme: themeName };
I think this should be setting `lightTheme`?

```suggestion
        patch = { lightTheme: themeName };
```

2021-02-16 02:13 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/settings-modal.js
> +        break;
It might be good to add the case for `'default'` as well, because `ColorScheme` is typed as `'default' | 'light' | 'dark'`

```suggestion
      case 'default':
      default:
        patch = { theme: themeName };
        break;
```

2021-02-16 02:13 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/theme.js
> +        <h2>Theme</h2>
I think we can get away with not having this header because it is on the tab itself 😄 Let's visually keep this part how it was previously

2021-02-16 02:13 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/theme.js
> +          disabled={disabled}
I'm not sure how I feel about the (default) opacity change when the button become disabled. Since the context of these custom buttons is to do with theming, it feels strange to show a skewed color scheme.

![2021-02-16 15 07 12](https://user-images.githubusercontent.com/4312346/108010281-5da67880-7069-11eb-812b-378c329c01ad.gif)


Functionally the disabling is good but perhaps we need to indicate "disabled" by:
- removing the opacity change
- disabling the hover animation
- not showing a border around the selected theme (when OS color scheme is enabled)


You'll just need to write a custom CSS class `themes__theme-disabled`.

@erickrico thoughts on the above, specifically for this use case?

2021-02-16 16:53 UTC, erickrico commented on packages/insomnia-app/app/ui/components/settings/theme.js
> +          disabled={disabled}
yea i agree, i think we should remove the selected border, but i think we should keep the opacity change, and do remove the hover animation

2021-02-27 16:47 UTC, flostellbrink commented on packages/insomnia-app/app/ui/components/settings/theme.js
> +          disabled={disabled}
Done and done

2021-02-28 22:40 UTC, develohpanda approved these changes
Awesome!! Very excited for this 🎉

2021-03-01 17:33 UTC, dimitropoulos requested changes
![Screenshot_20210301_122735](https://user-images.githubusercontent.com/15232461/109534638-8d9e4480-7a89-11eb-8277-a7eaf8f06242.png)

Can confirm this worked on Linux (Kubuntu).

My only qualm is that the UI isn't crystal clear to me at first as to what it's selecting (and also what is currently selected).  For example, it'd be nice if we could get a preview next to each of these (like exists above) for each dropdown.  Then, that would give the user some indication of what theme is currently active (which we have above), e.g.

![Screenshot_20210301_123213](https://user-images.githubusercontent.com/15232461/109535271-59775380-7a8a-11eb-8978-daabe75523ba.png)

2021-03-01 17:35 UTC, dimitropoulos reviewed
also, is it an option to instead use https://www.electronjs.org/docs/api/native-theme.  It seems better to rely on an electron javascript API than a css media query.  At least with the javascript API we can be notified by the type system if anything ever changes - while with CSS we just have to hope it never breaks.

2021-03-01 20:29 UTC, dimitropoulos approved these changes
On second thought, I see that a lot was done in this PR and what was implemented does work quite well from my testing.  Although my suggestion about the preview would be nice we can always iterate - I don't want to hold this up at this juncture.  I came and just immediately looked at the code and the code alone without looking at any of the discussion, my b. haha

2021-03-05 20:09 UTC, develohpanda commented
I think it might be worth investigating use of the Electron API mentioned above - if not trivial, we can stick with the CSS query for now.

2021-03-13 00:35 UTC, flostellbrink commented
Thanks for bringing up the API option @dimitropoulos!

I just read the [electron guide on dark mode](https://www.electronjs.org/docs/tutorial/dark-mode). That makes it sound like the nativeTheme API is more useful for other use cases like syncing an applications dark mode preferences back into the OS components.

For just updating our theme they recommend this:
> If your app has its own dark mode, you should toggle it on and off in sync with the system's dark mode setting. You can do this by using the prefer-color-scheme CSS media query.

And while I absolutely agree that having a strongly typed API for this would be nice, I think there is also something to be said for just using standard web apis when possible.

Either way, I don't think I can justify spending time on implementing that change at the moment.
Hope you understand.

2021-03-13 00:49 UTC, dimitropoulos commented
I most definitely understand.  Thanks for looking into it!!

2021-03-13 03:38 UTC, merged

2021-03-13 15:52 UTC, khyveasna11111908 commented
JJ

khyveasna

On Sat, 13 Mar 2021, 10:39 Opender Singh, ***@***.***> wrote:

> Merged #2868 <https://github.com/Kong/insomnia/pull/2868> into develop.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kong/insomnia/pull/2868#event-4453403453>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AODFS227NG5O6635OELRZCDTDLM6HANCNFSM4UBPL3GQ>
> .
>