add path parameters
getinsomnia/insomnia pull request #2936
Opened 2020-12-13 08:48 UTC by Vap0r1ze

I'm coming from issue #203 and wanted to open a PR to discuss my changes. Currently, how I have it working is you add entries to a table in a new "Params" tab, and it replaces the instances of `:${paramName}` (colon preceding parameter name), with the value of said param. I think I should add a visual indicator in the RequestUrlBar for params, similar to how environment variables appear. This is very WIP, so please let me know what must be changed or what is a bad idea. Thanks for being part of this wonderful app!

Image of Functionality:

![image](https://user-images.githubusercontent.com/20448879/93026051-16572000-f5d1-11ea-9b3e-a6a2bb60348c.png)

2020-12-28 08:33 UTC, Nisgrak commented
This should be a priorized feature.

2020-12-29 22:00 UTC, eltonsandre commented
feature that will help a lot, I look forward to this version.

2021-01-08 06:30 UTC, apisaint commented
Reading through the code, looks nice so far - great work, haven't determined whether it's backwards compatible yet.

> I think I should add a visual indicator in the RequestUrlBar for params, similar to how environment variables appear.

💯% It would be great if the indicator was similar to the env variables, and when you click on it, it focuses the parameter in the params table.

2021-01-08 06:33 UTC, apisaint commented on plugins/insomnia-plugin-request/index.js
> +  const templateUrl = insertPathParameters(url, pathParameters);
Nitpick, `templateUrl` makes me think of a regular expression or a template, rather than a parsed output.

2021-01-08 06:39 UTC, apisaint commented on packages/insomnia-url/src/path-parameters.js
> +    url = url.replace(`:${pathParam.name}`, pathParam.value);
Future enhancement could be to add a checkbox for regex replacement support (aka global). That way you can set one parameter for `:user` and it would replace all instances vs the current implementation you'd have to define a `:user` parameter for each usage.

2021-01-26 13:21 UTC, edbrannin commented
Maybe I should be suggesting this in the parent issue, and I'm not a maintainer, but:

Would Placeholders be able to supplement Environment variables and use the same syntax?

That way I could, for example, have a request like `{{ my_service.url }}/api/v1/user/{{ userId }}/attributes` with `my_service: { url: "..." }` in the environment and `userId` in the parameters tab.

I thought for a minute that would preclude @apisaint's [suggestion]:(https://github.com/Kong/insomnia/pull/2936#issuecomment-756576846):
> It would be great if the indicator was similar to the env variables, and when you click on it, it focuses the parameter in the params table
...but maybe in this case it would focus on the params table if it's defined there, and open the Environment Variable prompt if it's not?

2021-03-30 06:59 UTC, scollovati commented
+1 on this feature, since it tries to incorporate by default the `Path Variables` as in Postman.
There is this plugin as a temporary workaround https://github.com/gschier/insomnia-plugin-path-parameters, but the url preview does not work.

2021-06-18 22:20 UTC, danshapir commented
Any updates?

2021-07-06 19:44 UTC, eltonsandre commented
any update on this? Is work still ongoing?

2021-07-07 00:57 UTC, develohpanda commented
The parent issue was converted to a discussion and has a response on it, @danshapir and @eltonsandre to address this [#3551 (comment)](https://github.com/Kong/insomnia/discussions/3551?sort=new#discussioncomment-952413)

2021-11-24 10:59 UTC, ppsirius commented
@apisaint what's going on with this pull?
It's a crucial feature why you don't merge it?

2021-12-05 19:37 UTC, ts14ic commented on packages/insomnia-url/src/path-parameters.js
> +  for (const pathParam of pathParameters) {
I'd like to note, that given a URL like `https://example.com/:foo/:fooBar`, a replacement with `{foo: 10, fooBar: 20}` will result in `https://example.com/10/10Bar`. 
To fix this, pathParameters must be sorted by length in descending order.
This way, `:fooBar` gets replaced with 20 first, and only after that `:foo` gets replaced with 10, without breaking `:fooBar`

2021-12-05 19:52 UTC, ts14ic requested changes
Found Insomnia some days ago. Blown away by how flexible and cool it is. 

Given `insertPathParameters` is fixed, and all else (code generation?, generation from swagger/open api?) works OK, can't wait for this to become part of main branch :). 
I don't see any substantial difference between query and path params, so don't understand why so much discussion was needed about this feature.

2022-01-16 15:05 UTC, mugi-luffy commented
shouldn't the path parameters be like {paramName} instead of :paramName ?
This will conform with open api 3.0 [https://swagger.io/docs/specification/describing-parameters/](https://swagger.io/docs/specification/describing-parameters/)
The request generation in insomnia should also be fixed, because now {paramName} in design gets converted to {{paramName}} in debug 
![image](https://user-images.githubusercontent.com/23312130/149665601-262dce88-1be7-47fd-adbd-27577bddf9e3.png)
![image](https://user-images.githubusercontent.com/23312130/149665620-16e10e78-bb5d-4932-8666-e81fd98e5c8d.png)

2022-01-16 22:50 UTC, eltonsandre approved these changes

2022-01-18 16:01 UTC, edbrannin commented
> shouldn't the path parameters be like `{paramName}` instead of `:paramName`?

I've seen both in use, so it may be useful to support both somehow (with or without individual toggles)

2022-10-11 10:22 UTC, jackkav commented
Closed as stale.

2022-10-11 10:22 UTC, closed without merging

2022-10-11 10:24 UTC, Nisgrak commented
This won't be merged? What a foot shot....

2025-02-05 15:13 UTC, robross0606 commented
What is the deal here?  This was closed without merge.  Meanwhile, feature requests pointing to this MR are closed as "Completed".