autobind removal and react-hot-reload fix
getinsomnia/insomnia pull request #2963
Opened 2020-12-19 16:20 UTC by MrSnix

As requested by @develohpanda, I'm opening this PR as a proposal about issue #2468.

No precise specifications had been given on how to perform the removal of `@autobind` so with a bit of research I found out we may use the `@babel/plugin-proposal-class-properties` which **is currently declared by Insomnia** and transform all the functions to arrow functions (so `this` is lexically bound and we do not need to use `.bind(this)` anymore) and drop the decorator usage. Why do we need to define arrow functions as class properties? So React.js won't recreate them each time as an inline-arrow function.

Source: [StackOverflow](https://stackoverflow.com/questions/36677733/why-shouldnt-jsx-props-use-arrow-functions-or-bind)
Please **check the best** answer (more **specifically** `Binding methods to this without inlining arrow functions` on point 2.)

**Changes**:
The first commit on this PR :
- Removed the `@autobind` declaration mainly on insomnia-app and insomnia-components.
- Changed all functions to arrow functions.

The second commit on this PR:
- Updated the react-hot-reloading configuration in order to work again and it's dependencies.

Here is a gif that shows react-hot-reloading working again
 
![Fix](https://user-images.githubusercontent.com/20780192/102693912-23ae2700-421e-11eb-95df-5769d618c368.gif)

I'd be glad to hear feedback.
Thanks

2021-01-07 08:29 UTC, apisaint commented
Wow, this is a *massive* change. *sweating intensifies*

2021-01-07 08:30 UTC, apisaint commented on packages/insomnia-app/app/ui/components/base/button.js
> +  _handleClick = e => {
I would suggest to keep parenthesis even when there is a single value.

2021-01-07 22:00 UTC, MrSnix commented on packages/insomnia-app/app/ui/components/base/button.js
> +  _handleClick = e => {
Parenthesis are automatically removed by Prettier on a single argument function.
I need to **update the Prettier configuration** in order to make it work.

Can I do that?

2021-01-07 23:22 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/base/button.js
> +  _handleClick = e => {
I suggest not making this change at this stage/in this PR.

2021-01-08 02:44 UTC, apisaint commented on packages/insomnia-app/app/ui/components/base/button.js
> +  _handleClick = e => {
Ah, makes sense that this is something from the formatter. It's a really bad practice to remove parens around single properties, and makes it way more difficult to read for new developers. Unfortunate. I hope the maintainers really change their stance. Perhaps someone with more software experience on the team can chime in.

2021-01-08 03:02 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/base/button.js
> +  _handleClick = e => {
Hi @apisaint, this topic is wholly unrelated to the contents and purpose of this PR. In order to keep conversation on topic and avoid scope creep on an, as you identified, already large PR, I advise away from altering it in this PR and choose to not engage in further reasoning.

Please raise a separate PR, or an issue with your notes and reasoning, and it can be addressed by somebody. 

> Hope the maintainers really change their stance, and a maintainer with more experience chimes in given the lack of conversation from above. 

I don't have an opinion either way as it is an automated change which has little impact during development, but this is rude and misinformed.

2021-01-08 03:50 UTC, apisaint commented on packages/insomnia-app/app/ui/components/base/button.js
> +  _handleClick = e => {
If you don't have an opinion then I suggest that we make the change. It's directly related to this PR as it introduces thousands of cases. Apologies if you took it personally, but it's from observation and I don't have a way to privately request from those who seem more experienced based on their contributions!

2021-01-08 07:56 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/base/button.js
> +  _handleClick = e => {
The changes introduced in this changeset are not the only arrow functions in the codebase. When the new rule is applied, it will modify more files in addition to those currently changed. 

Adding this linting rule and fixing all instances, in this PR, is scope creep and a significant overhead for reviewing the contents of _this_ PR. I am not opposed to this rule being added, but it must be a separate pull request.

You are more than welcome to tag in a comment and request a review, but the GitHub reviewers panel is not available to contributors.

2021-01-08 07:58 UTC, apisaint commented on packages/insomnia-app/app/ui/components/base/button.js
> +  _handleClick = e => {
Honestly speaking, you are wrong. It makes it more difficult and the functions previously were wrapped. It's directly related. Whether it happens in this PR or another is a side conversation and isn't related to my original statement. I have no disagreement with that.

2021-01-08 08:02 UTC, apisaint commented on packages/insomnia-app/app/ui/components/base/button.js
> +  _handleClick = e => {
For the sake of not pinging Snix and keeping the community sane I will go ahead and hide this - but I personally think that taking everything personally rather than being conducive to Open Source community is a major negative and hope that the organization takes notice as it simply makes me lose faith in the ability of those making this amazing tool.

2021-01-08 08:19 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/base/button.js
> +  _handleClick = e => {
In that case it would be worthwhile to introduce the rule (and fix instances that break) introduced to develop first, in preparation for this PR. This is to ensure the modifications in this PR relate only to the linked issue. 

I respect your review and the changes you have requested, but want to avoid tacking on a large changeset onto an already large PR. 👍

2021-01-08 08:32 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/base/button.js
> +  _handleClick = e => {
Lastly, I will say that the configuration of this repository is ever changing, and the documentation or rules are complete, to our best efforts.

My suggestion to tag whomever you feel appropriate is used throughout this codebase albeit not formally documented. This approach, and which PR panels are editable by contributors is _not_ my personal opinion. If it is something you would like to see changed, we absolutely are open to explore those changes. 🙂

2021-01-09 07:19 UTC, apisaint commented on packages/insomnia-app/app/ui/components/base/button.js
> +  _handleClick = e => {
I waited a bit before responding, I really didn't want to. That message makes me not want to contribute. I'm going to assume you are coming from a good place, but when you use smilies and language in such a way it comes off as very passive aggressive and provoking and doesn't bode well for future interactions. I hope that going forward we can have a better dialog and remain professional.

2021-01-10 07:26 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/base/button.js
> +  _handleClick = e => {
Hi @apisaint! Please know that I do not intend for any comments to be aggressive, provoking or unprofessional at any time. Especially, the brevity of my initial answer was not to ignore or set aside the point that was raised, but perhaps I should have elaborated my reasoning sooner. I apologize for the part I played in our miscommunication and misunderstanding; this is an exception, I'm sure we will have fruitful dialog in future. I respect your feedback here and will take it on board, to the best of my ability.

I'm glad we have an agreement on the resolution (and I see you have already raised a PR - thanks). 😄

Lastly, I've noticed you have been responding to and addressing several PRs and issues, recently. We are a small team split across various aspects of Insomnia as a complete product and I, personally, appreciate the help. 🙏🏽

2021-01-21 00:31 UTC, develohpanda requested changes
First of all, great work! I'm really excited to have this in. I pulled your branch locally and did some QA, and the quality of life improvement from this is huge.

I have a couple of comments, most of them are observations but one or two changes that I think should be removed from this PR and moved to separate PRs.

Also, as a note - the first step was to get `react-hot-reloader` working again. Now we're in position to explore using [React Fast Refresh](https://github.com/facebook/react/issues/16604) (which is expected to replace react-hot-reloader). There exists an [experimental](https://github.com/pmmmwh/react-refresh-webpack-plugin/) plugin for it at the moment so it's not quite ready, but I'm glad we have hot-reloading in the meantime 😎 

I also found another useful post explaining the use of arrow functions using the babel plugin - https://frontarm.com/james-k-nelson/when-to-use-arrow-functions/.

2021-01-21 00:31 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/key-value-editor/row.js
>  };
Nice catch! 👍🏽

2021-01-21 00:31 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/viewers/response-headers-viewer.js
> +};
I don't think this one needs to be updated, but it's ok! 🙂

2021-01-21 00:31 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/viewers/response-viewer.js
> +  shouldComponentUpdate = (nextProps: Props, nextState: State) => {
I don't think it actually matters, but because React's lifecycle functions are never directly used, it might be better to not change these to arrow functions 🤔 thoughts?

2021-01-21 00:31 UTC, develohpanda commented on packages/insomnia-app/app/ui/containers/app.js
> +  };
Strange that this is an `async` function, but contains no `await`. Looks like there _is_ an await where it is used, on line 367, so it's okay.

2021-01-21 00:31 UTC, develohpanda commented on packages/insomnia-app/app/ui/containers/app.js
> +      async onComplete(name) {
In case I'm missing something, was there a particular reason for this change? Preference would be to keep it as before 🙂

2021-01-21 00:31 UTC, develohpanda commented on packages/insomnia-app/app/ui/containers/app.js
> +const mapStateToProps = (state, props) => {
Top level functions don't need to be changed, so I'd favor reverting the changes from here to the end of this file

2021-01-21 00:31 UTC, develohpanda commented on packages/insomnia-app/app/ui/index.js
> +    const TheHottestApp = hot(module)(app);
😆 🔥

2021-01-21 00:31 UTC, develohpanda commented on packages/insomnia-app/package.json
> -    "autobind-decorator": "^2.4.0",
![](https://media1.giphy.com/media/5nsiFjdgylfK3csZ5T/giphy.gif)

2021-01-21 00:31 UTC, develohpanda commented on packages/insomnia-app/webpack/webpack.config.development.babel.js
> -    new webpack.NamedModulesPlugin(),
I'm assuming this change is because the plugins are now deprecated; is it necessary or avoidable for hot-reloading? If avoidable can it please be moved to a separate PR? 🙏🏽

2021-01-21 00:31 UTC, develohpanda commented on packages/insomnia-importers/src/importers/openapi3.js
>  const VARIABLE_SEARCH_VALUE = /{([^}]+)}/g;
Interesting changes in this file; I didn't dig deep but please move to a separate PR with some notes about what has changed.

Again, let me know if I'm missing something, but I don't think the changes in this file are necessary for hot-reloading 😄

2021-01-21 00:31 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/sidebar/sidebar-children.js
> +      const hasActiveChild = children => {
This seems concerning - children is a parameter of this function and also its parent function `_renderChildren`, so there is a disambiguation issue here. I wouldn't make any changes here, but it seems like we should rename this parameter in another PR, or even move `hasActiveChild` out of `_renderChildren`.

2021-01-21 18:47 UTC, MrSnix commented on packages/insomnia-app/app/ui/components/viewers/response-viewer.js
> +  shouldComponentUpdate = (nextProps: Props, nextState: State) => {
I found this [facebook/react - 10810](https://github.com/facebook/react/issues/10810) and seems like you technically can do it, but it is unnecessary and may also hurt performance a little bit. So, would you like to revert this changes?
Let me know about it

2021-01-21 18:48 UTC, MrSnix commented on packages/insomnia-app/app/ui/containers/app.js
> +  };
Nice, so I mark this one as resolved

2021-01-21 18:52 UTC, MrSnix commented on packages/insomnia-app/app/ui/components/viewers/response-headers-viewer.js
> +};
Yes, you are right, it's not necessary because it's not binding anything, anyway while i was doing the conversion to arrow function I switched everything because i thought you would want to keep the same function's declaration/expression syntax for any components. 
I mark this as resolved but if you have something to say, please, let me know.

2021-01-21 18:54 UTC, MrSnix commented on packages/insomnia-app/app/ui/index.js
> +    const TheHottestApp = hot(module)(app);
![image](https://user-images.githubusercontent.com/20780192/105398311-7ebea980-5c22-11eb-8e6c-7eafd72b20e2.png)

2021-01-21 19:01 UTC, MrSnix commented on packages/insomnia-app/package.json
> -    "autobind-decorator": "^2.4.0",
![image](https://user-images.githubusercontent.com/20780192/105399101-761aa300-5c23-11eb-80a8-5669b9f6d2da.png)

2021-01-21 19:11 UTC, MrSnix commented on packages/insomnia-importers/src/importers/openapi3.js
>  const VARIABLE_SEARCH_VALUE = /{([^}]+)}/g;
Yes, it's out of scope from this PR. I apologize.

2021-01-21 19:14 UTC, MrSnix commented on packages/insomnia-app/app/ui/containers/app.js
> +const mapStateToProps = (state, props) => {
As requested, I'm reverting the changes 👍🏻

2021-01-21 19:15 UTC, MrSnix commented on packages/insomnia-app/app/ui/containers/app.js
> +      async onComplete(name) {
I switched everything because i thought you would want to keep the same function's declaration/expression syntax for every components. I revert the change, no prob. :D

2021-01-21 19:20 UTC, MrSnix commented on packages/insomnia-app/app/ui/components/sidebar/sidebar-children.js
> +      const hasActiveChild = children => {
I'm reverting the changes as requested

2021-01-21 22:24 UTC, MrSnix commented on packages/insomnia-app/webpack/webpack.config.development.babel.js
> -    new webpack.NamedModulesPlugin(),
> I'm assuming this change is because the plugins are now deprecated;

That's correct 👍🏻 

>  Is it necessary or avoidable for hot-reloading?

**I think it is avoidable and should works just fine anyway**, meanwhile I was fixing this I made the changes according to the Webpack official documentation. :P

> If avoidable can it please be moved to a separate PR?

Yes, I can move it to a separate PR, I felt like considering this one should "improve", "enhance" the wb configuration related to react-hot-reload it would be just fine for this PR. 😃 

Anyway, i'm reverting this as requested. :octocat:

2021-01-21 23:14 UTC, MrSnix commented on packages/insomnia-app/app/ui/components/viewers/response-viewer.js
> +  shouldComponentUpdate = (nextProps: Props, nextState: State) => {
Seems like you technically can do it, but it is unnecessary and may also hurt performance a little bit. So, would you like to revert all lifecycles functions? Let me know about it.
I want to clarify I switched everything to arrow functions because i thought you would want to keep the same function's declaration/expression syntax for every components.

2021-01-22 01:00 UTC, MrSnix commented on plugins/insomnia-plugin-kong-portal/src/deploy-to-portal.js
> +  async componentDidUpdate() {
This one shouldn't be modified in the first place, it has been reverted as originally it was.

2021-01-22 17:20 UTC, MrSnix commented
**Important**:
This PR was initially a proposal to replace the use of @autobind which prevented react-hot-reload from working properly. Recently, after subsequent investigations, we realized that using public-class-field as an autobind substitute is not efficient enough on a large scale. Therefore, I am closing this PR in favor of a new one that will be opened shortly containing the new proposal.

2021-01-22 17:20 UTC, closed without merging

2021-01-25 00:11 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/viewers/response-viewer.js
> +  shouldComponentUpdate = (nextProps: Props, nextState: State) => {
See https://github.com/Kong/insomnia/pull/2963#issuecomment-765565861

2021-01-25 00:15 UTC, develohpanda commented
Adding to the above comment: investigating the behavior of arrow functions of the lifecycle hooks helped us to realize that the existing `@autobind` class decorator from [`autobind-decorator`](https://www.npmjs.com/package/autobind-decorator) was not discerning between a React component class and a regular class.

React lifecycle methods (which are used by RHL) should not be bound, and the `@autoBindMethodsForReact` decorator from [`class-autobind-decorator`](https://www.npmjs.com/package/class-autobind-decorator) specifically ignores React lifecycle methods.