show inline reveal password option for auth
getinsomnia/insomnia pull request #2974
Opened 2021-01-02 18:56 UTC by tharun208

Added reveal password ( eyeball icon) next to the password field to toggle visibility.

Hide reveal password ( eyeball icon) when a user opts to use `show passwords` from settings.

closes #2929

2021-01-07 08:40 UTC, apisaint commented
This is awesome, what do you think about a single "OneLinePassword" (Input/Show-Hide) component? Seems like it would clean up the state on the parent as well as it's all contained within the component.

2021-01-07 09:09 UTC, tharun208 commented
> This is awesome, what do you think about a single "OneLinePassword" (Input/Show-Hide) component? Seems like it would clean up the state on the parent as well as it's all contained within the component.

@apisaint, Yes we can and but we need the state `showPassword` which is used by `TextInput`. What I thought is to keep the state (map of authType with bool) in the `auth-wrapper.js` and pass it.

2021-01-08 06:03 UTC, apisaint commented
> > This is awesome, what do you think about a single "OneLinePassword" (Input/Show-Hide) component? Seems like it would clean up the state on the parent as well as it's all contained within the component.
> 
> @apisaint, Yes we can and but we need the state `showPassword` which is used by `TextInput`. What I thought is to keep the state (map of authType with bool) in the `auth-wrapper.js` and pass it.

Absolutely, something like this? Note, I changed `showPasswords` to `showAllPasswords` but maybe it should be something like `preferencesShowPasswords` to indicate where it's from...

```js
@autobind
class PasswordInput extends React.PureComponent<Props, State> {
  constructor(props: Props) {
    super(props);
    this.state = {
      showPassword: false,
    };
  }

  _handleShowPassword() {
    this.setState({ showPassword: !this.state.showPassword });
  }

  render() {
    const { showPassword } = this.state;
    const { showAllPasswords, defaultValue, isVariableUncovered, onChange } = this.props;
    const icon = {showPassword ? <i className="fa fa-eye-slash" /> : <i className="fa fa-eye" />}

    return (
      <>
        <OneLineEditor
          type={showAllPasswords ? 'text' : 'password'}
          type={showAllPasswords || showPassword ? 'text' : 'password'}
          id="password"
          onChange={onChange}
          defaultValue={defaultValue}
          isVariableUncovered={isVariableUncovered}
        />
        </div>
        {!showAllPasswords ? (
        <Button
          className="btn btn--super-duper-compact pointer"
          onClick={this._handleShowPassword}
          value={showPassword}>
          {icon}
        </Button>
        ) : (<></>)}
      </>
    );
  }
}
```

2021-01-11 18:53 UTC, tharun208 commented
> > > This is awesome, what do you think about a single "OneLinePassword" (Input/Show-Hide) component? Seems like it would clean up the state on the parent as well as it's all contained within the component.
> > 
> > 
> > @apisaint, Yes we can and but we need the state `showPassword` which is used by `TextInput`. What I thought is to keep the state (map of authType with bool) in the `auth-wrapper.js` and pass it.
> 
> Absolutely, something like this? Note, I changed `showPasswords` to `showAllPasswords` but maybe it should be something like `preferencesShowPasswords` to indicate where it's from...
> 
> ```js
> @autobind
> class PasswordInput extends React.PureComponent<Props, State> {
>   constructor(props: Props) {
>     super(props);
>     this.state = {
>       showPassword: false,
>     };
>   }
> 
>   _handleShowPassword() {
>     this.setState({ showPassword: !this.state.showPassword });
>   }
> 
>   render() {
>     const { showPassword } = this.state;
>     const { showAllPasswords } = this.props;
> 
>     // Duplicate props for the OneLineEditor input, and remove additonal props
>     // This way we can treat the element as a OneLineEditor component
>     const inputProps = {...this.props};
>     delete inputProps.showAllPasswords;
> 
>     const icon = {showPassword ? <i className="fa fa-eye-slash" /> : <i className="fa fa-eye" />}
> 
>     return (
>       <>
>         <OneLineEditor
>           type={showAllPasswords ? 'text' : 'password'}
>           type={showAllPasswords || showPassword ? 'text' : 'password'}
>           id="password"
>           {...inputProps}
>         />
>         </div>
>         {!showAllPasswords ? (
>         <Button
>           className="btn btn--super-duper-compact pointer"
>           onClick={this._handleShowPassword}
>           value={showPassword}>
>           {icon}
>         </Button>
>         ) : (<></>)}
>       </>
>     );
>   }
> }
> ```
> 
> Hopefully the project moves towards leveraging redux for preferences so that way you don't have to pass them to each component.

so, for now can we live this and once support for redux is started, can we do the refractoring changes ?

2021-01-20 04:46 UTC, develohpanda requested changes
Hi @tharun208! Thanks for the PR. This generally looks good, although I agree with the previous review in that we can certainly avoid some of the duplication here but creating a `PasswordEditor` component, which wraps the `OneLineEditor` and the `fa-eye-lash` button.

Additionally, redux _can_ already be used for this purpose. You can connect the `PasswordEditor` component, and write a selector to get the settings, without needing to pass it down through props from `auth-wrapper.js`. Redux is not used extensively within the project, but data from the database does exist within it and can be used in this manner.

```js
// password-editor.js

const PasswordEditor = ({showPasswords, ...props}) = <>...</>;

const mapStateToProps = (state, props) => {
  const settings = selectSettings(state, props); // import from app/ui/redux/selectors.js

  return { showPasswords: settings.showPasswords };
};

export default connect(mapStateToProps)(PasswordEditor);
```

2021-01-20 04:51 UTC, tharun208 commented
> Hi @tharun208! Thanks for the PR. This generally looks good, although I agree with the previous review in that we can certainly avoid some of the duplication here but creating a `PasswordEditor` component, which wraps the `OneLineEditor` and the `fa-eye-lash` button.
> 
> Additionally, redux _can_ already be used for this purpose. You can connect the `PasswordEditor` component, and use an existing selector to get the settings, without needing to pass it down through props from `auth-wrapper.js`. Redux is not used extensively within the project, but data from the database does exist within it and can be used in this manner.
> 
> ```js
> // password-editor.js
> 
> const PasswordEditor = ({showPasswords, ...props}) = <>...</>;
> 
> const mapStateToProps = (state, props) => {
>   const settings = selectSettings(state, props); // import from app/ui/redux/selectors.js
> 
>   return { showPasswords: settings.showPasswords };
> };
> 
> export default connect(mapStateToProps)(PasswordEditor);
> ```

@develohpanda sure will do this 👍🏻

2021-02-01 04:32 UTC, tharun208 commented
@develohpanda, I am done with the changes

2021-02-16 06:03 UTC, develohpanda reviewed
Thanks for the updates and apologies for the delay. Well done for exploring the unit tests 👏🏽 I've just got a couple of observations from the updates.

Additionally, I've noticed there's a UI glitch introduced by these changes to the `OneLineEditor`.

Notice how the text shifts up and down on hovering over the element, however it doesn't happen in the live application right now. Is this something on my computer specifically or are you seeing the same?

![2021-02-16 19 01 46](https://user-images.githubusercontent.com/4312346/108024511-922a2c80-7089-11eb-939e-80902d6d4875.gif)

2021-02-16 06:03 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/__tests__/password-editor.test.js
> +import React from 'react';
Nice work adding UI tests!

Given the relative simplicity of this component I think we can get away with not introducing test ids.

You should be able to get the button with `getByRole('button')`, and the input using `getByDisplayValue(password)`.

2021-02-16 06:03 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/password-editor.js
> +};
`prop-types` is not really used for new components in this project (we'll look to remove it once we move to TS), so could you please translate this into a flow type? Have a look at many of the other methods. Don't worry about the exact types for the callback functions - just set them to be `Function` is they're not easy to find.

While the unit tests for this component all pass, they unfortunately litter the console with warnings due to prop-types. Changing to flow types should eliminate the warnings, and moving to TS will cause these errors at compile time instead of runtime.
![image](https://user-images.githubusercontent.com/4312346/108023718-05cb3a00-7088-11eb-871c-587a959c760f.png)

2021-02-16 06:03 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/password-editor.js
> +  }
Instead of accepting `request` as a prop, I feel that this generic component should accept `password` as a prop, and the `onChange` callback takes the updated password text as a parameter.

The calling component, in this case `BasicAuth` or `DigestAuth`, should contain the actual `_handlePasswordChange` implementation (which ultimately updates the database).

Essentially, I'm suggesting to separate the generic `PasswordEditor` component from the `Request` data model.

2021-02-16 06:54 UTC, tharun208 commented on packages/insomnia-app/app/ui/components/editors/__tests__/password-editor.test.js
> +import React from 'react';
agreed, but in the unit tests, we are verifying the type of the input box. so, can we have the text id for `OneLineEditor` alone?

2021-02-16 06:57 UTC, tharun208 commented on packages/insomnia-app/app/ui/components/editors/__tests__/password-editor.test.js
> +import React from 'react';
> Thanks for the updates and apologies for the delay. Well done for exploring the unit tests 👏🏽 I've just got a couple of observations from the updates.
> 
> Additionally, I've noticed there's a UI glitch introduced by these changes to the `OneLineEditor`.
> 
> Notice how the text shifts up and down on hovering over the element, however it doesn't happen in the live application right now. Is this something on my computer specifically or are you seeing the same?
> 
> ![2021-02-16 19 01 46](https://user-images.githubusercontent.com/4312346/108024511-922a2c80-7089-11eb-939e-80902d6d4875.gif)

No, I am not facing this in my local 😄

2021-02-16 08:49 UTC, tharun208 commented
@develohpanda, I addressed the feedbacks

2021-02-17 00:23 UTC, develohpanda reviewed
One last item, please 🙂

2021-02-17 00:23 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/password-editor.js
> +  request: Request,
This component is still bound to the `Request` model, but can be unbound by replacing this prop with `disabled: boolean` and `password: string` props.

2021-02-17 00:23 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/__tests__/password-editor.test.js
> +import React from 'react';
Looks like you managed to get things working without the test-id 👍🏽

2021-02-17 05:35 UTC, tharun208 commented on packages/insomnia-app/app/ui/components/editors/password-editor.js
> +  request: Request,
done

2021-02-17 05:57 UTC, develohpanda approved these changes
Nice 👍

2021-02-23 15:36 UTC, dimitropoulos commented
since this needs to be rebased anyway I thought I might ask if it's a simple change to extend the bottom line of the input to the eyeball so the eyeball is inline, e.g.:

![Screenshot_20210223_103351](https://user-images.githubusercontent.com/15232461/108867004-bf636700-75c2-11eb-90ce-242a4f453380.png)


compare that to what this PR implements.

![Screenshot_20210223_103533](https://user-images.githubusercontent.com/15232461/108867145-e15ce980-75c2-11eb-979b-0f0486dcee26.png)


but this is totally totally not blocking - feel free to disregard.

2021-02-25 06:27 UTC, develohpanda approved these changes

2021-02-25 12:19 UTC, DMarby approved these changes

2021-02-25 22:14 UTC, merged