Improve documentation
getinsomnia/insomnia pull request #2990
Opened 2021-01-08 13:49 UTC by Nezia1

This is a really trivial documentation update fixing some typos, and overall making it a bit more readable.

2021-01-11 00:46 UTC, develohpanda requested changes
Thanks for raising this PR, and welcome to the project! One small change, please 🙂

2021-01-11 00:46 UTC, develohpanda commented on DEVELOPMENT.md
> +- Redux stores are an in-memory duplicate of the local DB, unnecessarily doubling memory usage. Moving
The previous version is correct here, but might be worth rewording? `An in-memory duplicate of the local DB is stored in Redux, unnecessarily doubling...`

2021-01-11 00:46 UTC, develohpanda commented on DEVELOPMENT.md
> +- [`libcurl`](https://curl.se/libcurl/) is the library that Insomnia uses to make requests. Libcurl is the HTTP client of choice because it allows the deepest amount of debuggability and control of H
Nice catch 😅

2021-01-11 21:30 UTC, Nezia1 commented on DEVELOPMENT.md
> +- Redux stores are an in-memory duplicate of the local DB, unnecessarily doubling memory usage. Moving
Sorry about that, I got really confused about the use of "stores" here, I thought the sentence was mentioning the Redux stores. Given that it confused me, I rephrased it a bit, I think it makes it a bit easier to understand?

2021-01-11 21:34 UTC, Nezia1 commented on DEVELOPMENT.md
> +- Redux stores are an in-memory duplicate of the local DB, unnecessarily doubling memory usage. Moving
Sorry about that, I got really confused about the use of "stores" here, I thought the sentence was mentioning the Redux stores. My bad 😅

2021-01-12 02:23 UTC, develohpanda approved these changes

2021-01-12 02:23 UTC, merged

2021-01-12 02:24 UTC, develohpanda commented on DEVELOPMENT.md
> +- Redux stores are an in-memory duplicate of the local DB, unnecessarily doubling memory usage. Moving
I had to do a double-take as well 😆