feat: remember the last used import Uri
getinsomnia/insomnia pull request #3018
Opened 2021-01-22 09:00 UTC by sfabriece

Closes #3009

2021-01-24 23:09 UTC, develohpanda requested changes
Thanks for the PR! 🎉

2021-01-24 23:09 UTC, develohpanda commented on packages/insomnia-app/app/ui/redux/modules/global.js
> +    window.localStorage.setItem('insomnia.lastUsedImportUri', uri);
Is there a particular reason you chose to set this here? I think it might be better placed closer to where it is consumed, within the `onComplete` callback of the prompt options, in `import-export.js`.

The `lastExportFormat` value is stored in this file, but that's because the modal where it is consumed is also shown from this file.

2021-01-25 12:01 UTC, sfabriece commented on packages/insomnia-app/app/ui/redux/modules/global.js
> +    window.localStorage.setItem('insomnia.lastUsedImportUri', uri);
Made changes as recommended @develohpanda 😄

2021-01-25 12:03 UTC, sfabriece commented
Moved changes to import-export.js @develohpanda

2021-01-25 21:55 UTC, develohpanda approved these changes
Looks good now. Looks to be working after QA as well. Nice one! 🎉 

Note, this only persists in the import/export modal from _Preferences_. If using Designer, and on the homepage you choose to "Create" a document "From URL", it does not persist (which IMO is correct).

2021-01-27 12:28 UTC, DMarby approved these changes

2021-01-27 20:59 UTC, merged