Autobind replacement and react-hot-reload update
getinsomnia/insomnia pull request #3022
Opened 2021-01-22 19:46 UTC by MrSnix

As requested by @develohpanda, I'm opening this PR as a proposal about issue #2468.
This PR is an improved version from the previous one #2963 which has been closed in favor of this one.

**Context**
The auto-bind decorator is preventing react-hot-reload from working properly due to binding not only the class functions but even the React lifecycles functions (which is unnecessary and should be avoided) causing the following error:
![image](https://user-images.githubusercontent.com/20780192/105536787-31f5d400-5cf1-11eb-8cb2-a364a075094c.png)

**The current idea**
We aim to replace [autobind-decorator](https://www.npmjs.com/package/autobind-decorator) with [class-autobind-decorator](https://www.npmjs.com/package/class-autobind-decorator) that introduces `@autoBindMethodsForReact` a convenience decorator that skips auto binding methods from the React Component Spec that do not require binding.

Here is a gif that shows react-hot-reloading working again

![Test](https://user-images.githubusercontent.com/20780192/105537713-9d8c7100-5cf2-11eb-9e10-00384199267c.gif)

As always I'm glad to hear feedback.
Thanks

2021-01-25 00:10 UTC, develohpanda approved these changes
Much cleaner PR, and it seems to be working well too. Nice! 🎉 

[react-fast-refresh](https://github.com/facebook/react/issues/16604) isn't stable for [Webpack](https://github.com/pmmmwh/react-refresh-webpack-plugin/) yet, but that would be the next transition when the time comes.

2021-01-28 12:09 UTC, DMarby approved these changes
Thank you for doing this, seems to work great overall!

I noticed that it seems to break some functionality in the sidebar upon hot reloading, but I'll defer to @develohpanda as to whether that's best to fix before merging this or if it can be addressed later.

I'm not sure if we need to also manually ignore some of the lifecycle methods in the files where we use them @develohpanda?
The library automatically ignores these ones: https://github.com/jmrog/class-autobind-decorator/blob/master/src/lib/ReactComponentSpecMethods.js
However, some of them that we use have changed names, and might need to be manually ignored:
```
UNSAFE_componentWillMount
UNSAFE_componentWillUpdate
UNSAFE_componentWillReceiveProps
```
Not sure if there are also any new lifecycle methods we use that should be ignored.
Regardless, that could probably be addressed at a future date.

2021-01-28 12:09 UTC, DMarby commented on packages/insomnia-app/app/ui/index.js
> +    const app = () => (
It seems like hot reloading causes the sidebar drag functionality to break, after a hot reload occurs, if you try to drag and drop an item in the sidebar (eg to re-order requests), the following error occurs:

![image](https://user-images.githubusercontent.com/174626/106136409-8ffb3f00-6169-11eb-849d-2da3f31f4488.png)
![image](https://user-images.githubusercontent.com/174626/106136309-68a47200-6169-11eb-8cbb-992fd362a13a.png)

Interacting with the sidebar at all will also keep throwing errors in the sidebar, but it still seems to render correctly.

2021-01-28 21:42 UTC, MrSnix commented
In the last commit, I manually added unsafe react lifecycles as to be ignored by the decorator.
About the sidebar error, as @DMarby correctly stated, it is related to `react-dnd` and `react-hot-reload`. (We are so lucky...)
I found this: [react-dnd #186](https://github.com/react-dnd/react-dnd/issues/186)
I'll try to ship a fix for this if I manage to.

2021-02-02 03:38 UTC, develohpanda requested changes
Yes the `UNSAFE_*` lifecycle methods should be ignored too (and aren't currently as a result of the library being slightly outdated).

Nice work adding them @MrSnix 🎉, although (if it works) I think it might be safer to apply a common `autoBindConfig` to each instance of the decorator, rather than selectively depending on usage in a component. If specified per component, as it changes over time it is likely someone will forget to update the autoBind config for it.

```js
// common.js or somewhere
const autoBindConfig = {
  methodsToIgnore: ['UNSAFE_componentWillReceiveProps', ...],
};

// component file
@autoBindMethodsForReact(autoBindConfig)
class Component { ... }
```

2021-02-02 22:22 UTC, develohpanda approved these changes
🔥

2021-02-02 22:23 UTC, merged