Prevent deletes and validate proto files when uploading a directory
getinsomnia/insomnia pull request #3024
Opened 2021-01-25 04:43 UTC by develohpanda

This PR resolves two issues with one buffering fix: INS-431 and INS-433.

**Prevent deletes while uploading:** previously, buffering did not work as expected and would show files in the proto files list as they were loaded, instead of _after_ they were loaded. This meant one could delete the root proto directory, even though the loading process had not completed. This has been resolved in this PR by further controlling how the database chooses to flush it's changes to the UI.

**Validate proto files when uploading:** after uploading a directory, this PR will now try to parse each file that was uploaded to make sure all files are valid. If a single invalid file is found, the root proto directory and all of it's children are deleted.

2021-01-26 15:32 UTC, DMarby commented on packages/insomnia-app/app/network/grpc/proto-manager/ingest-proto-directory.js
> +  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
Just curious, but is there any particular reason why you're using localeCompare here?

2021-01-26 15:49 UTC, DMarby commented on packages/insomnia-app/app/network/grpc/proto-manager/ingest-proto-directory.js
> +    const result = await (entry.isDirectory()
I think we might need some logic handling errors here, as currently they would propagate straight up, meaning any previously inserted files on the current level will get orphaned and won't be cleaned up by the rollback logic, as they don't belong to any parent that exists until it's created further down?

2021-01-26 15:50 UTC, DMarby requested changes
Seems to work great 👍
Just one question regarding potential orphaning of db objects

2021-01-26 21:12 UTC, develohpanda commented on packages/insomnia-app/app/network/grpc/proto-manager/ingest-proto-directory.js
> +  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
No particular reason, although the name is a user defined and I want it to process each file alphabetically (so that errors are raised in the same order each time the user attempts to import).

2021-01-27 01:14 UTC, develohpanda commented on packages/insomnia-app/app/network/grpc/proto-manager/ingest-proto-directory.js
> +class ProtoDirectoryLoader {
This diff isn't very nice to look at. 😞 

I decided to move this logic into a class, to avoid passing a "createdIds" array between every function, or saving it globally in the file. Let me know if you have any thoughts around this @DMarby.

2021-01-27 01:20 UTC, develohpanda commented on packages/insomnia-app/app/network/grpc/proto-manager/ingest-proto-directory.js
> +    const result = await (entry.isDirectory()
Added a breaking test, and updated this logic.

2021-01-27 12:19 UTC, DMarby approved these changes

2021-01-27 12:19 UTC, DMarby commented on packages/insomnia-app/app/network/grpc/proto-manager/ingest-proto-directory.js
> +class ProtoDirectoryLoader {
Sounds like a reasonable approach

2021-01-27 22:00 UTC, merged