Add migration for workspace scope and apply defaults
getinsomnia/insomnia pull request #3031
Opened 2021-01-28 01:16 UTC by develohpanda

What it says on the tin, further details in the linked issue.

Closes INS-406

2021-01-28 10:57 UTC, DMarby requested changes
Changes look good, I think there's a few more places where we create workspaces that we should specify the scope for as well however?

For when removing a workspace from the workspace dropdown:
https://github.com/Kong/insomnia/blob/68949619fecbee12e128eeaf1f77bc12a23ac2d1/packages/insomnia-app/app/ui/components/wrapper.js#L433

And possibly when importing here, but I guess this is kind of moot if we're letting the user decide what kind of workspace to import soon anyway:
https://github.com/Kong/insomnia/blob/1fe337dd2dc353857219f258bb9a739f6e110a3e/packages/insomnia-app/app/common/import.js#L154

2021-01-28 10:58 UTC, DMarby commented on packages/insomnia-app/app/models/workspace.js
> +    case null:
*Should* never happen, but it might be worth adding a `default:` case here too just as a defensive measure?

2021-01-28 23:42 UTC, develohpanda commented
> I think there's a few more places where we create workspaces that we should specify the scope for as well however?

These are all catered for by the default applied here: https://github.com/Kong/insomnia/blob/590286d628366b5f62a87c9c43ecfe1b8c999993/packages/insomnia-app/app/models/workspace.js#L21-L27

2021-01-29 07:18 UTC, DMarby approved these changes

2021-02-02 03:02 UTC, merged