Fix for #2937 : Request Pane now displays URL parameters when "Import URL" is clicked
getinsomnia/insomnia pull request #3032
Opened 2021-01-28 09:40 UTC by ARKEOLOGIST

Closes #2937 
Request pane should display URL parameters immediately when "Import URL" is clicked.

2021-01-28 13:04 UTC, ARKEOLOGIST commented
@develohpanda Can you take a look at this?

2021-01-30 08:27 UTC, develohpanda commented
Thanks for the PR @ARKEOLOGIST and sorry about the delay in reviews (on this PR and your previous PR) 🤗 a lot on my plate atm but I'll get to it in the coming week for sure!

2021-02-06 08:16 UTC, ARKEOLOGIST commented
@develohpanda Any progress on the review?

2021-02-09 02:13 UTC, develohpanda requested changes
Thanks for the PR @ARKEOLOGIST and apologies for the delays! This looks to be working well 🎉 just a couple of comments worth addressing, please.

2021-02-09 02:13 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/key-value-editor/editor.js
> +      }
This seems like it's inspired from the constructor here: https://github.com/Kong/insomnia/blob/0779b0b8c435dd861aad70b32a0f0793d213b4f1/packages/insomnia-app/app/ui/components/key-value-editor/editor.js#L32-L38 I'd favor extracting this logic into another method on this class and reusing it, for example `_ensureIds`.

You also shouldn't need `pairs` and `index` as separate arrays. Just update the source array (`pairs`, not `this.props.pairs`), like is done in the constructor snippet above.

2021-02-09 02:13 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/key-value-editor/editor.js
> +    }
Is there a particular reason you chose to wrap this logic in a `try-catch`? Seems unnecessary.

2021-02-09 02:13 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/key-value-editor/editor.js
> +        console.log(prevPairs);
I think we can avoid this `console.log` statement 😄

2021-02-13 09:13 UTC, ARKEOLOGIST commented on packages/insomnia-app/app/ui/components/key-value-editor/editor.js
> +        console.log(prevPairs);
New commits address this.

2021-02-13 09:13 UTC, ARKEOLOGIST commented on packages/insomnia-app/app/ui/components/key-value-editor/editor.js
> +    }
Please have a look, I have removed it.

2021-02-13 09:13 UTC, ARKEOLOGIST commented on packages/insomnia-app/app/ui/components/key-value-editor/editor.js
> +      }
Yep, you're right, I didn't need it.

2021-02-14 21:27 UTC, ARKEOLOGIST commented
@develohpanda Please have a look at the changes if possible!

2021-02-15 22:54 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/key-value-editor/editor.js
> +      }
I think there's a slight misunderstanding here, let me clarify. 😄 You'll notice that the snippet in the comment above is nearly identical to a part of the logic you introduce. It appears to be logic that should be common across all usages, instead of duplicating it I suggest extracting that particular snippet into a separate method and consuming it in both the constructor and your bug fix.

2021-02-15 22:55 UTC, develohpanda commented
Looks like there's an issue when running through the reproduction steps in the original issue. Note: this was working before you made the changes in [`fa7ba9c` (#3032)](https://github.com/Kong/insomnia/pull/3032/commits/fa7ba9cc6912a09d2ff4e0c9d94370dcf5b0b055).

![2021-02-16 11 48 42](https://user-images.githubusercontent.com/4312346/107999825-4e193680-704d-11eb-89a4-43c6ab513c70.gif)

2021-02-18 07:12 UTC, ARKEOLOGIST commented
@develohpanda Reverted the changes. They should work now! Changes have been made to the constructor too so that code duplication isn't a thing.

2021-03-01 05:11 UTC, ARKEOLOGIST commented
Any updates on this @develohpanda? I've done the changes as asked.

2021-03-01 06:44 UTC, develohpanda commented
Hi @ARKEOLOGIST, my apologies for the delays, again. I am fairly bogged down right now with a release coming up and a lot of activity, so I really appreciate your patience with reviews 🙏🏽 rest assured your PR will not be ignored and we will get to it in due time. Thank you! 🤗

2021-04-02 06:28 UTC, ARKEOLOGIST commented
@develohpanda Sorry for asking again, but did you have the time to look at this?

2021-04-12 04:26 UTC, develohpanda reviewed
Hi @ARKEOLOGIST, it seems this still doesn't work as intended, see gif below where the key-value pairs are missing from the UI at the end.

![2021-04-12 16 24 47](https://user-images.githubusercontent.com/4312346/114340484-c31b6f00-9bab-11eb-8f2d-5ed9db449f1b.gif)

Note: I'm going to briefly work on the code here and may push to your branch if it works in order to get this PR through

2021-04-12 04:49 UTC, ARKEOLOGIST commented
@develohpanda The issue seems to arise from the fact that that the parameter extraction seems to run again after you come back to the request. Since the parameters already have been removed from the URL - you see no parameters. I'll try and see if I can shift my changes higher up, so that this problem can be averted.

2021-04-12 04:59 UTC, develohpanda commented
It happens when you make an edit without navigating away as well.

![2021-04-12 16 53 14](https://user-images.githubusercontent.com/4312346/114342281-b00a9e00-9baf-11eb-9565-2963c45b281d.gif)

This is related to the logic changed within `key-value-editor.js` rather than an issue upstream. When looking at how the `key-value-editor.js` component is behaving, an important question to ask which would guide a solution is the following.

What _should_ happen to `this.state.pairs` if `this.props.pairs` _changes_, given the state is derived from props in the constructor? Are there more suitable lifecycle events to use than `componentDidUpdate`?

I do have a solution but am happy to not give a direct answer if you'd like to do some sleuthing as this is a nice exercise/problem to debug.

2021-04-12 05:10 UTC, ARKEOLOGIST commented
@develohpanda I was stupid. Thanks for giving me the opportunity to figure this out on my own - I'll push my changes shortly and probably record a video as proof of my changes.

2021-04-12 05:11 UTC, develohpanda commented
No worries 🤗 take your time

2021-04-12 05:58 UTC, ARKEOLOGIST commented
There, it should work now.

2022-10-11 10:31 UTC, jackkav commented
Closed as stale.

2022-10-11 10:31 UTC, closed without merging