Data migration workflow from Designer to Core
getinsomnia/insomnia pull request #3051
Opened 2021-02-05 02:06 UTC by develohpanda

WIP

2021-02-05 02:23 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/general.js
> +              )}
This boolean flag is useful in development but should not be visible to users in production.

2021-02-05 02:23 UTC, develohpanda commented on packages/insomnia-app/app/ui/index.js
> +  //  Need to know all the rules for when to automatically show migration and what the previous/next step is
https://linear.app/insomnia/issue/INS-407#comment-22d89fe1

2021-02-08 14:10 UTC, DMarby requested changes
Awesome, seems to work great! 🎉 
Just one concern around getting the Insomnia Designer data path, as it doesn't work on Windows.

2021-02-08 14:10 UTC, DMarby commented on packages/insomnia-app/app/ui/components/wrapper-onboarding.js
> +    const { step } = this.state;
I'm assuming this is just a work in progress, since it duplicates some code from `renderPageBody`, which doesn't seem to ever be called anymore?

2021-02-08 14:10 UTC, DMarby commented on packages/insomnia-app/app/common/misc.js
> +  return envPaths('Insomnia Designer', { suffix: '' }).data;
This won't work correctly on Windows, as `env-paths` returns `%LOCALAPPDATA%/Insomnia Designer/Data` instead of the correct `%APPDATA%/Insomnia Designer%`.

I think it'd be better to use the Electron APIs:

```suggestion
  const { app } = electron.remote || electron;
  return pathJoin(app.getPath('appData'), 'Insomnia Designer');
```

2021-02-09 00:26 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-onboarding.js
> +    const { step } = this.state;
Oh yes this is a missed step, the function no longer needs to exist as most of it has been moved into `OnboardingContainer`

2021-02-09 01:03 UTC, develohpanda commented on packages/insomnia-app/app/common/misc.js
> +  return envPaths('Insomnia Designer', { suffix: '' }).data;
I have updated this, but cannot verify on Windows until later this evening. Nice catch though, I've removed envPaths as an app dependency as well.

2021-02-09 05:14 UTC, DMarby approved these changes

2021-02-09 19:48 UTC, DMarby approved these changes

2021-02-09 19:55 UTC, merged

2021-02-09 20:35 UTC, nijikokun commented on packages/insomnia-app/app/ui/components/wrapper-migration.js
> +        <strong>Would you like to migrate data from Insomnia Designer?</strong>
![image](https://user-images.githubusercontent.com/198276/107424038-02591100-6ad2-11eb-9bc9-acd93cbb00d8.png)

2021-02-09 20:35 UTC, nijikokun commented on packages/insomnia-app/app/ui/components/wrapper-migration.js
> +          label="Use Designer Settings"
`Copy Designer Application Settings`

2021-02-09 20:35 UTC, nijikokun commented on packages/insomnia-app/app/ui/components/wrapper-migration.js
> +            label="Core Data Directory"
Since `Core` is now `Insomnia` this should be: `Insomnia Data Directory`

2021-02-09 20:35 UTC, nijikokun commented on packages/insomnia-app/app/ui/components/wrapper-migration.js
> +          Cancel
`Skip for now`

2021-02-09 20:35 UTC, nijikokun commented on packages/insomnia-app/app/ui/components/wrapper-migration.js
> +        Restart
`Restart Now`

2021-02-09 20:35 UTC, nijikokun commented on packages/insomnia-app/app/ui/components/wrapper-migration.js
> +        Restart
`Restart Now`