Stop automatically appending .git to git repository URLs
getinsomnia/insomnia pull request #3054
Opened 2021-02-05 15:11 UTC by DMarby

Fixes #2095
Fixes INS-367

Tested by creating a repo on Azure DevOps and successfully interacting with it, before this PR all operations against it fails.

2021-02-05 20:51 UTC, DMarby commented on packages/insomnia-app/app/models/git-repository.js
> +  if (!doc.uri.endsWith('.git')) {
Reason for doing it this way rather then parsing the URL is that it's how `isomorphic-git` did it, so to ensure that we mimic the behaviour we do it the same way: https://github.com/isomorphic-git/isomorphic-git/blob/9176a3a7f0a28b059b0aae135ce5f325f5d737ec/src/managers/GitRemoteHTTP.js#L53

2021-02-05 20:52 UTC, DMarby commented on packages/insomnia-app/app/models/git-repository.js
> +  uriHasBeenMigrated: boolean,
Not super nice to need to add a new property for this, but not sure of a better approach since we only want to run this migration for old entries.

2021-02-09 01:56 UTC, develohpanda requested changes
Nice! Seems to be working, I tested with a git repo without the suffix, applied this PR and saw the suffix had been added as expected. 🎉 

A couple of comments to do with how and where `uriHasBeenMigrated` is set and extending the unit test which I think are worth addressing. 

Additionally, I think we need some UI prompts to make sure users don't see 404s if they don't suffix with `.git` manually.

For example, if you try to clone `https://github.com/develohpanda/designer` (note, no suffix), you get 404s while previously, it worked. Perhaps a tooltip or active warning which explains the requirement to suffix with `.git` _except_ in the currently known case with Azure DevOps.

2021-02-09 01:56 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/dropdowns/git-sync-dropdown.js
> +            uriHasBeenMigrated: true,
I think patching this flag should be done within the `create` function rather than out here. If I understand correctly, _any_ time the user will create a git repo in future, this should _always_ be set to true.

In this case it seems possible to contain a flag related to model migration to the model itself, which feels safer.

2021-02-09 01:56 UTC, develohpanda commented on packages/insomnia-app/app/models/__tests__/git-repository.test.js
> +    expect(newRepoWithoutSuffix.uri).toBe('https://github.com/foo/bar');
Also want to test that for all instances, the flag `uriHasBeenMigrated` is set (or retained) as `true`.

2021-02-09 01:56 UTC, develohpanda commented on packages/insomnia-app/app/models/git-repository.js
> +  uriHasBeenMigrated: boolean,
I agree, not nice to add a one-time entry, but it does seems necessary. There exist database repair scripts which run once on launch (as opposed to model migrations which can run more frequently).

You'd still need a flag somewhere but perhaps `_repairDatabase` is a better place to migrate? Not really fussed, but since this is a one-time migration it might be better in the repair 🤔 

https://github.com/Kong/insomnia/blob/b135a2c637768b5a21ae68a7e39e4ca8e5785ff0/packages/insomnia-app/app/common/database.js#L689-L699

2021-02-09 05:42 UTC, nijikokun commented
> Additionally, I think we need some UI prompts to make sure users don't see 404s if they don't suffix with `.git` manually.

I disagree. Let's not display assumptions about git systems, we know this is the case for this system, but not others and we might ultimately give the user bad advice while attempting to act in good faith. 

If it's a requirement, the input should be sufficient enough, anything further and perhaps we add a link to some documentation about specific systems external to the application where we can maintain without updating the application itself.

2021-02-09 06:00 UTC, develohpanda commented
> Let's not display assumptions about git systems, we know this is the case for this system, but not others and we might ultimately give the user bad advice while attempting to act in good faith.
> 
> If it's a requirement, the input should be sufficient enough, anything further and perhaps in later iterations after we see instances of issue we can add a link to some documentation about specific systems external to the application where we can maintain without updating the application itself.

The input doesn't seem to check whether `.git` is provided, and we don't mention anywhere that `.git` _needs_ to be provided as the suffix. From my testing and the isomorphic-git documentation, the `.git` suffix is a requirement for GitHub (and likely for GitLab). Omitting the `.git` suffix only seems to work for Azure DevOps. Previously it would automatically add the suffix if it was missing; now it needs to be manually added.

This means, that with GitHub for example, what worked before will seemingly stop working for new clones/repositories (a migration was added for existing repositories).

Given this behavior I think we need to say _something_, even if it is a tool-tip with a link to docs next to the label (like the auth token, for example, below)

![image](https://user-images.githubusercontent.com/4312346/107322212-e45ad300-6b08-11eb-9467-4723d7b6eb38.png)

2021-02-09 06:04 UTC, nijikokun commented
> don't mention anywhere that `.git` _needs_ to be provided as the suffix

It's here on the input:
![image](https://user-images.githubusercontent.com/198276/107322549-83c08d00-6a59-11eb-8c53-9200846c5d03.png)

2021-02-09 06:06 UTC, develohpanda commented
Really doesn't feel like a placeholder is sufficient, but I'll leave that up to you.

2021-02-09 06:57 UTC, DMarby commented on packages/insomnia-app/app/models/__tests__/git-repository.test.js
> +    expect(newRepoWithoutSuffix.uri).toBe('https://github.com/foo/bar');
Good catch 👍

2021-02-09 06:57 UTC, DMarby commented on packages/insomnia-app/app/ui/components/dropdowns/git-sync-dropdown.js
> +            uriHasBeenMigrated: true,
Agreed, harder to miss setting it with a create function, done 👍

2021-02-09 07:24 UTC, DMarby commented on packages/insomnia-app/app/models/git-repository.js
> +  uriHasBeenMigrated: boolean,
I think that sounds like a better place to put it, done.

2021-02-09 08:15 UTC, develohpanda approved these changes
Looking good! The discussion above about a tool-tip vs placeholder is not a blocker for this PR 😄

2021-02-09 08:15 UTC, develohpanda commented on packages/insomnia-app/app/models/git-repository.js
> +    uriNeedsMigration: true,
👍🏽

2021-02-09 08:15 UTC, develohpanda commented on packages/insomnia-app/app/models/git-repository.js
> +    uriNeedsMigration: false,
🔥

2021-02-09 08:17 UTC, merged

2023-09-19 08:21 UTC, swone1990 commented
Hey not sure but i tought the issue with the .git suffix is solved.
I still can not checkout AzureDevops Repositories, because the suffix got apppended.

Did I miss something in this Issue?