use operationId where possible in o2k generation
getinsomnia/insomnia pull request #3072
Opened 2021-02-10 19:24 UTC by dimitropoulos

Currently o2k generates custom incremental route names, Swagger already has a mechanism which allows the user to give routes a unique identifier through operationId which o2k should use before falling back to generated route names.

2021-02-10 19:52 UTC, nijikokun approved these changes
💯

2021-02-10 19:57 UTC, nijikokun commented on packages/openapi-2-kong/src/declarative-config/services.js
> +  if (typeof pathItem['x-kong-name'] === 'string') {
Actually, missed this in my initial review, the order here - while directive based - should also be hierarchical. Since `x-kong-name` is on the path, and not the method it should be as follows:

Current:

- `path.method.x-kong-name`
- `path.x-kong-name`
- `path.method.operationId`
- `generated`

Expected:

- `path.method.x-kong-name`
- `path.method.operationId`
- `path.x-kong-name`
- `generated`

2021-02-10 19:58 UTC, nijikokun requested changes

2021-02-10 19:58 UTC, nijikokun commented on packages/openapi-2-kong/src/declarative-config/services.js
> +  if (typeof pathItem['x-kong-name'] === 'string') {
Actually, missed this in my initial review, the order here - while directive based - should also be hierarchical. Since `x-kong-name` is on the path, and not the method it should be as follows:

Current:

- `path.method.x-kong-name`
- `path.x-kong-name`
- `path.method.operationId`
- `generated`

Expected:

- `path.method.x-kong-name`
- `path.method.operationId`
- `path.x-kong-name`
- `generated`

2021-02-10 20:16 UTC, DMarby approved these changes
Awesome 🎉

2021-02-10 20:16 UTC, DMarby commented on packages/insomnia-app/package.json
> +    "axios": "^0.21.1",
I think this change is fine, but in general we try to avoid unrelated changes in a PR, so in the future it would be good if something like this went into a separate PR

2021-02-11 07:05 UTC, develohpanda approved these changes
LGTM, awesome!

2021-02-11 07:05 UTC, develohpanda commented on packages/openapi-2-kong/src/__fixtures__/api-with-examples.expected.json
> +          "name": "Simple_API_overview-x_kong_name_override_at_path_item-get",
Are we aware of any name length limits in Kong?

2021-02-11 07:05 UTC, develohpanda commented on packages/openapi-2-kong/src/__fixtures__/api-with-examples.yaml
> +      x-kong-name: x-kong-name-override-at-method
💯

2021-02-11 07:05 UTC, develohpanda commented on packages/openapi-2-kong/src/declarative-config/services.js
> +  if (typeof pathItem['x-kong-name'] === 'string') {
I recall there is similar logic in the kong-for-kubernetes generation, they should probably match when we get around to updating that one as well

2021-02-11 07:05 UTC, develohpanda commented on packages/openapi-2-kong/types/openapi3.flow.js
> +};
Here comes the venture into flow types 😆 

These flow declaration files are _mostly_ pretty good. TS didn't complain too much after converting, yay!

2021-02-11 14:35 UTC, dimitropoulos commented on packages/openapi-2-kong/types/openapi3.flow.js
> +};
:)

2021-02-11 20:45 UTC, DMarby approved these changes
:shipit:

2021-02-11 20:45 UTC, DMarby commented on packages/openapi-2-kong/src/declarative-config/__tests__/names.test.js
> +describe('names', () => {
🔥

2021-02-11 21:58 UTC, dimitropoulos commented on packages/openapi-2-kong/src/__fixtures__/api-with-examples.expected.json
> +          "name": "Simple_API_overview-x_kong_name_override_at_path_item-get",
I hope not, haha, because one of the prior ones was `httpbin-Returns_the_specified_HTTP_status_code_or_a_random_status_code_if_more_than_one_are_given-delete`

2021-02-11 22:01 UTC, develohpanda commented on packages/openapi-2-kong/src/__fixtures__/api-with-examples.expected.json
> +          "name": "Simple_API_overview-x_kong_name_override_at_path_item-get",
🤣

2021-02-16 15:45 UTC, dimitropoulos commented on packages/openapi-2-kong/src/__fixtures__/api-with-examples.expected.json
> +          "name": "Simple_API_overview-x_kong_name_override_at_path_item-get",
(resolving since no name is now longer than before)

2021-02-16 17:15 UTC, nijikokun approved these changes

2021-02-16 21:34 UTC, merged