Insomnia CLI - Reporter integration
getinsomnia/insomnia pull request #3087
Opened 2021-02-14 01:05 UTC by MrSnix

The following PR contains these changes:
- Removed blocking-code for external reporters
- When using an external reporter (installed with npm) an info message is printed to say "be careful, we try our best but it may fail...if you can use our internal reporters".
- If the reporter is external, now it is able to print on console (because of some Insomnia code preventing it), so the result can be eventually piped
- If the external reporter is not found, it is now caught from Mocha and displayed to the user in a nice way

To-Do:
- Handle arguments given to the reporter

2021-02-14 22:52 UTC, nijikokun requested changes

2021-02-14 22:52 UTC, nijikokun commented on packages/insomnia-inso/src/commands/run-tests.js
> +    logger.info(`Reporter "${reporter}" is not recognized and is treated as external`);
While informational, we should avoid printing messages so they are not a part of any output piped to a file for other actions

2021-02-14 22:58 UTC, MrSnix commented on packages/insomnia-inso/src/commands/run-tests.js
> +    logger.info(`Reporter "${reporter}" is not recognized and is treated as external`);
Not even if  - - verbose option is provided? 🤔

2021-02-14 23:54 UTC, nijikokun commented on packages/insomnia-inso/src/commands/run-tests.js
> +    logger.info(`Reporter "${reporter}" is not recognized and is treated as external`);
Yes, as it’s more likely an intentional choice and the output desired is to go into other commands expecting specific formatting

2021-02-20 21:50 UTC, MrSnix commented
@nijikokun 
I wanted to put my hands on this before but my week has been busy 😭 

Anyway, it was challenging but in the end, I **won**! Let's begin.

**Context**
In order to handle the `--reporter-options` I had to make some changes inside the `insomnia-testing` package,
unluckily it was shipped with `insomnia-inso` package using the npm repository and I wasn't able to
make changes on it. So, the first thing I did was to use the `npm link` as a substitute for the dependency,
in that way the changes I was doing on the original code were reflected inside the package.
After my playground 🎮  was ready, I started doing researches. 👨🏻‍🔬 

I spent some time on the [Mocha.js API](https://mochajs.org/api/mocha) documentation and I found out
I could use the following interface to pass the argument to the reporter [Mocha Reporter API](https://mochajs.org/api/mocha#reporter). 
So, I modified `runInternal()` to support the new argument (`--reporter-options`) then, 
I had to add a new argument to insomnia-cli in order to parse the string containing the options for the reporter. 
The problems didn't end there. Mocha API wants an object meanwhile I was able to parse only a string. 
I built a function to extract an object from the string which was given as argument and BOOM! 💥 . 
It happened. It worked.

**Let's see it**

`inso run test --reporter mocha-simple-html-reporter --reporter-options output=/.../.../output.html`

![test](https://user-images.githubusercontent.com/20780192/108609195-b315b900-73cc-11eb-97dc-df9538ab4a23.gif)

Now, here is our little friend.
![image](https://user-images.githubusercontent.com/20780192/108609242-04be4380-73cd-11eb-8bfa-3ca9e0b00fe6.png)

Now, **I have some questions**:
1. Should I suppress the network messages?
2. I did changes on `insomnia-testing` too, should I push them separately or can I push everything here?

Thanks

2021-02-20 22:22 UTC, MrSnix commented
**I want to add one more thing because I'm not really sure about it** and  
if someone more expert than me can confirm it that would be great.  

In order to make `mocha-simple-html-reporter` be recognized by `insomnia-cli`
installing it as `global package` wasn't enough.
_(but I may assume it may be because `mocha-simple-html-reporter` is not invokable from the CLI)_

I had to install it as a dependency in order to make it works but **here comes the strange part.**

**Before** linking `insomnia-testing` with `insomnia-inso` I had to add the dependency to the `insomnia-inso` package
to make it recognizable. But **AFTER** linking it was not recognized anymore.  
Then, I **removed** the dependency from `insomnia-inso` package and I added it to the `insomnia-testing` package and... 
it is recognized again... **What?!**

So, my first assumption was that the first `node_modules` folder he finds is the one it searches into before throwing an error.

The final answer comes from here, the actual implementation:
```js
Mocha.prototype.reporter = function(reporterName, reporterOptions) {
[...]
    var reporter;
    // Try to load a built-in reporter.
    if (builtinReporters[reporterName]) {
      reporter = builtinReporters[reporterName];
    }
    // Try to load reporters from process.cwd() and node_modules
    if (!reporter) {
      try {
        reporter = require(reporterName);
      } catch (err) {
        if (err.code === 'MODULE_NOT_FOUND') {
          // Try to load reporters from a path (absolute or relative)
          try {
            reporter = require(path.resolve(utils.cwd(), reporterName));
          } catch (_err) {
            _err.code === 'MODULE_NOT_FOUND'
 [...]
```
[Source Code - Line 273](https://mochajs.org/api/mocha.js.html)

They are basically doing `require()`.

The require function will look for files in the following order:
1. Built-in core Node.js modules (like fs, path)
2. NPM Modules. It will look in the node_modules folder.
3. Local Modules. If the module name has a ./, / or ../, it will look for the directory/file in the given path. It matches the file extensions: *.js, *.json, *.mjs, *.cjs, *.wasm and *.node.

**So here comes my final question:**
If I install `insomnia-inso` and `mocha-simple-html-reporter` as global packages, launching them from the OS command line, will make them work?

This answer should be helpful for @develohpanda (I think?) which was asking about 3rd party modules integrations.

2021-02-21 21:25 UTC, develohpanda commented
> **So here comes my final question:**
> If I install `insomnia-inso` and `mocha-simple-html-reporter` as global packages, launching them from the OS command line, will make them work?
> 
> This answer should be helpful for @develohpanda (I think?) which was asking about 3rd party modules integrations.

This was the expectation but it definitely needs some research; as you've found in your experiments it doesn't seem to work?

Ideally we should avoid installing/bundling external reporters within Inso, so if installing globally is not trivial, we'll need to look at a different approach.

2021-02-23 07:57 UTC, nijikokun commented
> as you've found in your experiments it doesn't seem to work?

From reading it sounds like the experiment was local to the development see @MrSnix earlier comments about how he was linking through npm, not global installation. It would be good to test global installation, as it sounds - from what I read - the require *should* look in the same `node_modules` directory as the globally installed `inso` and should find the relative `mocha-simple-html-reporter` package.

> Ideally we should avoid installing/bundling external reporters within Inso, so if installing globally is not trivial, we'll need to look at a different approach.

Agree'd

2021-02-23 08:41 UTC, develohpanda commented
I think `npm link` is being used to make sure changes to `insomnia-testing` can be seen by `insomnia-inso`? Regardless, I misinterpreted the last question, thanks for the clarification. 😊

Another approach for installing the dev version of inso globally would be to build inso, then run `npm install -g packages/insomnia-inso` directly. Worth expanding the readme with this (or the pack file) .

If that finds the reporter, epic!

2021-02-23 22:33 UTC, MrSnix commented
**Before reading:**
_Warning_: I don't **really** know why it works like this (I can just assume) but this is what I found out.

This time it was a real adventure. 🤦🏻 

**Let's begin**
I used `npm pack` on `insomnia-inso` and built our beloved ❤️ `insomnnia-inso.tar`.
I executed `npm install -g ./insomnia-inso.tar` then I proceeded to install `mocha-simple-html-reporter` globally.
```shell
~ % npm -g list --depth=0 
/Users/xyz/.nvm/versions/node/v12.18.3/lib
├── insomnia-inso@2.2.28
├── mocha-simple-html-reporter@2.0.0
```

I wrote the command `inso run test --reporter mocha-simple-html-reporter`, I selected everything I had to... 
then I pressed Enter..........

Failure. 💥 

I was astonished. I was expecting it to work. The reporter was not recognized. 
So, I started thinking ... why it is not working? Both are installed globally... they should see each other.
I stared at the screen for a while and I was about to set the cli on fire ... **then something clicked-in.**

I took `mochawesome`, I installed it globally then I run again the same command...

**Working**, the reporter was recognized.

So, I run again `mocha-simple-html-reporter` with insomnia

**Working**, the reporter was recognized.

But this time I knew what I had to look for, **I felt enlightened.** 💡 

```shell
% npm -g list --depth=0
/Users/xyz/.nvm/versions/node/v12.18.3/lib
├── insomnia-inso@2.2.28
├── mocha@8.3.0
├── mocha-simple-html-reporter@2.0.0
├── mochawesome@6.2.2
```

Here the solution:
**If Mocha.js is NOT installed globally, other reporters won't be recognized.**

I don't know about your opinion but I supposed that:
if `insomnia-cli` already declares `mocha` as a direct dependency, it should have worked.
Well, it turned out: "No" it doesn't.

So I went on `mochawesome` repository and started doing some considerations which met my expectations 📖 .

Even if they declare and use `mocha` the same way as `insomnia-inso`, the `key difference` is that **they DO NOT list `mocha` as dependency BUT as **peer-dependency**** which makes sense now!
Proof: [mochawesome - package.json](https://github.com/adamgruber/mochawesome/blob/master/package.json) 

Maybe you knew already about it, but I was confused because nor the `mocha-simple-html-reporter` nor `insomnia-inso` declares `mocha` as a peer dep.

So, I strongly advise applying the same to `insomnia-inso` package. 📦 

After that, everything seemed working.
It took me some hours but definitely really funny 🤯  and worth it. 😂 

**So, now I ask, what's next?**
I'd like to keep testing a bit the new code and change the `package.json` as stated before.
Am I missing anything else?

**Q&A**

> You should be able to get away without using `npm link` because we're using `lerna` so dependencies should be linked. 

Lerna builds the packages in each directory but seems like it does not correlate (link) them. 
(I don't know a lot about Lerna, so I may be wrong 😢 , I apologize if the case)

> Are you running `inso` in [watch mode](https://github.com/Kong/insomnia/tree/develop/packages/insomnia-inso#development)?

The link reference `npm run start`, so I dug a bit and it is using webpack watch mode. 🤔 
So I went on the configuration and turned out it is building `insomnia-inso` (as expected) 😄  but is not linking or referencing `insomnia-testing` at all 😭 . I keep highlighting it references the npm general public copy (on the npm registry) rather than the local copy. (Correct me if wrong)

Thanks for reading!

2021-03-11 00:55 UTC, develohpanda commented
It looks like `mochawesome` is a reporter instead of a runner, so there isn't direct comparison between that and inso/insomnia-testing.

Also, peer dependencies are not automatically installed, and expecting users to install inso and mocha separately, globally, is not a desirable solution at the moment (last option), so this will need some more exploration unfortunately.

Lerna _does_ link them, but it doesn't alter the `package.json` so you won't see it there. As long as you run `npm run bootstrap` from the root of the repository, it will link dependencies correctly and not use the npm general copy for dependencies it can find in the monorepo.

2021-03-11 02:57 UTC, develohpanda commented
After playing around with this approach locally, it seems non-trivial and might need some webpack magic to handle it... so, careful how deep into the abyss you explore for now @MrSnix 😅

2021-03-18 06:20 UTC, develohpanda requested changes
Nice work 🎉

2021-03-18 06:20 UTC, develohpanda commented on packages/insomnia-inso/package.json
> +    "commander": "^6.1.0",
Is a major upgrade required for the contents of this PR? Ideally we should decouple this and do it separately, but if it is strictly needed we can keep it here.

2021-03-18 06:20 UTC, develohpanda commented on packages/insomnia-inso/src/cli.js
> +      `standard reporters options are [${reporterTypes}] (default: ${defaultReporter})`,
Let's change this and work with the Mocha example:

```suggestion
      `specify reporter to use (default: ${defaultReporter})`,
```

2021-03-18 06:20 UTC, develohpanda commented on packages/insomnia-inso/src/commands/run-tests.js
> +    ? await runTestsCli(testFiles, config)?.catch(e => isReporterFailure(reporter, e.toString()))
This line has a mixture of `async-await`, `promise.catch` and null-coallescing inside a ternary.

There is a lot going on and in cases like these it's generally good to favor being verbose for the sake of clarity, so lets expand this to an `if-else` statement, and use a `try-catch` so the data flow is clearer at a glance. 🙂

2021-03-18 06:20 UTC, develohpanda commented on packages/insomnia-testing/src/run/index.js
> +}
This seems like it's extracting CLI arguments for use by Mocha. But `insomnia-testing` doesn't inherently know that it is being used via the CLI, so from my understanding this logic actually belongs in `insomnia-inso`.

`insomnia-testing` shouldn't need to manipulate the reporter options before sending them to mocha.

Am I missing some context here? If so, please let me know 🙂

In any case, whether this belongs in `insomnia-testing` or `insomnia-inso` it's a perfect candidate for input/output unit tests so I'd love to see some added please!

2021-03-18 06:20 UTC, develohpanda commented on packages/insomnia-testing/src/run/index.js
>    reporter?: Reporter,
I believe this should now be typed as `string | Function`?

2021-03-18 06:20 UTC, develohpanda commented on packages/insomnia-inso/src/commands/run-tests.js
> +  const testFiles = await getTestFileContent(db, suites);
This actually generates a single test file

```suggestion
  const testFile = await getTestFile(db, suites);
```

2021-03-18 06:20 UTC, develohpanda commented on packages/insomnia-inso/src/commands/run-tests.js
> +  const environment = await getEnvironments(db, ci, suites, env);
```suggestion
  const environment = await findEnvironment(db, ci, suites, env);
```

2021-03-18 06:20 UTC, develohpanda commented on packages/insomnia-inso/src/commands/run-tests.js
> +  return reporter && !TestReporterEnum[reporter];
Because mocha supports [these reporters](https://github.com/mochajs/mocha/blob/master/lib/reporters/index.js) internally, `TestReporterEnum` needs to be updated so that this check (`isExternalReporter`) works as expected.

2021-03-18 06:20 UTC, develohpanda commented on packages/insomnia-inso/src/commands/run-tests.js
> +    logger.fatal(`The following reporter \`${reporter}\` was not found!`);
```suggestion
    logger.fatal(`Reporter "${reporter}" not found: ${err}`);
```

2021-03-18 06:20 UTC, develohpanda commented on packages/insomnia-inso/src/commands/run-tests.js
> +    logger.fatal(`An unknown error occurred: ${err}`);
Because this is a complete failure we don't necessarily need to prefix it with anything.

https://github.com/Kong/insomnia/blob/eff9cda1b2862863de0ce832dee48b00e454bcea/packages/insomnia-inso/src/commands/lint-specification.js#L43

```suggestion
    logger.fatal(err);
```

2021-03-18 06:20 UTC, develohpanda commented on packages/insomnia-inso/src/commands/run-tests.js
>    reporter: $Keys<typeof TestReporterEnum>,
I believe this should be typed as string now

```suggestion
  reporter: string,
```

2021-03-18 06:20 UTC, develohpanda commented on packages/insomnia-inso/src/commands/run-tests.js
>  // @flow
Could you please add tests for this file to ensure the options behave correctly? They belong here: https://github.com/Kong/insomnia/blob/eff9cda1b2862863de0ce832dee48b00e454bcea/packages/insomnia-inso/src/__tests__/cli.test.js#L152-L192

2021-03-18 10:51 UTC, MrSnix commented on packages/insomnia-inso/package.json
> +    "commander": "^6.1.0",
Yes, because it supports variable arguments (varargs) natively (I use them to retrieve `reporter-options`).
I **checked their changelog** while upgrading from 5.1 to 6.1 , there were **only two breaking changes** but I didn't find any code related to them in our codebase:

> Breaking - the options property has the same case as a flag. e.g. flag -n accessed as opts().n (previously uppercase)

> Breaking - throw an error if there might be a clash between an option name and a Command property, with advice on how to resolve 

[Changelog](https://github.com/tj/commander.js/blob/master/CHANGELOG.md)

2021-03-18 17:48 UTC, MrSnix commented on packages/insomnia-inso/src/cli.js
> +      `standard reporters options are [${reporterTypes}] (default: ${defaultReporter})`,
Changed

2021-03-18 18:34 UTC, MrSnix commented on packages/insomnia-inso/src/commands/run-tests.js
> +    logger.fatal(`The following reporter \`${reporter}\` was not found!`);
Are you sure you want to print the stack-trace (err) even if it is a simple not found exception?

2021-03-30 08:21 UTC, MrSnix commented on packages/insomnia-inso/src/commands/run-tests.js
> +    // Assign
While I was building this function, I realized that `commander.js` treats everything as a string and doesn't do any kind of parsing on the values. 
So for example:`inso run test -r some-reporter -ro booleanKey=true` is translated as `{ booleanKey: "true" }` rather then `{ booleanKey: true }`. **I don't know** what should be the desired behaviour. I quickly looked up on some runners and I saw the options are expressed as a string and boolean mainly, so I supposed that a minimal parsing on common values like 'booleans' should be done... What do you think?

2021-04-28 06:58 UTC, develohpanda requested changes
I can't seem to get my reporter options to flow through to the external reporter. Here are my steps, after checking out this branch:

```
npm run bootstrap
cd packages/insomnia-inso
npm pack
npm install -g <package>.tgz mocha@8 mochawesome
cd src/db/__fixtures__/git-repo
inso run test --reporter mochawesome --reporterOptions reportFilename=abcd json=false --env env_env_ca046a uts_fe901c
```

![image](https://user-images.githubusercontent.com/4312346/116358666-00415b80-a852-11eb-8930-b184c3a0a00d.png)

As you can see in the command, I specify that the `reportFilename` should be `abcd` and to not output a JSON report, but it appears neither of those options were followed.

Does this work for you? If so, could you show me what you've done to make this work, using the `reporter` and `reporterOptions` I'm using above?

2021-04-28 06:58 UTC, develohpanda commented on packages/insomnia-inso/src/commands/__tests__/run-tests.test.js
> +  it('should return true if reporter options are decoded properly', async () => {
Nice test!

2021-04-28 06:58 UTC, develohpanda commented on packages/insomnia-inso/src/commands/__tests__/run-tests.test.js
> +      testFilter: undefined,
Seems redundant

```suggestion
```

2021-04-28 06:58 UTC, develohpanda commented on packages/insomnia-inso/src/commands/run-tests.js
> +  const db = await loadDb(options);
Unfortunately this line change results in Flow type errors, and it should return to the previous implementation where the options object is constructed specifically for `loadDb` as `{ workingDir, appDataDir }`.

2021-04-28 06:58 UTC, develohpanda commented on packages/insomnia-inso/src/commands/run-tests.js
> +    // Assign
Given Mocha doesn't parse them I would lean towards not parsing them as well, but I would be able to give a better answer after testing the behavior, which I wasn't able to get working

2021-04-28 06:58 UTC, develohpanda commented on packages/insomnia-inso/src/commands/run-tests.js
> +function getReporterOptions(data: Array<string> = []): Object {
This looks fairly generic (and useful), might be good to move to https://github.com/Kong/insomnia/blob/develop/packages/insomnia-inso/src/util.js and add tests accordingly

2021-06-09 20:45 UTC, MrSnix commented
Hi @develohpanda, I introduced the typescript support on this PR too. 
I even addressed your requests in the last commit. As always, I'm open to any feedback.

**The local copy**:
This time I was able to make it work simply using Lerna itself... I don't know if you upgraded the dependencies and eventually the bug got fixed but this is what I did and it worked:

```
1. npm run clean
2. npm run bootstrap
3. node insomnia-inso/bin/inso run test 
    --appDataDir "/.../Application Support/Insomnia" 
    -r .../node/v12.18.3/lib/node_modules/mocha-simple-html-reporter 
    -ro output=/Users/xyz/Desktop/out.html
 
✔ Select a document or unit test suite · Swagger Petstore 1.0.2 - spc_f93e89
✔ Select an environment · OpenAPI env - env_env_59a715
The report is written in "/Users/xyz/Desktop/out.html" file.

Process finished with exit code 0
```

Proof: 
![image](https://user-images.githubusercontent.com/20780192/121419564-613d7280-c96c-11eb-8719-0d2eae84a80c.png)

*Note*: 
I'm using absolute paths because I have multiple node versions and I'm running the dev version.

2022-02-09 22:30 UTC, develohpanda commented
Some of the difficulties in this PR related to both inso and the custom reporter being installed from npm into the same directory, and inso not being able to see/access it.

We might be able to explore a different route or solution, now that we ship a single executable for inso and inso can be decoupled from npm.

2022-03-15 17:00 UTC, closed without merging