Update onboarding flow
getinsomnia/insomnia pull request #3101
Opened 2021-02-22 05:02 UTC by develohpanda

2021-02-22 05:14 UTC, develohpanda commented on packages/insomnia-app/app/models/settings.js
> +    hasPromptedOnboarding: false,
How can we better initialize this value? It should be false if this is a fresh install of Insomnia v20201.1, or it should be true if this is an update.

2021-02-22 05:14 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-onboarding.js
> +    // TODO: this is going to blow away migrated data, needs to be smarter about forcing to current workspace
❗ This is a blocker

2021-02-22 05:14 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-onboarding.js
> +        // TODO: this is going to blow away migrated data, needs to be smarter about forcing to current workspace
❗ This is a blocker

2021-02-22 05:14 UTC, develohpanda commented on packages/insomnia-app/app/ui/redux/modules/global.js
> +function _getNextActivity(settings: Settings, currentActivity: GlobalActivity): GlobalActivity {
Many changes in this file; the main entry points are:
- `goToNextActivity()` used by sequential flows (like migration, onboarding, home) to automatically go to the "next" activity, depending on different conditions
- `setActiveActivity(activity)` used by any explicit navigation, for example the tab switcher
- `initActiveActivity()` as the name suggests, used for initialization of this redux module to ensure we launch with the expected activity

2021-02-22 09:19 UTC, develohpanda commented on packages/insomnia-smoke-test/core/migration.test.js
> +  it('can skip migration and proceed onboarding', async () => {
Local macOS runs
![Screen Shot 2021-02-22 at 8 23 36 PM](https://user-images.githubusercontent.com/4312346/108687755-f81c2580-755b-11eb-908d-b9d6760b3e36.png)

2021-02-22 09:19 UTC, develohpanda commented on packages/insomnia-smoke-test/core/migration.test.js
> +  it('can migrate and proceed onboarding', async () => {
Local macOS runs
<img width="368" alt="Screen Shot 2021-02-22 at 9 56 52 PM" src="https://user-images.githubusercontent.com/4312346/108687846-12ee9a00-755c-11eb-816a-b791eb343019.png">

2021-02-22 22:10 UTC, develohpanda commented on packages/insomnia-app/app/models/settings.js
> +    hasPromptedOnboarding: false,
Are we able to use notification local storage keys to initialize this value? Doesn't feel very reliable. Might need to build something in to indicate install vs update 🤔

2021-02-23 01:29 UTC, develohpanda commented on packages/insomnia-app/app/ui/containers/app.js
> +  async _handleDbChange(changes) {
Extracted from inline-arrow function so that the listener can be removed on unmount

2021-02-23 01:29 UTC, develohpanda commented on packages/insomnia-app/app/ui/redux/modules/__tests__/global.test.js
> +describe('global', () => {
![image](https://user-images.githubusercontent.com/4312346/108791244-7c65bb80-75e3-11eb-80e5-4e88751f9efe.png)

2021-02-23 04:25 UTC, develohpanda commented on packages/insomnia-app/app/ui/css/components/onboarding.less
> +      overflow: auto;
It works but this is a fairly basic solution to prevent page overflow when the window height is small and the user clicks "advanced options" on the migration page.

2021-02-23 08:44 UTC, DMarby commented on packages/insomnia-app/app/models/settings.js
> +    hasPromptedOnboarding: false,
We have some logic in main.js for detecting whether an update happened or not, to decide whether to show the update notification, perhaps we could initialize this value there?

https://github.com/Kong/insomnia/blob/958ba792560dd7ef68f26206e9bef5663cf4b7ae/packages/insomnia-app/app/main.development.js#L151

2021-02-23 09:06 UTC, develohpanda commented on packages/insomnia-app/app/models/settings.js
> +    hasPromptedOnboarding: false,
Epic!! I should be able to use an approach inspired by this. Thank you!

2021-02-23 22:38 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-onboarding.js
> +    // TODO: this is going to blow away migrated data, needs to be smarter about forcing to current workspace
After discussion, during onboarding, we don't need to force import into the current workspace. If anything, we should force import into a new workspace, so as to not clutter anything existing.

This cluttering issue is more prevalent now that we have a potential migration step _prior_ to onboarding which could import x number of workspaces.

2021-02-23 22:40 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-onboarding.js
> +        // TODO: this is going to blow away migrated data, needs to be smarter about forcing to current workspace
Same as https://github.com/Kong/insomnia/pull/3101/files#r581441418

2021-02-24 04:01 UTC, develohpanda commented on packages/insomnia-app/app/models/settings.js
> +export async function getOrCreate(): Promise<Settings> {
`getOrCreate()` shouldn't take a `patch` parameter (like the previous implementation) because it is ignored if a model has already been created. This is quite misleading and can cause issues. Luckily, there were no usages (outside of unit tests) of `getOrCreate(patch)` so we can safely remove the parameter.

2021-02-24 21:26 UTC, DMarby approved these changes
Tested a bunch of the different scenarios, seems to work great!
Found one potential issue, but not sure if it needs to be addressed or not.

2021-02-24 21:26 UTC, DMarby commented on packages/insomnia-app/app/ui/redux/modules/global.js
> +      default:
It is possible to get stuck in the onboarding flow if `hasPromptedOnboarding` is true, but the localStorage activity key is not set (thus rendering the onboarding flow due to the == null condition in `wrapper.js`, can be reproduced by deleting the localstorage key and restarting the app), since that we the current activity is null, causing _getNextActivity to always return null, not sure if that needs to be addressed?

2021-02-24 23:37 UTC, develohpanda commented on packages/insomnia-app/app/ui/redux/modules/global.js
> +      default:
Nice catch! I raised a separate PR to handle invalid values at #3116

2021-02-25 01:30 UTC, nijikokun commented on packages/insomnia-app/app/ui/components/settings/general.js
>                  'Has prompted to migrate',
```suggestion
                'Has been prompted to migrate from Insomnia Designer',
```

2021-02-25 01:31 UTC, nijikokun commented on packages/insomnia-app/app/ui/components/settings/general.js
> +              {this.renderBooleanSetting('Has prompted Onboarding', 'hasPromptedOnboarding')}
```suggestion
              {this.renderBooleanSetting('Has seen onboarding experience', 'hasPromptedOnboarding')}
```

2021-02-25 01:33 UTC, nijikokun requested changes

2021-02-25 01:33 UTC, nijikokun commented on packages/insomnia-app/app/ui/components/settings/general.js
>                {this.renderBooleanSetting(
Let's make each flag an individual row.

2021-02-25 01:34 UTC, nijikokun commented on packages/insomnia-app/app/ui/components/settings/general.js
> +        </div>
Can we make the button `inline-block` rather than `full-width`?

2021-02-25 01:35 UTC, nijikokun commented on packages/insomnia-app/app/ui/components/wrapper-onboarding.js
> +        handleImportUri(value, ForceToWorkspaceKeys.new);
🙌

2021-02-25 01:37 UTC, nijikokun commented on packages/insomnia-app/app/ui/redux/modules/global.js
> +      // Have we the onboarding step? Go to home, otherwise go to onboarding
```suggestion
      // Have we shown the onboarding step? Go to home, otherwise go to onboarding
```

2021-02-25 01:55 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/general.js
>                {this.renderBooleanSetting(
<img width="636" alt="image" src="https://user-images.githubusercontent.com/4312346/109091350-7acdfc00-7779-11eb-82d3-65e0555a1d9d.png">

2021-02-25 01:59 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/general.js
> +        </div>
Looks a little strange that way as well.

![image](https://user-images.githubusercontent.com/4312346/109091437-a94bd700-7779-11eb-8945-e95590f20f12.png)

We could also move it under the data tab as a single button that says "Migrate from Designer".

![image](https://user-images.githubusercontent.com/4312346/109091557-e57f3780-7779-11eb-9b1c-4d678e4c7b97.png)

@nijikokun / @erickrico let me know where you'd like this to move to :)

2021-02-25 02:15 UTC, develohpanda commented
Updated screenshot 
<img width="902" alt="image" src="https://user-images.githubusercontent.com/4312346/109092884-4445b080-777c-11eb-907a-66465deeb4da.png">

2021-02-25 10:24 UTC, DMarby approved these changes

2021-02-25 20:10 UTC, nijikokun approved these changes

2021-02-25 20:13 UTC, merged