Add option to disable migrating workspaces
getinsomnia/insomnia pull request #3108
Opened 2021-02-23 06:04 UTC by develohpanda

As per the description in INS-469

This PR slightly changes the option order and sets all migration options to false by default

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/4312346/108807620-bf3a8a00-7609-11eb-8f48-25a0be0c19e6.png">

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/4312346/108807705-ec873800-7609-11eb-8d77-e8b9704e5ac3.png">

2021-02-23 13:36 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/wrapper-migration.js
> +          label="Copy all workspaces"
```suggestion
          label="Copy All Workspaces"
```

2021-02-23 13:36 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/wrapper-migration.js
> +          label="Copy Designer application settings"
```suggestion
          label="Copy Designer Application Settings"
```

2021-02-23 13:36 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/wrapper-migration.js
> +          label="Copy all plugins"
```suggestion
          label="Copy All Plugins"
```

2021-02-23 14:14 UTC, dimitropoulos requested changes
the acceptance criteria states:
> (and a tooltip to explain that "this means everything")

But I didn't see that anywhere.

2021-02-24 00:40 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-migration.js
> +          label="Copy Designer application settings"
I intentionally set them to lowercase but am not fussed either way 😄

2021-02-24 14:44 UTC, dimitropoulos approved these changes
noice.

2021-02-24 22:08 UTC, DMarby approved these changes

2021-02-25 21:04 UTC, develohpanda commented
Smoke test failed as expected because after this PR the migration button is disabled by default 🤩

2021-02-25 23:01 UTC, merged