Differential (Additive/Removal) patching when switching between design / debug
getinsomnia/insomnia pull request #3124
Opened 2021-02-26 11:54 UTC by apisaint

😩 Finally got tired of dealing with it so I tried fixing it.

This patch adds differential patching for imports that occur during the switching between design and debug tabs inside of Designer. As reported through #2971, and others, this patch favors existing data over imported data, values that exist already on the document will remain unchanged, only new values (including array based values) will be added / removed.

This also includes a bypass feature for urls, currently these options are not exposed through the interface but could be. This feature is an object to allow for future properties for preference-based patching.

👇 Included:

- Adds `options.enableDiffBasedPatching` and `options.enableDiffDeep` to `importRaw` for backwards compat.
- Adds `options.bypassDiffProps.url` for url bypassing and use an object for future items.
- Adds `diffPatchObj` based on differential patching for objects (works with arrays as well).

💭 Future ideas:

- `hasBeenModifiedByUser` property map object to allow changing properties that haven't been touched by the user with options.

⚠️ Notes:

Basically this makes changes additive, which is better than the current scenario especially when paired with #2979, what does that imply? See below.

- When the `url` changes for a Request, it does not change the `name`, so the sidebar does not auto-update. This can be resolved in a future update with future ideas point one.
- When items / values inside of the Headers change it does not auto-update, this would require either a bypass option, or rely on the future idea.

Closes #2971, #2882, #3038, #2442

2021-02-26 16:29 UTC, reynolek commented
We have this on our list of issues to tackle, thanks for taking the time to look into it! Going to add @nijikokun to review it from a product perspective along with @develohpanda and @dimitropoulos for code.

2021-02-26 19:35 UTC, nijikokun requested changes

2021-02-26 19:35 UTC, nijikokun commented on packages/insomnia-app/app/common/import.js
> +      if (options.enableDiffBasedPatching) {
`options` isn't checked for existence so this will fail with other import methods.

2021-02-26 19:55 UTC, nijikokun commented
Oh wow. Taking a look now  👀 

> * backwards compat.

Beautiful 🙌 

> This also allows endpoints to stay in position when moved or grouped in folders.

Absolutely amazing 🎉 

> * it will update the url in the url bar but it does not change the `name`, so the sidebar will not auto-update. This can be resolved in a future or with a modified check for the name using the future idea explained above.

While we do have `modified` you're right we don't have something that tells us whether it's been modified by the user or through creation, at least to my knowledge, so I agree this can be a future improvement. 👍 

> * Notice icon when clicked displays dialogue with changes that a user can choose to apply. Underlying diff method can be augmented to create such patch objects or use a lib.

Love this idea 💯, maybe this could also be expanded to sync at some point 🤔

> * `hasBeenModifiedByUser` property map object to allow changing properties that haven't been touched by the user with options.

Makes sense, track properties that change, and update the ones that haven't, seems like a good future improvement.  💯 

> * Adds `options.bypassDiffProps.url` for url bypassing and use an object for future items.

👍 

---

Amazing, love the breakdown. Found an issue in the code, but other than that it's definitely an improvement over the current situation and I'll take it.

2021-02-26 20:10 UTC, apisaint commented on packages/insomnia-app/app/common/import.js
> +      if (options.enableDiffBasedPatching) {
Good catch, instead of worrying about existence decided to default the argument to an object and let type checking do the worrying about input for us.

2021-02-26 20:11 UTC, nijikokun approved these changes

2021-03-03 16:40 UTC, dimitropoulos approved these changes

2021-03-03 16:47 UTC, dimitropoulos commented
(working on making sure I correctly resolve the merge conflict of the prior commit on master then this is next up to be merged)

2021-03-03 17:57 UTC, merged