Migration flow stylistic updates
getinsomnia/insomnia pull request #3132
Opened 2021-03-01 17:37 UTC by sonicyeti

This PR covers a handful of stylistic updates to the designer to core migration UI. 

- Header & sub-header are styled consistently with on-boarding
- Styled deader & sub-header used for primary verbiage, reducing redundancy
- Theme support updates

Fixes INS-494

Examples in various themes:

![Screen Shot 2021-03-01 at 11 47 19 AM](https://user-images.githubusercontent.com/52717970/109535353-790e7c00-7a8a-11eb-853a-255f48b9b8f0.png)

![Screen Shot 2021-03-01 at 11 47 02 AM](https://user-images.githubusercontent.com/52717970/109535364-7c096c80-7a8a-11eb-90de-68773cb25d88.png)

![Screen Shot 2021-03-01 at 11 47 56 AM](https://user-images.githubusercontent.com/52717970/109535305-698f3300-7a8a-11eb-95f2-29808d8dc554.png)

![Screen Shot 2021-03-01 at 11 48 52 AM](https://user-images.githubusercontent.com/52717970/109535296-64ca7f00-7a8a-11eb-8551-02262410649f.png)

2021-03-01 17:56 UTC, nijikokun approved these changes
Styling approved. 💅 Beautiful

2021-03-01 20:19 UTC, DMarby approved these changes

2021-03-02 01:23 UTC, develohpanda requested changes

2021-03-02 01:23 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-onboarding.js
> +        header={getAppLongName()}
Should this be `Welcome to {getAppLongName()}`?

2021-03-02 01:23 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-onboarding.js
>  import { showPrompt } from './modals';
It would be nice to update the buttons in this file to stylistically match the migration buttons

<img width="376" alt="Screen Shot 2021-03-02 at 2 22 19 PM" src="https://user-images.githubusercontent.com/4312346/109582285-c4945900-7b62-11eb-9ac4-176e28f037eb.png">
<img width="372" alt="Screen Shot 2021-03-02 at 2 22 23 PM" src="https://user-images.githubusercontent.com/4312346/109582296-c65e1c80-7b62-11eb-8a1a-e04507b6cc16.png">

2021-03-02 01:38 UTC, sonicyeti commented on packages/insomnia-app/app/ui/components/wrapper-onboarding.js
>  import { showPrompt } from './modals';
@nijikokun @erickrico Thoughts on the above? If yes, which of these buttons should be treated as primary where they have the solid BGs w/ white text.

2021-03-02 21:31 UTC, erickrico commented on packages/insomnia-app/app/ui/components/wrapper-onboarding.js
>  import { showPrompt } from './modals';
got it, if there is only one button "share usage analytics" lets make it primary, if there are 2 i think the secondary treatment is ok

2021-03-02 21:36 UTC, nijikokun commented on packages/insomnia-app/app/ui/components/wrapper-onboarding.js
>  import { showPrompt } from './modals';
Agree with @erickrico

2021-03-02 21:52 UTC, sonicyeti commented on packages/insomnia-app/app/ui/components/wrapper-onboarding.js
>  import { showPrompt } from './modals';
Ok all set, screenshot: 

![Screen Shot 2021-03-02 at 4 51 56 PM](https://user-images.githubusercontent.com/52717970/109720088-9f5e1580-7b77-11eb-8798-3bbbb6d128c8.png)

2021-03-03 02:43 UTC, develohpanda approved these changes

2021-03-03 02:43 UTC, merged