Designer workspace scope
getinsomnia/insomnia pull request #3194
Opened 2021-03-15 16:21 UTC by sonicyeti

This PR covers the shift away from "designer" as a workspace scope name in favor of "design".
• Existing workspaces
• Imported workspaces from (legacy core & designer)
• Updated for export (from insomnia)

Fixes INS-533

2021-03-15 20:19 UTC, develohpanda requested changes
Since there are changes directly related to it, it would be good to convert the hard-coded instances of `design` which you have found, to use the flow enum `WorkspaceScopeKeys.design`. It'll save us from having to work through the code-base again looking for things to replace. Whether you want to include that in this PR or raise a subsequent one is up to you, although I encourage doing it in this PR.

Other than that the changes look good, just found a couple of minor things that need cleanup

2021-03-15 20:19 UTC, develohpanda commented on packages/insomnia-app/app/common/migrate-from-designer.js
>        // For each workspace coming from Designer, mark workspace.scope as 'designer'
Need to update the comment here as well
```suggestion
      // For each workspace coming from Designer, mark workspace.scope as 'design'
```

2021-03-15 20:19 UTC, develohpanda commented on packages/insomnia-app/app/models/workspace.js
>      workspace.scope === WorkspaceScopeKeys.designer ||
This first line needs to be removed - `WorkspaceScopeKeys.designer` no longer exists. TS will save us here in the future.

2021-03-15 20:19 UTC, develohpanda commented on packages/insomnia-app/app/models/workspace.js
> +  type OldScopeTypes = 'spec' | 'debug' | 'designer' | null;
👍🏽

2021-03-16 13:28 UTC, DMarby approved these changes

2021-03-16 14:56 UTC, DMarby approved these changes

2021-03-16 23:27 UTC, develohpanda approved these changes

2021-03-16 23:28 UTC, merged