Finish line on PR#1804
getinsomnia/insomnia pull request #3203
Opened 2021-03-18 02:26 UTC by coolhome

Fixed unit tests & upgraded win-ca.

Tested using `start` and a `package` build. Works great!

2021-03-18 02:38 UTC, develohpanda commented
Okay wow this is awesome! You got it working 🤯

Lets change the base of this PR to be `kong:develop`, and I can close #2020 and just bring any items from the description across to this PR. This way it'll attribute your contribution properly; my initial plan was to change the author details after merging 😅

We'll have to run this through some QA but I can raise it with the team tomorrow about producing an alpha build. IIRC there were some comments in one of the original issues offering to QA as well! 🎉

2021-03-18 02:43 UTC, develohpanda commented on packages/insomnia-app/package.json
> +    "test:jest": "cross-env NODE_ENV=test npx jest --silent",
This is an issue with lerna I believe. A common version of jest does exist at the root but that means this script has to be executed through lerna for it to work properly.

I think for the time being omitting `npx` _should_ work in CI (which runs tests through lerna)

2021-03-18 03:34 UTC, develohpanda commented
Interesting, I think netlify is failing and the checks aren't running because of the conflicts or not being up to date with `kong:develop`. Let me know if you need a hand with those, I incorrectly assumed [`fa47722` (#3203)](https://github.com/Kong/insomnia/pull/3203/commits/fa47722bfd0d4e499341cbcbf2c4700c4721d3c1) was resolving it.

`settings.js` and `network.js` should be fairly straightforward. The two `electronbuilder.*.json` files have been merged into a single one now, just called `electronbuilder.json` so that should be straightforward as well.

2021-03-18 23:13 UTC, coolhome commented
I had some conflicts and I must of did something wrong because my branch was not building after kong upstream merge. Thanks for the help @develohpanda! 🎉

It's a bit too early to use it but it is exciting! I just found out about an experimental feature `CURLSSLOPT_NATIVE_CA` added to libcurl 7.71.0 when compiled correctly will pull from windows cert store. I imagine this would be more desirable than `win-ca` with an executable in the long run.

ref: https://curl.se/libcurl/c/CURLOPT_SSL_OPTIONS.html

https://github.com/curl/curl/blob/b7e01382d65b4ba6b5b14b24e6ba4319fd9abe20/lib/vtls/openssl.c#L2859-L2863

2021-03-19 03:02 UTC, develohpanda commented
No worries mate! We've got this (and a few more SSL related items) on our roadmap so it's awesome to see movement on it 😄 I'll defer to @DMarby about the desirable approach as he has some more context in this area, but I'm here to help get this PR through 🙌🏽

2021-03-19 14:59 UTC, DMarby requested changes
Hi @coolhome, thank you so much for your work on this, this is awesome!

This looks very close to being ready to merge to me, there is one change that I'd like to request however, and that is making a custom bundle, or pulling certificates from the windows store additive to the default certificate bundle, rather then a replacement, meaning that:
- We always use the certs from the built-in certificate bundle (we recently made this be used for all platforms, instead of macOS being specialcased https://github.com/Kong/insomnia/pull/3030)
- If a custom trust store file is defined in settings, the certificates from it are also fetched and included
- If the windows certificates store fetching is enabled, certificates from it are also fetched and included
- The final result is written to disk and passed to curl as Curl.option.CAINFO.

The reasoning for this is two-fold:
1. Most frequently, you'll want to be able to make requests to both endpoints using regular certificates with roots found in the bundled trust store, as well as your own internal/self-signed ones. It would be inconvenient for users not using the windows trust store to need to provide their own full copy of the bundled trust store that also has their internal certs added to it, instead of just providing one containing their own internal certs.
2. The windows trust store lazy-loads certificates on use, so by only using it as the entire trust store, while all your user provided (manually, via GPO, etc) certificates will work, you are likely going to run into issues accessing other endpoints, which will only get resolved if you visit them in a browser. If we make it additive, this issue goes away.

2021-03-19 14:59 UTC, DMarby commented on packages/insomnia-app/app/network/network.js
> +import winCa from 'win-ca';
We should import `win-ca/api` here instead to avoid the import side-effects (overwriting the node trust store) that `win-ca` does by default:
```suggestion
import winCa from 'win-ca/api';
```

I think we might also need to add `win-ca/api` to `externals` in the insomnia-app and possibly insomnia-inso webpack configuration for this to work.

2022-10-18 06:19 UTC, abaumg commented
Any updates on this PR?

2022-12-08 16:19 UTC, jackkav commented
Closing in favour of: #5498

2022-12-08 16:19 UTC, closed without merging