Expose identity token for oauth2
getinsomnia/insomnia pull request #3211
Opened 2021-03-19 11:14 UTC by sayoojs

Closes #1423 

Exposed identity token in the UI for all grant types in Oauth2.
![image](https://user-images.githubusercontent.com/64190577/111771432-b28c1780-88d1-11eb-8038-40272338dddb.png)

Shows both identity token and refresh token in the Ctrl+Space autocomplete list for ease of use.
![image](https://user-images.githubusercontent.com/64190577/111771747-11ea2780-88d2-11eb-9818-1032a0f46dd6.png)

Made sure to handle populating identity token on clicking the `Refresh Token` button.

2021-03-22 04:58 UTC, develohpanda requested changes
Generally looks good but a couple of changes to make here 😄 

I am also not set up to be able to QA this, if you could outline some of your QA steps to show this works and fails correctly that would be very much appreciated.

2021-03-22 04:58 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/auth/o-auth-2-auth.js
> +                onChange={this._handleUpdateAccessToken}
Seems like this should have it's own `this._handleUpdateIdentityToken` handler.

![2021-03-22 17 56 27](https://user-images.githubusercontent.com/4312346/111945737-16ffde80-8b3f-11eb-83e3-3a3acf287dd7.gif)

2021-03-22 04:58 UTC, develohpanda commented on plugins/insomnia-plugin-request/index.js
> +            value: 'oauth2-access',
Ideally changing value is the right thing to do but changing this value is a breaking change.

On the current release, the tag `{% request 'oauth2', '', 0 %}` resolves correctly but on this branch it renders as
<img width="118" alt="image" src="https://user-images.githubusercontent.com/4312346/111941940-19f6d100-8b37-11eb-9eaf-e457ce650642.png"> and clicking on the tag it shows as 
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/4312346/111941965-2e3ace00-8b37-11eb-9cca-8ac6d6f89e58.png">

The new values you have added below for identity and refresh are all good, but let's keep the access token `value` as it is (`oauth2`) and only change the display name, and add a comment to explain why. How does that sound?

2021-03-22 06:02 UTC, sayoojs commented on packages/insomnia-app/app/ui/components/editors/auth/o-auth-2-auth.js
> +                onChange={this._handleUpdateAccessToken}
Yes, will add an input handling function for the identity field. Missed that on first pass.

2021-03-22 06:03 UTC, sayoojs commented on plugins/insomnia-plugin-request/index.js
> +            value: 'oauth2-access',
Got it! Reverted access token tag value back to `oauth`. Left a comment to address the inconsistency.

2021-03-22 06:20 UTC, sayoojs commented
@develohpanda The QA I've done so far is 

- With 'Grant Type' as `Authorization Code`, tried querying an endpoint protected by AWS Cognito user pools which uses the identityToken as Bearer. Successfully retrieved a 200.
- In cases where there is no `identityToken` returned by the auth provider, the input field will show `n/a`, and 'No token' message is shown on auto complete(Ctrl+Space).
- - In case of either an empty string value or a null. Checked if the 'No token' message showed up on the autocomplete tag's edit screen. 
- Have **NOT** tested any of the other grant types due to not having any existing environments which uses those authentication grant methods at hand. **This is a concern**. 

![image](https://user-images.githubusercontent.com/64190577/111947588-cf0f9600-8b03-11eb-9fa5-8e2487122911.png)
![image](https://user-images.githubusercontent.com/64190577/111947602-d46ce080-8b03-11eb-9b12-58e76ee859f8.png)

I've also made the requested changes and pushed the commit, but since I forked, Vercel, is asking for authentication.

2021-03-22 06:52 UTC, develohpanda approved these changes
Thanks for the quick turnaround and your notes! 🙌🏽

I am happy with the code and usability though I'm not sure about the expectation for token expiry (should it be the same as the access token?). We may also need to explore how to QA this, maybe allowing users from the parent issue to QA a beta build.

@DMarby may have some thoughts on QA as well.

2021-03-22 06:52 UTC, develohpanda commented on plugins/insomnia-plugin-request/index.js
> +            /*
👍🏽

2021-03-26 11:00 UTC, sayoojs commented
Hi @develohpanda 

I've pushed another commit which addresses handling the Identity Token expiry separately. 
What I've done is decode the `identityToken` JWT to fetch the `exp` and render the expiry from that value.
So on the off chance the expiry for the identity token is different from that of the access token, it should render differently.

Also, any updates on including this in a beta build?

Thanks in advance! :smiley:

2021-03-26 11:21 UTC, develohpanda commented
Awesome! I will review again, and I'll raise it with the team next week to make sure we get some more reviews on this PR and figure out a way forward. 🤗

2021-03-30 09:54 UTC, develohpanda approved these changes
Nice 🎉

2021-03-30 09:54 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/auth/o-auth-2-auth.js
> +    const expDigitCount = exp.toString().length;
Looks like it's using [`moment`](https://momentjs.com/docs/#/parsing/unix-timestamp-milliseconds/) to create the timestamp.

What does the expiry extracted from the token look like/represent? Feels like the padding or removing of digits could cause some strange behavior 🤔

2021-03-30 23:21 UTC, develohpanda requested changes
There is a bug here such that `window.atob()` fails fatally if the identity token is not a valid string (if you just type anything into the field). The field has a requirement to be encoded in a particular way from what I can see, which is fine, but there shouldn't be a UI failure if it's _not_ encoded as expected. 🤔 

<img width="1455" alt="image" src="https://user-images.githubusercontent.com/4312346/113068717-5dc69600-921b-11eb-8cd8-5e7acd8c3bb1.png">

Another bug in comments below. Once these are fixed up I can trigger an alpha build, or you can bundle it locally for your OS by running `npm run app-package:smoke` and fetching artefacts from the `packages/insomnia-app/dist` folder.

2021-03-30 23:21 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/auth/o-auth-2-auth.js
> +    const base64Url = token.split('.')[1];
I just pulled this down locally to test and the Oauth2 tab fails to render for a brand new request as a result of this implementation. The following suggestion matches how `renderExpireAt` is written

```suggestion
  static renderExpiryFromJWT(token: ?OAuth2Token): React.Element<*> | string | null {
    if (!token || !token.identitiyToken) {
      return null;
    }

    const base64Url = token.identitiyToken.split('.')[1];
```

2021-03-30 23:21 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/auth/o-auth-2-auth.js
> +    const identityExpireLabel = OAuth2Auth.renderExpiryFromJWT(tok.identityToken);
```suggestion
    const identityExpireLabel = OAuth2Auth.renderExpiryFromJWT(tok);
```

2021-03-31 14:55 UTC, sayoojs commented on packages/insomnia-app/app/ui/components/editors/auth/o-auth-2-auth.js
> +    const base64Url = token.split('.')[1];
I'll make this change. 
I was trying to keep the function generic, to be able to be used with any JWT :sweat_smile:
I guess since accessToken already has an expiry function, i'll make this one dedicated to identityToken.

2021-03-31 15:01 UTC, sayoojs commented on packages/insomnia-app/app/ui/components/editors/auth/o-auth-2-auth.js
> +    const expDigitCount = exp.toString().length;
The extracted expiry for identityToken was a 10 digit epoch representation in my case (Eg: `1617202697` Precision up to seconds).
For accessToken's `expires_in` key its 13 digit epoch (Eg: `1617202697111`  Precision up to milliseconds).

2021-04-01 03:53 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/auth/o-auth-2-auth.js
> +    const base64Url = token.split('.')[1];
Fair enough 😅 it fails because likely somewhere in the render loop this logic is reached while token is `undefined`, and the previous code would fail with an error like `identityToken cannot be found on undefined`

2021-04-01 04:01 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/auth/o-auth-2-auth.js
> +    const expDigitCount = exp.toString().length;
I see! Reading some docs about the JWT `exp` property it seems this is usually in seconds. Is this always the case or situational? If always, I'd be more comfortable with a solution what converts seconds to milliseconds by multiplying by 1000, rather than removing or padding digits 🤔 since we're working with numbers the multiplication seems easier to follow.

2021-04-01 04:55 UTC, sayoojs commented on packages/insomnia-app/app/ui/components/editors/auth/o-auth-2-auth.js
> +    const expDigitCount = exp.toString().length;
Oh no, by padding (as shown in snippet below) that's what I'm doing. 

I'm essentially dividing or multiplying by 10^n, where n is calculated as the difference between the number 13 and the actual digit count of epoch generated from the JWT exp property. 
  
`exp = exp * 10 ** (13 - expDigitCount);`

So in cases of epoch seconds, that code multiplies by 10^3. 
In case of epoch microseconds, that code multiplies by 10^-3. Which essentially remove the digits that representing the microseconds.

Maybe I should force cast the result to big int to prevent floating points on x10^-n

2021-04-01 05:33 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/auth/o-auth-2-auth.js
> +    const expDigitCount = exp.toString().length;
Ahhhh okay, thanks for explaining that!!

> Maybe I should force cast the result to big int to prevent floating points on x10^-n

That sounds reasonable.

I think it would be good to extract these few lines into a standalone utility method somewhere and writing a few tests as a way to document input/output of this logic. 🙌🏽

2021-04-01 07:33 UTC, sayoojs commented on packages/insomnia-app/app/ui/components/editors/auth/o-auth-2-auth.js
> +    const expDigitCount = exp.toString().length;
Which lines specifically? The padding/trimming part?

2021-04-01 07:36 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/auth/o-auth-2-auth.js
> +    const expDigitCount = exp.toString().length;
Yep! The padding and trimming

2021-04-01 08:00 UTC, sayoojs commented on packages/insomnia-app/app/ui/components/editors/auth/o-auth-2-auth.js
> +    const expDigitCount = exp.toString().length;
Is there a file with preexisting util functions? Where I can export this to? Or do I just create a static method within this class itself?

2021-04-01 09:17 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/auth/o-auth-2-auth.js
> +    const expDigitCount = exp.toString().length;
This might be a good place! Looks like there a similar helper here too, for snapping a number to a minimum or maximum.

https://github.com/Kong/insomnia/blob/45c210eb41f52ddc8cb67abb424c4bd786c4e0ea/packages/insomnia-app/app/common/misc.js#L444

2021-04-05 11:20 UTC, sayoojs commented on packages/insomnia-app/app/ui/components/editors/auth/o-auth-2-auth.js
> +    const identityExpireLabel = OAuth2Auth.renderExpiryFromJWT(tok.identityToken);
This fix is implemented.

2021-04-05 11:23 UTC, sayoojs commented on packages/insomnia-app/app/ui/components/editors/auth/o-auth-2-auth.js
> +    const expDigitCount = exp.toString().length;
Moved this func to misc.js and added tests. (Do review the tests, this is the first time I've written JS tests)

2021-04-05 11:30 UTC, sayoojs commented
@develohpanda  I've implemented the requested changes.

Any idea why the Ubuntu tests might be failing? I couldn't infer anything from the logs. Could you try re-triggering it?

2021-04-05 12:20 UTC, develohpanda approved these changes
Thank you so much 🙏🏽 Sometimes Spectron (the E2E test framework we use for Electron) fails to connect to the chrome driver and gives cryptic errors like that. I have re-triggered, no action needed from your side 🤗

2021-04-05 17:03 UTC, merged

2022-03-14 17:14 UTC, kateefimova-eb commented
What an amazing feature! Thank you so much 👏