Change it block from lambda to anonymous function
getinsomnia/insomnia pull request #3215
Opened 2021-03-19 23:18 UTC by jswitzer-lulus

Changing the function passed to the it block from a lambda to an anonymous function allows access to the mocha context from within the test. This allows users to change the timeouts for individual unit tests via the exposed code blocks.
ex:

this.timeout(10000);
const response1 = await insomnia.send();
expect(response1.status).to.equal(200);

will timeout after 10 seconds instead of 5.

Closes #3214

2021-03-22 02:50 UTC, develohpanda approved these changes, later dismissed
Seems like an OK code-solution to timeouts for the moment, will need to seek product approval.

The test fixtures will need to be updated as well, please, as they now fail CI 🙏🏽

2021-03-22 15:34 UTC, DMarby requested changes
Thank you for this PR @jswitzer-lulus!

I'm not sure this is the best approach however, as exposing the entire Mocha context means that we could have potential un-noticed breakage when upgrading it in the future, and prevents us from potentially changing the test runner in the future without breaking things.

In order to avoid this, it would be better to explicitly expose `timeout` (and in the future other methods we may want to expose) through a shim, or through the `insomnia` global defined in tests.

2021-03-23 13:03 UTC, dimitropoulos commented
and, on that note, there has been a lot of talk lately, as I've been working with insomnia-testing, to update the runner to be `jest-runner`, now that it exists (in the days when this solution was created jest was still backed by mocha, I believe).  That has a number of things it solves for our project that I won't get into here, but needless to say - it's on my radar.

2022-10-11 10:32 UTC, jackkav commented
Closed as stale.

2022-10-11 10:32 UTC, closed without merging