`strip_path` explicit support, and `x-kong-route-defaults` support
getinsomnia/insomnia pull request #3273
Opened 2021-04-09 20:38 UTC by dimitropoulos

closes: INS-122

2021-04-09 21:46 UTC, reynolek requested changes

2021-04-09 21:46 UTC, reynolek commented on packages/openapi-2-kong/src/declarative-config/services.js
> +        strip_path: api.strip_path || false,
So there are 2 things mentioned in that JIRA ticket -- 1) Provide a way to set `strip_path` to override the default and 2) The [docs](https://www.npmjs.com/package/openapi-2-kong#services) explicitly say that `strip_path` is always true, when clearly in the code its default is false.

I think at this point the best thing to do is to update the [README](https://github.com/Kong/insomnia/blob/develop/packages/openapi-2-kong/README.md#servicesroutes) to say that it defaults to false

2021-04-09 21:46 UTC, reynolek commented on packages/openapi-2-kong/src/declarative-config/__tests__/services.test.js
> +      it('will not override options on the route with `x-kong-route-defaults` at the root', async () => {
Should this be `will override`?

2021-04-09 21:46 UTC, reynolek commented on packages/openapi-2-kong/src/declarative-config/__tests__/services.test.js
> +      it('will not override options on the route with `x-kong-route-defaults` at the root', async () => {
This test and the one above it have the exact same string description, which makes it hard to know what is different between the two.

2021-04-09 21:46 UTC, reynolek commented on packages/openapi-2-kong/src/declarative-config/__tests__/services.test.js
> +      it('allows overriding strip_path at the root', async () => {
To my knowledge we dont support `strip_path` at the root. I believe we should only support it at the route definition level (or at the `x-kong-route-default` level)

2021-04-13 17:08 UTC, dimitropoulos commented on packages/openapi-2-kong/src/declarative-config/__tests__/services.test.js
> +      it('allows overriding strip_path at the root', async () => {
the linear ticket and the jira ticket got crossed in my mind, sorry, fixed in 6ad54dfe5c6fb799919e05b1b5de74bfc341587f

2021-04-13 17:09 UTC, dimitropoulos commented on packages/openapi-2-kong/src/declarative-config/__tests__/services.test.js
> +      it('will not override options on the route with `x-kong-route-defaults` at the root', async () => {
totally: was a mistake: fixed in b92d702bd1eb8739017b1b3cc4a486c1dc560327

2021-04-13 17:09 UTC, dimitropoulos commented on packages/openapi-2-kong/src/declarative-config/__tests__/services.test.js
> +      it('will not override options on the route with `x-kong-route-defaults` at the root', async () => {
fixed in b92d702bd1eb8739017b1b3cc4a486c1dc560327

2021-04-13 17:09 UTC, dimitropoulos commented on packages/openapi-2-kong/src/declarative-config/services.js
> +        strip_path: api.strip_path || false,
fixed in 64498f939c28530bdc61712c850bd1a396408e24

2021-04-13 20:30 UTC, reynolek approved these changes

2021-04-14 16:24 UTC, Tieske commented on packages/openapi-2-kong/src/declarative-config/__tests__/services.test.js
> +      strip_path: false,
I don't think this is wise. `strip_path` can be specified in `x-kong-route-defaults` and if not specified at all it should simply pick up Kong defaults when synced to Kong by decK.

Adding those named properties here will create a tightly couple the implementation. We should try to keep that to a minimum. So only where actual logic is involved, eg. with the request-validator generation.

dwyt @develohpanda @dimitropoulos ?

2021-04-14 16:54 UTC, Tieske commented on packages/openapi-2-kong/src/declarative-config/__tests__/services.test.js
> +      it('x-kong-route-defaults only works at the root', async () => {
To make it consistent with the plugins, I this one should be possible on doc/path/operation level. Where the more specific level override the more generic ones (completely, so no merging of objects).

That would be consistent with the plugins, right @develohpanda ?

2021-04-14 16:55 UTC, Tieske commented on packages/openapi-2-kong/src/declarative-config/__tests__/services.test.js
> +      it('allows overriding strip_path at the path level', async () => {
only allowing `strip_path` doesn't make sense to me, and I think it also complicates the implementation (though that's hard for me to judge)

2021-04-21 04:33 UTC, develohpanda commented on packages/openapi-2-kong/src/declarative-config/__tests__/services.test.js
> +      it('x-kong-route-defaults only works at the root', async () => {
Yis that is how plugins behave now - no merging, most specific is used.

https://github.com/Kong/insomnia/blob/70738103d792ca7340464b585cad52842ca7be85/packages/openapi-2-kong/src/declarative-config/plugins.js#L179-L180

2021-04-22 15:02 UTC, dimitropoulos commented on packages/openapi-2-kong/src/declarative-config/__tests__/services.test.js
> +      strip_path: false,
I strongly agree with you.  The trouble is that the prior implementation hardcoded in `strip_path` to `false` and there was no way to specify it or not.  To change this behavior now would be a breaking change, we feel.

2021-04-22 15:14 UTC, dimitropoulos commented on packages/openapi-2-kong/src/declarative-config/__tests__/services.test.js
> +      it('x-kong-route-defaults only works at the root', async () => {
I implemented it this way originally, and it was decided against because it kinda defeats the semantics of a top-level default, which is different from other properties.  @reynolek can say more, but that was the general idea.

2021-04-22 15:15 UTC, dimitropoulos commented on packages/openapi-2-kong/src/declarative-config/__tests__/services.test.js
> +      it('allows overriding strip_path at the path level', async () => {
I agree, but [as I said above](https://github.com/Kong/insomnia/pull/3273#discussion_r618484885), the issue ultimately is that we had this hardcoded to false for all paths before which kinda locks us into this.

2021-04-22 15:21 UTC, develohpanda commented on packages/openapi-2-kong/src/declarative-config/__tests__/services.test.js
> +      it('x-kong-route-defaults only works at the root', async () => {
I sort of agree with Thijs here about specificity. Use the top-level default but override when set at a more specific location

2021-04-22 16:51 UTC, reynolek commented on packages/openapi-2-kong/src/declarative-config/__tests__/services.test.js
> +      it('x-kong-route-defaults only works at the root', async () => {
Lets go with making it consistent with other plugins. Looks like I directed you away from that earlier, not realizing we did it other ways in other places.

2021-04-22 18:40 UTC, Tieske commented on packages/openapi-2-kong/src/declarative-config/__tests__/services.test.js
> +      strip_path: false,
actually I was wrong. It should be set to `false`, if not specified in `x-kong-route-defaults`, only if `x-kong-route-defaults` sets it to `true` it should be `true`, in all other cases it should be `false`.

Reason being; the part of the path that is matched by Kong, will be stripped. This is because Kong treats it as a path-prefix. But the nature of OpenAPI specs is that the entire path is specified. So if stripped, it would mean that the entire path is stripped, and hence every endpoint would be reduced to only `/`, which obviously is useless.

2021-04-22 18:43 UTC, Tieske commented on packages/openapi-2-kong/src/declarative-config/__tests__/services.test.js
> +      it('x-kong-route-defaults only works at the root', async () => {
agreed, merging objects can have weird edge cases. Let's put the can of worms back on the shelf 😄

2021-04-22 18:45 UTC, Tieske commented on packages/openapi-2-kong/src/declarative-config/__tests__/services.test.js
> +      it('allows overriding strip_path at the path level', async () => {
yep, should be as per other comments, full set of defaults, no merging. And strip_path only goes to `true` if there is a `true` in the defaults, if absent it goes to `false`.

2021-04-23 20:34 UTC, dimitropoulos commented on packages/openapi-2-kong/src/declarative-config/__tests__/services.test.js
> +      it('allows overriding strip_path at the path level', async () => {
should be updated now.  enough has changed anyway that I think another top-level look is necessitated.

2021-04-23 20:34 UTC, dimitropoulos commented on packages/openapi-2-kong/src/declarative-config/__tests__/services.test.js
> +      strip_path: false,
should be updated now.  enough has changed anyway that I think another top-level look is necessitated.

2021-04-23 20:35 UTC, dimitropoulos commented on packages/openapi-2-kong/src/declarative-config/__tests__/services.test.js
> +      it('x-kong-route-defaults only works at the root', async () => {
should be updated now.  enough has changed anyway that I think another top-level look is necessitated.

2021-04-24 10:08 UTC, Tieske requested changes
I think we should close this and replace it with #3319

2021-04-24 10:08 UTC, Tieske commented on packages/openapi-2-kong/src/declarative-config/services.js
> +      const operationRouteDefaults = pathItem['x-kong-route-defaults'];
This is actually the "path" default

2021-04-24 10:08 UTC, Tieske commented on packages/openapi-2-kong/src/declarative-config/services.js
> +      const pathRouteDefaults = api.paths['x-kong-route-defaults'];
this is not right, a path default on that array does not make sense. The array has a 1-on-1 relation ship with the root document, hence from a scoping perspective this would be identical to `x-kong-route-defaults` on root level.

2021-04-26 15:13 UTC, Tieske commented on packages/openapi-2-kong/src/declarative-config/services.js
> +    // remove semicolon i.e. convert `https` to `https`
```suggestion
    // remove semicolon i.e. convert `https:` to `https`
```

2021-04-26 15:45 UTC, Tieske approved these changes

2021-04-26 16:17 UTC, merged