Custom & default tagging for plugins
getinsomnia/insomnia pull request #3286
Opened 2021-04-14 16:01 UTC by sonicyeti

Abstracting out our default 'OAS3_import' tag to be re-used, applying custom tags to plugins while including the default OAS3_import tag.

![2021-04-14 11 58 01](https://user-images.githubusercontent.com/52717970/114741552-df88ea00-9d18-11eb-8603-68e4d1d63ad3.gif)

Fixes INS-611

2021-04-15 20:59 UTC, develohpanda requested changes
There are security plugins which are not being assigned tags (and should be). The following is one example but I think all of the plugins in the following fixture result should contain a tag.

https://github.com/Kong/insomnia/blob/eb4ae99f8428e99b8322e5c1b4125ddc14d316fb/packages/openapi-2-kong/src/__fixtures__/security.expected.json#L23

2021-04-15 20:59 UTC, develohpanda commented on packages/openapi-2-kong/src/declarative-config/plugins.js
> +    plugin.config = {};
This is redundant if you already have the check on line 28

2021-04-15 20:59 UTC, develohpanda commented on packages/openapi-2-kong/src/declarative-config/plugins.js
> +    config: value.config ? value.config : {},
if `value.config` is not defined, fallback to `{}`

```suggestion
    config: value.config || {},
```

2021-04-16 01:46 UTC, develohpanda requested changes

2021-04-16 01:46 UTC, develohpanda commented on packages/openapi-2-kong/src/__fixtures__/httpbin.expected.json
> +          "plugins": [{"config": {"tags": ["OAS3_import"]}, "name": "correlation-id"}],
Is the tag applied to the correct location? I don't think so. The tag needs to be on the parent object, not in the config property. 

```
{
  "plugins": [{
    "config": {...},
    "tags": ["OAS3_import"],
    "name": "correlation-id"
  }]
}
````

2021-04-16 13:36 UTC, sonicyeti commented on packages/openapi-2-kong/src/__fixtures__/httpbin.expected.json
> +          "plugins": [{"config": {"tags": ["OAS3_import"]}, "name": "correlation-id"}],
We need to support tags on the plugin's config object per [FTI-2444](https://konghq.atlassian.net/browse/FTI-2444). Notice the other issue regarding tags in plugin root. 

Current output being (covering 2444):

![Screen Shot 2021-04-16 at 9 32 17 AM](https://user-images.githubusercontent.com/52717970/115032076-e63d6b80-9e96-11eb-84dc-6f56595f6b3a.png)

2021-04-19 04:59 UTC, develohpanda commented on packages/openapi-2-kong/src/__fixtures__/httpbin.expected.json
> +          "plugins": [{"config": {"tags": ["OAS3_import"]}, "name": "correlation-id"}],
[FTI-2444](https://konghq.atlassian.net/browse/FTI-2444) doesn't seem related to this PR? This PR looks like it's fixing [FTI-2305](https://konghq.atlassian.net/browse/FTI-2305), which is reflected from #2682. The YAML example in FTI-2305 has lost all indenting from what was in GitHub (which is crucial for YAML). Worth confirming with someone but to the best of my knowledge tags should not be part of the _config_ object (which is specific to a plugin), but should be on the parent item (because tags is a global property).

2021-04-19 15:37 UTC, sonicyeti commented on packages/openapi-2-kong/src/__fixtures__/httpbin.expected.json
> +          "plugins": [{"config": {"tags": ["OAS3_import"]}, "name": "correlation-id"}],
Ok I'll circle back with Thjis for clarification. The linear ticket (INS-611) touches on the relationship between the above tickets, it's not capture in this PR though.

2021-04-20 00:59 UTC, develohpanda requested changes
Some cleanup left after changes 🧹

2021-04-20 00:59 UTC, develohpanda commented on packages/openapi-2-kong/src/declarative-config/plugins.js
> +    config: value.config,
1. Now that tags are no longer placed on the `config` object this logic to handle `value.config` should return to it's previous implementation. 
2. the tags logic can be simplified because we don't need to work with the config object anymore
	  ```js
	  plugin.tags = [
	    ...defaultTags,
	    ...(value.tags ?? []),
	  ];
	  ```

2021-04-20 00:59 UTC, develohpanda commented on packages/openapi-2-kong/src/index.js
> +  return generateFromSpec(api, type, [defaultTags.join(), ...tags]);
Is the `.join()` necessary? Doing the following should be enough

```suggestion
  return generateFromSpec(api, type, [...defaultTags, ...tags]);
```

Or even
```suggestion
  return generateFromSpec(api, type, defaultTags.concat(tags));
```

2021-04-20 01:42 UTC, develohpanda commented
@sonicyeti happy to pair for resolving conflicts here as they arise from one of my recent PRs

2021-04-21 00:33 UTC, develohpanda approved these changes
LGTM - I have created a roll-up ticket (INS-629) regarding tags on plugins and marked which parts of that are covered by this PR

2021-04-21 00:34 UTC, merged