Publish NPM packages through CI
getinsomnia/insomnia pull request #3311
Opened 2021-04-21 06:25 UTC by develohpanda

What it says on the tin. The updated release workflow will:
- run tests on all OSs
- then, publish NPM packages
- then, release each OS bundle

Closes INS-630

2021-04-21 07:14 UTC, reynolek approved these changes

2021-04-21 09:06 UTC, DMarby requested changes

2021-04-21 09:06 UTC, DMarby commented on .github/workflows/release-core.yml
> +      - run: npm run publish
I think we need a step before this to configure authentication with NPM so that we're able to publish?
Since access tokens are bound to a user, not an organisation, it would probably be good to create a new NPM user and add it to our credentials vault, and then add a token to that to be used here.

2021-04-21 09:08 UTC, develohpanda commented on .github/workflows/release-core.yml
> +      - run: npm run publish
Oh, yes we absolutely do, I forgot to add in the description. That's why I created a separate PR for it 😅 I agree, creating an org account to publish with will be good

2021-04-21 13:01 UTC, sonicyeti approved these changes

2021-04-22 09:47 UTC, develohpanda commented
Reminder to myself to rebase `git rebase --onto develop 928dec2`

2021-05-14 12:08 UTC, DMarby approved these changes

2021-05-14 21:09 UTC, merged