Fix issue chaining multiple requests
getinsomnia/insomnia pull request #3385
Opened 2021-05-13 16:41 UTC by vincendep

Closes #3382

2021-05-13 19:53 UTC, dimitropoulos commented on plugins/insomnia-plugin-response/index.js
> +        shouldResend = ! response || (Date.now() - response.created) / 1000 > maxAgeSeconds;
please revert this change

2021-05-13 19:54 UTC, dimitropoulos commented on plugins/insomnia-plugin-response/index.js
> +        const requestChain = context.context.getExtraInfo('requestChain') || []
Is there a reason to grab this again?  It's already declared 8 lines above (now).

2021-05-13 19:55 UTC, dimitropoulos requested changes
Thanks for the quick PR!

Other than two very minor things, we should be ready to go with this.  I can confirm that this fixes the issue.

Here is how I tested this:
https://insomnia.rest/run?label=Multiple%20Chaining%20Test&uri=https%3A%2F%2Fgist.githubusercontent.com%2Fdimitropoulos%2F64fdb4a75a5bd68998dbe1cae5cf71e4%2Fraw%2F9441f985d80e9f8e99e369689e60cb79d07b7abf%2Fmultiple-chain.json

For this to work you'd need to run `npm run serve` from `packages/insomnia-smoke-test`.

2021-05-13 20:36 UTC, vincendep commented on plugins/insomnia-plugin-response/index.js
> +        const requestChain = context.context.getExtraInfo('requestChain') || []
nope...removed :sweat_smile:

2021-05-13 22:39 UTC, dimitropoulos approved these changes

2021-05-14 00:00 UTC, dimitropoulos commented
@vincendep sorry, I didn't catch it sooner.  any idea what the changes to the package-lock are all about?  I'm done for the day today but I'll take a look tomorrow and maybe we can get this merged tomorrow one way or the other.

2021-05-14 07:13 UTC, vincendep commented
> @vincendep sorry, I didn't catch it sooner. any idea what the changes to the package-lock are all about? I'm done for the day today but I'll take a look tomorrow and maybe we can get this merged tomorrow one way or the other.

mmm no idea what those changes are. I ve only run npm run bootstrap && npm run app-start from the root to test the changes I ve made. (But first time I was using a wrong version of node)

2021-05-14 12:29 UTC, dimitropoulos commented
haha, welp.  I also nave no idea where those lockfile changes came from.  I removed them and ran a bootstrap and they didn't return.  /shrug.

All the same, I re-tested just to make sure and this seems to be working as expected.  Thanks again for contributing!

2021-05-14 13:22 UTC, vincendep commented
thank you too...happy to contribute!

2021-05-14 17:13 UTC, dimitropoulos commented
ok, sorry to renege, but I would like @develohpanda to take a look at this.  There was a test that needed to be updated.  I studied it for some time, indeed, and concluded that the change we made to the behavior (to fix the bug) needed to be made to the original, but now I'm worried that there's a potential for a different use-case for recursion that there wasn't before.  The test was written in such a way that looks like it is expecting an infinite loop, but now there isn't one.  Since I'm not sure and out of an abundance of caution, let's @develohpanda a chance to take a look.

2021-05-25 06:41 UTC, develohpanda approved these changes
This looks good to me - I tested some of the recursive scenarios I could think of both on Live and in this PR and they seem to be working as intended. I like the `requestChain` approach over the boolean flag.

I think it would be good to add a safety net into the chain, however - so it doesn't grow to an unreasonable amount (maybe hard-coded at 5 or 10?) I am mostly imagining malicious use of it; if someone was to export a workspace online with many requests but in the background, when someone imports and runs a request which chains several hundred together, this could cause issues.

2021-05-25 06:45 UTC, develohpanda requested changes
Comment on the test which is worth addressing

2021-05-25 06:45 UTC, develohpanda commented on plugins/insomnia-plugin-response/__tests__/index.test.js
> +      expect(response).toBe('Response res_1')
@dimitropoulos I think this test needs to still test what it describes, though, this time using the `requestChain` context value instead of `fromResponseTag`

2021-05-27 20:12 UTC, develohpanda approved these changes

2021-05-27 20:12 UTC, develohpanda commented on plugins/insomnia-plugin-response/__tests__/index.test.js
> +      expect(response).toBe('Response res_1')
Fixed in c4b0f25

2021-05-27 20:36 UTC, merged