add search for graphQL schemas
getinsomnia/insomnia pull request #3388
Opened 2021-05-16 21:21 UTC by Hademumel

This PR adds search functionality to the graphQL schema explorer.

The search input is visible on the initial schema component and can be jumped to by using a shortcut. The search results are divided into two categories "Types" and "Fields". The number of found elements is thereby limited to 100 per category, and the update function is debounced, in order to allow performant searches in large schemas.

Closes #2720

2021-05-16 23:04 UTC, develohpanda commented
Wow, this is awesome! Thanks for opening a PR, added to my list for review. 🙌🏽 

In the meantime, since this change involves some UI could you please add screenshots/gifs into the PR description? Thanks!

2021-07-19 20:20 UTC, Hademumel commented
Is there nobody who can review this? I implemented this feature cause I want to use it myself 😅

2021-07-20 02:32 UTC, develohpanda requested changes
Hi @Hademumel! Thank you for this PR and apologies for the delays, we have a lot of work flowing through.

I've just done a preliminary code review. In general this PR looks good, although there are some aspects of the implementation that are a little confusing and worth refactoring - please see my comments below. I have also pushed a commit, fixing up some type definitions. 😄 

As an aside, when you update this PR, could you please make sure to exclude any extra changes that get included as a result of formatting rules in your code-editor (I presume)? It reduces the noise in a code-review and thus helps us to review faster. I updated these for now, but given there will need to be an iteration and further review, please keep it in mind. Thank you! 🙏🏽

2021-07-20 02:32 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/graph-ql-explorer/graph-ql-explorer-type.tsx
> +  static renderFieldsList(
This function was extracted and made static to that it can be re-used in `GraphQLExplorerSearchResults`, but it would be better suited as a standalone component.

This code-base is transitioning to Function components and hooks, and while that's not a specific ask for this PR for the larger components, using static helpers from other class components definitely slows that conversion process.

2021-07-20 02:32 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/graph-ql-explorer/graph-ql-explorer-search-results.tsx
> +        foundTypes: this.renderFoundTypes(),
Curious why you chose to store the rendered elements in state, rather than the filtered data (`GraphQLType` and `GraphQLFieldWithParentName`) and leave the rendering up to the render method.

If there's no specific reason I think it might be cleaner to refactor this and only store the filter results in state

2021-07-20 02:32 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/graph-ql-explorer/graph-ql-explorer-schema.tsx
> +        ) : (
Should this ternary exist in `GraphQLExplorerSchema` or in `GraphQLExplorer`?

It looks like the component `GraphQLExplorerSearchResults` does not use anything from `GraphQLExplorerSchema` and the props introduced just drill down. For that reason I think this logic of whether to show the explorer or search results, belongs in the parent component here: https://github.com/Hademumel/insomnia/blob/1d79de95c2bbf15a575e624c9a3818f9118adeac/packages/insomnia-app/app/ui/components/graph-ql-explorer/graph-ql-explorer.tsx#L234-L244

2021-07-20 02:32 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/graph-ql-explorer/graph-ql-explorer-search-results.tsx
> +  updateSearchResults = debounce(() => {
IMO this is the wrong place to debounce. We should debounce storing the input value into state rather than debounce the render. I see (in `GraphQLExplorer`) that you use a regular `input`. There is a `DebouncedInput` component in this codebase, are you able to use that?

2021-08-01 20:35 UTC, Hademumel commented on packages/insomnia-app/app/ui/components/graph-ql-explorer/graph-ql-explorer-type.tsx
> +  static renderFieldsList(
I extracted the function to its own functional component

2021-08-01 20:38 UTC, Hademumel commented on packages/insomnia-app/app/ui/components/graph-ql-explorer/graph-ql-explorer-search-results.tsx
> +        foundTypes: this.renderFoundTypes(),
I also think thats clearer, I refactored according to the suggestion.

2021-08-01 20:38 UTC, Hademumel commented on packages/insomnia-app/app/ui/components/graph-ql-explorer/graph-ql-explorer-type.tsx
> +  static renderFieldsList(
I extracted this to its own functional component

2021-08-01 20:39 UTC, Hademumel commented on packages/insomnia-app/app/ui/components/graph-ql-explorer/graph-ql-explorer-schema.tsx
> +        ) : (
Good point, I moved the SearchResults to the parent component

2021-08-01 20:40 UTC, Hademumel commented on packages/insomnia-app/app/ui/components/graph-ql-explorer/graph-ql-explorer-search-results.tsx
> +  updateSearchResults = debounce(() => {
I refactored this, so the Debounced Component is used. I had to make some changes to it though.

2021-08-02 05:17 UTC, develohpanda reviewed
Thank you for making those changes! I updated how refs are being used with `DebouncedInput` to match the existing pattern to simplify. Overall LGTM 🔥 I will hold off on approval until the following questions regarding UX have been addressed from the team.

While testing I noticed that empty states could be better represented. Perhaps with a note under each header (or change the header itself, or not show at all). @wdawson would you have any suggestions on behavior and/or wording?

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/4312346/127807199-a918672b-7cf9-4763-accc-72c2603b6032.png">

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/4312346/127807155-02cc4e60-0ef5-424a-8112-3f718895c49b.png">

Additionally, @erickrico could you please suggest how best to represent/style this concatenation message? This PR will only show 100 results, but if more are found it will present a message like below:

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/4312346/127807358-998a1bab-c865-4957-b579-2c14f151d417.png">

2021-08-02 05:17 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/graph-ql-explorer/graph-ql-explorer-search-results.tsx
> +    const fields: GraphQLFieldWithParentName[] = [...this.state.foundFields];
Can this just use `this.state.Foundfields` or does it need to be a new array?

2021-08-02 17:53 UTC, wdawson commented
> While testing I noticed that empty states could be better represented. Perhaps with a note under each header (or change the header itself, or not show at all). @wdawson would you have any suggestions on behavior and/or wording?

@erickrico may have thoughts here too. But I'd suggest hiding the headers completely if nothing is found for them. If there are no hits across any of the headers, then I'd show some message like "No results found."

2021-08-17 21:49 UTC, erickrico commented
> > While testing I noticed that empty states could be better represented. Perhaps with a note under each header (or change the header itself, or not show at all). @wdawson would you have any suggestions on behavior and/or wording?
> 
> @erickrico may have thoughts here too. But I'd suggest hiding the headers completely if nothing is found for them. If there are no hits across any of the headers, then I'd show some message like "No results found."

I agree to remove the headers, we should just display something like "no results found, try agin with a different schema", and for the "show 30 more results" @develohpanda  i think using a lighter color works best, also what happens when a user click on that, will we load the 30+ results beneath the first batch or results?

2021-08-17 22:55 UTC, develohpanda commented
> what happens when a user click on that, will we load the 30+ results beneath the first batch or results?

Currently nothing, that's not a button, just a label. I think the intention is for users to make the search/filter more specific, though it would probably be better if it would show another batch of results 🤔 @erickrico

2021-08-18 20:59 UTC, gatzjames commented
👍 I tested it with a couple of different graphql schemas and it works really well!

2021-08-22 15:49 UTC, Hademumel commented
I worked on the proposed changes. Thanks for the suggestions. I used --color-surprise as the color for the "more elements found" hint. Im not sure if this is a good color to use, but I felt it was a good choice to differentiate between the other colors in the schema explorer.

2021-08-25 05:57 UTC, develohpanda commented
@Hademumel thank you for making those updates, much appreciated!

I have pushed a few more commits to improve the TS types (following on from my previous commits). I also pushed an update to replace search with a fuzzy search algorithm Insomnia already uses in other areas, but largely your changes are great! 🙌🏽  I have been testing with various schemas alongside and it seems to be working smoothly. I'm super excited for us to get this through, it's bound to be so useful.

2021-08-25 06:32 UTC, develohpanda approved these changes
### QA

<details>
<summary>🟢 Click to navigate to docs</summary>

![2021-08-25 18 24 43](https://user-images.githubusercontent.com/4312346/130738322-3a2a45ca-567a-4844-91fb-c22e0fce7786.gif)

</details>

<details>
<summary>🟢 Fuzzy search finds all results</summary>

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/4312346/130737771-d1652a47-e665-4484-90b8-c86f7dfdaaa4.png">

</details>

<details>
<summary>🟢 Fuzzy search finds only types</summary>

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/4312346/130737885-724cc27a-007d-42a5-a6cf-cf61425f8f5e.png">


</details>

<details>
<summary>🟢 Fuzzy search finds only fields</summary>

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/4312346/130737993-7159b15e-ef45-40e1-8286-df9abbba0c19.png">

</details>

<details>
<summary>🟢 Fuzzy search finds nothing </summary>

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/4312346/130738055-4add1fe0-baa8-4f2c-b31e-81239a219512.png">


</details>

<details>
<summary>🟢 Show more results, clear search </summary>

This batch size is set to 100, but for this demo I pushed it down to 5.

![2021-08-25 18 31 15](https://user-images.githubusercontent.com/4312346/130738354-8837aef1-7f91-45c2-9d6d-1755891e5ad5.gif)


</details>

2021-08-25 07:55 UTC, gatzjames approved these changes
💯

2021-08-25 21:09 UTC, dimitropoulos approved these changes
Worked well with the GitHub API.  Thanks!

![Screenshot_20210825_162835](https://user-images.githubusercontent.com/15232461/130860068-4e162862-9a68-42c5-9dc7-fed89932b31b.png)

2021-08-26 05:43 UTC, merged