INS-674 - First pass at making the send button more visible
getinsomnia/insomnia pull request #3414
Opened 2021-05-21 21:16 UTC by reynolek

Closes #3152
Closes INS-674

This is a first pass attempt at a way to make the send button more visible in the current layout. I verified all current core themes to make sure each had the improvement.

Below are some example screenshots of different themes, with hover states as well.

<img width="626" alt="Screen Shot 2021-05-21 at 2 12 20 PM" src="https://user-images.githubusercontent.com/5934780/119198739-b1e14000-ba3e-11eb-8620-602b3fe43f02.png">
<img width="628" alt="Screen Shot 2021-05-21 at 2 14 14 PM" src="https://user-images.githubusercontent.com/5934780/119198860-eb19b000-ba3e-11eb-852a-86b47ec020da.png">
<img width="624" alt="Screen Shot 2021-05-21 at 2 12 30 PM" src="https://user-images.githubusercontent.com/5934780/119198742-b279d680-ba3e-11eb-8123-9c31e4cae868.png">
<img width="626" alt="Screen Shot 2021-05-21 at 2 14 33 PM" src="https://user-images.githubusercontent.com/5934780/119198862-ec4add00-ba3e-11eb-9a12-701d194d8b59.png">
<img width="617" alt="Screen Shot 2021-05-21 at 2 12 48 PM" src="https://user-images.githubusercontent.com/5934780/119198746-b3126d00-ba3e-11eb-94ac-a57273e044d6.png">
<img width="622" alt="Screen Shot 2021-05-21 at 2 14 44 PM" src="https://user-images.githubusercontent.com/5934780/119198866-ece37380-ba3e-11eb-8aaa-827728222ee6.png">

2021-05-24 20:11 UTC, dimitropoulos commented
I rebased it for you and added 33fbde6e14cc3f646bbfd61df62dcf90564556ec which does:
![Screenshot_20210524_160901](https://user-images.githubusercontent.com/15232461/119402066-603ced80-bcaa-11eb-810a-f22d6c26f4a1.png)

The color isn't right (obvi) but I had a moment to throw it in there.  Since this change is all about making it standout/so prominent, I thought that it would be appropriate for the preview to have it.  Not 100% sure how to theme it, but I'm sure we can figure it out by observing how the other things (e.g. sidebar) are themed.  I only had a few moments between two calls to do it so I thought it'd be better than nothing to get the ball rolling with at least placing it.

2021-05-24 20:21 UTC, reynolek commented
Ah interesting! I didnt even think to update that little SVG. I'll dig in on how to get proper colors in.

2021-05-24 21:09 UTC, reynolek commented
Updated the colors

![image](https://user-images.githubusercontent.com/5934780/119407824-a76eb280-bc99-11eb-9e4b-7e4c4907bef8.png)

2021-05-24 23:38 UTC, dimitropoulos commented
no biggie, but I'm curious: why is it that in the core default the color for the dark theme is `#a39af9` while the swatch is `#796dc5`.  For all of the rest of them it seems to match, but for just core-default it's brighter.

![image](https://user-images.githubusercontent.com/15232461/119419155-3cd06d80-bcbf-11eb-8ed9-0ebf446d783f.png)

2021-05-25 23:31 UTC, develohpanda approved these changes
LGTM!

2021-05-25 23:59 UTC, develohpanda requested changes
If you add a long URL, there's no padding any more (there wasn't before either, but by virtue of the button having the same background color it didn't matter)

<img width="842" alt="image" src="https://user-images.githubusercontent.com/4312346/119582833-72896980-be19-11eb-9b39-538759c217c7.png">

The button for gRPC also needs the same theme color: https://github.com/Kong/insomnia/blob/develop/packages/insomnia-app/app/ui/components/buttons/grpc-send-button.tsx
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/4312346/119582945-b2505100-be19-11eb-8b7b-c984e026ac6b.png">

2021-05-26 23:04 UTC, reynolek commented
Code updated to change the gRPC button (since it uses `insomnia-components` as its more modern) and updated the CSS to add a small left margin to prevent text from pushing up against the rest/graphql send button

2021-05-27 09:17 UTC, develohpanda approved these changes
Looks so fresh now!

<img width="745" alt="image" src="https://user-images.githubusercontent.com/4312346/119800132-d783b300-bf30-11eb-82e4-4a08b2f14a02.png">

<img width="745" alt="image" src="https://user-images.githubusercontent.com/4312346/119800106-cfc40e80-bf30-11eb-8806-45c31073ddfd.png">

2021-05-27 09:17 UTC, develohpanda commented on packages/insomnia-components/src/button/button.tsx
> +// Text sets the `bg` color as the text color
Nice comments - this is kind of messy though, I'm hoping when we come back to this we can clean it up. 🤞🏽

2021-05-27 09:41 UTC, merged

2021-05-27 16:26 UTC, reynolek commented on packages/insomnia-components/src/button/button.tsx
> +// Text sets the `bg` color as the text color
Yeah all good -- This type of thing just took longer to grok than it should have (although some of that was because live reloading wasnt working for me properly...).

Its at least something, and will be useful in its current form until better addressed.