Skip apt repo publish if not stable tag
getinsomnia/insomnia pull request #3423
Opened 2021-05-26 00:57 UTC by develohpanda

Using the example approach [here](https://stackoverflow.com/a/58869470)

2021-05-26 01:40 UTC, DMarby requested changes

2021-05-26 01:40 UTC, DMarby commented on .github/workflows/publish.yml
> +      if: steps.stable-tag.outputs.is-stable == 'true'
I guess this is not needed anymore since the check is moved to a job instead? Same for the one below

2021-05-26 01:44 UTC, DMarby approved these changes

2021-05-26 06:20 UTC, develohpanda commented
@DMarby I tested this and it didn't exit/continue properly 😆 will need to pair briefly

2021-05-26 16:55 UTC, DMarby commented
> @DMarby I tested this and it didn't exit/continue properly 😆 will need to pair briefly

Forgot that we were doing POSIX regex 😅 `\d` isn't supported, so we'll need to change it to this instead and it should work:
```
^core@[0-9]{4}\.[0-9]+\.[0-9]+$
```

2021-05-27 01:00 UTC, develohpanda commented
Looks like it's working now!

2021-05-27 01:00 UTC, merged