fix DebouncedInput (and delay handling) and change handlers
getinsomnia/insomnia pull request #3438
Opened 2021-06-02 15:23 UTC by dimitropoulos

During the review in a prior PR, a bug in DebouncedInput was discovered, namely that if the delay (which is a prop) changes, the component behavior will not change to debounce (or not) since the behavior is set only in the constructor.

Along the way, there were a few other low-hanging fruit to address, so I did those in a limited capacity.

2021-06-02 23:12 UTC, develohpanda requested changes

2021-06-02 23:12 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/base/debounced-input.tsx
> +      debounce(onChange, delay || 500)(value);
This change doesn't actually work. It now generates a _new_ debounced handler with every keystroke, removing the memoization we get with the previous implementation.

Yes initializing the handler in the constructor isn't right either, in case the `onChange` or `delay` props are changed

Develop:
![2021-06-03 11 07 21](https://user-images.githubusercontent.com/4312346/120563268-49da2300-c45c-11eb-8b19-19df86fad9b3.gif)

This PR:
![2021-06-03 11 09 21](https://user-images.githubusercontent.com/4312346/120563271-4d6daa00-c45c-11eb-8e36-db69811744c2.gif)

2021-06-03 13:40 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/base/debounced-input.tsx
> +      debounce(onChange, delay || 500)(value);
ok, all fixed now.

<details>
<summary>expand to see a version of `space-settings-modal.tsx` you can test with</summary>

```tsx
import React, { PureComponent } from 'react';
import { autoBindMethodsForReact } from 'class-autobind-decorator';
import { AUTOBIND_CFG } from '../../../common/constants';
import { DebouncedInput } from '../base/debounced-input';
import Modal from '../base/modal';
import ModalBody from '../base/modal-body';
import ModalHeader from '../base/modal-header';
import PromptButton from '../base/prompt-button';
import * as models from '../../../models/index';
import { Space } from '../../../models/space';
import { strings } from '../../../common/strings';
import { selectActiveSpace } from '../../redux/selectors';
import { bindActionCreators } from 'redux';
import * as spaceActions from '../../redux/modules/space';
import { connect } from 'react-redux';

interface ReduxStateProps {
  space?: Space;
}

interface ReduxDispatchProps {
  handleRemoveSpace: (space: Space) => void;
}

interface State {
  delay: number;
}

interface Props extends ReduxStateProps, ReduxDispatchProps { }

@autoBindMethodsForReact(AUTOBIND_CFG)
class SpaceSettingsModal extends PureComponent<Props, State> {
  modal: Modal | null = null;

  state: State = {
    delay: 500,
  }

  constructor(props: Props) {
    super(props);
    setTimeout(() => {
      console.log('changing the delay to 2 seconds');
      this.setState({ delay: 2000 });
    }, 10_000);

    setTimeout(() => {
      console.log('changing the onChange and the delay to 3 seconds');
      this._handleRename = async () => { console.log('new onChange (does nothing)'); };
      this.setState({ delay: 3000 });
    }, 20_000);
  }

  _handleSetModalRef(n: Modal) {
    this.modal = n;
  }

  _handleRemoveSpace() {
    if (this.props.space) {
      this.props.handleRemoveSpace(this.props.space);
    }

    this.hide();
  }

  async _handleRename(name: string) {
    const { space } = this.props;

    if (space) {
      await models.space.update(space, { name });
    }
  }

  show() {
    this.modal && this.modal.show();
  }

  hide() {
    this.modal && this.modal.hide();
  }

  render() {
    const { space } = this.props;
    if (!space) {
      return null;
    }

    console.log('rendering space-settings-modal');
    return (
      <Modal ref={this._handleSetModalRef} freshState>
        <ModalHeader key={`header::${space._id}`}>
          {strings.space.singular} Settings{' '}
          <div className="txt-sm selectable faint monospace">{space._id}</div>
        </ModalHeader>
        <ModalBody key={`body::${space._id}`} className="pad">
          <div className="form-control form-control--outlined">
            <label>
              Name
              <DebouncedInput
                type="text"
                delay={this.state.delay}
                placeholder="My Space"
                defaultValue={space.name}
                onChange={this._handleRename}
              />
            </label>
          </div>
          <h2>Actions</h2>
          <div className="form-control form-control--padded">
            <PromptButton
              onClick={this._handleRemoveSpace}
              addIcon
              className="width-auto btn btn--clicky inline-block">
              <i className="fa fa-trash-o" /> Delete
            </PromptButton>
          </div>
        </ModalBody>
      </Modal>
    );
  }
}

const mapStateToProps = (state): ReduxStateProps => {
  const space = selectActiveSpace(state);
  return { space };
};

const mapDispatchToProps = (dispatch): ReduxDispatchProps => {
  const boundSpaceActions = bindActionCreators(spaceActions, dispatch);
  return {
    handleRemoveSpace: boundSpaceActions.removeSpace,
  };
};

export default connect(mapStateToProps, mapDispatchToProps, null, { forwardRef: true })(SpaceSettingsModal);
```

</details>

I guess, upon really looking at it, it ALSO didn't respond to changes to the change handler (the `onChange` prop).  That's pretty bad, actually, come to think of it.  That's also fixed now. d11a54ab910bd578a3bbf2ccdedb4b9ce87137f3

While on the one hand I realllly don't like having to use derived state, this really is the (one?) use-case where it's required, where we actually need to know the previous state since we're calling a function (debounce) that spans multiple state transitions.

2021-06-30 05:29 UTC, develohpanda reviewed
QA'd locally and looks to be working! A couple of comments so not approving yet 🙌🏽

2021-06-30 05:29 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/base/debounced-input.tsx
> +    }
I think we can simplify this by having a single `onChange` property in state, which gets set to `props.onChange` or `debounce(props.onChange, ...)` depending on `props.delay` being defined.

As an aside, the `defaultDelay` fallback seems redundant since the debounced handler will never be reached if `props.delay` is not set 🤔

2021-06-30 05:29 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/codemirror/code-editor.tsx
> +interface Props extends InheritedAttributes, ExtendedAttributes {
This looks like a nice approach for extending and overriding but inheriting types correctly types

2021-06-30 05:29 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/codemirror/one-line-editor.tsx
>    disabled?: boolean;
Could it be that this is also an inherited attribute?

2021-06-30 05:29 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/body/form-editor.tsx
>    parameters: any[],
Should this also be `RequestBodyParameter[]`?

2021-06-30 05:29 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/body/url-encoded-editor.tsx
>    parameters: any[];
Should this also be `RequestBodyParameter[]`?

2021-06-30 05:29 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/key-value-editor/editor.tsx
>    pairs: any[];
Should this also be `RequestHeader[]`?

2021-06-30 05:29 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/space-settings-modal.tsx
> -              // @ts-expect-error -- TSCONVERSION props are spread into an input element
So glad to have this fixed

2021-06-30 05:29 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/key-value-editor/row.tsx
> -  readOnly?: boolean,
I am assuming there is nothing that sends the `readOnly` prop?

2021-06-30 05:29 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/codemirror/one-line-editor.tsx
>    getRenderContext?: Function;
See types here

https://github.com/Kong/insomnia/blob/3998e8b48969fdf0a668435c8b017384c5cc38a0/packages/insomnia-app/app/ui/components/editors/body/body-editor.tsx#L41-L42

2021-06-30 16:06 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/codemirror/code-editor.tsx
> +interface Props extends InheritedAttributes, ExtendedAttributes {
:)

2021-06-30 16:08 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/key-value-editor/editor.tsx
>    pairs: any[];
good call: 86f51efd059309fdedb4bd8992bc5cf411eec53d

2021-06-30 16:08 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/editors/body/url-encoded-editor.tsx
>    parameters: any[];
good call: 86f51efd059309fdedb4bd8992bc5cf411eec53d

2021-06-30 16:08 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/editors/body/form-editor.tsx
>    parameters: any[],
good call: 86f51efd059309fdedb4bd8992bc5cf411eec53d

2021-06-30 16:09 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/modals/space-settings-modal.tsx
> -              // @ts-expect-error -- TSCONVERSION props are spread into an input element
it's a great feeling, isn't it :)

2021-06-30 16:20 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/key-value-editor/row.tsx
> -  readOnly?: boolean,
no, opposite, things were sending it but this component isn't/wasn't using it.

I did the git spelunking so you could double check my work, but the TLDR; is `readOnly` was never actually used but was allowed before when types weren't checked, but is not now. 

Actually, it _was_ once upon a time using it, but [`KeyValueEditorRow` was just passing it to `OneLineEditor`](https://github.com/Kong/insomnia/blob/bdb4b4e6610f69e84a0ae7ea1296078c59bbe88e/packages/insomnia-app/app/ui/components/key-value-editor/row.js#L219), which [wasn't using it](https://github.com/Kong/insomnia/blob/bdb4b4e6610f69e84a0ae7ea1296078c59bbe88e/packages/insomnia-app/app/ui/components/codemirror/one-line-editor.js).

So far as I can tell, this has been wrong all along.  At [the time this was added](https://github.com/Kong/insomnia/commit/a25b62b994b283bffb6ba0a947a9b96332e6d2f1#diff-d2a68d459e2d7ba43df733366da4c7db204b7759746b037e0aebae4ae9082d1fR218) if you look at [this component at that time](https://github.com/Kong/insomnia/blob/a25b62b994b283bffb6ba0a947a9b96332e6d2f1/packages/insomnia-app/app/ui/components/codemirror/one-line-editor.js) you should see that it wasn't used then, either.

2021-06-30 16:23 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/key-value-editor/row.tsx
> -  readOnly?: boolean,
Perhaps the confusion arose because CodeEditor (but not OneLineEditor) actually uses `readOnly`: https://github.com/Kong/insomnia/blob/develop/packages/insomnia-app/app/ui/components/codemirror/code-editor.tsx#L1140

2021-06-30 16:28 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/codemirror/one-line-editor.tsx
>    getRenderContext?: Function;
Ahh, cool.  I was wondering how I missed this because I know I did a gloabl search before.  Turns out some are prefixed with `handle` and some are not.  Fun stuff.

![Screenshot_20210630_122722](https://user-images.githubusercontent.com/15232461/123997564-871fcb00-d99e-11eb-832a-2000cfd5d452.png)

It'd be cool if they were consistent although this PR already does plenty - I don't want to expand the scope.  Next time.

2021-06-30 16:29 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/codemirror/one-line-editor.tsx
>    getRenderContext?: Function;
fixed in 26ec600afe1117bc12a264acd25f70a55a84fe12

2021-06-30 16:40 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/base/debounced-input.tsx
> +    }
I removed the default delay in c63036d7f1b784fcf7d3de52c043dda1baf0aabc but I'd like to ask you to reconsider re: combining the onChange.

The reason is that it will make the code (and debugging) more complicated since you never know at any given moment which one you're working with.  I implemented what I believe you're asking for in 914474d7213f5dc7ac6f7580a1ccfb8510ab20c1.  I agree that the code is more tight, but I think it comes at the cost of readability.

HOWEVER, I was thinking we can actually make this a lot better by simply requiring that there's always a delay and that it's always debounced.  I'm not sure if that matters, but it seems like if you didn't want debouncing you shouldn't use DebouncedInput.  From that perspective, maybe it makes sense to just remove the code path that uses the callback _without_ a debounce (like the component now supports).  Thoughts?

2021-06-30 16:46 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/base/debounced-input.tsx
> +    }
OHHH I think I remember a reason they need to be separate.  Doesn't that mean that otherwise there's no way to compare if the prop changed.  If we always set it to something new, it would create an infinite loop since `state.onChange !== props.onChange` will always evaluate to true, right?

![Screenshot_20210630_124518](https://user-images.githubusercontent.com/15232461/123999917-07dfc680-d9a1-11eb-8a48-2ad308d92deb.png)

2021-06-30 16:47 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/codemirror/one-line-editor.tsx
>    disabled?: boolean;
that's just the thing, though.  I don't see anywhere where this is actually passed or spread into a child component.

2022-10-11 10:25 UTC, jackkav commented
Closed as stale.

2022-10-11 10:25 UTC, closed without merging