Automatically enable sync for collections created in a remote space
getinsomnia/insomnia pull request #3474
Opened 2021-06-15 03:34 UTC by develohpanda

2021-06-16 02:52 UTC, develohpanda commented on packages/insomnia-app/app/ui/redux/modules/git.tsx
> -      onConfirm: async () => await dispatch(createWorkspaceWithGitRepo(gitRepo)),
This doesn't return a promise so doesn't need async-await

2021-06-16 03:27 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/dropdowns/sync-dropdown.tsx
> +        disabled={initializing}
When the drop-down is opened it runs some refresh logic. If the drop-down is opened while pushing during initialize, the push fails. We can either do `vcs.newInstance().push()` but I feel like disabling the drop-down is the cleaner option, because you shouldn't do anything in the drop-down while initializing anyway.

2021-06-16 15:23 UTC, DMarby approved these changes

2021-06-17 19:27 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/dropdowns/sync-dropdown.tsx
> +        disabled={initializing}
too bad our dropown doesn't support a loading state e.g. https://ant.design/components/dropdown/
![Screenshot_20210617_152717](https://user-images.githubusercontent.com/15232461/122460743-82135280-cf80-11eb-8033-a4073f4a05ed.png)

2021-06-17 20:47 UTC, dimitropoulos requested changes
(we debugged it on a call but updating here for posterity) there as a breaking bug whereby if you followed the reproduction steps exactly (i.e. without clicking into a collection in the remote steps) you would have a broken vcs instance and sync will not work.

2021-06-21 09:41 UTC, develohpanda commented
> (we debugged it on a call but updating here for posterity) there as a breaking bug whereby if you followed the reproduction steps exactly (i.e. without clicking into a collection in the remote steps) you would have a broken vcs instance and sync will not work.

Looks like this is not related to the vcs instance being broken, but the bug (where sync fails to set up automatically) occurs when the collection being created is the _first workspace (document or collection) in the space_. This is why the gif in the description above works but it didn't work on your computer, following the same steps.

This is a deeply nested issue but it is caused by the following two facts:
1. the database is mirrored in redux, but through events (which cause background updates)
2. the requirement for an active workspace to always exist

I have created a separate ticket (thus will be a separate PR) to handle this bug INS-771 (currently in progress). As a solution I will be concretely exploring how difficult it is to remove the requirement for an active workspace to always exist

2021-06-22 20:33 UTC, dimitropoulos approved these changes

2021-06-22 20:45 UTC, merged