Disabling ApplePressAndHoldEnabled to fix the Vim mode on Insomnia
getinsomnia/insomnia pull request #3476
Opened 2021-06-15 18:59 UTC by MrSnix

**Summary**:
This line has been introduced to make the Vim mode correctly work on macOS.
Contrary to other platforms, if you preventDefault() a keypress event, no repeat events are fired for that key as it is being held down. This snippet, reintroduce the event firing disabling the Apple behaviour. The flag applies only at app level (just for Insomnia), it won't influence other applications.

When set to **false**, the custom apple behaviour is disabled and works as expected by code-mirror.

`systemPreferences.setUserDefault('ApplePressAndHoldEnabled', 'boolean', false);`

![Jun-15-2021 19-47-04](https://user-images.githubusercontent.com/20780192/122107821-c802d600-ce1b-11eb-91e9-c789718d93d3.gif)

I'm holding `j` and `k` in this gif

**Important**:
I have put this one-liner near the `BrowserWindow` object because I feel like it's more appropriate, it is part of the main Electron interface. As always, you can commit to this branch and put it somewhere else if you have a better and more appropriate place. Lastly, you must wrap the statement inside an `if(isMac())` to prevent it from running against Windows or Linux systems.

It closes #3448

2021-06-15 19:28 UTC, dimitropoulos commented on packages/insomnia-app/app/main/window-utils.ts
> +    // @ts-ignore
```suggestion
    // @ts-expect-error <description of why there's a type error on this line>
```

2021-06-15 19:29 UTC, dimitropoulos commented on packages/insomnia-app/app/main/window-utils.ts
> +    * */
```suggestion
    */
```

doing this mirrors how jsdoc comments terminate

2021-06-15 19:35 UTC, dimitropoulos commented on packages/insomnia-app/app/main/window-utils.ts
> +    * This snippet, reintroduce the event firing disabling the Apple behaviour.
I'm not sure I understand what this line is saying.  Perhaps try to rephrase?

2021-06-15 19:38 UTC, dimitropoulos commented on packages/insomnia-app/app/main/window-utils.ts
> +    * That's why the type-checking has been disabled in the next line.
Regarding line wrapping, I know we aren't very consistent about this (yet!) in this project, but it's ideal to avoid wrapping these kinds of comments for the sake of line length and nothing else.  For example, I frequently split screen with line wrapping and here's how this would look in (even) a fairly wide split:

<img src="https://user-images.githubusercontent.com/15232461/122112300-a8a18400-cdee-11eb-94d6-b792cc4c8b91.png" width="300" />

compare that to a more inlined version (not apples to apples):
<img src="https://user-images.githubusercontent.com/15232461/122112994-81978200-cdef-11eb-9fb6-94a397691aba.png" width="300" />

2021-06-15 19:39 UTC, dimitropoulos commented on packages/insomnia-app/app/main/window-utils.ts
> +    * (i.e. defaults write -g ApplePressAndHoldEnabled -bool true),
it's helpful if you use backticks to delineate code from text, for example:

```
    /*
    * This line has been introduced to make the Vim mode correctly work on MacOS.
    * Contrary to other platforms, if you `preventDefault()` a keypress event no repeat events are fired for that key as it is being held down.
    * This snippet, reintroduce the event firing disabling the Apple behaviour. The flag applies only at app-level (just for Insomnia), and won't influence other applications.
    *
    * Note: if you've set `ApplePressAndHoldEnabled` at a global level (i.e. `defaults write -g ApplePressAndHoldEnabled -bool true`), this will override app-level preferences.
    */

    // @ts-expect-error the type definition for: `setUserDefault(key: string, type: string, value: string): void` is expecting a string for the 'value' field but not really... The implementation is expecting a primitive value, not a string.
    systemPreferences.setUserDefault('ApplePressAndHoldEnabled', 'boolean', false);
```

2021-06-15 19:39 UTC, dimitropoulos commented on packages/insomnia-app/app/main/window-utils.ts
> +    // @ts-ignore
see https://github.com/Kong/insomnia/pull/3476/files#r652096873 for a concrete example

2021-06-15 20:08 UTC, MrSnix commented
@dimitropoulos 
I have applied the requested changes. 
As always, let me know. 
I'm open to any feedback :D

I apologize if I missed something.

2021-06-15 20:24 UTC, dimitropoulos commented on packages/insomnia-app/app/main/window-utils.ts
> +
oh, only one final thing is that maybe we should remove this empty line because the comment starts with `this line` and then isn't butt-up right against the line it's talking about?

2021-06-15 20:24 UTC, dimitropoulos reviewed
I can't test it, but the code looks good to me!  thanks!

2021-06-15 20:41 UTC, DMarby commented
@reynolek @MrSnix @develohpanda @dimitropoulos I don't have a strong opinion, but do you think it might make sense/be possible to only conditionally set the system preference if vim mode is enabled?

By default in maCOS if you hold eg `a`, rather then `a` repeating itself a bunch of times, you get a popup menu for special characters: 
![image](https://user-images.githubusercontent.com/174626/122120091-436b8400-ce2a-11eb-8db5-98dc64e8a6ca.png)

With this change I think we'd lose that behaviour within the app, which I think would be good to avoid if possible when vim mode is not enabled.

2021-06-15 21:45 UTC, reynolek commented
Ah good call -- It'd be even better if it was limited to non-insert mode with vim bindings enabled (although I dont know if thats possible).

2021-06-15 22:01 UTC, MrSnix commented
Hi @DMarby, thanks for your feedback :D
I did some test but **it is not** working as I'd expect.

I will investigate and try to let you know more tomorrow.

2021-06-15 23:50 UTC, develohpanda commented
> Do you think it might make sense/be possible to only conditionally set the system preference if vim mode is enabled (and perhaps use removeUserDefault when vim mode is disabled to fallback to the system global setting)?

1. It feels like this should be an option which is given to the user, because even with Vim mode enabled, some users may want to keep using the special-characters instead of press-and-hold for navigation. We're adding one feature but taking another away.
  1. If we provide an option, what should this default to, depending on the OS level setting?
1. On looking at how other IDEs handle this, the official vim plugin for VS Code does not provide an option for VS Code to internally override it (remember, VS Code is also electron), but rather specifies in it's [README](https://github.com/VSCodeVim/Vim#mac).

With the above reasons in mind, I think we shouldn't programmatically disable this option, rather add an info icon with a link to documentation which describes to disable this option using the command:
```
defaults write com.insomnia.app ApplePressAndHoldEnabled -bool false 
```

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4312346/122137288-646abe00-ce98-11eb-9623-99578abc204f.png">

2021-06-16 00:06 UTC, develohpanda commented
I have added documentation [here](https://support.insomnia.rest/article/203-key-maps): `https://support.insomnia.rest/article/203-key-maps`

Documentation in the app is defined [here](https://github.com/Kong/insomnia/blob/5f4c19da35e90ffa2f3ae27e9b309ee48f9d4e16/packages/insomnia-app/app/common/documentation.ts) for use throughout the app.

2021-06-16 00:10 UTC, develohpanda requested changes
Following on from the reasons outlined in https://github.com/Kong/insomnia/pull/3476#issuecomment-861906734, I suggest we only link to documentation and have users change the setting themselves.

I have added documentation [here](https://support.insomnia.rest/article/203-key-maps): `https://support.insomnia.rest/article/203-key-maps`

Documentation links in the app are defined [here](https://github.com/Kong/insomnia/blob/5f4c19da35e90ffa2f3ae27e9b309ee48f9d4e16/packages/insomnia-app/app/common/documentation.ts) for use throughout the app.

2021-06-16 00:20 UTC, reynolek commented
So in my testing, I disabled the value. In Insomnia press and works. If I switch over to iMessages or my browsers, press and hold still brings up other accented letters.

But other apps like Discord it no longer works (is discord electron? I always forget if they transitioned away or not).

2021-06-16 00:29 UTC, develohpanda commented
> But other apps like Discord it no longer works (is discord electron? I always forget if they transitioned away or not).

@reynolek which command did you run?

In my testing, I ran `defaults write com.insomnia.app ApplePressAndHoldEnabled -bool false`, restarted both Insomnia and Discord - I see repeating characters in Insomnia and the special characters in Discord.

2021-06-16 03:17 UTC, reynolek commented
Ahh you know what, i did it globally 👍

2021-06-16 19:22 UTC, MrSnix commented
As requested, I applied the changes.

Feel free to modify the text content if there is a better alternative.
As always, I'm open to any feedback :D

2021-06-16 23:57 UTC, develohpanda approved these changes
Made a slight wording adjustment, but LGTM! 🎉 

<img width="820" alt="image" src="https://user-images.githubusercontent.com/4312346/122309678-d0195d80-cf62-11eb-9cd9-0c66373d0442.png">

2021-06-17 13:32 UTC, dimitropoulos approved these changes

2021-06-17 13:32 UTC, merged