Base Space export
getinsomnia/insomnia pull request #3479
Opened 2021-06-16 14:46 UTC by dimitropoulos

closes INS-763

Take a look at the diff below, but it turns out there were also errant entities in a user-created space (e.g. environments).

<details>
<summary>base space diff (before and after this PR)</summary>

```diff
 {
   "_type": "export",
   "__export_format": 4,
   "__export_date": "2021-06-16T14:21:46.976Z",
   "__export_source": "insomnia.desktop.app:v2021.4.0-beta.1",
   "resources": [
     {
       "_id": "req_996f6574b994433fbc71bc75562b4620",
       "parentId": "wrk_474584b3e1f84fd3b7bee6cf59d05f66",
       "modified": 1623779717676,
       "created": 1623779717676,
       "url": "",
       "name": "Insomnia Space | Insomnia Collection | Request",
       "description": "",
       "method": "GET",
       "body": {},
       "parameters": [],
       "headers": [],
       "authentication": {},
       "metaSortKey": -1623779717676,
       "isPrivate": false,
       "settingStoreCookies": true,
       "settingSendCookies": true,
       "settingDisableRenderRequestBody": false,
       "settingEncodeUrl": true,
       "settingRebuildPath": true,
       "settingFollowRedirects": "global",
       "_type": "request"
     },
     {
       "_id": "wrk_474584b3e1f84fd3b7bee6cf59d05f66",
       "parentId": null,
       "modified": 1623778497238,
       "created": 1623778497238,
       "name": "Insomnia",
       "description": "",
       "scope": "design",
       "_type": "workspace"
     },
     {
-      "_id": "req_511fcf24b9df41c0843d0632de55788d",
-      "parentId": "wrk_f791238459b64d4ab7c8221478dcc0b1",
-      "modified": 1623779675301,
-      "created": 1623779616174,
-      "url": "",
-      "name": "Test Space | Collection | Request",
-      "description": "",
-      "method": "GET",
-      "body": {},
-      "parameters": [],
-      "headers": [],
-      "authentication": {},
-      "metaSortKey": -1623779616174,
-      "isPrivate": false,
-      "settingStoreCookies": true,
-      "settingSendCookies": true,
-      "settingDisableRenderRequestBody": false,
-      "settingEncodeUrl": true,
-      "settingRebuildPath": true,
-      "settingFollowRedirects": "global",
-      "_type": "request"
-    },
-    {
-      "_id": "wrk_f791238459b64d4ab7c8221478dcc0b1",
-      "parentId": "sp_6eb890aca9ad40279b1b2956abc3a038",
-      "modified": 1623779683769,
-      "created": 1623778518889,
-      "name": "Test Space | Collection",
-      "description": "",
-      "scope": "collection",
-      "_type": "workspace"
-    },
-    {
       "_id": "env_071b0b01476c343a50625e00b302762fc4e42d8b",
       "parentId": "wrk_474584b3e1f84fd3b7bee6cf59d05f66",
       "modified": 1623778497430,
       "created": 1623778497430,
       "name": "Base Environment",
       "data": {},
       "dataPropertyOrder": null,
       "color": null,
       "isPrivate": false,
       "metaSortKey": 1623778497431,
       "_type": "environment"
     },
     {
       "_id": "jar_071b0b01476c343a50625e00b302762fc4e42d8b",
       "parentId": "wrk_474584b3e1f84fd3b7bee6cf59d05f66",
       "modified": 1623778497432,
       "created": 1623778497432,
       "name": "Default Jar",
       "cookies": [],
       "_type": "cookie_jar"
     },
     {
       "_id": "spc_5c9be62ea9ba4c0dad653d51f9256bfd",
       "parentId": "wrk_474584b3e1f84fd3b7bee6cf59d05f66",
       "modified": 1623779724150,
       "created": 1623778497244,
       "fileName": "Insomnia Collection",
       "contents": "",
       "contentType": "yaml",
       "_type": "api_spec"
-    },
-    {
-      "_id": "env_75ba291b166a0aa61060b5d3cd58a5721d768dd3",
-      "parentId": "wrk_f791238459b64d4ab7c8221478dcc0b1",
-      "modified": 1623778519101,
-      "created": 1623778519101,
-      "name": "Base Environment",
-      "data": {},
-      "dataPropertyOrder": null,
-      "color": null,
-      "isPrivate": false,
-      "metaSortKey": 1623778519101,
-      "_type": "environment"
-    },
-    {
-      "_id": "jar_75ba291b166a0aa61060b5d3cd58a5721d768dd3",
-      "parentId": "wrk_f791238459b64d4ab7c8221478dcc0b1",
-      "modified": 1623778519104,
-      "created": 1623778519104,
-      "name": "Default Jar",
-      "cookies": [],
-      "_type": "cookie_jar"
-    },
-    {
-      "_id": "spc_3d1955f755be4b06adbfa69f11285e1b",
-      "parentId": "wrk_f791238459b64d4ab7c8221478dcc0b1",
-      "modified": 1623778518895,
-      "created": 1623778518895,
-      "fileName": "My Collection",
-      "contents": "",
-      "contentType": "yaml",
-      "_type": "api_spec"
     }
   ]
 }
```

</details>

<details>
<summary>testing space diff (before and after this PR)</summary>

```diff
  {
   "_type": "export",
   "__export_format": 4,
   "__export_date": "2021-06-16T14:22:04.368Z",
   "__export_source": "insomnia.desktop.app:v2021.4.0-beta.1",
   "resources": [
     {
-      "_id": "req_996f6574b994433fbc71bc75562b4620",
-      "parentId": "wrk_474584b3e1f84fd3b7bee6cf59d05f66",
-      "modified": 1623779717676,
-      "created": 1623779717676,
-      "url": "",
-      "name": "Insomnia Space | Insomnia Collection | Request",
-      "description": "",
-      "method": "GET",
-      "body": {},
-      "parameters": [],
-      "headers": [],
-      "authentication": {},
-      "metaSortKey": -1623779717676,
-      "isPrivate": false,
-      "settingStoreCookies": true,
-      "settingSendCookies": true,
-      "settingDisableRenderRequestBody": false,
-      "settingEncodeUrl": true,
-      "settingRebuildPath": true,
-      "settingFollowRedirects": "global",
-      "_type": "request"
-    },
-    {
-      "_id": "wrk_474584b3e1f84fd3b7bee6cf59d05f66",
-      "parentId": null,
-      "modified": 1623778497238,
-      "created": 1623778497238,
-      "name": "Insomnia",
-      "description": "",
-      "scope": "design",
-      "_type": "workspace"
-    },
-    {
       "_id": "req_511fcf24b9df41c0843d0632de55788d",
       "parentId": "wrk_f791238459b64d4ab7c8221478dcc0b1",
       "modified": 1623779675301,
       "created": 1623779616174,
       "url": "",
       "name": "Test Space | Collection | Request",
       "description": "",
       "method": "GET",
       "body": {},
       "parameters": [],
       "headers": [],
       "authentication": {},
       "metaSortKey": -1623779616174,
       "isPrivate": false,
       "settingStoreCookies": true,
       "settingSendCookies": true,
       "settingDisableRenderRequestBody": false,
       "settingEncodeUrl": true,
       "settingRebuildPath": true,
       "settingFollowRedirects": "global",
       "_type": "request"
     },
     {
       "_id": "wrk_f791238459b64d4ab7c8221478dcc0b1",
       "parentId": "sp_6eb890aca9ad40279b1b2956abc3a038",
       "modified": 1623779683769,
       "created": 1623778518889,
       "name": "Test Space | Collection",
       "description": "",
       "scope": "collection",
       "_type": "workspace"
     },
     {
-      "_id": "env_071b0b01476c343a50625e00b302762fc4e42d8b",
-      "parentId": "wrk_474584b3e1f84fd3b7bee6cf59d05f66",
-      "modified": 1623778497430,
-      "created": 1623778497430,
-      "name": "Base Environment",
-      "data": {},
-      "dataPropertyOrder": null,
-      "color": null,
-      "isPrivate": false,
-      "metaSortKey": 1623778497431,
-      "_type": "environment"
-    },
-    {
-      "_id": "jar_071b0b01476c343a50625e00b302762fc4e42d8b",
-      "parentId": "wrk_474584b3e1f84fd3b7bee6cf59d05f66",
-      "modified": 1623778497432,
-      "created": 1623778497432,
-      "name": "Default Jar",
-      "cookies": [],
-      "_type": "cookie_jar"
-    },
-    {
-      "_id": "spc_5c9be62ea9ba4c0dad653d51f9256bfd",
-      "parentId": "wrk_474584b3e1f84fd3b7bee6cf59d05f66",
-      "modified": 1623779724150,
-      "created": 1623778497244,
-      "fileName": "Insomnia Collection",
-      "contents": "",
-      "contentType": "yaml",
-      "_type": "api_spec"
-    },
-    {
       "_id": "env_75ba291b166a0aa61060b5d3cd58a5721d768dd3",
       "parentId": "wrk_f791238459b64d4ab7c8221478dcc0b1",
       "modified": 1623778519101,
 [...]

2021-06-16 18:02 UTC, dimitropoulos commented
(need to figure out why the tests are unhappy, pulling back to draft until then)

2021-06-16 20:45 UTC, dimitropoulos commented
(ok, tests are passing now)

2021-06-17 00:06 UTC, develohpanda commented on packages/insomnia-app/app/common/export.ts
> +  const promises = rootDocs.map(getDocWithDescendants(includePrivateDocs));
I had no idea `[].map(foo => func(foo, bar))` was the same as `[].map(func(bar))`

2021-06-17 00:16 UTC, develohpanda requested changes
Changes requested only for the plugin API update

2021-06-17 00:16 UTC, develohpanda commented on packages/insomnia-app/app/plugins/context/data.ts
> +  workspaces?: Workspace[];
This is a breaking change and we need to be backwards compatible with plugins, otherwise all existing plugins that use this functionality will break.

I suggest we don't change this but only accept one workspace (as is the case now) and consume as `exportWorkspacesData([workspace], ...)`

2021-06-17 00:16 UTC, develohpanda commented on packages/insomnia-app/app/common/export.ts
> +  parentDocs: BaseModel[],
I wonder if we can restrict this to be `Workspace[]`, because it should only be a list of workspaces. Does changing this break any usages?

2021-06-17 00:16 UTC, develohpanda commented on packages/insomnia-app/app/common/export.ts
> +  parentDocs: BaseModel[],
Same as above, does restricting this to be `Workspace[]` break any usages?

2021-06-17 13:33 UTC, dimitropoulos commented on packages/insomnia-app/app/plugins/context/data.ts
> +  workspaces?: Workspace[];
ahh, good call.  the problem wasn't that so much as that it could be undefined before and null/undefined wasn't allowed.  I'll find another way to accomplish things.

2021-06-23 19:50 UTC, dimitropoulos commented on packages/insomnia-app/app/plugins/context/data.ts
> +  workspaces?: Workspace[];
should be implemented in 2b9639119f0db899218297535bf52018bfac22fe

2021-06-23 20:08 UTC, dimitropoulos commented on packages/insomnia-app/app/common/export.ts
> +  parentDocs: BaseModel[],
I was thinking to change this but I wasn't sure if it was valid that we don't use this for anything else.  Upon second look, I can see that it is totally fine to make this change d767b151c5768d6a952729eccad0a2d2a56b76c9

2021-06-23 20:08 UTC, dimitropoulos commented on packages/insomnia-app/app/common/export.ts
> +  parentDocs: BaseModel[],
see https://github.com/Kong/insomnia/pull/3479#discussion_r657426451

2021-06-28 21:00 UTC, develohpanda approved these changes

2021-06-28 21:00 UTC, develohpanda commented on packages/insomnia-app/app/common/export.ts
> +  const rootDocs = workspaces.length === 0 ? [null] : workspaces;
Is a comment needed for why `[null]` is a thing?

2021-06-30 15:08 UTC, dimitropoulos commented on packages/insomnia-app/app/common/export.ts
> +  const rootDocs = workspaces.length === 0 ? [null] : workspaces;
I tried to write one just now but I wasn't quite sure what to say or how to describe it.  I did my best: 91202029a15bd0d7ddcc07c97f23c5357035c3f1

We can always iterate on it more in the future I suppose.

2021-06-30 15:33 UTC, merged