Load local GraphQL schema
getinsomnia/insomnia pull request #3803
Opened 2021-07-11 10:42 UTC by lodi-g

I often work with GraphQL, and sometimes the introspection requests are blocked. In these case, the developers give me a GraphQL schema so I can still have the documentation.
However, Insomnia does not support importing local schema files, only fetching from internet. Therefore I must use Postman for this case, but I'd prefer to use Insomnia.

Closes #2743

2021-07-12 06:21 UTC, develohpanda reviewed
Looking good! I haven't tested with a local schema file yet, but code and UX looks good - submitting this review with one small piece of feedback.

<img width="485" alt="image" src="https://user-images.githubusercontent.com/4312346/125239936-7deb1280-e33d-11eb-81ca-7b16219e3942.png">

Error message looks good too

<img width="410" alt="image" src="https://user-images.githubusercontent.com/4312346/125240217-ef2ac580-e33d-11eb-91e6-f36e4e6e56d5.png">

I also pushed a commit to fix up how state is being used to avoid the `as any` 😄

2021-07-12 06:21 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/body/graph-ql-editor.tsx
> +          name: 'GraphQL file',
I suggest using the following helper if it's possible - we recently faced an issue with the `OpenDialogOptions.filters[*].name` field on Linux, and it was fixed generically here, so reusing this helper will avoid the issue showing up again.

 https://github.com/Kong/insomnia/blob/9f3705a8a8d784c621b29a7ef635c561e9d15990/packages/insomnia-app/app/common/select-file-or-folder.ts#L14-L14

See more context here: https://github.com/Kong/insomnia/pull/3348

2021-07-13 04:21 UTC, develohpanda approved these changes
Tested with https://github.com/apollographql/apollo-tooling/blob/master/__fixtures__/starwars/schema.json and looks to be working well!

![2021-07-13 16 19 25](https://user-images.githubusercontent.com/4312346/125390032-48563000-e3f6-11eb-8b4a-3a9a68ad2004.gif)

2021-07-13 04:25 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/body/graph-ql-editor.tsx
> +          name: 'GraphQL file',
I addressed this in [`7304fb8` (#3803)](https://github.com/Kong/insomnia/pull/3803/commits/7304fb884bc433c7d6bd4f414df8422b3a6b6271); it wouldn't be possible to use `selectFileOrFolder` in the current state

2021-07-14 15:44 UTC, dimitropoulos requested changes
![image](https://user-images.githubusercontent.com/15232461/125646139-070378b1-cb3d-4572-8f7c-03afbeb60115.png)

Works as advertised but I have a few questions.

In general, I think this is a bigger feature than we're making it out to be in terms of UX consideration (and this particular item is a good example of that).  () is a good example of that, but another one is: should there be any indication anywhere to a user that they're using a remote vs local schema?  Right now there isn't one, right?  I think their should be.

Don't get me wrong: I love this PR and I really like the use-case it solves, but I also want to be considerate to a good user experience when users are uploading local schemas.

2021-07-14 15:44 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/editors/body/graph-ql-editor.tsx
> +      this.setState(existingState => ({ ...existingState, ...newState }));
is there a reason to do this instead of `this.setState(newState)`?

2021-07-14 15:44 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/editors/body/graph-ql-editor.tsx
> +    });
is this the same as `this.setState({ handleSchemaFetchErrors: false }, this._loadAndSetLocalSchema)`?

2021-07-14 15:44 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/editors/body/graph-ql-editor.tsx
> +    const newState: Partial<State> = {
personally, I find it much easier to follow what's going on when we don't create intermediate state like this.  We can avoid it by just setting the values that we need to _when_ we need to:

```ts
  async _loadAndSetLocalSchema() {
    const options: OpenDialogOptions = {
      title: 'Import GraphQL introspection schema',
      buttonLabel: 'Import',
      properties: ['openFile'],
      filters: [
        // @ts-expect-error https://github.com/electron/electron/pull/29322
        {
          extensions: ['', 'json'],
        },
      ],
    };

    const { canceled, filePaths: paths } = await electron.remote.dialog.showOpenDialog(options);

    if (canceled) {
      return;
    }

    try {
      const path = paths[0]; // showOpenDialog is single select
      const file = readFileSync(path);

      const content = JSON.parse(file.toString());
      if (!content.data) {
        throw new Error('JSON file should have a data field with the introspection results');
      }

      if (this._isMounted) {
        return;
      }
      this.setState({
        schema: buildClientSchema(content.data),
        schemaLastFetchTime: Date.now(),
        schemaFetchError: null,
        schemaIsFetching: false,
      });
    } catch (err) {
      console.log('[graphql] ERROR: Failed to fetch schema', err);
      if (!this._isMounted) {
        return;
      }
      this.setState({
        schemaFetchError: {
          message: `Failed to fetch schema: ${err.message}`,
          response: null,
        },
        schemaIsFetching: false,
      });
    }
  }
```

If anyone's amenable to it I think it would improve the maintainability of this code to do the above (or something like it).

2021-07-14 15:44 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/editors/body/graph-ql-editor.tsx
> +    const { canceled, filePaths: paths } = await electron.remote.dialog.showOpenDialog(options);
```suggestion
    const { canceled, filePaths } = await electron.remote.dialog.showOpenDialog(options);
```

I think we should not alias this.  It isn't being done to avoid a shadowing of `paths` somewhere else (so far as I can tell), and just adds cognitive overhead (to me).  Maybe it'd be good, in kind, to also do:

```ts
      const filePath = filePaths[0]; // showOpenDialog is single select
      const file = readFileSync(filePath);
 ```
 
 below as well

2021-07-14 15:44 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/editors/body/graph-ql-editor.tsx
>      );
(github won't let me _quite_ select the line I want, but I'm talking here about `_handleRefreshSchema`).

As a user of this, the very first thing I did was change the schema on disk and hit "Refresh Schema":
![image](https://user-images.githubusercontent.com/15232461/125650871-0da10905-97f4-4c0a-b9fd-12cdb0ecceb5.png)


And it just returns the error at the bottom "schema not yet fetched".  I think if we're introducing a local schema option, we really need to handle this case.

2021-07-14 19:36 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/body/graph-ql-editor.tsx
> +      this.setState(existingState => ({ ...existingState, ...newState }));
I did this; if we don't do it this way, newState cannot be a partial. Try it out locally

2021-07-14 19:41 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/body/graph-ql-editor.tsx
>      );
IMO this works the same way as proto files, as a one time import. There's no persistent link to a file on the file system (and I think this is good) such that refresh schema should work for local files.

2021-07-19 21:41 UTC, dimitropoulos approved these changes

2021-07-19 21:42 UTC, develohpanda commented
Thanks for the PR and contribution @lodi-g 😄 We're merging this for functionality, and we'll put in a follow-up PR to address some of the feedback above, as well as a slight improvement to the UX to discern between working with remote schemas (refresh and auto-fetch) and local schemas. 🙌🏽

2021-07-19 22:00 UTC, wdawson approved these changes

2021-07-19 22:02 UTC, merged

2021-07-20 09:08 UTC, lodi-g commented
Thanks for accepting it @develohpanda. I unfortunately did not have the time to address your feedback but I wholeheartedly agree that the UX of my PR can be improved. Cheers! 🍻