Fix swagger import
getinsomnia/insomnia pull request #3804
Opened 2021-07-11 23:13 UTC by vincendep

Closes #3453

2021-07-12 00:57 UTC, develohpanda requested changes
While this does fix the exact bug described it introduces a regression. 

Deterministic IDs are used to ensure that when navigating from design to debug in a design document, the import at that time does not keep creating new requests, which now happens because we always use a unique request ID.

https://www.loom.com/share/772a6123693840a799d23fa072f7ad75

I think the solution may need to explore including the workspace Id as part of the generated request id, so it is unique _per workspace_, but not unique _within_ the same workspace. For example, the openapi-3 importer doesn't exhibit this behavior when working with an equivalent spec, due to it's generated requestId [taking into account](https://github.com/Kong/insomnia/blob/9006babd38aff34917fd351711c0ebcade141d0f/packages/insomnia-importers/src/importers/openapi-3.ts#L550-L573) the workspace it exists in.

My QA steps used the spec defined here: https://github.com/Kong/insomnia/issues/3453#issuecomment-877886904

2021-07-12 22:35 UTC, vincendep commented
Hi! All right I've understood the issue and added some changes looking at the openapi-3 importer.

2021-07-13 05:50 UTC, develohpanda approved these changes
Thanks for updating, seems to be working well now! https://www.loom.com/share/0c4144b467074036b734f3d1692e001e

It's unfortunate but this does mean that anybody that has imported requests previously through the swagger importer, and then tries to import the same spec again, new requests will be generated because the generated ids have changed. 😞 I don't see a clean way out, though

2021-07-13 05:50 UTC, develohpanda commented on packages/insomnia-importers/src/importers/swagger-2.ts
> +      const requestId = `${generateUniqueRequestId(endpointSchema)}_${index > 0 ? index : ''}`;
I think instead of tacking on an index here, it would be better to use the approach used by the openapi-3 importer

https://github.com/Kong/insomnia/blob/9006babd38aff34917fd351711c0ebcade141d0f/packages/insomnia-importers/src/importers/openapi-3.ts#L565-L570

2021-07-13 08:45 UTC, vincendep commented on packages/insomnia-importers/src/importers/swagger-2.ts
> +      const requestId = `${generateUniqueRequestId(endpointSchema)}_${index > 0 ? index : ''}`;
Ok...I was not sure that it was necessary in this case

2021-07-13 09:48 UTC, develohpanda commented on packages/insomnia-importers/src/importers/swagger-2.ts
> +      const requestId = `${generateUniqueRequestId(endpointSchema)}_${index > 0 ? index : ''}`;
Fair enough 😊 i noticed while testing that adding an additional tag to the root and then the operation resulted in the same behaviour as the openapi 3 importer (as it should). So it seems reasonable to keep the implementation/approach similar too

2021-07-13 18:20 UTC, vincendep commented on packages/insomnia-importers/src/importers/swagger-2.ts
> +      const requestId = `${generateUniqueRequestId(endpointSchema)}_${index > 0 ? index : ''}`;
I've updated the importer so now it use the same id generation strategy of the openapi3 importer. 
btw I have some issue running the bootstrap script (again), it keep updating all my package.lock.

2021-07-13 23:33 UTC, develohpanda commented on packages/insomnia-importers/src/importers/swagger-2.ts
> +      const requestId = `${generateUniqueRequestId(endpointSchema)}_${index > 0 ? index : ''}`;
Awesome :) don't worry about the `package-lock.json` since you didn't change any dependencies in this PR - it'll get updated eventually

2021-07-19 21:45 UTC, wdawson commented
> It's unfortunate but this does mean that anybody that has imported requests previously through the swagger importer, and then tries to import the same spec again, new requests will be created (as opposed to existing requests updated) because the generated ids have changed. 😞 I don't see a clean way out, though. @wdawson this likely comes down to communication 🤔

Hmm... Yeah, this is unfortunate. I'm inclined to say that we should keep the existing behavior for now so that the requests would be updated. Unless we can write up a smart way to detect those requests from the spec and/or work around the ID issue, I don't think we should merge this yet. But I could also see a future path that cleanly delineates a workflow for creating a new workspace vs updating existing requests and having "import" and "sync" functionality, respectively. That would take a lot more work though.

2021-09-26 20:03 UTC, skyhirider commented
I  was the one that reported this issue and its not really great - I was showing Insomnia to a colleague explaining why its better than Postman then this bug happened. Postman it remained.

2022-10-11 10:34 UTC, jackkav commented
Closed as stale.

2022-10-11 10:34 UTC, closed without merging