Duplicate from dashboard and from settings
getinsomnia/insomnia pull request #3820
Opened 2021-07-16 01:14 UTC by develohpanda

2021-07-23 20:30 UTC, wdawson approved these changes
Assuming duplicating from a remote to local/base also works ⛵

2021-07-26 13:08 UTC, DMarby commented
@develohpanda Do we need to wire up any logic here to run the same "Setup sync" logic when duplicating into a Remote space, as we do when you create a new collection in a remote space?

2021-07-27 06:18 UTC, develohpanda commented
@DMarby & @wdawson please see the demos in the description again - I updated this to PR to activate/open the workspace after it is duplicated, regardless of if it's duplicated from the dashboard or from settings.

In addition, I updated this PR such that if a user is duplicating _into_ a remote space, and they are logged in, and they are duplicating a request collection (the only thing supported by Insomnia sync right now), the duplicated workspace will automatically connect with sync.

2021-07-27 06:20 UTC, develohpanda commented on packages/insomnia-app/app/ui/redux/modules/workspace.ts
> +export const activateWorkspace = (workspace: Workspace) => {
We activate the workspace in various places; ideally we start using this action in the future

2021-07-27 23:05 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/modals/workspace-duplicate-modal.tsx
> +    {space.name} ({isBaseSpace(space) ? 'Base' : isLocalSpace(space) ? 'Local' : 'Remote'})
since we're using it already in a few places do you think it's worthwhile to put `Base`, `Local`, and `Remote` in `strings.ts` somewhere or something?

2021-07-27 23:07 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/workspace-duplicate-modal.tsx
> +    {space.name} ({isBaseSpace(space) ? 'Base' : isLocalSpace(space) ? 'Local' : 'Remote'})
That seems like a reasonable thing to do

2021-07-27 23:31 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/modals/workspace-duplicate-modal.tsx
> +    {space.name} ({isBaseSpace(space) ? 'Base' : isLocalSpace(space) ? 'Local' : 'Remote'})
does... our Dropdown component not work with react-hook-form?

I was gonna 

<img height="150" src="https://user-images.githubusercontent.com/15232461/127239973-1c206304-e402-4860-84f6-da7e959db077.png" />

gets the icons like
<img height="200" src="https://user-images.githubusercontent.com/15232461/127239976-ec88aa00-3147-4fc8-807d-bf0fd6529425.png" />

But I switched it out real quick for `Dropdown` and `DropdownItem` to see and it did not render.

2021-07-27 23:31 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/modals/workspace-duplicate-modal.tsx
> +  <option key={space._id} value={space._id}>
does... our Dropdown component not work with react-hook-form?

I was gonna 

<img height="150" src="https://user-images.githubusercontent.com/15232461/127239973-1c206304-e402-4860-84f6-da7e959db077.png" />

gets the icons like
<img height="200" src="https://user-images.githubusercontent.com/15232461/127239976-ec88aa00-3147-4fc8-807d-bf0fd6529425.png" />

But I switched it out real quick for `Dropdown` and `DropdownItem` to see and it did not render.

2021-07-27 23:37 UTC, dimitropoulos commented on packages/insomnia-app/app/models/helpers/workspace-operations.ts
> +export async function duplicate(w: Workspace, { name, parentId }: Pick<Workspace, 'name' | 'parentId'>) {
https://user-images.githubusercontent.com/15232461/127240988-c54f9d72-0a90-4285-8c8e-5bfc3eeb3a52.mp4

2021-07-27 23:39 UTC, dimitropoulos commented on packages/insomnia-app/app/sync/vcs/initialize-project.ts
> +  // A race condition causes us to hit this codepath twice while activating a workspace but the first time it has no project so we shouldn't do anything
a race between which two things? (just for my own understanding)

2021-07-27 23:40 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/modals/workspace-duplicate-modal.tsx
> +    const duplicateToSpace = spaces.find(s => s._id === spaceId);
nothing major but `space => space._id` or `({ _id }) => _id` may be a readability improvement here>

2021-07-27 23:44 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/modals/workspace-duplicate-modal.tsx
> +            {strings.space.plural} to duplicate into
```suggestion
            {strings.space.singular} to duplicate into
```

@wdawson I don't know how much you care about stuff like this so I'm moreso asking to learn your preference, but there's an argument to be made here for this to always be singular because we're always copying into a single space (this isn't a multi-select box at this time)?

<img height="150" src="https://user-images.githubusercontent.com/15232461/127241346-fa2cace2-e689-4ce1-833d-6f73525fd51c.png" />

2021-07-27 23:47 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/workspace-duplicate-modal.tsx
> +            {strings.space.plural} to duplicate into
Oops! Yeah this should probably be singular

2021-07-27 23:47 UTC, dimitropoulos commented on packages/insomnia-app/package.json
> +    "react-hook-form": "^7.11.0",
latest is now `7.12.1`

2021-07-27 23:50 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/redux/selectors.ts
> +  (state: RootState) => state.global,
should we have `const selectGlobal = (state: RootState) => state.global` since this is duplicated here?

2021-07-27 23:51 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/redux/modules/workspace.ts
> +export const activateWorkspace = (workspace: Workspace) => {
If you're aware of some I would thoroughly support you notating them briefly in a ticket so we can remember to do this later.

2021-07-27 23:51 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/redux/modules/global.tsx
> +import { GlobalActivity } from '../../../common/constants';
![200](https://user-images.githubusercontent.com/15232461/127241953-223140ca-3e18-445d-823b-86e97616bbcd.gif)

2021-07-27 23:53 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/redux/modules/__tests__/workspace.test.ts
> +        },
whenever the time comes, as an aside, redux toolkit is going to greatly reduce the boilerplate here:

```
.toEqual([
  setActiveSpace(space._id),
  setActiveWorkspace(workspace._id),
  setActiveActivity(ACTIVITY_SPEC),
])
```

2021-07-27 23:54 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/redux/modules/__tests__/workspace.test.ts
> -
wow, nice.

2021-07-27 23:55 UTC, dimitropoulos requested changes
saw some things.  lemme know whatcha think

2021-07-28 01:08 UTC, develohpanda commented on packages/insomnia-app/app/ui/redux/selectors.ts
> +  (state: RootState) => state.global,
Fixed in 16f7b15fc

2021-07-28 01:15 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/workspace-duplicate-modal.tsx
> +  <option key={space._id} value={space._id}>
It should work we'll just need to link up some of the events - for this I used a traditional select (none of the forms in Insomnia use the custom dropdown yet)

2021-07-28 01:26 UTC, develohpanda commented on packages/insomnia-app/app/sync/vcs/initialize-project.ts
> +  // A race condition causes us to hit this codepath twice while activating a workspace but the first time it has no project so we shouldn't do anything
Added more details in comments 9d598a6c53e3f9ea0b40b104678a11b65e2ebaeb

2021-07-28 03:51 UTC, develohpanda commented on packages/insomnia-app/app/models/helpers/workspace-operations.ts
> +export async function duplicate(w: Workspace, { name, parentId }: Pick<Workspace, 'name' | 'parentId'>) {
This is an existing issue that exists with both the Swagger 2 and OpenAPI 3 importers and the way in which they generate IDs.

In the openapi3 importer, a request id is deterministic and includes the workspace id. In the swagger2 importer, a request id is not yet deterministic, see #3804

2021-07-28 04:24 UTC, develohpanda commented on packages/insomnia-app/app/models/helpers/workspace-operations.ts
> +export async function duplicate(w: Workspace, { name, parentId }: Pick<Workspace, 'name' | 'parentId'>) {
See [this thread](https://kongstrong.slack.com/archives/GPARXT60G/p1626052892004200?thread_ts=1626048539.003100&cid=GPARXT60G)

2021-07-28 05:00 UTC, develohpanda commented on packages/insomnia-app/app/ui/redux/modules/workspace.ts
> +export const activateWorkspace = (workspace: Workspace) => {
Drafted a follow-up PR: https://github.com/Kong/insomnia/pull/3856

2021-07-28 05:01 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/workspace-duplicate-modal.tsx
> +            {strings.space.plural} to duplicate into
[`3d1a59f` (#3820)](https://github.com/Kong/insomnia/pull/3820/commits/3d1a59fdc5e2edaf47b7af4266d0b24bfbf33e7e)

2021-07-28 12:13 UTC, develohpanda commented on packages/insomnia-app/app/models/helpers/workspace-operations.ts
> +export async function duplicate(w: Workspace, { name, parentId }: Pick<Workspace, 'name' | 'parentId'>) {
We do need to look into this but because it's behavior that already exists in the app I'm inclined to not change in this PR. Now that we're suggesting duplication as an actual user flow to move a workspace between spaces, we need to address the funkiness that arises

2021-07-28 15:08 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/redux/modules/workspace.ts
> +export const activateWorkspace = (workspace: Workspace) => {
wow! great!  I was just thinkin of having a bulleted list but this is way better! thanks!

2021-07-28 15:09 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/modals/workspace-duplicate-modal.tsx
> +  <option key={space._id} value={space._id}>
well maybe timebox it to 20 minutes or something but it'd be really great to see how react-hook-form looks/works with our standard dropdown.

2021-07-28 15:10 UTC, dimitropoulos commented on packages/insomnia-app/app/models/helpers/workspace-operations.ts
> +export async function duplicate(w: Workspace, { name, parentId }: Pick<Workspace, 'name' | 'parentId'>) {
perfect - just wanted to double triple check that it wasn't a regression in some way or unintended consequence of changes in this PR.  totally not appropriate to solve in this PR - 100% agree

2021-07-28 15:15 UTC, dimitropoulos approved these changes
I'd really love to see us use our Dropdown component with react-hook-form, but it's getting to the end of the sprint and it's not worth blocking this if you don't have time.  everything else looks great!

Nice improvements in practically every PR.  What a life we're livin' with this project.  Fun stuff.

2021-07-28 16:09 UTC, wdawson commented on packages/insomnia-app/app/ui/components/modals/workspace-duplicate-modal.tsx
> +            {strings.space.plural} to duplicate into
Definitely should be singular! Happy to get the pings for this stuff if there's confusion or contention 👍

2021-07-28 20:13 UTC, DMarby approved these changes

2021-07-28 20:40 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/workspace-duplicate-modal.tsx
> +  <option key={space._id} value={space._id}>
Okay! I'll timebox and give it a go, I'd like to use our dropdown as well

2021-07-28 21:49 UTC, merged