[feat] creating a cookie has an extra step
getinsomnia/insomnia pull request #3848
Opened 2021-07-26 18:47 UTC by dimitropoulos

closes: INS-779

2021-07-29 05:24 UTC, develohpanda reviewed
Hmmm I'm experiencing some strange/unexplainable behavior when playing with the raw string - recorded a gif to log keystrokes

![2021-07-29 17 20 00](https://user-images.githubusercontent.com/4312346/127436366-609c629a-7c13-43c2-a40a-a3cf8abeda8a.gif)

On another note, is this a valid cookie (with everything blank)? I think it might be nicer to not add a cookie (into the database) until it's been filled out properly. Right now we add and modify (to fill in details), but I think it might be nicer, as long as it's a valid approach, to collect details and _then_ add.

<img width="863" alt="image" src="https://user-images.githubusercontent.com/4312346/127436228-bd0acbbc-18ee-479a-86ad-cc91b4061a41.png">

2021-07-29 05:24 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/cookie-modify-modal.tsx
> -    this._rawTimeout = setTimeout(async () => {
Why was it doing a timeout previously and why do we no longer need it?

After looking through the implementation I think it makes sense to either keep the debounce here or use a `<DebouncedInput />` component if it's possible, to prevent immediate updates to the database.

I don't think this is a hugely pressing thing because of the context (cookies), but I'm just cautious of removing debounces. Maybe worth checking history about why the debounce exists/was added in the first place?

2021-07-29 05:24 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/cookie-modify-modal.tsx
> +                  Raw Cookie String
I've hit this snag too, is there a lint rule we could use?

```suggestion
                    Raw Cookie String
```

2021-07-29 05:24 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/cookie-modify-modal.tsx
> +export const showModifyCookieModal = (cookie: Cookie) => showModal(CookieModifyModal, cookie);
I like that you're doing this; because we can't get rid of the generic `ShowModal` yet, restricting/hiding it away like this is useful for our type-system (and sanity)

2021-07-29 05:24 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/cookies-modal.tsx
> +                      placeholder="example.com"
👍🏽

2021-07-29 17:15 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/modals/cookie-modify-modal.tsx
> +                  Raw Cookie String
fixed in https://github.com/Kong/insomnia/pull/3860 and 5975f816abe3d29f1236183a21b39a73c5114efb

2021-07-29 17:30 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/modals/cookie-modify-modal.tsx
> -    this._rawTimeout = setTimeout(async () => {
regarding history, I did the full git archaeology and found that it was introduced here https://github.com/Kong/insomnia/commit/9ba6e4710b771bc031e563733c0a48b72cbad8f7 pretty arbitrarily (meaning, in a commit `Some small tweaks` right to develop with no PR and no other description).

-----

It seems clear to me that there were as many as 2 motivations for the debounce:
- the cookie conversion (call to `insomnia-cookies`) may have been viewed as computationally heavy, but, it isn't.
- the writes to the database, see below.

I would like to challenge this based on both subjective and objective findings.

Objectively, as far as NeDB is concerned: it was benchmarked by the author on a "not-so-fast dev machine" _5 years ago_ as follows on a database with 10,000 documents (probably 2 orders of magnitude more than we typically deal with as a maximum):
> * Insert: **10,680 ops/s**
> * Find: **43,290 ops/s**
> * Update: **8,000 ops/s**
> * Remove: **11,750 ops/s**  

This would be a document update so we can very very comfortably assume based on this data that we will never bottleneck the database by hitching-our-wagon to an input.

Subjectively, just try it.  It feels so much smoother and snappy (to me, anyway), and I think this would be the same on low-power devices as well.  Removing the debounce is just an improvement all around because you expect things to update as you type. In fact in my video you can see that I hadn't yet removed the debounce and I thought the demo was failed and that it was broken because it took so long to update.

2021-07-30 03:34 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/cookie-modify-modal.tsx
> -    this._rawTimeout = setTimeout(async () => {
It does feel smoother and snappier for sure. We could reduce the debounce timeout as well, but, in this context I think it's probably fine to remove it altogether.

2021-07-30 03:35 UTC, develohpanda commented
> On another note, is this a valid cookie (with everything blank)? I think it might be nicer to not add a cookie (into the database) until it's been filled out properly. Right now we add and modify (to fill in details), but I think it might be nicer, as long as it's a valid approach, to collect details and then add.

@wdawson would you have any thoughts about this workflow?

2021-07-30 05:05 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/modals/cookie-modify-modal.tsx
> -    this._rawTimeout = setTimeout(async () => {
cool.  we can always add it back if we have a problem.  thanks

2021-07-30 05:40 UTC, dimitropoulos commented
> I think it might be nicer to not add a cookie (into the database) until it's been filled out properly.

I seriously considered doing this but after I looked at it I felt it would balloon the scope of the whole ticket and implementation quite a bit.  This was supposed to be a straightforward little ticket where we improve the UX such that you don't have to click twice.  Remember, adding it to the database before you make changes is the existing behavior in the app right now so this isn't really a change in that regard.  The difference is that before it was added with intentionally invalid values (e.g. a timestamp that's at the maximum we support) and now it's clear.

I found about 5 other things (e.g. removing the tabs, validation for the date, etc.) along the way that were other existing problems and fixed them.  I'd rather call it an evening on this PR/ticket and make new ones if we see fit.

2021-07-30 09:46 UTC, develohpanda commented
> I seriously considered doing this but after I looked at it I felt it would balloon the scope of the whole ticket and implementation quite a bit. This was supposed to be a straightforward little ticket where we improve the UX such that you don't have to click twice. Remember, adding it to the database before you make changes is the existing behavior in the app right now so this isn't really a change in that regard. The difference is that before it was added with intentionally invalid values (e.g. a timestamp that's at the maximum we support) and now it's clear.

That's understandable, but because of the changes in this PR (removing the defaults), we now end up in a state like this after creating a cookie and closing the modal (whereas previously real data was used).

![image](https://user-images.githubusercontent.com/4312346/127634907-905e852b-1d46-4715-8893-f51283868cb2.png)

So, I think while we've made an improvement in some areas we've gone backwards in others and the UX now feels incomplete

2021-07-30 17:29 UTC, dimitropoulos commented
> whereas previously real data was used

This is a key part of where we're seeing things from a different perspective and I'd like you to reconsider.

To me as a user there is nothing whatsoever "real" about a cookie with a key of `foo` and a value of `bar` and an expiration that is literally invalid (because it's the maximum allowable date).  Before it was like comically fake data that was only in your way, almost like a booby trap or something, haha (I say that because there's no real indication to the user that the date that's put in is the maximum and also the format of the date is the _wrong_ format so it guides the user towards the wrong road).  And except for devs working at `domani.com` the domain was also in your way.

To use this form at all in the past you had to manually enter each input and delete each value.  Now you don't.  There was no "real data" before and there's literally nothing valid about the cookie from before `foo=bar; Expires=Tue, 19 Jan 2038 03:14:07 GMT; Domain=domain.com; Path=/` except the last character, `/`, which is a debatably reasonable value.

Still, we're gonna focus on that part in another iteration, so it's no biggie, but I just wanted to try to close the loop on how I'm thinking about it.

2021-08-02 05:37 UTC, develohpanda commented
> To me as a user there is nothing whatsoever "real" about a cookie with a key of foo

I used the wrong wording when talking about "real" data, I was referring to non-empty data (even though it is invalid). From a UX perspective the null-cookie state looks very incomplete (as you allude to in the ticket below).

Not defaulting the fields (as this PR changes) is one step of two; the second being not creating a cookie unless we have all the necessary data. So, on that note, the creation of https://linear.app/insomnia/issue/INS-834/create-a-cookie-modal addresses my concern, and I hope we can address that one soon.

2021-08-10 00:45 UTC, develohpanda requested changes
As a preview, the raw string input seems fine to update as you update the form fields. But the experience of using the raw string is significantly worse than what is in the live version, so much so that I am not confident in approving this PR in the current state. There is also very strange behavior with the time input. A help tooltip is an option that could make the process of entering or modifying the expiry time better, but as it stands it's hard to use.

For some examples, see my QA items below

### QA

<details>
<summary>🔴 Updating the raw string doesn't update the form inputs until hovering on them</summary>

![2021-08-10 12 06 15](https://user-images.githubusercontent.com/4312346/128789354-b9a7424a-2b28-47aa-9053-2ad6d95e31ab.gif)

</details>

<details>
<summary>🔴 Pasting a valid raw string doesn't update the checkboxes form elements until the modal is reopened</summary>

![2021-08-10 12 17 23](https://user-images.githubusercontent.com/4312346/128790083-d109f066-58c8-438d-bcc8-cbbd19addb7f.gif)

</details>

<details>
<summary>🔴 The domain default remains even if the filter is empty</summary>

1. open cookies modal
2. add filter (abcd.com)
3. add new cookie, notice domain exists as filter (abcd.com)
4. close modify cookie modal
5. close cookies modal
6. open cookies modal
7. notice filter is empty
8. add new cookie, notice domain exists as the previous filter (abcd.com)

![2021-08-10 12 11 07](https://user-images.githubusercontent.com/4312346/128789662-bc07f235-55f9-4af9-8606-634495dda2c2.gif)

</details>

<details>
<summary>🔴 Strange behavior with the filter</summary>

1. open cookies modal
2. add filter (abcd.com)
3. add new cookie
4. close modify cookie modal
5. notice 0 cookies in list
6. close cookies modal
7. open cookies modal
8. notice 1 cookie in list
9. add new cookie
10. close modify cookie modal
11. notice 1 cookie in list
12. close cookies modal
13. open cookies modal
14. notice 2 cookie in list
15. and so on...

![2021-08-10 12 27 01](https://user-images.githubusercontent.com/4312346/128790694-8e1b808a-0529-4307-8cdd-f8889a81665a.gif)

</details>

<details>
<summary>🔴 Raw editor is mostly unusable</summary>

In the current live version of Insomnia, I am able to type in, for example, `; Secure; HttpOnly` at the end of the raw string.

![2021-08-10 12 30 31](https://user-images.githubusercontent.com/4312346/128790860-df2ac729-2c1c-43cd-8045-1a9692adb7b1.gif)

On this branch, I am unable to type `;` at the end of the string to append to it

![2021-08-10 12 33 38](https://user-images.githubusercontent.com/4312346/128791046-ccd0b2d1-6375-415c-8da9-1fdd0ec97b60.gif)

Typing a raw cookie is also really hard

![2021-08-10 12 37 44](https://user-images.githubusercontent.com/4312346/128791304-409583c2-62be-4638-af28-9f1f64d788ed.gif)

</details>

<details>
<summary>🔴 The time disappears/changes (seemingly) randomly</summary>

As soon as I start typing, the placeholder disappears so I can't see the expected format either. Using a regular number (as before) doesn't work anymore.

![2021-08-10 12 39 09](https://user-images.githubusercontent.com/4312346/128791622-11463dc0-4b07-4b51-9cf2-7a8df85c5ad8.gif)

</details>

2021-08-10 00:45 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/cookie-modify-modal.tsx
> +      const cookie: Cookie = toughCookie.Cookie.parse(value)?.toJSON();
Since this line contains optional chaining, I would be inclined to type this cookie as `Cookie | undefined` and handle the `undefined` case, otherwise I would remove the optional chain

2021-08-10 00:45 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/cookie-modify-modal.tsx
> +      console.warn(`Failed to parse cookie string "${value}"`, err);
This error message no longer encapsulates the logic the `try-catch` has wrapped. Previously it was only handling errors thrown by `toughCookie.Cookie.parse` so the verbiage was appropriate, but now the try block is doing more than just parsing the cookie string.

It would be good to either a) refactor such that only the parse is being wrapped by this try-catch, or b) update the message verbiage. Personally I think option A is the one to go with but I'll let you decide

2021-08-10 00:45 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/cookie-modify-modal.tsx
> +  validateExpires() {
Would be nice to see unit tests for this new validation logic

2021-08-10 00:45 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/cookie-modify-modal.tsx
> +                    <label key={field}>
:+1:

2021-08-10 19:52 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/modals/cookie-modify-modal.tsx
> +  validateExpires() {
It isn't really validation logic, I've learned.  It only happens when the the toughCookie parsing fails.  date handling was deeply broken before this PR (you couldn't ever edit it after the first time) and to really fix this we need to go a lot deeper on this specific field (and, more than likely, update toughCookie along the way).

2021-08-11 02:00 UTC, dimitropoulos commented
(we are pausing on this until after the spaces release.  I pushed what I had for now.)

2022-10-11 10:26 UTC, jackkav commented
Closed as stale.

2022-10-11 10:26 UTC, closed without merging