[feat] Sort Dashboard Cards
getinsomnia/insomnia pull request #3850
Opened 2021-07-27 13:25 UTC by gatzjames

Adds the ability to sort the dashboard cards by
- Last Modified
- Name (Ascending/Descending)
- Newest/Oldest

The UI is similar to the one used in the Collection list and the selected option is persisted in the Space model.

![image](https://user-images.githubusercontent.com/12115431/127160110-5bc042de-cdc6-4402-9633-28d616996ed9.png)

Some concerns regarding this feature:
- [ ] Not sure the UI works fine for users that use the Team plan
- [ ] Does adding a new option to the Space model require a migration? For now this uses the LastModified as a default sorting option in case a space doesn't have one.

Closes: INS-543

2021-07-27 19:34 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +      default:
seems like we need to add `DateModifiedAscending` to `SpaceItemsSortOrder` and include that case here and use `unreachableCase`.

```ts
...
      case 'DateCreatedDescending':
        return cardB.workspace.created - cardA.workspace.created;
      case 'DateModifiedAscending':
        return cardB.lastModifiedTimestamp - cardA.lastModifiedTimestamp;
      default:
        unreachableCase(orderBy, `space card ordering "${orderBy}" is invalid`);
    }
...
```

2021-07-27 19:36 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +      </DropdownItem>
@develohpanda what are your thoughts on the approach taken here (i.e. not mapping a data structure).  @gatzjames and I had already talked about it but I'm curious what you think.

2021-07-27 19:38 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +> | null {
Is there a reason to specify all of this?  seems like typescript infers it just fine?

![Screenshot_20210727_153720](https://user-images.githubusercontent.com/15232461/127216939-5a821fea-34c7-4757-a718-d27244ed1c32.png)

2021-07-27 19:41 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +      .sort(orderSpaceCards(activeSpace?.order || 'DateModifiedDescending'))
`DateModifiedDescending` if this is truly the default, then should it be handled in the `default` of the case statement inside `orderSpaceCards`?

2021-07-27 19:44 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +          workspace,
up to you, but if this is the way it's designed to be used (mapping on workspaces) it may be more natural/better to do

```ts
interface MapWorkspaceToWorkspaceCardInput {
  apiSpecs: ApiSpec[];
  workspaceMetas: WorkspaceMeta[];
  filter: string;
}

const mapWorkspaceToWorkspaceCard = (input: MapWorkspaceToWorkspaceCardInput) => (workspace: Workspace) =>  {
```

which will enable us to compose this better e.g.
```ts
      .map(mapWorkspaceToWorkspaceCard({
        workspaceMetas,
        apiSpecs,
        filter,
      }))
```

2021-07-27 19:48 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +  filter: string;
it appears that `filter` is unused.

see https://github.com/Kong/insomnia/pull/3850/files#r677748563 for more context, but this kind of thing is one of the reasons I find it better to do these kinds of things inline because it's much harder to make the mistake of leaving something there that isn't actually needed (anymore).

2021-07-27 20:05 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +function WorkspaceCard(props: WorkspaceCardProps) {
is there any way we can move this component out of `wrapper-home`?  I'd really love to hear that we can, if we can.

we're trying to reduce all the "single responsibility" breakage in this file.  I know some of this was already here, but this is a fine time to correct course in the direct context of what you're working on.

2021-07-27 20:10 UTC, dimitropoulos commented on packages/insomnia-app/app/models/space.ts
> +  order: SpaceItemsSortOrder;
is `order` really clear enough? are we going to regret this later when some other aspect of spaces needs to be ordered, you know?

I was gonna suggest `dashboardOrder` but then I realized that that's a bad idea because I absolutely expect this to be at least _potentially_ usable for more things that just the dashboard (e.g. in a dropdown of spaces to select, maybe, at some time).

@develohpanda any ideas?

2021-07-27 20:15 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +    workspaceMeta?.cachedGitLastCommitTime,
so here we use `workspaceMeta?.cachedGitLastCommitTime` instead of `lastCommitTime` from above (which is the same thing).  as a reader, I find this confusing and arbitrary.  I would rather just use the actual values and then assign them new names if we have to, but directly in the object that this function returns.

2021-07-27 20:16 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +  // @TODO Figure out how we should handle a missing timestamp
@develohpanda any suggestions on this?

2021-07-28 06:03 UTC, develohpanda commented
A couple of initial notes, haven't had a chance to fully review yet

2021-07-28 06:04 UTC, develohpanda commented on packages/insomnia-app/app/common/misc.ts
> +export function isNotNullOrUndefined<ValueType>(
Love to see it

2021-07-28 06:04 UTC, develohpanda commented on packages/insomnia-app/app/models/space.ts
> +  order: SpaceItemsSortOrder;
There is a question here I'd like to pose to @wdawson first.

Should the workspace sort order be on a _per space_ basis, or for _all spaces on the client_? IMO, the latter.

In some future state we do expect to be able to export and share a space, and in that case the sorting will also be shared. This isn't desirable though (right?). Sorting is always a user specific, it's a user preference.

So IMO this doesn't belong on the `Space` model at all, it belongs in the Settings object, potentially as a `dashboardSortOrder` setting.

2021-07-28 06:04 UTC, develohpanda commented on packages/insomnia-app/app/ui/redux/modules/space.ts
> +  };
Usually a helper like this would just sit on the space itself, it doesn't need to be in `redux/modules/...` because it doesn't use state or dispatch in any way

2021-07-28 06:04 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +    }
Is it possible to use the sort methods available in https://github.com/Kong/insomnia/blob/0178533e5284cbcaff2c39a4ba2d560b16422e4c/packages/insomnia-app/app/common/sorting.ts? These are all unit tested properly, it would be nice to re-use. It does seem possible without any major refactoring

2021-07-28 06:04 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +function OrderFilterDropdown(props: OrderFilterDropdownProps) {
Just to follow the pattern in this code-base for function components (inline arrow-funcs typed with FC<>), I suggest `const OrderFilterDropdown: FC<OrderFilterDropdownProps> = ({ onSelect }) => <Dropdown />`

2021-07-28 06:04 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +      </DropdownItem>
I feel strongly that mapping a data structure (like https://github.com/Kong/insomnia/blob/0178533e5284cbcaff2c39a4ba2d560b16422e4c/packages/insomnia-app/app/ui/components/sidebar/sidebar-sort-dropdown.tsx) is a more stable approach for something like this.

As one example of a benefit, it couples the sort type/label _and_ the handler, which means you can't have one without the other. In the current implementation, I will be allowed to remove the "NameAscending" switch case in the sort handler, for example, but the dropdown item will still exist. The only time I will notice this mismatch is in runtime.

Why did you choose to do it this way (without a map) and what are your thoughts on it; what am I missing?

2021-07-28 06:04 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +  const workspaceModified = workspaceMeta?.modified;
The previous implmenetation used `workspace.modified` if `workspaceMeta` didn't exist

2021-07-28 06:04 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +  lastActiveBranch?: string | null;
Now that we're cleaning this up I think we should avoid the optional and nullable properties; rather standardize to optional

`lastActiveBranch?: string`

2021-07-28 06:04 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +function WorkspaceCard(props: WorkspaceCardProps) {
I agree with this, the sort dropdown and workspace card can be standalone components in separate files

2021-07-28 06:04 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +  // @TODO Figure out how we should handle a missing timestamp
Can we investigate how we can end up in a state where `lastModifiedTimestamp` is falsey? It doesn't feel like this is a valid situation so there might be a typing issue further up.

2021-07-28 06:04 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +        <TimeFromNow className="text-danger" timestamp={modifiedLocally || new Date()} /> (unsaved)
I don't think `new Date()` is a reasonable value to put here as a fallback :thinking:

2021-07-28 12:10 UTC, develohpanda commented
> Does adding a new option to the Space model require a migration? For now this uses the LastModified as a default sorting option in case a space doesn't have one.

Nope; migrations in this app aren't akin to regular database migrations introducing a new column for instance. Migrations can be used to change entities as required, but because the Insomnia database is essentially a document store, we just need to add a property, give it a default, and that property will be added to all existing documents/entities on launch

2021-07-28 16:06 UTC, wdawson commented on packages/insomnia-app/app/models/space.ts
> +  order: SpaceItemsSortOrder;
Yeah, I would think the sort order should be ephemeral (not stored with the data). How you want the APIs sorted on your screen feels like a separate concern to what a Space is. I could see the simplest thing to be to have a client-side cross-Space preference for how you want to sort the dashboards (i.e. alphabetical, recently updated, created, etc.)

2021-07-28 16:25 UTC, gatzjames commented on packages/insomnia-app/app/models/space.ts
> +  order: SpaceItemsSortOrder;
@dimitropoulos agree on the naming not being clear enough. Some other thoughts I had: `sortOrder`, `sortWorkspacesBy`

@develohpanda I initially had the same thought on using a global setting.
My thoughts on having a different sort order per space is that updating the current view of a Space shouldn't affect other views outside of it.
As a user I would switch to another space, change the sort order, go back to the previous space and now everything would look different.
It would also make things cleaner if we were getting the space items list by calling an api where with a global orderBy filter we would have to re-fetch the data for a view that the user might have just visited.
That said, I also wouldn't want to bloat the Space model if this isn't true from a UX perspective.

2021-07-28 17:44 UTC, wdawson commented on packages/insomnia-app/app/models/space.ts
> +  order: SpaceItemsSortOrder;
> As a user I would switch to another space, change the sort order, go back to the previous space and now everything would look different.

I agree that it would be confusing depending on how the UX behaved. However, I'd expect switching spaces to be relatively rare. And if you switched space A from alphabetical to most recently created (for example), I don' think that it's completely unexpected for space B to also be sorted that way. What makes it slightly more challenging from a UX perspective is that the attributes you can sort by are not all show on the cards, so it's a bit ambiguous as to how they are sorted sometimes.

2021-07-28 19:03 UTC, dimitropoulos commented on packages/insomnia-app/app/models/space.ts
> +  order: SpaceItemsSortOrder;
> the attributes you can sort by are not all show on the cards

This completely changed my mind.  After reading and considering this it seems clear that it needs to be global.  It's just too fiddly to grok all the different states.  In fact, maybe we should duplicate this setting in the main settings so people can configure it there as well?

2021-07-28 19:55 UTC, wdawson commented on packages/insomnia-app/app/models/space.ts
> +  order: SpaceItemsSortOrder;
I always hesitate to duplicate settings. I would rather it stay out of a settings menu that is away from the context of the thing they are changing. But @erickrico may have other opinions that I would trust more.

2021-07-28 21:23 UTC, develohpanda commented on packages/insomnia-app/app/models/space.ts
> +  order: SpaceItemsSortOrder;
It doesn't need any kind of duplication in settings/Preferences modal. The dropdown on the dashboard can be connected to and update the single global settings field.

Speaking of, since we're persisting this sort order, we should also show a tick for which sort order is selected (similar to how we show a tick to indicate which space is selected)

2021-08-04 05:26 UTC, develohpanda requested changes
Nice one; I tested it locally and it seems to be working well! The sort functionality was built in Flow and it's nice to see it receive some TS love. It's not completely there yet, but it is close; with a few minor changes we can remove a lot of repetition which I hope to address after this PR is merged in. 🙌🏽 

I have a couple of observations and notes that ideally need to be addressed. Most importantly, we should avoid deviating from existing patterns, and if we want to change the existing pattern we should apply that change to all uses of that pattern. I understand that we are making incremental improvements to this codebase but in that process we shouldn't end up in a state where we have multiple naming patterns/implementation patterns for the same underlying concept. In particular this feedback applies to how the `spaceSortOrder` is being initialized from local storage into redux, but it applies generally as well.

Could you also please the previous review comments as resolved and/or link to the commit where it was address, but at the very least mark as resolved; I think you'll find that some of the comments have been missed (eg. one of the sort options isn't available in the dropdown, and I don't know if that's intentional or it was missed).

Lastly, as an aside, while you are self-reviewing this PR, could you please make sure to exclude any extra changes that get included as a result of formatting rules in your code-editor (I presume)? It reduces the noise in a code-review and thus helps to review faster. I'm on board (and encourage) if we want to change any lint & formatting rules, but ideally we should avoid allowing smaller formatting user preferences from sneaking in with PRs.

2021-08-04 05:26 UTC, develohpanda commented on packages/insomnia-app/app/common/constants.ts
> +export const SORT_TYPE_ASC = 'type-asc';
Curious why you removed the type from these?

2021-08-04 05:26 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +  return (cardA: Pick<WorkspaceCardProps, 'workspace' | 'lastModifiedTimestamp'>, cardB: Pick<WorkspaceCardProps, 'workspace' | 'lastModifiedTimestamp'>) => {
What is the rationale behind making these props `Pick<WorkspaceCardProps, ...>` instead of the entire `WorkspaceCardProps` interface?

2021-08-04 05:26 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +      default:
Unless I am missing something, it looks like this comment still needs to be addressed.

2021-08-04 05:26 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +import OrderFilterDropdown from './dropdowns/space-sort-dropdown';
Aliasing default exports like this has been used (historically) in a few places and it's _so confusing_ when debugging through it. We are moving away from default exports and unnecessary aliasing anywhere, but especially from aliasing component names and their imports in this way. Let's change `SpaceSortDropdown` to be a named export.

2021-08-04 05:26 UTC, develohpanda commented on packages/insomnia-app/app/ui/redux/modules/global.tsx
> +export const initActiveSpace = () => (dispatch) => {
This initialization helper, the same as `initActiveWorkspace` and `initActiveActivity` should only serve one purpose, to initialize the active space from local storage. I don't think initializing any other loosely related properties should happen here.

We should instead create a separate initializer to for the sort order named `initSpaceSortOrder`, which should only serve one purpose and should be nearly identical to the existing ones in terms of logic and functionality.

Once they are individual functions serving one purpose, then this refactor to a thunk won't be necessary either.

2021-08-04 05:26 UTC, develohpanda commented on packages/insomnia-app/app/ui/redux/modules/__tests__/global.test.ts
> +        'type': 'global/space-sort-order',
Should be using the exported constant rather than hard-coding a string

2021-08-04 05:26 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +    setSpaceSortOrder: bound.setSpaceSortOrder,
Please use `handleSetSpaceSortOrder` even though the `handleSet...` wording seems redundant. Consistency is king; if we want to drop the `handle` terminology we certainly can but mix-matched naming leads to an overhead

2021-08-04 05:26 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +          onSelect={(value) => activeSpace && setSpaceSortOrder(value)}
Why is the `activeSpace` check necessary here?

2021-08-04 05:26 UTC, develohpanda commented on packages/insomnia-app/app/ui/redux/selectors.ts
> +);
This should be the following to match the existing global selectors (see the bottom of this file)

```suggestion
export const selectSpaceSortOrder = createSelector(
  selectGlobal,
  global => global.spaceSortOrder,
);
```

2021-08-04 05:56 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +      default:
Just noticed that the Linear ticket specifies the criteria as below

* Alphabetical (asc/desc)
* Creation Date (asc/desc)
* Last Modified (Default)

I will create a follow-up ticket to address this

2021-08-04 06:01 UTC, develohpanda commented on packages/insomnia-app/app/models/space.ts
> +  order: SpaceItemsSortOrder;
> Speaking of, since we're persisting this sort order, we should also show a tick for which sort order is selected (similar to how we show a tick to indicate which space is selected)

Added a linear ticket to address this: INS-842

2021-08-04 07:56 UTC, gatzjames commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +          onSelect={(value) => activeSpace && setSpaceSortOrder(value)}
Nice one. Removed the check

2021-08-04 07:59 UTC, gatzjames commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +    setSpaceSortOrder: bound.setSpaceSortOrder,
Updated! Agree on consistency plus naming is hard 💯

2021-08-04 08:01 UTC, gatzjames commented on packages/insomnia-app/app/ui/redux/modules/global.tsx
> +export const initActiveSpace = () => (dispatch) => {
Good one. My reasoning was to put together all things related to initialising a space together but that could be another fn that calls these but that's out of this context.

2021-08-04 08:08 UTC, gatzjames commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +  return (cardA: Pick<WorkspaceCardProps, 'workspace' | 'lastModifiedTimestamp'>, cardB: Pick<WorkspaceCardProps, 'workspace' | 'lastModifiedTimestamp'>) => {
The WorspaceCard also accepts the `onSelect, activeSpace, filter` props which are required and not available on the orderSpaceCards fn. We could also make another type e.g.

```
interface SortableWorkspaceCard {
  workspace: Workspace;
  lastModifiedTimestamp: number;
}
``` 

and change it like that:

```suggestion
  return (cardA: SortableWorkspaceCard, cardB: SortableWorkspaceCard) => {
```

2021-08-04 08:19 UTC, gatzjames commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +        <TimeFromNow className="text-danger" timestamp={modifiedLocally || new Date()} /> (unsaved)
Agree. Added a check to update the log if the modifiedLocally has a value.
This probably won't be needed once we remove null from the types.

2021-08-04 08:22 UTC, gatzjames commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +  lastActiveBranch?: string | null;
I tried removing null from the types but the changes required touch a lot of files and logic.
I'd suggest making another PR for removing null from our types.

2021-08-04 08:23 UTC, gatzjames commented on packages/insomnia-app/app/ui/redux/modules/space.ts
> +  };
Removed and using redux store for persistence.

2021-08-04 08:26 UTC, gatzjames commented on packages/insomnia-app/app/models/space.ts
> +  order: SpaceItemsSortOrder;
Great feedback 🙏. Updated the sort order is persisted in the localStorage and the global state in redux.

2021-08-04 08:28 UTC, gatzjames commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +          workspace,
Nice one I also think currying makes it cleaner!

2021-08-04 08:34 UTC, gatzjames commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +      </DropdownItem>
I tried to follow the write-what-you-know approach tbh. Wasn't sure how things were going to evolve e.g. what would happen if we wanted to add a separator between different items etc. I prefer to have the view logic e.g. how something is going to be shown and interacted with, separate from the data layer as they usually deviate. I agree that this is a more stable approach though plus it makes it more consistent with how things are done in the codebase so I updated it accordingly!

2021-08-04 08:42 UTC, gatzjames commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +      default:
Added the unreachableCase handler for the default switch case. 
One thing I wanted to share is that TS will check if all possible values of the switch value are handled and if not will require a default case which I think makes it redundant.

@develohpanda yep showing the First Modified(modified-asc) option might not be what users want plus I think we should add it to the other sorting dropdowns if that's the case for consistency.

2021-08-04 15:00 UTC, gatzjames commented on packages/insomnia-app/app/common/constants.ts
> +export const SORT_TYPE_ASC = 'type-asc';
They are now being used as values for the SpaceSortOrder type too, plus declaring a const string as a union type doesn't provide any additional value (except autocomplete choice) since they are treated as literal types by TS.

2021-08-04 15:01 UTC, gatzjames commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +> | null {
Fixed and now uses the curry version of the fn

2021-08-05 04:20 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +      default:
There was a hotfix we had to do a while back because a default case wasn't handled: https://github.com/Kong/insomnia/pull/3778 & https://github.com/Kong/insomnia/pull/3779. Maybe TS requires strict mode enabled before it errors for these, but until then we'll want to keep using the lint rule and `unreachableCase`

2021-08-05 04:28 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +      </DropdownItem>
Thanks for sharing your approach!

> Wasn't sure how things were going to evolve e.g. what would happen if we wanted to add a separator between different items etc.

Would you agree that we also shouldn't be preparing for an unknown future state? If it evolves, so does the implementation at that time.

> I prefer to have the view logic e.g. how something is going to be shown and interacted with, separate from the data layer as they usually deviate.

This is case-by-case though, isn't it; in this case the view and data layers _shouldn't_ deviate ever. That is to say, every dropdown item should have a handler and we should try and make it as difficult as possible for a handler to _not_ exist. In the initial implementation, how might you avoid a bug caused by a typo in the `value` prop? For example, if you defined `DateCreatedDescending` incorrectly as `CreatedDateDescending`?


Of course it's a balance because we could go to extremes in either direction but if we make it harder for us to make mistakes it's definitely a win IMO

2021-08-05 04:32 UTC, develohpanda commented on packages/insomnia-app/app/common/constants.ts
> +export const SORT_TYPE_ASC = 'type-asc';
Gotcha; yep the autocomplete choice was the only reason the type existed in the first place. Enums aren't useful everywhere, and this is also a remnant of Flow (which doesn't support enums) but I think this is a great candidate for TS enums in a future refactor

2021-08-05 04:34 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper-home.tsx
> +  return (cardA: Pick<WorkspaceCardProps, 'workspace' | 'lastModifiedTimestamp'>, cardB: Pick<WorkspaceCardProps, 'workspace' | 'lastModifiedTimestamp'>) => {
Ah I understand. That's fine for the scope of this PR I think though this card logic could use another sweep further down the track. It just feels more complex than it realistically needs to be (not as a result of this PR, just the original implementation to begin with)

2021-08-05 04:35 UTC, develohpanda commented on packages/insomnia-app/app/ui/redux/modules/global.tsx
> +export const initActiveSpace = () => (dispatch) => {
Gotcha; there is a common fn that calls all the initializers already so I see the `initSpaceSortOrder` just adding into that. Is that what you meant?

https://github.com/Kong/insomnia/blob/37815afd2e8774fe1da9211367f3cc7cfaba2c60/packages/insomnia-app/app/ui/redux/modules/global.tsx#L729-L729

2021-08-05 05:43 UTC, develohpanda approved these changes
Wooohooo!

![2021-08-05 17 36 15](https://user-images.githubusercontent.com/4312346/128296863-cbafcd7d-39e9-46fe-a537-a8e39d19619e.gif)

2021-08-05 05:43 UTC, develohpanda commented on packages/insomnia-app/app/ui/redux/modules/global.tsx
> +export function initSpaceSortOrder() {
Thanks for splitting this out ❤️

2021-08-05 16:55 UTC, wdawson approved these changes
Going off Opender's gif, looks great! ⛵

2021-08-05 17:38 UTC, merged