Space Sync Error improvement
getinsomnia/insomnia pull request #3923
Opened 2021-08-17 16:14 UTC by dimitropoulos

2021-08-17 16:15 UTC, dimitropoulos commented on packages/insomnia-app/app/sync/vcs/util.ts
> +      throw new Error(`You no longer have permission to ${action} the "${resourceName}" ${resourceType}.  Contact your team administrator if you think this is an error.`);
I'm thinkin' since we don't actually use the stack trace, there's nothing really being lost by the re-throw working as it does.  thoughts?

2021-08-17 23:36 UTC, develohpanda commented on packages/insomnia-app/app/sync/vcs/util.ts
> +      throw new Error(`You no longer have permission to ${action} the "${resourceName}" ${resourceType}.  Contact your team administrator if you think this is an error.`);
I'm ok with that in order to not block this PR. In the future it might be better to throw custom errors and send the existing error internally, following something like this example

https://github.com/Kong/insomnia/blob/0ef92797cdad1606df31bbf34f9047670f0c609d/packages/insomnia-inso/src/errors.ts#L3-L22

2021-08-18 00:00 UTC, develohpanda commented on packages/insomnia-app/app/sync/vcs/util.ts
> +    console.log('trying');
```suggestion
```

2021-08-18 00:00 UTC, develohpanda commented on packages/insomnia-app/app/sync/vcs/util.ts
> +    console.log('catching', error);
```suggestion
```

2021-08-18 00:00 UTC, develohpanda commented on packages/insomnia-app/app/sync/vcs/vcs.ts
> +    await this.setProject(project);
This change doesn't make sense; now, if a project is not found by `_getProjectByRootDocument` we exit instead of setting `this._project` to null...?

2021-08-18 00:22 UTC, dimitropoulos commented on packages/insomnia-app/app/sync/vcs/util.ts
> +    console.log('trying');
ugg. sorry.  I did a self review (before the squash) and removed a few of these but clearly I didn't get them all.

2021-08-18 00:23 UTC, dimitropoulos commented on packages/insomnia-app/app/sync/vcs/util.ts
> +    console.log('trying');
fixed in 285787a7948940524d3bc59451c0df83a86da6ce

2021-08-18 00:23 UTC, dimitropoulos commented on packages/insomnia-app/app/sync/vcs/util.ts
> +    console.log('catching', error);
285787a7948940524d3bc59451c0df83a86da6ce

2021-08-18 00:25 UTC, dimitropoulos commented on packages/insomnia-app/app/sync/vcs/vcs.ts
> +    await this.setProject(project);
I don't understand your feedback, could you please rephrase?  Before it was doing "if it's not equal to null set it otherwise set it equal to null".  now it's saying "if it's already null then you're all done.  if not, then set it"

2021-08-18 00:26 UTC, dimitropoulos commented on packages/insomnia-app/app/sync/vcs/vcs.ts
> +    await this.setProject(project);
I'm not married to this change being in this PR, btw, if you wanna have it removed - just seemed like an obvious change to make when we were looking at it to increase reading comprehension of the thing we were trying to debug to make this PR happen.

2021-08-18 00:27 UTC, develohpanda commented on packages/insomnia-app/app/sync/vcs/vcs.ts
> +    await this.setProject(project);
but `project`, the constant in this scope being checked in the if condition, is different to `this._project`, the class property being set in the if-else block

2021-08-18 00:30 UTC, develohpanda commented on packages/insomnia-app/app/sync/vcs/vcs.ts
> +    await this.setProject(project);
The previous implementation was:

```ts
const foo = await this._getProjectByRootDocument();
if (foo !== null) {
	await this.setProject(foo);
} else {
	this._project = null;
}
```

But the updated implementation is

```ts
const foo = await this._getProjectByRootDocument();
if (foo === null) {
	return;
}

await this.setProject(foo);
```

The two are fundamentally different, there's nothing that is setting `this._project = null` in the updated implementation

2021-08-18 00:46 UTC, develohpanda commented on packages/insomnia-app/app/sync/vcs/vcs.ts
> +    await this.setProject(project);
(I posted this before by GH landed in a bugged state...)

The previous implementation was:

```ts
const foo = await this._getProjectByRootDocument();
if (foo !== null) {
	await this.setProject(foo);
} else {
	this._project = null;
}
```

But the updated implementation is

```ts
const foo = await this._getProjectByRootDocument();
if (foo === null) {
	return;
}

await this.setProject(foo);
```

The two are fundamentally different, there's nothing that is setting `this._project = null` in the updated implementation

2021-08-18 09:34 UTC, DMarby requested changes

2021-08-18 09:34 UTC, DMarby commented on packages/insomnia-app/app/sync/vcs/vcs.ts
> +    await this.setProject(project);
This change definitely needs to be reverted, if switching from a workspace with sync setup to a workspace that does not have sync setup, it will not correctly clear the state of the VCS instance after this change.

2021-08-18 09:34 UTC, DMarby commented on packages/insomnia-app/app/ui/hooks/workspace.ts
> +      const newVCS = new VCS(driver);
Please revert this change as well.

While this change **should** work correctly, given how brittle our sync-related code is and the customer impact of things breaking, and that this PR needs to be included in the upcoming release, please avoid any changes that are not strictly needed.

2021-08-18 12:12 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/hooks/workspace.ts
> +      const newVCS = new VCS(driver);
sure: @develohpanda sent me this code and asked me to change it while we were working on it - happy to remove.  I think he was saying we are trying to move all of the new instance methods to something like this.

2021-08-18 12:16 UTC, dimitropoulos commented on packages/insomnia-app/app/sync/vcs/vcs.ts
> +    await this.setProject(project);
sorry, my brain crossed `this.project` and `project`.  definitely a bad change.  @develohpanda and I (but ultimately me) made this change in a live share when we were debugging like 4 things at once and I think that's where blindness came from.  neither of us noticed at the time - glad we caught it now.  thanks.  fixed in 75c750c0dc53e4b876cc438202ebf5b7e638a43e

2021-08-18 12:17 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/hooks/workspace.ts
> +      const newVCS = new VCS(driver);
removed in 3dd4587994acf415224dfc5f3a3f24e0aae943cc

2021-08-18 12:19 UTC, dimitropoulos commented on packages/insomnia-app/app/sync/vcs/util.ts
> +      throw new Error(`You no longer have permission to ${action} the "${resourceName}" ${resourceType}.  Contact your team administrator if you think this is an error.`);
since we were both working on this simultaneously should I wait for the solution you come up with after https://github.com/Kong/insomnia/pull/3920 or is now a good time to make the helper, myself?  Since it'll be a good few hours until you get a chance to read this I think I might try (in a separate PR).

2021-08-18 12:24 UTC, develohpanda commented on packages/insomnia-app/app/sync/vcs/util.ts
> +      throw new Error(`You no longer have permission to ${action} the "${resourceName}" ${resourceType}.  Contact your team administrator if you think this is an error.`);
That PR is unrelated to this area (that's to do with O2K) and there's no simultaneous work happening so no risk of conflict or overwrite. Up to you how you'd like to go about it :)

2021-08-18 17:13 UTC, DMarby requested changes
Seems to work well for the operations that it's intercepting, it's not currently intercepting all pulls or pushes as it should however:
![2021-08-18 19 11 50](https://user-images.githubusercontent.com/174626/129942463-4ae22829-7b7c-4b85-9d1e-81b7f0eca3f9.gif)

To intercept that (as well as pushes directly from the sync menu), the following pull and push calls needs to be intercepted as well: https://github.com/Kong/insomnia/blob/0ef92797cdad1606df31bbf34f9047670f0c609d/packages/insomnia-app/app/ui/components/dropdowns/sync-dropdown.tsx#L229
https://github.com/Kong/insomnia/blob/0ef92797cdad1606df31bbf34f9047670f0c609d/packages/insomnia-app/app/ui/components/dropdowns/sync-dropdown.tsx#L249

It's also not intercepting the loading of remote branches in the branches modal: 
![image](https://user-images.githubusercontent.com/174626/129942971-ceeb29d8-dc86-4bc6-8364-ce336f889cf8.png)

2021-08-18 19:42 UTC, dimitropoulos commented on packages/insomnia-app/app/sync/vcs/util.ts
> +      throw new Error(`You no longer have permission to ${action} the "${resourceName}" ${resourceType}.  Contact your team administrator if you think this is an error.`);
see: https://github.com/Kong/insomnia/pull/3925

2021-08-18 19:43 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/hooks/workspace.ts
> +      const newVCS = new VCS(driver);
fixed in 5956617b069b2348d303062244908d27c730779a

2021-08-19 00:05 UTC, develohpanda commented on packages/insomnia-app/app/ui/hooks/workspace.ts
> +      const newVCS = new VCS(driver);
Just for context here, because I didn't ask to make this improvement just because we're in the area.

We were debugging the class instance error we faced with the VCS class, but that ended up being related to closures and not how the instance was being created. Although this is something we do need to look into, it was no longer necessary for this PR so in the future we should remove our WIP changes

2021-08-19 19:52 UTC, dimitropoulos commented
@DMarby here's an example of the push error (pull was also protected):
![Screenshot_20210819_155117](https://user-images.githubusercontent.com/15232461/130134857-95f4b5fb-bcfb-4003-9da0-5f13700df46b.png)


and here's an example of the remote ones
![Screenshot_20210819_155043](https://user-images.githubusercontent.com/15232461/130134778-09578ca3-827a-4e07-9744-a2ba11d76835.png)

check out 7b94cfee855db8914c60896ef4d976b7b3d33d46

2021-08-20 06:33 UTC, develohpanda commented
Code LGTM, haven't had a chance to QA

2021-08-20 11:46 UTC, DMarby approved these changes

2021-08-20 11:49 UTC, merged