removes hardcoded import names
getinsomnia/insomnia pull request #3935
Opened 2021-08-23 20:29 UTC by dimitropoulos

I noticed while QA'ing for the next release that these names are hardcoded.  I see no reason that doing so benefits us - and it's a 1-line change to update it.

before:
![before](https://user-images.githubusercontent.com/15232461/130515049-364e0b5f-9be2-4127-8e0e-307102c1f904.png)

after:
![after](https://user-images.githubusercontent.com/15232461/130515063-240c958a-1741-4de3-97b6-11493bef0b79.png)

2021-08-23 22:56 UTC, develohpanda requested changes

2021-08-23 22:56 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/import-export.tsx
> +import { importers } from '../../../../../insomnia-importers/dist/src';
I don't think it's a good idea to import from `/dist`, might have been an oversight. I think it's totally reasonable to have a top-level export from `insomnia-importers` containing the supported formats/names and using that instead

2021-08-24 00:20 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/settings/import-export.tsx
> +import { importers } from '../../../../../insomnia-importers/dist/src';
TOTALLY a mistake.  Dang autoimporter getting ambitious.  I wonder if there's a way to tell it to never do this?

8da3c45082a6c83515eabadd2a59dcc90e627444

I double checked the line below, but didn't think about this one.

2021-08-24 00:21 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/settings/import-export.tsx
> +import { importers } from '../../../../../insomnia-importers/dist/src';
(good catch, thanks!)

2021-08-24 01:24 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/import-export.tsx
> +import { importers } from '../../../../../insomnia-importers/dist/src';
Oh nice, it was already a top-level export!

> I wonder if there's a way to tell it to never do this?

[`no-relative-packages`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-relative-packages.md) seems very useful for us, it comes as part of `eslint-plugin-import`.

2021-08-24 01:25 UTC, develohpanda approved these changes, later dismissed

2021-08-24 01:34 UTC, develohpanda commented
@wdawson should we display in this much detail with versions? For instance, we don't need to show older Insomnia formats. People don't usually know which format file they have, and should safely assume that all Insomnia export versions can be imported. And the Postman ones are now separated into "Postman" and "Postman Environment", and I'm not sure what the difference is between the two.

IMO we don't need to show the level of detail of supported formats; Insomnia will error if it's not able to import. Or we could de-clutter the tab and show the full (and potentially growing) list in a tool-tip, for instance.

2021-08-24 01:37 UTC, develohpanda commented
(@dimitropoulos I initially approved, and then disabled auto-merge because I wanted Wils's opinion. Then figured I'll dismiss my review because I have an outstanding question, so I re-enabled auto-merge again like you had done so initially 😅)

2021-08-24 01:50 UTC, dimitropoulos commented
Sure, it's no rush

2021-08-24 16:13 UTC, wdawson commented
I definitely wouldn't bold the list. I like the tooltip suggestion. People need some place to see what's supported (the full list). That could live in the docs eventually if things get too out of hand. But tooltip would work nicely for now. "Supported import formats include: x, y, z"

2021-08-25 03:04 UTC, develohpanda requested changes
> I definitely wouldn't bold the list. I like the tooltip suggestion. People need some place to see what's supported (the full list). That could live in the docs eventually if things get too out of hand. But tooltip would work nicely for now. "Supported import formats include: x, y, z"

Let's go with this approach

2021-09-01 21:09 UTC, dimitropoulos commented
ok, I updated:
![image](https://user-images.githubusercontent.com/15232461/131745423-75d4a1be-9e85-4191-8bdc-d99debe6c17d.png)

2021-09-01 21:16 UTC, wdawson approved these changes
⛵ ship it! Thanks!

2021-09-02 04:57 UTC, develohpanda approved these changes
![](https://media1.giphy.com/media/l0MYSryDg63YEmXVS/giphy.gif)

2021-09-02 04:57 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/import-export.tsx
> +          supported formats include: {importers.map(importer => importer.name).join(', ')}
```suggestion
          Supported formats include: {importers.map(importer => importer.name).join(', ')}
```

2021-09-02 14:22 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/settings/import-export.tsx
> +          supported formats include: {importers.map(importer => importer.name).join(', ')}
you know, haha, I did this at first and then changed it before committing because it isn't a sentence.  despite that being technically correct I didn't think to check what the app does in this situation anyway, and it seems very much the norm to cap the first letter - sentence or not.  good catch.

2021-09-02 14:46 UTC, merged