fixes "Hide menu bar" setting
getinsomnia/insomnia pull request #3961
Opened 2021-08-27 15:51 UTC by dimitropoulos

Also, while I was there, I removed the requirement to restart the application.  Now you can change this value and immediately see the change take place - no restart required.

closes INS-908

2021-08-30 09:07 UTC, develohpanda requested changes
Couple of suggestions. Can you also please include a gif in the description? I only have a dev environment available on MacOS. If it works on Linux we can merge this, and validate Windows in the patch release candidate.

2021-08-30 09:07 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/general.tsx
> +                }}
I reckon instead of this being an explicit callback here, it can be an effect powered by `settings.autoHideMenuBar` in `app-hooks.tsx`

```ts
export const useMenuBarVisibility = () => {
  const { autoHideMenuBar } = useSelector(selectSettings);

  useEffect(() => {
    setMenuBarVisibility(autoHideMenuBar);
  }, [autoHideMenuBar]);
}
```

Otherwise, it might be better to send the _updated_ settings object into the `callback()`, though I think an effect bound to the setting is a nicer approach.

2021-08-30 09:07 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/boolean-setting.tsx
> +  callback?: () => void;
Following a previous comment, I suggest we remove the callback here and create an effect at a higher level that depends on the setting value

2021-08-30 09:07 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/boolean-setting.tsx
> +  setting: string;
```suggestion
  setting: keyof Settings;
```

2021-08-30 09:07 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/boolean-setting.tsx
> +  }, [callback, setting, settings]);
This change will prevent the callbacks for all `BooleanSetting` instances changing because of a different setting. This is the same approach we used in the [themes](https://github.com/Kong/insomnia/blob/251287062d2f9e345c88041006ee380b1275faee/packages/insomnia-app/app/ui/hooks/theme.ts#L49), for the same reason.

```suggestion
  const onChange = useCallback(async (event: ChangeEvent<HTMLInputElement>) => {
    const { checked } = event.currentTarget;
    await models.settings.patch({
      [setting]: checked,
    });
    callback?.();
  }, [callback, setting]);
```

2021-08-30 15:55 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/settings/boolean-setting.tsx
> +  setting: string;
actually, it did cause an error but one that I think we want to catch - that we weren't casting to boolean for `checked`, which we should have been because otherwise it throws a runtime react error.  fixed in 0ccc891c54931e64236676dddf0bac072516445a.

2021-08-30 20:21 UTC, gatzjames reviewed
LGTM 👍
Left a small copy improvement suggestion and a question but nothing blocking!

2021-08-30 20:21 UTC, gatzjames commented on packages/insomnia-app/app/ui/components/settings/boolean-setting.tsx
> +          <Tooltip message="Will restart app" className="space-left">
```suggestion
          <Tooltip message="Will restart the app" className="space-left">
```

2021-08-30 20:21 UTC, gatzjames commented on packages/insomnia-app/app/ui/components/settings/general.tsx
> +                }}
I see that in the app we sometimes use ipcRenderer <-> ipcMain and others we access the electron.remote module to use some apis.
In this case would it make sense to listen for the update of the `settings. autoHideMenuBar` and run the `setMenuBarVisibility` from the main process? What do you think? 🤔 Curious how we handle these cases in general.

2021-08-31 04:00 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/settings/general.tsx
> +                }}
@gatzjames I don't see why we couldn't do that? I'm not sure if that will require a restart of the app or if it can happen on the fly if we do so in the main process instead of the render process. 

I will add that there isn't much boilerplate in place to communicate between main <-> render in a safe and maintainable manner right now. There is the gRPC implementation where an attempt has been made using React.Context and confined to the gRPC context. I know we'll have to go down this route in future so there's definitely scope to be thinking about it. In general cases like these happen in the render process unless it _needs_ to happen in the main process.

I hope that helps with an explanation for the current state?

2021-08-31 04:31 UTC, develohpanda approved these changes

2021-08-31 04:31 UTC, merged