Plugin API feature: added getInfo method to context.app
getinsomnia/insomnia pull request #3975
Opened 2021-08-30 15:51 UTC by monrax

- This closes #3974 
- The method returns an object with the app `version`, `ID`, `name` and `platform` using the helper methods from `common/constants`

2021-08-31 04:36 UTC, develohpanda requested changes
Thanks for the PR! One small update, please 🙌🏽 

Looks like there are a couple of lint errors too, they can be auto-fixed by running `npm run lint:fix` from the root of the repository

2021-08-31 04:36 UTC, develohpanda commented on packages/insomnia-app/app/plugins/context/app.tsx
> +      },
As discussed in Slack, let's change this to only return the version and platform for now, and we can add any extra fields as they become necessary in future!

2021-09-03 04:21 UTC, develohpanda commented on packages/insomnia-app/app/plugins/context/app.tsx
> +      },
Updated in d84322d 😊

2021-09-03 04:25 UTC, develohpanda approved these changes
🚀 tested with the following example plugin

```js
module.exports.workspaceActions = [
  {
    action: async (context) => {
      const info = context.app.getInfo();
      await context.app.alert('Info', JSON.stringify(info));
    },
    label: 'Show info',
  },
]
```

![2021-09-03 16 24 06](https://user-images.githubusercontent.com/4312346/131950310-4250f2ea-31b1-48b6-a447-1d6f59540287.gif)

2021-09-03 13:48 UTC, monrax commented on packages/insomnia-app/app/plugins/context/app.tsx
> +      },
I'm so ashamed I left this unfinished like that. Thank you once again @develohpanda you're the best 🙏️ 🚀️

2021-09-03 13:53 UTC, develohpanda commented on packages/insomnia-app/app/plugins/context/app.tsx
> +      },
Hey no worries!! It was a very small change, and I'd like to see this get through 😊

2021-09-07 05:36 UTC, develohpanda approved these changes
Strange how there were some additional lint changes that went in; how did you run lint fix? Was it `npm run lint:fix` from the root directory of this project?

Anyway that's okay, I reverted those. Thank you for adding tests! LGTM

2021-09-07 11:30 UTC, monrax commented
Yes, I ran it like that but I also thought it was strange how it changed functions into arrow functions and just not accepting them otherwise. Maybe there's something wrong with my setup. Sorry about that, and glad I could help!

2021-09-07 11:34 UTC, develohpanda commented
That's all good! I'll have a look at it 😊

2021-09-15 20:00 UTC, dimitropoulos approved these changes
I think this is ready to go!

I noticed there is a z-index problem, but that isn't related to what this PR implements:
https://user-images.githubusercontent.com/15232461/133501061-c60b5401-4bb8-4d4e-9968-50015d0c0194.mp4

2021-09-15 20:10 UTC, merged