fixes updating, fixes styling, fixes copying nothing
getinsomnia/insomnia pull request #3995
Opened 2021-09-02 20:30 UTC by dimitropoulos

closes https://github.com/Kong/insomnia/issues/3788

I removed the debounce (as we have been, there's absolutely no need for it here) and that solved the bug.  I fixed the positioning while I was there (the text wasn't centered vertically before) as well as the fact that the copy button wasn't disabled when there was nothing to copy.

2021-09-03 03:27 UTC, develohpanda requested changes
Ran locally and looks to be working as intended 🙌🏽 As with removing any debounce timeouts, do you know why it might have been there in the first place? Was there a valid reason for it? 

The above question is _not_ the requested change; rather the comment below. But I'm still curious if there is any background for this debounce to exist (even if it wasn't working as intended).

2021-09-03 03:27 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/rendered-query-string.tsx
> +  }, [request, handleRender]);
I would suggest changing this implementation so that the the only items from `request` needed in the dependency array are `request.url` and `request.settingEncodeUrl`.

I don't think it's necessary to trigger a re-render (which is why, my guess is, the debounce existed) as any property on the `request` changes.

2021-09-03 15:12 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/rendered-query-string.tsx
> +  }, [request, handleRender]);
cool - updated in 869c95923a128afb02e769d4e69646dbaad732a1

2021-09-03 15:21 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/rendered-query-string.tsx
> +  }, [request, handleRender]);
This component has basically been this way from the beginning with no explanation (that I can find).  I remember react back in 2016 and this kind of thing was in vogue back then because... well... haha, it was the beginning in a lot of ways and performance wasn't anywhere near what it is now.  People were looking for ways to squeeze performance out of react and this was one of the ones they came up with. 
 
https://github.com/Kong/insomnia/commit/bb6e3859716264dc443842d45dc829040de04a4b#diff-c9d2ff9244afd131e2c8d0be1635a2e3de6d63220bd739205e282b89463224d8 is the start "`LOts of good stuff`".  You can see in that commit that this wasn't the only file he did this to - which is more evidence that this wasn't something that had a product need per-se, but rather just a general approach he was trying out. 

The refactor to `debouncedUpdate` came later https://github.com/Kong/insomnia/commit/14640eafd6c395da8872c3a13a7c7479d3d48708 but the end result is essentially the same, in the `Some small fixes` commit.

2021-09-03 17:25 UTC, gatzjames commented
Works nice! 👍  Added some space between the button and the text and made the button sticky

![sticky-button](https://user-images.githubusercontent.com/12115431/132044302-da2cb713-0c82-42fc-ad58-82f0442bbf5a.gif)

2021-09-03 17:27 UTC, gatzjames approved these changes

2021-09-03 17:36 UTC, dimitropoulos commented
Wow great suggestion @gatzjames !  Love it!

2021-09-03 18:25 UTC, merged

2021-10-11 13:58 UTC, DusanLesan commented
Great. Thank you for fixing this. I cannot wait for release.