fixes all react/prefer-stateless-function warnings
getinsomnia/insomnia pull request #4019
Opened 2021-09-10 15:00 UTC by dimitropoulos

There are two things to look out for in reviewing this PR:

1. a component that did `const { x, y } = this.props` at the top but then later did `this.props.z` in the meat of the component.  Thankfully this didn't appear to happy in any of the affected components because they were all so small.  I did a self review at the end and didn't find any of these.
1. there are duplicate components (Dropdown) in insomnia-app and insomnia-components.  It's possible that I messed up an import somewhere.  I did a self review and caught two of these.  One _really_ cool thing about this is that if this changes it will cross the "empty line internal vs. external dependency barrier" because of the import sorting!!! that's how I noticed it, first.  _very_ convenient.

Other than conversion to function components, there should be no logical changes in this PR.

2021-09-10 15:03 UTC, dimitropoulos commented on packages/insomnia-app/app/__jest__/with-redux-store.tsx
> +);
this was the only one that gave me trouble.  if you fix to sfc it complains that it doesn't have a display name, but I couldn't figure a way how to do it otherwise.

2021-09-10 15:06 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/base/dropdown/dropdown-right.tsx
> -import classnames from 'classnames';
this component is not used anywhere in the monorepo and is not exported.   it was excluded from the index file (https://github.com/Kong/insomnia/blob/develop/packages/insomnia-app/app/ui/components/base/dropdown/index.ts).

aside from being touched in global typescript and eslint refactors, this file appears not to have been touched in 5 years.

2021-09-10 15:10 UTC, dimitropoulos commented on packages/insomnia-components/src/card-container.tsx
> -}
I sat and thought about this to make sure that it is logically equivalent and I cannot see a way in which it is not.  always good to double check, though.  This is a "straight out of the docs" way to do styled components and while I can understand how someone might write code like this when we were first learning how to use styled-components (https://github.com/Kong/studio/commit/7c58e5907fdc1bcacbb52b0b97cfce7db40dfeba#diff-3562ac93155ce13a13bc5cb18b227c72bdcc674a8174e430060fc195fc1f4007) the extra components provides no value.

2021-09-15 11:50 UTC, jackkav requested changes

2021-09-15 11:50 UTC, jackkav commented on packages/insomnia-app/app/ui/components/graph-ql-explorer/graph-ql-default-value.tsx
> +  // Make Flow happy :/
What flow? 😉

2021-09-15 11:50 UTC, jackkav commented on packages/insomnia-app/app/ui/components/base/dropdown/dropdown.tsx
> +import { DropdownItem } from './dropdown-item';
```suggestion
import { DropdownItem } from './dropdown-item';
import { DropdownButton }  from './dropdown-button';
```

2021-09-15 11:50 UTC, jackkav commented on packages/insomnia-app/app/ui/components/base/dropdown/dropdown.tsx
> +const isDropdownDivider = isComponent(DropdownDivider.name);
```suggestion
const isDropdownDivider = isComponent(DropdownDivider.name);
const isDropdownButton = isComponent(DropdownButton.name);
```

2021-09-15 12:01 UTC, jackkav commented on packages/insomnia-app/app/ui/components/graph-ql-explorer/graph-ql-default-value.tsx
> +  // Make Flow happy :/
Looks awesome so far, I'm curious why you chose FC over plain functions in light of [this article](https://fettblog.eu/typescript-react-why-i-dont-use-react-fc/), but just a nitpick for my benefit.

I tried out the DropdownButton changes to make it run, and get lots of console logs complaining about `Dropdown needs exactly one DropdownButton!` and missing components
![image](https://user-images.githubusercontent.com/3679927/133429518-52b6d13b-12c3-43cd-a549-9e832f3682c3.png)

2021-09-15 13:52 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/graph-ql-explorer/graph-ql-default-value.tsx
> +  // Make Flow happy :/
dang, I thought I got that in b01a15affbff41d7ab4540fe1cca7a14d2d9265b

2021-09-15 16:36 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/graph-ql-explorer/graph-ql-default-value.tsx
> +  // Make Flow happy :/
(reverted all changes to dropdown components in https://github.com/Kong/insomnia/pull/4019/commits/318989242973b53ddcf400e79a887c7abbc39fd4).  There is neither the time nor do I have the requisite energy to fix it "for real" right now.

2021-09-15 20:04 UTC, gatzjames approved these changes
🎉 LGTM

2021-09-15 20:16 UTC, merged