remove kong-bundle
getinsomnia/insomnia pull request #4079
Opened 2021-10-05 10:40 UTC by jackkav

Removes the deprecated convenience bundle left over from when these plugins were optional.

2021-10-06 09:12 UTC, develohpanda requested changes

2021-10-06 09:12 UTC, develohpanda commented on packages/insomnia-app/app/common/migrate-from-designer.ts
> -    'insomnia-plugin-kong-bundle',
We still want to keep this around; when migrating from Designer to Core, this plugin likely existed and we want to delete it.

2021-10-06 13:50 UTC, jackkav commented on packages/insomnia-app/app/common/migrate-from-designer.ts
> -    'insomnia-plugin-kong-bundle',
Thanks!

2021-10-07 23:13 UTC, develohpanda approved these changes
LGTM

2021-10-08 07:00 UTC, merged