only add upstreams when needed
getinsomnia/insomnia pull request #4105
Opened 2021-10-13 14:12 UTC by jackkav

Upstream config is only needed when load balancing, which is indicated by having two services, or by using the x-kong-upstream-default tag.

Closes INS-837

2021-10-13 21:14 UTC, Tieske commented on packages/openapi-2-kong/src/declarative-config/fixtures/callback-example.expected.json
> -          "target": "backend.com:80",
since we're no longer creating an upstream, the `service.name` field should now be taken from the url. So in this case the `service.name` should not be `Callback_Example.upstream` (since there is no host nor upstream by that name anymore). `service.name` should now become `backend.com`.

The `service.protocol` is already taken from the url I suspect.

Also the `service.name` gets a default value of `80` probably, and that should now be set from the url as well. Where the cases should be:
- use port if specified in url
- use `80` if scheme is `http`
- use `443` if scheme is `https`

(this warrants some tests probably)

2021-10-14 06:33 UTC, jackkav commented on packages/openapi-2-kong/src/declarative-config/fixtures/callback-example.expected.json
> -          "target": "backend.com:80",
The conditional adding of .upstream is useful here, however to perform the subsequent naming and port changes I would need examples to show the desired state.

2021-10-18 00:29 UTC, develohpanda commented on packages/openapi-2-kong/src/declarative-config/fixtures/callback-example.expected.json
> -          "target": "backend.com:80",
@Tieske, do you mean `service.host` should become `backend.com` (instead of `service.name`)?

As examples, I am guessing that with the following spec:

```yaml
openapi: '3.0.2'
info:
  title: Sample Spec
  version: '1.2'
servers:
  - url: https://200.insomnia.rest
paths:
  /global:
    get:
      responses:
        '200':
          description: OKs
```

this would be the expected difference

```diff
_format_version: "1.1"
services:
  - name: Sample_Spec
    protocol: https
-    host: Sample_Spec
+    host: 200.insomnia.rest
    port: 443
    path: /
    plugins: []
    routes:
      - tags:
          - OAS3_import
        name: Sample_Spec-global-get
        methods:
          - GET
        paths:
          - /global$
        strip_path: false
    tags:
      - OAS3_import
-upstreams:
-  - name: Sample_Spec
-    targets:
-      - target: 200.insomnia.rest:443
-        tags:
-          - OAS3_import
-    tags:
-      - OAS3_import
```

And with the following spec:

```yaml
openapi: '3.0.2'
info:
  title: Sample Spec
  version: '1.2'
servers:
  - url: https://200.insomnia.rest
  - url: https://300.insomnia.rest
paths:
  /global:
    get:
      responses:
        '200':
          description: OKs
```

this would be the expected result

```diff
_format_version: "1.1"
services:
  - name: Sample_Spec
    protocol: https
    host: Sample_Spec
    port: 443
    path: /
    plugins: []
    routes:
      - tags:
          - OAS3_import
        name: Sample_Spec-global-get
        methods:
          - GET
        paths:
          - /global$
        strip_path: false
    tags:
      - OAS3_import
upstreams:
  - name: Sample_Spec
    targets:
      - target: 200.insomnia.rest:443
        tags:
          - OAS3_import
+      - target: 300.insomnia.rest:443
+        tags:
+          - OAS3_import
    tags:
      - OAS3_import

```

> Also the service.name gets a default value of 80 probably, and that should now be set from the url as well. Where the cases should be...

Do we have to think about this, considering `service.port` already exists?

2021-10-19 10:17 UTC, Tieske commented on packages/openapi-2-kong/src/declarative-config/fixtures/callback-example.expected.json
> -          "target": "backend.com:80",
@develohpanda yes, your input with expected output examples are correct.

as for the `port` logic, I think that logic is there for the `targets` added to the upstream. The `target` entities require an explicit port. When setting it in the `service` entity, I don't know whether the same logic is present. Hence my comment to add some tests for that so we are sure it works as expected.

2021-10-19 10:49 UTC, jackkav commented on packages/openapi-2-kong/src/declarative-config/fixtures/callback-example.expected.json
> -          "target": "backend.com:80",
There is a notable test case `no-targets-example.yaml` without a hostname in the OAS, which I have set to fallback to `localhost`
How am I doing?

2021-10-20 05:58 UTC, develohpanda commented on packages/openapi-2-kong/src/declarative-config/fixtures/callback-example.expected.json
> -          "target": "backend.com:80",
<details>
<summary>The spec in question</summary>

```yaml
openapi: '3.0.0'
info:
  title: Simple API overview
  version: v2
servers:
  - url: /path
paths:
  /:
    x-kong-name: x-kong-name-override-at-path-item
    get:
      x-kong-name: x-kong-name-override-at-method
      operationId: listVersionsv2
      summary: List API versions
      responses:
        '200':
          description: |-
            200 response
        '300':
          description: |-
            300 response
  /v2:
    x-kong-name: x-kong-name-override-at-path-item
    get:
      operationId: getVersionDetailsv2
      summary: Show API version details
      responses:
        '200':
          description: |-
            200 response
        '203':
          description: |-
            203 response

```

</details>

According to the OpenAPI docs, `localhost` seems most logical: https://swagger.io/docs/specification/api-host-and-base-path/#relative-urls.

Relative URLs are supported by OpenAPI, and they resolve against the server that is hosting the spec.

As a test, I wanted to see how the Insomnia importer would handle this exact spec, and it doesn't do so gracefully, and leaves the host environment variable blank, but it should probably default to `localhost` (no changes requested here, that's out of scope).

![image](https://user-images.githubusercontent.com/4312346/138036522-6a744c4b-0994-42dd-941d-249145787d2e.png)

2021-10-20 06:14 UTC, develohpanda requested changes
Largely LGTM! There's a comment outlining a small refactor to re-use logic, that will allow us to write some unit tests as well.

2021-10-20 06:14 UTC, develohpanda commented on packages/openapi-2-kong/src/declarative-config/services.ts
> +  let host = parsedUrl.hostname || 'localhost';
If you see fit, it might be worth documenting in a comment here that this fallback is valid given the OpenAPI spec docs (rather than just a logical best-guess) https://swagger.io/docs/specification/api-host-and-base-path/#relative-urls

2021-10-20 06:14 UTC, develohpanda commented on packages/openapi-2-kong/src/declarative-config/services.ts
> +  if (hasUpstreamDefaults || hasMoreThanOneServer) {
Could you please combine this conditional check into a utility function, and re-use it here, in [`generate.ts`](https://github.com/jackkav/insomnia/blob/af27fdbf866450f2c46a151d59671df8eb8b897d/packages/openapi-2-kong/src/declarative-config/generate.ts#L17) and in [`upstreams.ts`](https://github.com/jackkav/insomnia/blob/d8b4724fe78368a1cfe3e8818941c70552201f6b/packages/openapi-2-kong/src/declarative-config/upstreams.ts#L22-L24). The duplication of logic of this nature three times, isn't worth it IMO. Not too concerned about where you put the function.

As an extra win, extracting it will allow us to write a unit test against it (fixture tests are useful, but provide little context)

2021-10-20 06:14 UTC, develohpanda commented on packages/openapi-2-kong/src/generate.test.ts
> -      expect(dc.upstreams.length).toBe(1);
Why not update this assertion to be `expect(dc).not.toHaveProperty('upstreams');`? Same as below

2021-10-20 12:34 UTC, jackkav commented on packages/openapi-2-kong/src/generate.test.ts
> -      expect(dc.upstreams.length).toBe(1);
donezo

2021-10-22 13:12 UTC, Tieske approved these changes

2021-10-22 15:13 UTC, develohpanda approved these changes

2021-10-24 19:10 UTC, merged