Handle request send hotkey for gRPC
getinsomnia/insomnia pull request #4126
Opened 2021-10-16 14:33 UTC by vincendep

Closes #3272

2021-10-18 00:08 UTC, develohpanda requested changes
I've just made a note to memoize the handler, but the feature works well!

2021-10-18 00:08 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/panes/grpc-request-pane/index.tsx
> +    <KeydownBinder onKeydown={_handleKeyDown}>
We'll want to memoize this arrow function using `useCallback`, otherwise it will change every time this component updates causing unnecessary re-renders.

Ideally this `onKeyDown` handler is actually created within `useActionHandlers` but that involves a bit more of a refactor to account for the conditions, so we can just memoize here for the time being.

2021-11-17 06:49 UTC, develohpanda approved these changes
Tested and LGTM, thank you for the PR! 🎉

2021-12-10 17:07 UTC, dimitropoulos approved these changes
thank you so much for the PR.  despite being small, this is a really important feature.  I personally apologize for it taking so long for this to get over the finish line.  we really do appreciate the contribution!

2021-12-10 17:34 UTC, merged

2021-12-17 16:05 UTC, vincendep commented
Hi @dimitropoulos, happy to contribute!!