Show gRPCs in requests dialog
getinsomnia/insomnia pull request #4127
Opened 2021-10-16 17:06 UTC by vincendep

Closes #3271

2021-10-17 23:30 UTC, develohpanda requested changes
Thanks for the PR! We do need to add some UI for GRPC requests in the request switcher as well. For instance, the following is what I see when hitting `cmd + p`.

Ideally we follow a similar pattern to REST requests.

![image](https://user-images.githubusercontent.com/4312346/137648799-ecbaa742-6ff8-467a-b684-f3b642dbf531.png)

I also noticed the following lines: https://github.com/vincendep/insomnia/blob/21047c818165a63c79d9484edf723e39cd85416b/packages/insomnia-app/app/ui/components/modals/request-switcher-modal.tsx#L34-L35

We'll need to remove this (now that GRPC requests have been introduced to the request switcher), and determine whether there are any implications. I couldn't see any while browsing this file.

Lastly, could you also please (at the very least) add screenshots or gifs to PR descriptions? It really helps with code reviews. Thank you! 🙏🏽

2021-10-18 08:49 UTC, vincendep commented
Hi @develohpanda, so sorry for my lazyness 😄, I'll be more explicative for my next pull requests. Speaking of UI changes, do you think would be ok to show only "gRPC" (as Add Request dropdown), 

![Schermata 2021-10-18 alle 10 44 58](https://user-images.githubusercontent.com/37916223/137699000-957d3bcf-7d29-429e-9fbe-ca05e5e30879.png)

or maybe we should include the selected gRPC  method some how?

2021-10-18 08:56 UTC, develohpanda commented
No worries at all! It would be nice to show the url + selected grpc method name. Should be fairly straightforward to get that information I think

2021-12-13 12:21 UTC, filfreire commented
@vincendep, in case you are interested you could achieve what @develohpanda mentioned with something like:

Near line 224:
```diff
       finalUrl = joinUrlAndQueryString(finalUrl, buildQueryStringFromParams(request.parameters));
     }
 
+    if (isGrpcRequest(request)) {
+      finalUrl = request.url + request.protoMethodName;
+    }
+
     const match = fuzzyMatchAll(
       searchStrings,
       [request.name, finalUrl, request.method || '', this._groupOf(request).join('/')],
```

Near line 477:
```diff
                       </div>
                       <div className="margin-left-xs faint">
                         { isRequest(r) ? <MethodTag method={r.method} /> : null }
-                        <Highlight search={searchString} text={r.url} />
+                        <Highlight
+                          search={searchString}
+                          text={ isGrpcRequest(r) ? r.url + r.protoMethodName : r.url }
+                        />
                       </div>
                     </Button>
                   </li>

```


Example of how it would look like:

<img width="783" alt="Screenshot 2021-12-13 at 12 06 53" src="https://user-images.githubusercontent.com/11976836/145811259-80f7824d-334f-451f-aeee-8968f5575a48.png">
<img width="805" alt="Screenshot 2021-12-13 at 12 02 32" src="https://user-images.githubusercontent.com/11976836/145811265-9177391e-6c3a-4311-8082-3c69f0906f0f.png">

2021-12-16 15:01 UTC, vincendep commented
Sorry about end of communications by I didn't found time to work on this.  
Hi @filfreire, thanks for your help, I'll give it a try soon and see if I can close this. Btw I think that would be nice to show also the gRPC tag in place of the method tag

2021-12-18 09:21 UTC, vincendep commented
Here a screenshoot of the update

<img width="792" alt="Schermata 2021-12-18 alle 10 06 01" src="https://user-images.githubusercontent.com/37916223/146636103-dc279235-8ea4-48a0-bd79-c7dad80ef6db.png">

2022-01-04 17:35 UTC, filfreire approved these changes
Looks good to me, great work @vincendep 👍 

![Screenshot 2022-01-04 at 17 32 35](https://user-images.githubusercontent.com/11976836/148100228-61c547f1-6f0f-4a8c-971f-574baf21ea24.png)

2022-01-12 16:50 UTC, filfreire commented
FYI @dimitropoulos @develohpanda this PR would be a good candidate to get merged before the next release.

2022-01-13 05:22 UTC, develohpanda approved these changes
Thanks for the updates @vincendep! I pushed a few small commits, please take a look!

These commits remove a redundant comment and improves some TS types that were incorrect after the changes in this PR (due to a quirk of TS and not your fault 🤗)

2022-01-13 05:22 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/modals/request-switcher-modal.tsx
> +      .filter(child => isRequest(child) || isGrpcRequest(child))
Unfortunately with this change we lose type safety (`matchedRequest` should not be of type `RequestGroup`). There's a known bug in TS regarding this, and I haven't seen any reliable workarounds for it.

After
<img width="595" alt="image" src="https://user-images.githubusercontent.com/4312346/149269118-b2be1b53-99b6-40ae-b8af-c3272ff3e41d.png">

Before
<img width="486" alt="image" src="https://user-images.githubusercontent.com/4312346/149269187-9bc5d33e-7d19-4e38-b1b4-645d836e4315.png">

I've updated some of the type definitions here to bring the `as` cast alongside: e3486969243ca51f81b6788ab24692f5dea6b2a8

2022-01-13 09:14 UTC, vincendep commented on packages/insomnia-app/app/ui/components/modals/request-switcher-modal.tsx
> +      .filter(child => isRequest(child) || isGrpcRequest(child))
Hi @develohpanda. Thanks for the explanation, since I'm a beginner with TS every advice is welcome

2022-01-14 19:29 UTC, dimitropoulos approved these changes

2022-01-14 19:29 UTC, merged