Append upstream name using a utility
getinsomnia/insomnia pull request #4135
Opened 2021-10-20 06:22 UTC by develohpanda

This is a minor refactor which should help avoid typos, but more importantly it _contextually connects_ the upstream name to the service host.

It reduces the risk of the service host and upstream name from falling out of sync (even though fixture tests would catch it).

2021-10-25 20:23 UTC, jackkav requested changes

2021-10-25 20:23 UTC, jackkav commented on packages/openapi-2-kong/src/declarative-config/upstreams.ts
> +export const appendUpstreamName = (name: string) => `${name}.upstream`;
I would suggest the wording `appendUpstreamToName`

2021-10-26 18:38 UTC, dimitropoulos commented on packages/openapi-2-kong/src/declarative-config/services.ts
> +    host: appendUpstreamName(name),
apologies if I missed it: is there a test that covers this line?  I was expecting to see one when I saw this PR.  It'd be a test that fails if this line were changed to something like this, for example:
```diff
- host: appendUpstreamName(name),
+ host: name,
```

2021-10-26 18:39 UTC, dimitropoulos commented on packages/openapi-2-kong/src/declarative-config/services.ts
> +    host: appendUpstreamName(name),
put another way, if we're going to extract this to a utility, it seems prudent to write a test to ensure that the utility is actually used where we expect it to be (in addition to a test that the utility has the behavior we'd expect, which has already been done :smile:).

2021-10-26 18:41 UTC, develohpanda commented on packages/openapi-2-kong/src/declarative-config/services.ts
> +    host: appendUpstreamName(name),
There are fixture tests

2021-11-03 14:17 UTC, jackkav approved these changes

2021-11-08 11:11 UTC, merged