Reduce AppBar sizing and add Project Name to breadcrumbs
getinsomnia/insomnia pull request #4159
Opened 2021-10-28 16:08 UTC by dimitropoulos

> Note: this PR is still awaiting design decisions on the color of the background bar (and thus, some subtle color changes of the multiswitch)

closes INS-845

This PR implements a reduction in size of the app's top bar.

| BEFORE | AFTER |
| - | - |
| ![Screenshot_20211028_120101](https://user-images.githubusercontent.com/15232461/139293123-5bc676fb-2c65-49a2-b5cc-a151f8340bdd.png) | ![Screenshot_20211028_115518](https://user-images.githubusercontent.com/15232461/139293151-0d03ff9a-9642-4db2-9637-44e5318cf0f0.png) |

2021-10-28 16:16 UTC, dimitropoulos reviewed
![image](https://user-images.githubusercontent.com/15232461/139295191-d1e70811-4f7a-4cbc-84e0-af941858f690.png)

By they way, it crossed my mind to also make sure to update the sizing of the bar as it's represented in the theme selector preview.  But then, when I looked at it, I found that it's actually been more narrow all along.  It's a loose representation of the app, anyway, so it doesn't _deeply_ matter that a tweak of the sort that's implemented in this PR, but I just wanted to mention that I checked and it looks good already.

2021-11-01 23:27 UTC, develohpanda requested changes
Insomnia Sync button on a request collection inside a remote project is broken

<img width="222" alt="image" src="https://user-images.githubusercontent.com/4312346/139755193-55cc3d32-d2b0-4f7a-b172-fc75fa0f2b25.png">

2021-11-01 23:27 UTC, develohpanda commented on packages/insomnia-components/src/breadcrumb.tsx
> +    color: var(--color-font) !important;
Is there a way we can avoid `!important`? What is taking prcedence over this resulting in the need for `!important`?

2021-11-01 23:27 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/app-header.tsx
> +          <Breadcrumb crumbs={crumbs} isLoading={isLoading}/>
Why not expact `breadcrumbProps` into this? `<Breadcrumb {...breadcrumbProps} />1

2021-11-01 23:27 UTC, develohpanda commented on packages/insomnia-app/app/ui/css/components/dropdown.less
> +    cursor: pointer;
This only works on some dropdowns. Eg on the dashboard, the card context menu dropdown has a pointer cursor, but the project dropdown, pull dropdown, create dropdown all still have the default cursor

2021-11-02 20:11 UTC, dimitropoulos commented on packages/insomnia-components/src/breadcrumb.tsx
> +    color: var(--color-font) !important;
oh, I really wanted to, but I couldn't find another way.  it's already `!important`ed higher up, so there isn't much option without ripping it up a lot more than I was trying to do in this PR.

2021-11-02 20:14 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/app-header.tsx
> +          <Breadcrumb crumbs={crumbs} isLoading={isLoading}/>
sure, 81182def3ff043f2316a6f879bf3b8364129c3a1.

the answer to "why" is that it's a habit of mine from using TypeScript and React in the very beginning.  It was a while before TypeScript could really reliably handle spread props, and due to that I don't think to do it very often out of habit, even in situations like this where it makes total sense and even these days when TypeScript can handle it just fine.

2021-11-02 20:38 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/css/components/dropdown.less
> +    cursor: pointer;
good to know.  yeah, we'll get to them all eventually I hope, but I just wanted to stay focused on the design that's in scope for this job.  I'd love it if you could open a PR to change the rest, I'm not actually sure where they all are.

if you'd like some change to take place for this PR, please unresove and let me know.

2021-11-02 20:38 UTC, dimitropoulos commented
d4d46a5ed7f657bd1284296493f2aae83ea4101c fixes the dropdown sync button

2021-11-02 20:51 UTC, develohpanda commented on packages/insomnia-components/src/breadcrumb.tsx
> +    color: var(--color-font) !important;
Ah all good then, thanks for trying to

2021-11-02 20:51 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/app-header.tsx
> +          <Breadcrumb crumbs={crumbs} isLoading={isLoading}/>
Awesome!

2021-11-02 21:01 UTC, wdawson commented
Is the `Project name` breadcrumb still clickable? It looks like it wouldn't be because it's grey. I think it should be to take you to the dashboard for that project.

2021-11-02 22:10 UTC, develohpanda approved these changes
LGTM  🚀 

> Is the Project name breadcrumb still clickable? It looks like it wouldn't be because it's grey. I think it should be to take you to the dashboard for that project.

@wdawson yep still clickable: https://www.loom.com/share/69c139125b08481b983115cadab65239

2021-11-02 22:10 UTC, merged