fonts settings UI changed
getinsomnia/insomnia pull request #4186
Opened 2021-11-07 19:45 UTC by sergiyladnych

This PR Closes #2279. It was changed UI element to set Interface and Editor fonts from Dropdown to Text Input. Help texts were added for both.

2021-11-08 17:05 UTC, wdawson commented
Thanks for the PR @sergiyladnych ! Could you please include some screenshots of the app before and after like in [this PR](https://github.com/Kong/insomnia/pull/4159)?

2021-11-09 18:59 UTC, sergiyladnych commented
> Thanks for the PR @sergiyladnych ! Could you please include some screenshots of the app before and after like in [this PR](https://github.com/Kong/insomnia/pull/4159)?



> Thanks for the PR @sergiyladnych ! Could you please include some screenshots of the app before and after like in [this PR](https://github.com/Kong/insomnia/pull/4159)?

Done. I have updated initial comment.

2021-11-14 10:20 UTC, sergiyladnych commented
@develohpanda hello. I'm curious, is there any difficulties to do review of the PR?

2021-11-18 00:32 UTC, develohpanda approved these changes
Thanks for the PR! I tested and reviewed, and have made a couple of text updates to the tooltip messaging. In a future PR I think we can drop font-scanner entirely 🎉

![2021-11-18 13 31 28](https://user-images.githubusercontent.com/4312346/142314345-fa138888-759b-4398-9af6-3ccf21f81325.gif)

2021-11-18 08:33 UTC, jackkav requested changes

2021-11-18 08:33 UTC, jackkav commented on packages/insomnia-app/app/ui/components/settings/general.tsx
> -    const { fonts, fontsMono } = this.state;
Thanks @sergiyladnych As fonts, and fontsMono are removed in this PR and aren't used in the rest of this component or anywhere else in the code, the following lines should also be removed as part of this change.
- line: 2 import font-scanner
- line: 40-44 const
- line 52-62 state interface
- line 65-84 state declaration and componentDidMount
and finally
packages/insomnia-app/package.json
- line 95 font-scanner
the `npm run bootstrap` in the root folder to update the package lock

2021-11-18 19:37 UTC, sergiyladnych commented on packages/insomnia-app/app/ui/components/settings/general.tsx
> -    const { fonts, fontsMono } = this.state;
@jackkav Thank you for feedback.
I have committed changes

2021-11-19 00:08 UTC, jackkav commented on packages/insomnia-app/app/ui/components/settings/general.tsx
> -    const { fonts, fontsMono } = this.state;
awesome, can you also run `npm run bootstrap` in the root folder, to get the font-scanner out of the package lock

2021-11-21 10:27 UTC, sergiyladnych commented on packages/insomnia-app/app/ui/components/settings/general.tsx
> -    const { fonts, fontsMono } = this.state;
@jackkav I did run `npm run bootstrap` first time that you asked me. Now when I dod that there is no difference/changes to commit. If you still think that I should do that, could you be more precise what is expected from that run.

2021-11-25 08:39 UTC, jackkav commented on packages/insomnia-app/app/ui/components/settings/general.tsx
> -    const { fonts, fontsMono } = this.state;
The package-lock.json should have updated and removed the references to font-scanner. I can take a look.

2021-11-25 08:46 UTC, jackkav commented on packages/insomnia-app/app/ui/components/settings/general.tsx
> -    const { fonts, fontsMono } = this.state;
my bad, it needed a `npm run clean && npm run bootstrap` I'll push the commit, we've been looking for a way to get rid of this binary dependency, should improve dx a lot! huge thanks!

2021-11-25 08:47 UTC, jackkav approved these changes
🚀

2021-11-25 10:26 UTC, merged