decouple plugins from networking
getinsomnia/insomnia pull request #4223
Opened 2021-11-17 20:31 UTC by jackkav

Closes INS-1189

Makes _actuallySends return error value significant rather than tracking noPlugins for error cases. Also ensures response and requests hooks happen in the same closure, separating concerns.

2021-11-18 08:23 UTC, develohpanda requested changes

2021-11-18 08:23 UTC, develohpanda commented on packages/insomnia-app/app/network/network.ts
>            elapsedTime: 0, // 0 because this path is hit during plugin calls
This comment is no longer applicable; should it still be 0, or can it be non-zero? Why/why not?

2021-11-18 08:23 UTC, develohpanda commented on packages/insomnia-app/app/network/network.ts
> +  }
This code being duplicated between `send` and `sendWithSettings` makes it very brittle. Please extract and re-use a common implementation in this file itself, at the very least.

As a stretch, this is also an opportunity to pull the plugin hooks out of `network.ts` entirely and have it them alongside in a `network-plugin-hooks.ts` file, for example.

2021-11-18 08:26 UTC, develohpanda commented on packages/insomnia-app/app/network/network.ts
> +  }
Actually, looking at this again, `sendWithSettings` doesn't appear to apply the request plugin hooks. It seems like a bug that it applies response plugin hooks 🤔 but I understand this is preserving existing behavior (and we shouldn't change that for now). Maybe worth making a note in the code about this.

`send` applies both request and response hooks, `sendWithSettings` only applies response hooks.

2021-11-18 08:41 UTC, jackkav commented on packages/insomnia-app/app/network/network.ts
> +  }
I've been holding back on creating any new files to keep git blame intact. The goal of this change is trying to reduce abstractive complexity in (untangle) this file, so I would encourage `write everything twice` until we can extract code from this file feature by feature just to keep things simple for future untangling efforts.

2021-11-18 08:48 UTC, jackkav commented on packages/insomnia-app/app/network/network.ts
>            elapsedTime: 0, // 0 because this path is hit during plugin calls
nice catch!

2021-11-18 08:49 UTC, develohpanda commented on packages/insomnia-app/app/network/network.ts
> +  }
Additional files I understand, but I respectfully don't agree with the `write everything twice` approach. This stuff isn't tested enough to give confidence that if we write things twice and only change one between now and a-future-time-where-everything-is-untangled, that tests will pick up discrepancies.

2021-11-18 08:57 UTC, jackkav commented on packages/insomnia-app/app/network/network.ts
> +  }
You have a point that the try catches around _apply_R_hooks could be moved into their respective functions.

2021-11-18 08:59 UTC, develohpanda commented on packages/insomnia-app/app/network/network.ts
> +  }
Just the block of code highlighted with this code comment is what I'm referring to. And from what I can see, only the try-catch for `_applyResponsePluginHooks` is duplicated (which I think is a bug, but preserving existing behavior is 💯)

2021-11-18 09:07 UTC, jackkav commented on packages/insomnia-app/app/network/network.ts
>            elapsedTime: 0, // 0 because this path is hit during plugin calls
Looks like it should stay because the try catch inside the plugin hook throws up to this one to get `err.plugin.name` if we scope in to this pr the change mentioned below, we should understand what the fail cases might be. Luckily we only expect two strings in the error object so it's not unreasonable.

2021-11-19 06:11 UTC, jackkav commented on packages/insomnia-app/app/network/network.ts
> +  }
Solved by pulling the outer try catch into the `_applyResponsePluginHooks` function. Thanks.

2021-11-19 06:12 UTC, jackkav commented on packages/insomnia-app/app/network/network.ts
>            elapsedTime: 0, // 0 because this path is hit during plugin calls
On second thought, going to avoid removing any try catches in this work, too much unknown still.

2021-11-22 08:01 UTC, develohpanda approved these changes

2021-11-24 09:32 UTC, merged