Add gRPC Headers (INS-362) (#3667)
getinsomnia/insomnia pull request #4244
Opened 2021-11-24 18:14 UTC by filfreire

Closes #3667 and [INS-362](https://linear.app/insomnia/issue/INS-362/grpc-headersmetadata)

This PR adds initial support for gRPC "Headers" (aka. Metadata).

### How to test

1. Checkout this branch 
2. Run `npm run bootstrap && npm run app-start`
3. Clone https://github.com/filfreire/grpc-example-python and follow instructions to build/run
4. Import this [Insomnia collection](https://raw.githubusercontent.com/filfreire/grpc-example-python/main/grpc_insomnia.json) (URL is `https://raw.githubusercontent.com/filfreire/grpc-example-python/main/grpc_insomnia.json`)

### Example recording

https://user-images.githubusercontent.com/11976836/143292010-52b29127-bf8c-458f-b76b-584286ad8ed7.mp4

### Ongoing problems

- Only tested unary gRPC requests. Still need to add support and test metadata for server, client and bidirectional streams.
- There's 2 tests failing, not sure yet how to fix them just yet (maybe @dimitropoulos or @develohpanda you can help me in this case). More details:

```
insomnia-app:   ● grpc › grpc.start › unary › should make unary request with error response
insomnia-app:     TypeError: grpc.Metadata is not a constructor
insomnia-app:       291 |   metadata: GrpcRequestHeader[]
insomnia-app:       292 | ): grpc.Metadata => {
insomnia-app:     > 293 |   const grpcMetadata = new grpc.Metadata({});
insomnia-app:           |                        ^
insomnia-app:       294 |   if (metadata) {
insomnia-app:       295 |     for (const entry of metadata) {
insomnia-app:       296 |       if (!entry.disabled) {
insomnia-app:       at _parseMetadata (network/grpc/index.ts:293:24)
insomnia-app:       at _makeUnaryRequest (network/grpc/index.ts:54:24)
insomnia-app:       at Object.start (network/grpc/index.ts:167:14)
insomnia-app:       at Object.<anonymous> (network/grpc/__tests__/index.test.ts:182:9)
insomnia-app:   ● grpc › grpc.start › unary › should make unary request with valid response
insomnia-app:     TypeError: grpc.Metadata is not a constructor
insomnia-app:       291 |   metadata: GrpcRequestHeader[]
insomnia-app:       292 | ): grpc.Metadata => {
insomnia-app:     > 293 |   const grpcMetadata = new grpc.Metadata({});
insomnia-app:           |                        ^
insomnia-app:       294 |   if (metadata) {
insomnia-app:       295 |     for (const entry of metadata) {
insomnia-app:       296 |       if (!entry.disabled) {
insomnia-app:       at _parseMetadata (network/grpc/index.ts:293:24)
insomnia-app:       at _makeUnaryRequest (network/grpc/index.ts:54:24)
insomnia-app:       at Object.start (network/grpc/index.ts:167:14)
insomnia-app:       at Object.<anonymous> (network/grpc/__tests__/index.test.ts:219:9)
```

2021-11-25 10:42 UTC, develohpanda commented
@filfreire I think the tests are likely failing because the grpc dependency is mocked [here](https://github.com/Kong/insomnia/blob/develop/packages/insomnia-app/app/__mocks__/%40grpc/grpc-js.ts). I'd be happy to pair next week on this, sorry I couldn't get to it today!

2021-11-30 16:30 UTC, filfreire commented
> @filfreire I think the tests are likely failing because the grpc dependency is mocked [here](https://github.com/Kong/insomnia/blob/develop/packages/insomnia-app/app/__mocks__/%40grpc/grpc-js.ts). I'd be happy to pair next week on this, sorry I couldn't get to it today!

@develohpanda I've since managed to fix it in [my last commit](https://github.com/Kong/insomnia/pull/4244/commits/b08164173a3466a4d0e27db5b71dcb778eb42621) after some debugging to try and understand how the mocks were being used.

2021-12-01 04:42 UTC, develohpanda commented on packages/insomnia-app/app/network/grpc/index.ts
> +  if (metadata) {
I think we can skip this if-condition because `metadata` isn't optional

2021-12-01 04:44 UTC, develohpanda commented on packages/insomnia-app/app/network/grpc/index.ts
> +  const grpcMetadata = new grpc.Metadata({});
According to the TS types, the argument for `grpc.Metadata` is optional so `new grpc.Metadata()` is also valid. Is the empty object as a parameter necessary here or can be removed?

2021-12-01 04:49 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/panes/grpc-request-pane/index.tsx
> +              <ErrorBoundary key={uniquenessKey} errorClassName="font-error pad text-center">
I'd love to hear why you chose to use an `ErrorBoundary` here

2021-12-01 04:54 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/panes/grpc-request-pane/index.tsx
> +                  handleGetAutocompleteValueConstants={RequestHeadersEditor._getCommonHeaderValues}
Are the autocomplete name constants and value constants valid for gRPC?

If so, I think we should create a standalone function and consume that in this component and in `RequestHeadersEditor`, instead of invoking the static method on `RequestHeadersEditor` from this component.

Feels strange to be calling into `RequestHeadersEditor` from here

2021-12-01 05:01 UTC, develohpanda commented
> There's a tiny UI bug, that I suspect might be general to wherever KeyValueEditor is used - if the user switches between environments - and is using (and disabling) variables from two environments, the value field stops being in an error state, but the color stays red (check the video above near the end).

Yeah this is an existing bug in CodeEditor and the [nunjucks-tags](https://github.com/Kong/insomnia/blob/d53ef39c9b76aefcfa71630078d838bb95eaad56/packages/insomnia-app/app/ui/components/codemirror/extensions/nunjucks-tags.ts) extension. It's pretty nasty because that extension does DOM manipulation because of how CodeMirror works, so it could use some love for sure.

2021-12-01 05:31 UTC, develohpanda requested changes
### QA

I tried to follow the instructions [here](https://github.com/filfreire/grpc-example-python#how-to-build-and-run) but build fails with an error. Do I need python installed as well?

<img width="785" alt="image" src="https://user-images.githubusercontent.com/4312346/144176113-5bf6e45b-d1ed-437d-8a24-a04d4e284bc7.png">

<details>
<summary>🔴 Overflow doesn't scroll</summary>

Upon looking at other uses of KeyValueEditor it likely needs to be wrapped with a div containing the `scrollable` class

https://www.loom.com/share/ec90b36d3fdd4e1aada6a706f385a65a

</details>

<details>
<summary>🟢 Template tags in the metadata value</summary>

https://www.loom.com/share/6f79cc4f02af47d597166496a718dcac

</details>

<details>
<summary>🔴 Illegal characters in metadata key</summary>

https://www.loom.com/share/a956753d917a4a90ab5193d57eee32b2

</details>

2021-12-02 13:23 UTC, filfreire commented on packages/insomnia-app/app/network/grpc/index.ts
> +  if (metadata) {
True 👍

2021-12-02 13:23 UTC, filfreire commented on packages/insomnia-app/app/network/grpc/index.ts
> +  const grpcMetadata = new grpc.Metadata({});
Indeed it is not needed, I left it there by chance when I was debugging failed tests, good catch 👍

2021-12-02 13:27 UTC, filfreire commented on packages/insomnia-app/app/ui/components/panes/grpc-request-pane/index.tsx
> +              <ErrorBoundary key={uniquenessKey} errorClassName="font-error pad text-center">
I noticed we were using it as well on Requests Pane (e.g. https://github.com/Kong/insomnia/blob/develop/packages/insomnia-app/app/ui/components/panes/request-pane.tsx) on the `RequestHeadersEditor` so I decided to follow a similar structure. During development it prevented Insomnia from freezing with an exception when I opened the gRPC Headers section, printing the exception instead.

Not sure in this case, if we should keep it or remove it?

2021-12-02 14:01 UTC, filfreire commented on packages/insomnia-app/app/ui/components/panes/grpc-request-pane/index.tsx
> +                  handleGetAutocompleteValueConstants={RequestHeadersEditor._getCommonHeaderValues}
@develohpanda I couldn't find a lot of examples of common "headers" for gRPC, so I did the change you mentioned, moved both functions into `packages/insomnia-app/app/common/common-headers.ts` that way we're not depedent on `RequestHeadersEditor` and we can create different common headers for newer implementations.

2021-12-02 14:32 UTC, filfreire commented
> This PR is awesome @filfreire!!
> 
> > There's a tiny UI bug, that I suspect might be general to wherever KeyValueEditor is used - if the user switches between environments - and is using (and disabling) variables from two environments, the value field stops being in an error state, but the color stays red (check the video above near the end).
> 
> Yeah this is an existing bug in CodeEditor and the [nunjucks-tags](https://github.com/Kong/insomnia/blob/d53ef39c9b76aefcfa71630078d838bb95eaad56/packages/insomnia-app/app/ui/components/codemirror/extensions/nunjucks-tags.ts) extension. It's pretty nasty because that extension does DOM manipulation because of how CodeMirror works, so it could use some love for sure.
> 
> One thing that might help is identifying specific reproduction steps and creating a ticket in Linear Triage for it, and we can tidy things up bit by bit

@develohpanda I've identified some steps we can do to reproduce, and reported on  Linear (see [INS-1245](https://linear.app/insomnia/issue/INS-1245/error-state-styling-issues-in-header-keyvalueeditor)

2021-12-02 17:25 UTC, filfreire commented
@develohpanda regarding the above review https://github.com/Kong/insomnia/pull/4244#pullrequestreview-819820051

<details><summary>✅   Fixed the Overflow doesn't scroll</summary>

![Kapture 2021-12-02 at 17 13 25](https://user-images.githubusercontent.com/11976836/144472136-7283d1e9-a926-43fb-bdfa-6d15b120d242.gif)

</details>

<details><summary>✅   Fixed the Illegal characters in metadata key, now it should show an error similar to when the request body is invalid</summary>
<img width="1046" alt="Screenshot 2021-12-02 at 16 37 03" src="https://user-images.githubusercontent.com/11976836/144471053-9f7623bd-ec79-4a17-bb80-0843eb414c1b.png">
</details>

<details><summary> ❓   Couldn't reproduce the control sync shows `-metadata` instead of `+metadata` issue, in my case it didn't show a `-` or `+` character 🤔 </summary>
<img width="794" alt="Screenshot 2021-12-02 at 16 46 17" src="https://user-images.githubusercontent.com/11976836/144471097-32410e6c-17c0-46bf-9e26-bd507769be65.png">
</details>

2021-12-03 00:18 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/panes/grpc-request-pane/index.tsx
> +              <ErrorBoundary key={uniquenessKey} errorClassName="font-error pad text-center">
I was looking for that as an example and somehow missed it 😢 let's keep it!

2021-12-03 00:58 UTC, develohpanda approved these changes
Full reproduction steps of the `-metadata` bug: https://www.loom.com/share/edbd6eb17cca40a7a4a82396f32bdaae. It happens because we've introduced a new property on the data model that a previously synced collection doesn't know about. You should have access to the project and collection I'm using in the video there. (To reiterate though I don't think this is a blocker for this PR as I think it's a more underlying problem in the diff-ing)

Looks good to me! I wasn't able to test metadata itself actually flowing through to a backend (the example one in your description wouldn't work on my machine), but the functionality within the app is 👌🏽

2021-12-03 00:58 UTC, develohpanda commented on packages/insomnia-app/app/common/common-headers.ts
> +export const _getCommonHeaderValues = (pair: RequestHeader): any[] => {
Was there a particular reason you chose the underscope prefix? If not, we're trying to move away from it and it feels reasonable to just use `getCommonHeaderValues` here :)

Would love to see some simple unit tests for this function now that it's just a standalone utlity too (but can be follow-up PR, doesn't have to block this PR)

2021-12-03 00:58 UTC, develohpanda commented on packages/insomnia-app/app/network/grpc/index.ts
> +        respond.sendError(requestId, err);
I think we can write some mocked tests for this, let's pair and do so in a separate PR to not block this one

2021-12-03 11:04 UTC, filfreire commented on packages/insomnia-app/app/network/grpc/index.ts
> +        respond.sendError(requestId, err);
Ok 👍

2021-12-03 11:04 UTC, filfreire commented on packages/insomnia-app/app/common/common-headers.ts
> +export const _getCommonHeaderValues = (pair: RequestHeader): any[] => {
I've fixed the naming, and also added some simple unit tests 👍

2021-12-03 12:43 UTC, jackkav approved these changes
Tested with `docker build --tag grpc-example:latest . && docker run -it --rm -p 50051:50051 --name grpc-example grpc-example:latest`
and the hello world sample, looks great!

2021-12-03 20:11 UTC, develohpanda commented
Hey @filfreire! Sorry about the conflicts, they will have come up after merging #4248. Should be fairly straightforward to resolve

2021-12-06 09:28 UTC, filfreire commented
> Hey @filfreire! Sorry about the conflicts, they will have come up after merging #4248. Should be fairly straightforward to resolve

@develohpanda No worries, I've resolved the conflicts 👍

2021-12-06 10:12 UTC, merged