Move Nunjucks rendering into React Context
getinsomnia/insomnia pull request #4248
Opened 2021-11-25 06:03 UTC by develohpanda

An approach to remove the prop drilling of `handleRender` and `handleGetRenderContext`

2021-11-30 15:05 UTC, jackkav commented on packages/insomnia-app/app/ui/components/codemirror/code-editor.tsx
> +        baseMode: UnconnectedCodeEditor._normalizeMode(rawMode),
There seems to be a convention mismatch with 
- CodeEditor + UnconnectedCodeEditor
- OAuth2Auth + OAuth2AuthInternal
Both appear to be signifying a react component and a wrapper usually injecting props, but using different language.

There are probably a few patterns for this in the codebase, which one should this PR use? There are a few that come to mind.
- UnconnectedMyButton + MyButton
- MyButton + MyButtonInternal
- MyButton + MyButtonComponent
- MyButtonWrapper + MyButton
- MyButtonHOC + MyButton
- MyButtonWithRedux + MyButton

https://charlypoly.com/publications/react-components-naming-convention

This article cites the third one, but I'm not fussy which naming pattern I just like consistency. It's also great that each are co-located beside each other so it's not too much trouble to figure out what they mean.

2021-11-30 15:08 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/context/nunjucks/index.ts
> +export { useNunjucksEnabled } from './nunjucks-enabled-context';
I'd like to hear more about your rationale for this index file.  To me, it adds a layer of complexity (literally and complexity) that has very few benefits for something not exported by the package.

If these functions are so related that we want them to come from the same place (i.e. `app/ui/context/nunjucks`) then why not make a file (i.e. `app/ui/context/nunjucks.ts`) and put them there?  All 4 of these are small enough that it seems reasonable to do that.  Creating the index file makes go-to-definition more complicated, and it makes auto imports difficult, and it also creates a situation for ambiguous imports in the rest of the app where some places go directly to the file and some use the index file (which, we've seen a lot and been undoing with Buttons, for a recent example).

2021-11-30 18:19 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/codemirror/code-editor.tsx
> +  } = useGatedNunjucks({ disabled: !Boolean(enableNunjucks) });
```suggestion
  } = useGatedNunjucks({ disabled: !enableNunjucks });
```

I might be mistaken, but I believe we don't need the Boolean cast here

2021-11-30 18:26 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/codemirror/code-editor.tsx
> +        baseMode: UnconnectedCodeEditor._normalizeMode(rawMode),
It's a pattern in the app that we use this `UnconnectedXYZ` terminology.  I chuckle when I see it because (from my perspective) it's exactly the opposite case.  When you do `export const MyComponent = connect(mapStateToProps)(UnconnectedComponent)` it's actually `UnconnectedComponent` that is _connected_ to redux.  I see it the other way too, that `Unconnected` might have been intended to mean "the thing that needs to be used with `connect` in order to work".  Anyway, hopefully that provides a bit more context as to why we do this.

![Screenshot_20211130_132034](https://user-images.githubusercontent.com/15232461/144105158-25ea9098-d669-415b-8cdd-a8bcd76ae462.png)

___

And besides, my guess is that @develohpanda would like to just pull those static methods out of this component altogether, but he avoided doing so as to restrict scope.  We could also solve the problem here by just using `this`, e.g. `this._isJSON`.  I'm not personally convinced the pseudo-private static method (lol) does a lot for us here.

2021-11-30 18:35 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/codemirror/code-editor.tsx
> +const useDerivedProps = ({ enableNunjucks, ignoreEditorFontSettings }: FCProps) => {
If you can think of a way to inline `useDerivedProps` into `CodeEditorFCWithRef` I think it would aid in readability.  Presently you have to jump up and down the file a bit to have context as to what is actually going on.  I can see from fiddling with it (before making this comment) that it's likely the reason you split it out was so that we could do `type Props = RawProps & ReturnType<typeof useDerivedProps>`.  We're in weird territory here, aren't we, because if we were just using regular classes `typeof mapStateToProps` would be plenty, and if we were using hooks then the type of the selector would also be plenty, but because we to translate from one to the other it gets a little strange.

All the same - I'm cool with what's here but just wanted to point out that if you can think of a better way, it'd be cool.

2021-11-30 18:43 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/rendered-text.tsx
> +class InternalRenderedText extends PureComponent<Props, State> {
```suggestion
class RenderedTextInternal extends PureComponent<Props, State> {
```

there are 6+ others like this that all put `Internal` at the end.  If we go with this approach for this PR I think we should keep the name consistent here with those others.

2021-11-30 18:45 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/editors/auth/asap-auth.tsx
> +class AsapAuthInternal extends PureComponent<Props> {
If we move forward with the approach for getting access to the nunjucks hook, I'd ask for an immediate followup ticket for `AsapAuthInternal`, `OAuth1AuthInternal`, `OAuth2AuthInternal`, `KeyValueEditorRowInternal`, `MarkdownPreviewInternal`, `CookiesModalInternal`, `InternalRenderedText`, `TagEditorInternal`, and `VariableEditorInternal` all being converted to proper function components and for this wrapping layer to be removed.

2021-11-30 18:50 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/wrapper.tsx
> +                {/* TODO: Why isn't CookiesModal registered? :O */}
indeed: looks like you removed it by accident in https://github.com/Kong/insomnia/pull/4248/commits/e7cff3c612252c75d78ea1c36b0fb01ff107c176#diff-af7e9001ce392681816ece64171c85c0ae80449a3d55018201e61295859376adL584

2021-11-30 18:57 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/modals/workspace-environments-edit-modal.tsx
>                  isVariableUncovered={isVariableUncovered}
I'm so happy, as an aside, to be getting rid of inconsistencies like this.  As the saying goes...

> the best API is no API

2021-11-30 19:25 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/context/nunjucks/use-render-functions.ts
> +    return getRenderContext({
this isn't a criticism of your efforts in this PR, or this line in particular because I know 90% of the code in this file was simply ported from `App.tsx`, but this line exactly is where I, as a reader, get lost, as it calls out to some other big complex thing (i.e. `getRenderContext`) that has a bunch of its own things going on.  There's so many layers of abstraction going on here.  This PR makes the situation better, MOST DEFINITELY, but I wonder what else we can do to make such a critical path of the app make more intuitive sense.

2021-11-30 19:27 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/containers/app.tsx
> -   * Heavily optimized render function
so... about this comment.  It's hard to know exactly what this is ultimately getting at, but I just wanted to ask (since it's been removed) if there's any more context you have on what's here to describe what this is referring to.

2021-11-30 19:28 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/containers/app.tsx
> -   * @param contextCacheKey - if rendering multiple times in parallel, set this
it would be great to preserve these two notes

2021-11-30 19:34 UTC, jackkav commented on packages/insomnia-app/app/ui/components/codemirror/code-editor.tsx
> +        baseMode: UnconnectedCodeEditor._normalizeMode(rawMode),
The name Unconnected seems to couple the redux HOC with the React component being composed with it. I get that it's conventional now, and should be too concerned within in this PR scope, but it still reads weird to me. Probably distracting conversation away from the point of the PR, I'll resolve it.

2021-11-30 19:38 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/codemirror/code-editor.tsx
> +        baseMode: UnconnectedCodeEditor._normalizeMode(rawMode),
Thanks for raising it, it super valid because a) this component is no longer using the redux connect function, b) you're right that it couples the component name with redux and c) inconsistent with the "internal" terminology too.

In a follow-up PR I'll address all of them and make consistent. I like the "internal" word because it's explicitly says its internal and shouldn't be exported. So something like `ComponentInternal` (my preference) or `InternalComponent`.

2021-11-30 19:39 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/context/nunjucks/nunjucks-enabled-context.tsx
> +    <NunjucksEnabledContext.Provider value={{ enabled }}>
One thing that jumps out at me when first reading this is to make this suggestion to just remove the need for secondary state (i.e. with `useState` and `useEffect` watching that state) altogether.

```suggestion
    <NunjucksEnabledContext.Provider value={{ enabled: !disable }}>
```

If I had to guess, the rationale might have been to avoid a re-render, but I don't think that's what will happen (unless I missed something).

Here's the react docs https://reactjs.org/docs/context.html#contextprovider

> All consumers that are descendants of a Provider will re-render whenever the Provider’s value prop changes. The propagation from Provider to its descendant consumers (including .contextType and useContext) is not subject to the shouldComponentUpdate method, so the consumer is updated even when an ancestor component skips an update.

The next part is significant, too:

> Changes are determined by comparing the new and old values using the same algorithm as Object.is.

So, in this case:

```ts
Object.is({ enabled: true }, { enabled: true }) // => false
```

Thoughts?  Do you know of a way whether we could test whether using `useState`+`useEffect` here actually does anything?

2021-11-30 19:40 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/context/nunjucks/use-nunjucks.ts
> +  // context: enabled,  prop: enabled  -> should enable
would love to see some tests on this

2021-11-30 19:46 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/context/nunjucks/use-nunjucks.ts
> +export const useNunjucks = () => useNunjucksRenderFuncs();
is this re-call here because of the module-level state (i.e. `NunjucksRenderFunctionContext`) in `./nunjucks-render-function-context`?  If so take a look at https://github.com/Kong/insomnia/pull/4248/files?w=0#r759373287.  I think this is a concrete example of complexity introduced by separating things into files that are closely coupled anyway.  Like always, lemme know if I missed something.

2021-12-01 02:48 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/codemirror/code-editor.tsx
> +const useDerivedProps = ({ enableNunjucks, ignoreEditorFontSettings }: FCProps) => {
Addressed in 48f214dc07fab2b7812ab17515f91fd874dfe464 by moving the FC closer to `useDerivedProps`

2021-12-01 02:50 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/codemirror/code-editor.tsx
> +  } = useGatedNunjucks({ disabled: !Boolean(enableNunjucks) });
Nice catch bc423eec98900cdda8112a2ffddd7096a4fbccca

2021-12-01 02:55 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/editors/auth/asap-auth.tsx
> +class AsapAuthInternal extends PureComponent<Props> {
https://linear.app/insomnia/issue/INS-1235#comment-36ee9bd2

2021-12-01 02:57 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper.tsx
> +                {/* TODO: Why isn't CookiesModal registered? :O */}
Oops! Thanks for looking into it <3

2021-12-01 02:58 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/rendered-text.tsx
> +class InternalRenderedText extends PureComponent<Props, State> {
47318dd30362a626ca684f3584da56bd552e75b6

2021-12-01 02:59 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/wrapper.tsx
> +                {/* TODO: Why isn't CookiesModal registered? :O */}
6765bbe52ceea5f332ed2406f1cd7f024ee34bdf

2021-12-01 03:01 UTC, develohpanda commented on packages/insomnia-app/app/ui/containers/app.tsx
> -   * @param contextCacheKey - if rendering multiple times in parallel, set this
Yep that's my bad, good call. 44d19b55689ad3a60145dbb5e7a8b55402b55bca

2021-12-01 03:04 UTC, develohpanda commented on packages/insomnia-app/app/ui/context/nunjucks/nunjucks-enabled-context.tsx
> +    <NunjucksEnabledContext.Provider value={{ enabled }}>
This is a great catch. We can (and I will) test this, but we don't need `useState` and `useEffect` here. f8c168e4f145d2dc698f632d2dd1517794c0df00

2021-12-01 03:35 UTC, develohpanda commented on packages/insomnia-app/app/ui/context/nunjucks/use-nunjucks.ts
> +export const useNunjucks = () => useNunjucksRenderFuncs();
Fixed in 19f541e72bb995cf0da95d72af03c6546793a914

2021-12-01 03:36 UTC, develohpanda commented on packages/insomnia-app/app/ui/context/nunjucks/index.ts
> +export { useNunjucksEnabled } from './nunjucks-enabled-context';
Fixed in 19f541e72bb995cf0da95d72af03c6546793a914. Not resolving this yet as I intend to write a readme (similar to the PR description here).

2021-12-01 06:33 UTC, develohpanda commented on packages/insomnia-app/app/ui/context/nunjucks/nunjucks-enabled-context.tsx
> +    <NunjucksEnabledContext.Provider value={{ enabled }}>
[`958c7db` (#4248)](https://github.com/Kong/insomnia/pull/4248/commits/958c7db54743a034b468001ab188a612b7d8f7a5)

2021-12-01 07:20 UTC, develohpanda commented on packages/insomnia-app/app/ui/context/nunjucks/use-nunjucks.ts
> +  // context: enabled,  prop: enabled  -> should enable
Added in [`1433836` (#4248)](https://github.com/Kong/insomnia/pull/4248/commits/143383614bae8ac11ce58ba7d867eb590d1edd6b)

2021-12-01 11:35 UTC, gatzjames commented on packages/insomnia-app/app/ui/context/nunjucks/use-render-functions.ts
> + * @deprecated this hook is intended to only be used by `NunjucksRenderFunctionProvider`
🤔 Curious why this is deprecated before it's even created?

2021-12-01 11:44 UTC, gatzjames commented on packages/insomnia-app/app/ui/context/nunjucks/use-render-functions.ts
> +  const handleRender: HandleRender = useCallback(async <T>(obj: T, contextCacheKey: string | null = null) => {
We could use undefined instead of null here
```suggestion
  const handleRender: HandleRender = useCallback(async <T>(obj: T, contextCacheKey?: string) => {
```
 or even better not accept an undefined cache key in the function

2021-12-01 12:25 UTC, gatzjames commented on packages/insomnia-app/app/ui/context/nunjucks/use-render-functions.ts
> +    setTimeout(() => delete getRenderContextPromiseCache[contextCacheKey], 5000);
I think we should reevaluate the usage of setTimeout here and the promise cache invalidation.
One problem I see with the current implementation is that the timeout is not reset if we store the same `contextCacheKey` which can lead to race condition trouble here.
Imo if we need the ability to invalidate records on the cache it would be better if that functionality is on the cache layer itself.
e.g.
```ts
// Imaginary cache api that handles timeouts and resets the timeout if the same key is stored
cache.set(key, data, { timeout: 5000 })

// A few moments later (<5s)
let contextEarly = await cache.get(key) // data

// A few moments later than before (>5s)
let contextLate = await cache.get(key) // null
```

As a quick solution for this we could store the timeoutId with the contextCacheKey and clear the timeout if it's being reused:
e.g.
```ts
const contextPromiseTimeoutCache = new Map<string, string>();

const previousTimeoutId = contextPromiseTimeoutCache.get(contextCacheKey);

if (previousTimeoutId) {
  clearTimeout(previousTimeoutId)
}

const timeoutId = setTimeout(() => delete getRenderContextPromiseCache[contextCacheKey], 5000);

contextPromiseTimeoutCache.set(contextCacheKey, timeoutId)
```

2021-12-01 12:30 UTC, gatzjames commented on packages/insomnia-app/app/ui/context/nunjucks/use-gated-nunjucks-render-functions.ts
> +  const shouldEnable = shouldEnableNunjucks({
🤔 I think that this function could be replaced with a simpler
```suggestion
const isNunjucksTemplatingEnabled = enabled && !props.disabled
```

2021-12-01 16:26 UTC, gatzjames commented on packages/insomnia-app/app/ui/components/sidebar/sidebar-request-row.tsx
> +export const UnconnectedSidebarRequestRowWithRender: FC<Omit<Props, 'handleRender'>> = props => {
Tested this and seems like the drag'n'drop api expects a ref to be passed otherwise reordering won't work 😅. Using forwardRef and passing the ref to the class component seems to do the magic!

2021-12-01 16:59 UTC, gatzjames requested changes
👏 This is some awesome work!
Found an issue with forwarding refs so we should double check and make sure that there's no ref expectation for the components that we moved to functions or if there is that we forward the ref properly.

2021-12-02 00:17 UTC, develohpanda commented on packages/insomnia-app/app/ui/context/nunjucks/use-render-functions.ts
> +    setTimeout(() => delete getRenderContextPromiseCache[contextCacheKey], 5000);
This relates to one of dimitri's comments above where this whole logic is a bit confusing: https://github.com/Kong/insomnia/pull/4248#discussion_r759592758.

I mainly copy-pasted it from app.tsx and don't want to change it, but let's address in a follow-up PR? I'll create a ticket for us to revisit this logic

2021-12-02 00:18 UTC, develohpanda commented on packages/insomnia-app/app/ui/context/nunjucks/use-render-functions.ts
> +  const handleRender: HandleRender = useCallback(async <T>(obj: T, contextCacheKey: string | null = null) => {
Same as https://github.com/Kong/insomnia/pull/4248#discussion_r760670168, just refactored as-is from app.tsx

2021-12-02 00:22 UTC, develohpanda commented on packages/insomnia-app/app/ui/context/nunjucks/use-render-functions.ts
> + * @deprecated this hook is intended to only be used by `NunjucksRenderFunctionProvider`
@jackkav & @dimitropoulos and I talked about this on a call yesterday. It's because we need to export this to test it and use it in `NunjucksRenderFunctionProvider`, but it should _only_ be used by `NunjucksRenderFunctionProvider`, as the context provider provides a "cached" instance to all consumers via `useNunjucksRenderFunctions` and `useGatedNunjucksRenderFunctions`.

I'd love to chat about any other suggestions you have for how we can improve this.

_something something in js all exports are created equal_ :(

2021-12-02 00:29 UTC, develohpanda commented on packages/insomnia-app/app/ui/context/nunjucks/use-render-functions.ts
> +    return getRenderContext({
Follow-up INS-1224.

I want to write _some_ tests for this at least for the current state, I'll document any findings, but the ticket above is a larger follow-up to address some of James' comments below too.

How does that sound?

2021-12-02 00:30 UTC, develohpanda commented on packages/insomnia-app/app/ui/containers/app.tsx
> -   * Heavily optimized render function
INS-1224. As mentioned above, I'll document what I find as I write some tests still.

2021-12-02 00:34 UTC, develohpanda commented on packages/insomnia-app/app/ui/context/nunjucks/use-gated-nunjucks-render-functions.ts
> +  const shouldEnable = shouldEnableNunjucks({
I addressed this in [`39bc60a` (#4248)](https://github.com/Kong/insomnia/pull/4248/commits/39bc60a1944dd372f534b4c270a9da8f99c3104f), let me know what you think!

2021-12-02 00:46 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/sidebar/sidebar-request-row.tsx
> +export const UnconnectedSidebarRequestRowWithRender: FC<Omit<Props, 'handleRender'>> = props => {
Wow that's not misleading at all 🤯 Thanks for being so diligent in QA for this. I'll double check other components, but at least passing a ref _manually_ into a FC actually fails 🎉 

```tsx
const SomeComponent: FC = () => <div />;

// Not allowed
<SomeComponent ref={...} />
```

2021-12-02 01:22 UTC, develohpanda commented on packages/insomnia-app/app/ui/components/sidebar/sidebar-request-row.tsx
> +export const UnconnectedSidebarRequestRowWithRender: FC<Omit<Props, 'handleRender'>> = props => {
At first I did [`4e17fa0` (#4248)](https://github.com/Kong/insomnia/pull/4248/commits/4e17fa06250727a100258c80744ac57ef026e410) but opted for [`17eeeb4` (#4248)](https://github.com/Kong/insomnia/pull/4248/commits/17eeeb483e905096b418adbcfaf025504da00759) instead. This way we avoid manually working with the ref.

I also removed the generic prop definitions because TS resolves them correctly (and better than manually typing them).

Really good find :)

![2021-12-02 14 21 44](https://user-images.githubusercontent.com/4312346/144340373-0c3b8ad5-5569-4a85-8e3d-d0de944594f1.gif)

2021-12-02 01:28 UTC, develohpanda commented
> we should double check and make sure that there's no ref expectation for the components that we moved to functions or if there is that we forward the ref properly.

The `row` component is the only other component that uses DnD, and it forwards the refs as expected

![2021-12-02 14 27 13](https://user-images.githubusercontent.com/4312346/144340871-3543cf6c-36cf-4f35-a598-7b7e37508d99.gif)

2021-12-02 04:58 UTC, develohpanda reviewed
Screenshots of tests so they're easier to process

2021-12-02 04:58 UTC, develohpanda commented on packages/insomnia-app/app/ui/context/nunjucks/__tests__/use-render-functions.test.ts
> +describe('useRenderFunctions', () => {
<img width="727" alt="image" src="https://user-images.githubusercontent.com/4312346/144360174-f7dd4022-616a-414b-bc23-ef8623eaa0e9.png">

2021-12-02 04:58 UTC, develohpanda commented on packages/insomnia-app/app/ui/context/nunjucks/__tests__/nunjucks-enabled-context.test.tsx
> +describe('NunjucksEnabledProvider', () => {
<img width="464" alt="image" src="https://user-images.githubusercontent.com/4312346/144360235-497d2de9-f4fd-4823-8146-7beadb20f2e1.png">

2021-12-02 04:58 UTC, develohpanda commented on packages/insomnia-app/app/ui/context/nunjucks/__tests__/nunjucks-provider.test.tsx
> +describe('NunjucksProvider', () => {
<img width="452" alt="image" src="https://user-images.githubusercontent.com/4312346/144360291-5df96fb8-1bbb-4f41-a5d7-35642887f04c.png">

2021-12-02 04:58 UTC, develohpanda commented on packages/insomnia-app/app/ui/context/nunjucks/__tests__/nunjucks-render-function-context.test.tsx
> +describe('NunjucksRenderFunctionProvider', () => {
<img width="714" alt="image" src="https://user-images.githubusercontent.com/4312346/144360370-188442bc-2d75-4d14-944d-ab148a44e403.png">

2021-12-02 04:58 UTC, develohpanda commented on packages/insomnia-app/app/ui/context/nunjucks/__tests__/use-gated-nunjucks-render-functions.test.tsx
> +describe('useGatedNunjucksRenderFunctions', () => {
<img width="688" alt="image" src="https://user-images.githubusercontent.com/4312346/144360431-f2a1e7d0-e105-4870-8136-614aefc88f8d.png">

2021-12-02 09:15 UTC, jackkav commented on packages/insomnia-app/app/ui/context/nunjucks/use-render-functions.ts
> + * @deprecated this hook is intended to only be used by `NunjucksRenderFunctionProvider`
I think it's a code smell to indicate to developers which functions to use and not to use, especially misleading them with this new deprecated convention. Instead consider the reason for the indication and resolve that. In this case it appears to be the complexity of the code paths moved over from app.tsx if they were simplifed would it be necessary to house them in their own, "don't use me functions"?

2021-12-02 10:28 UTC, develohpanda commented on packages/insomnia-app/app/ui/context/nunjucks/use-render-functions.ts
> + * @deprecated this hook is intended to only be used by `NunjucksRenderFunctionProvider`
It's not the complexity of the functions having moved out of app.tsx requiring a "don't use me". It's the fact this hook is preparing data for react context and we want consumers to pull from context.

I've tried to in-line the contents of this hook within `NunjucksRenderFunctionProvider` and also within the file itself, to prevent an export entirely, to no avail.

In-lining also adds some degree of indirection when unit testing, but this is less of a concern.

Please share any concrete suggestions for how you might see this working and I'll adapt, otherwise I'll give it another go at in-lining tomorrow but will likely need to pair.

> especially misleading them with this new deprecated convention

Lastly I'd like to add that using a deprecated flag is what we had decided on a call two days ago between @jackkav and @dimitropoulos, so this comment comes as a surprise

2021-12-02 13:30 UTC, gatzjames commented on packages/insomnia-app/app/ui/context/nunjucks/use-render-functions.ts
> + * @deprecated this hook is intended to only be used by `NunjucksRenderFunctionProvider`
Got it!
I think that using `@deprecated` for marking internal functions feels a bit off.
Does this stop the function from being imported elsewhere?
If not I think a comment about it's usage should be enough or we could use an index file in the nunjucks folder and specify which functions etc get exported from there?

2021-12-02 13:32 UTC, gatzjames commented on packages/insomnia-app/app/ui/context/nunjucks/use-render-functions.ts
> +    setTimeout(() => delete getRenderContextPromiseCache[contextCacheKey], 5000);
Definitely for another PR! This is going to be quite some work plus testing etc!

2021-12-03 00:04 UTC, develohpanda commented on packages/insomnia-app/app/ui/context/nunjucks/use-render-functions.ts
> + * @deprecated this hook is intended to only be used by `NunjucksRenderFunctionProvider`
I changed this up in [`cc5f97a` (#4248)](https://github.com/Kong/insomnia/pull/4248/commits/cc5f97a6560b2fc066701750f4552c2dc486e9cb), have a look at the end result (as the commit itself will be a bit verbose. How does it feel now?

I've removed the `NunjucksRenderFunctionProvider` and moved the cache to be a singleton, so anything that needs to render functions only needs to use `useNunjucks` and `useGatedNunjucks`. There's no depreated "don't use me" function anymore.

I've also added a test which will fail if the cache _isn't_ a singleton (the last one here)

<img width="728" alt="image" src="https://user-images.githubusercontent.com/4312346/144522070-a7ae1b37-2005-479e-b263-151c6f427a34.png">

2021-12-03 00:11 UTC, develohpanda commented on packages/insomnia-app/app/ui/context/nunjucks/__tests__/use-gated-nunjucks.test.tsx
> +describe('useGatedNunjucks', () => {
<img width="696" alt="image" src="https://user-images.githubusercontent.com/4312346/144522723-f14b5926-422b-4fbd-99b7-c04dcf69fb38.png">

2021-12-03 00:13 UTC, develohpanda commented on packages/insomnia-app/app/ui/context/nunjucks/__tests__/use-nunjucks.test.ts
> +describe('useNunjucks', () => {
<img width="716" alt="image" src="https://user-images.githubusercontent.com/4312346/144522783-bc89a4be-b16a-482d-a033-9a4b07e17368.png">

2021-12-03 15:57 UTC, gatzjames commented on packages/insomnia-app/app/ui/context/nunjucks/use-render-functions.ts
> + * @deprecated this hook is intended to only be used by `NunjucksRenderFunctionProvider`
Looks great! I like that it removes the problem of reusing this fn completely!

2021-12-03 15:59 UTC, gatzjames approved these changes
👏 🎉 🙏

2021-12-03 20:08 UTC, merged