Import multiple envs when importing OpenAPI3
getinsomnia/insomnia pull request #4254
Opened 2021-11-28 09:06 UTC by sixdouglas

When the OpenApi file to import contains multiple servers, import each one as an environment.

Closes #3627

2021-12-03 20:46 UTC, ryanholden8 commented
Really looking forward to using this, thank you!

2021-12-05 22:21 UTC, develohpanda commented
Thank you for the PR! A couple of notes, namely the `_id` and `name` generation for the sub-environments.

2021-12-05 22:22 UTC, develohpanda requested changes
Thank you for the PR! A couple of notes, namely the `_id` and `name` generation for the sub-environments.

(The CI errors are linting, which should be fixed up with `npm run lint:fix`).

2021-12-05 22:22 UTC, develohpanda commented on packages/insomnia-importers/src/importers/openapi-3.ts
> +          _id: 'env___BASE_ENVIRONMENT_ID___sub',
This will cause all of the sub environments to have the same id and insomnia won't see them as unique.

In other areas we append a hash of the dependent property to make the id deterministic and unique. What would be a dependent property here - the URL? Ie. if the server URL changes, a _new_ sub environment will be created.

2021-12-05 22:22 UTC, develohpanda commented on packages/insomnia-importers/src/importers/openapi-3.ts
> +          name: 'OpenAPI env',
Same note as above, the name for each sub environment will be `OpenAPI env`. What would you expect the environment created from each new server to be named?

2021-12-05 22:22 UTC, develohpanda commented on packages/insomnia-importers/src/convert.test.ts
> +describe('Import OpenApi', () => {
Any particular reason you chose to add tests like this instead of adding to the fixtures in packages/insomnia-importers/src/importers/fixtures/openapi3?

2021-12-13 20:20 UTC, sixdouglas commented on packages/insomnia-importers/src/importers/openapi-3.ts
> +          _id: 'env___BASE_ENVIRONMENT_ID___sub',
Nice catch. I'll fix it.

2021-12-13 20:20 UTC, sixdouglas commented on packages/insomnia-importers/src/importers/openapi-3.ts
> +          name: 'OpenAPI env',
I'll fix it too

2021-12-13 20:23 UTC, sixdouglas commented on packages/insomnia-importers/src/convert.test.ts
> +describe('Import OpenApi', () => {
No particular reason, just didn't understand the test mechanism. So I wrote this one.
I'll do it in the same way as the other tests.

2022-06-30 14:22 UTC, Fishbowler commented
This would be really useful for getting Insomnia into my organisation. Is there something I can do to help get this finished? I'm not sure what's left to do.

2022-09-19 08:43 UTC, antonioturdo commented
I also hope to have this improvement in Insomnia.

2022-11-27 07:48 UTC, dgmora commented
This feels very necessary to work with insomnia when our primary source is OpenAPI. Is there a problem with the PR?

2022-11-30 19:28 UTC, filfreire approved these changes
Sorry for the long wait @sixdouglas

Rebased with latest develop and fixed lint and tests.

Tested locally, LGTM! Waiting for someone else from @Kong/team-insomnia to give the 👍

2022-12-05 11:31 UTC, merged