Chore: replace spectron with playwright
getinsomnia/insomnia pull request #4305
Opened 2021-12-13 20:55 UTC by jackkav

Related: https://github.com/electron-userland/spectron/issues/1045

Notes:
- windows doesn't start properly so theres a forced reload in the test setup

Todo
- docs
- test setup fixtures
- better insomnia request collection fixture

2021-12-14 22:24 UTC, dimitropoulos commented on packages/insomnia-smoke-test/package.json
> +    "playwright:package": "xvfb-maybe cross-env BUNDLE=package PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 npx playwright@1.17.1 test",
just curious what the reason was for flipping where `xvfb-maybe` is ordered in

2021-12-14 22:25 UTC, dimitropoulos commented on packages/insomnia-smoke-test/specs/app.spec.ts
> +    : path.join('linux-unpacked', 'insomnia');
could we possibly un-nested-ternary this?

2021-12-14 22:54 UTC, jackkav commented on packages/insomnia-smoke-test/package.json
> +    "playwright:package": "xvfb-maybe cross-env BUNDLE=package PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 npx playwright@1.17.1 test",
The additional env var

2021-12-14 22:54 UTC, jackkav commented on packages/insomnia-smoke-test/specs/app.spec.ts
> +    : path.join('linux-unpacked', 'insomnia');
Done-zo

2021-12-16 10:40 UTC, develohpanda requested changes
I know you've chosen to descope writing utilities/page objects from this PR. In theory that's fine, it's a work in progress, but we're deleting a _lot_ of valuable code and if we slightly alter the approach we can take a step up from Spectron instead of start from scratch. Note that what we are changing is the test framework, and from what I've seen in this PR that doesn't need to involve starting from scratch.

The existing page object approach of writing an e2e test is agnostic of the framework being used. If you look at the overall functions - click a request, click send, click a tab, open a dropdown - and how they are parameterized, they describe user actions, and the implementation describes how the test framework should handle those user actions.

We've changed our test framework from Spectron to Playwright. Updating the page object implementations to work with Playwright's API will allow us to keep the existing tests (which are much more readable than the what I'm reviewing in this PR) and continue from there.

I have a strong opinion that it is not necessary to delete all of the existing tests and page objects and start, effectively, from scratch.

This is feedback about the overall approach, please don't misunderstand it as a request to increase the scope of this PR. How can we help ourselves build on top of what's already written, instead of start from scratch?

2021-12-16 10:40 UTC, develohpanda commented on packages/insomnia-app/app/main.development.ts
> +  app.setPath('userData', process.env.INSOMNIA_DATA_PATH ?? newPath);
Why is this needed? We have https://github.com/Kong/insomnia/blob/8918b1511383ecf2904d564ff50beb3228855ea8/packages/insomnia-app/app/common/electron-helpers.ts#L26-L29. Super wary of making data path changes.

2021-12-16 10:40 UTC, develohpanda commented on packages/insomnia-smoke-test/README.md
> +If the playwright test runner doesn't start the following command will show the stack on launch `DEBUG=pw:browser`
"The following command" or "the following environment variable?

2021-12-16 10:40 UTC, develohpanda commented on packages/insomnia-smoke-test/README.md
> -When raising a PR, paste a screenshot of the test results showing at least 20 successful iterations.
Please reinstate these lines, as they are not specific to Spectron

2021-12-16 10:40 UTC, develohpanda commented on packages/insomnia-smoke-test/package.json
> +    "playwright:build": "xvfb-maybe cross-env BUNDLE=build PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 npx playwright@1.17.1 test",
Why use npx instead of installing playwright as a propery dependency? If it's a dependency, it will be checked by dependabot, for example

2021-12-16 10:40 UTC, develohpanda commented on packages/insomnia-smoke-test/playwright.config.ts
> +  },
This is very cool!

2021-12-16 10:40 UTC, develohpanda commented on packages/insomnia-smoke-test/playwright.config.ts
> +  testDir: 'specs',
Please call the "test" terminology instead of "spec" to a) differentiate between openapi specs, and b) follow the pattern this repository? `tests/foo.test.ts` or `__tests__/foo.test.ts`.

2021-12-16 10:40 UTC, develohpanda commented on packages/insomnia-smoke-test/playwright/paths.ts
> +"npm run app-build:smoke"`);
```suggestion
  console.error(`ERROR: ${mainPath} not found at ${path.resolve(cwd, mainPath)}. Have you run "npm run app-build:smoke"?`);
```

2021-12-16 10:40 UTC, develohpanda commented on packages/insomnia-smoke-test/playwright/paths.ts
> +"npm run app-package:smoke"`);
```suggestion
  console.error(`ERROR: ${insomniaBinary} not found at ${path.resolve(cwd, insomniaBinary)}. Have you run "npm run app-package:smoke"?`);
```

2021-12-16 10:40 UTC, develohpanda commented on packages/insomnia-smoke-test/specs/app.spec.ts
> +const isPackageTest = process.env.BUNDLE === 'package';
This line also exists inside `paths.ts`, please consolidate

2021-12-16 10:40 UTC, develohpanda commented on packages/insomnia-smoke-test/specs/app.spec.ts
> +const newPage = async ({ playwright, options }: ({ playwright: Playwright; options: {} })) => {
Given `options` is actually being used further down, please add a type definition instead of  `{}`

2021-12-16 10:40 UTC, develohpanda commented on packages/insomnia-smoke-test/specs/app.spec.ts
> +  const options = { INSOMNIA_DATA_PATH: randomDataPath };
It looks to me like `randomDataPath` will not change between tests. So, if I have 3 unique tests in this suite, they will all use the same data path. If this is correct, is this behaviour intentional, and is it appropriate? Why/why not?

2021-12-16 11:39 UTC, jackkav commented on packages/insomnia-smoke-test/package.json
> +    "playwright:build": "xvfb-maybe cross-env BUNDLE=build PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 npx playwright@1.17.1 test",
I was just applying a convention from cypress, to avoid dev deps that might contain binaries like chrome, but since @playwright/test contains playwright, and browser is disabled there is no need to use the convention, thanks for the push.

2021-12-16 12:15 UTC, jackkav commented on packages/insomnia-smoke-test/specs/app.spec.ts
> +  const options = { INSOMNIA_DATA_PATH: randomDataPath };
yep this was a mistake, thanks for the catch

2021-12-16 12:19 UTC, jackkav commented on packages/insomnia-smoke-test/specs/app.spec.ts
> +const newPage = async ({ playwright, options }: ({ playwright: Playwright; options: {} })) => {
fair

2021-12-16 12:20 UTC, jackkav commented on packages/insomnia-smoke-test/specs/app.spec.ts
> +const isPackageTest = process.env.BUNDLE === 'package';
this function isn't related to paths I'll just remove it.

2021-12-16 12:33 UTC, jackkav commented on packages/insomnia-smoke-test/README.md
> +If the playwright test runner doesn't start the following command will show the stack on launch `DEBUG=pw:browser`
thanks docs are hard

2021-12-16 12:34 UTC, jackkav commented on packages/insomnia-app/app/main.development.ts
> +  app.setPath('userData', process.env.INSOMNIA_DATA_PATH ?? newPath);
I tried it without this and it seems good, thanks for the push

2021-12-16 12:40 UTC, jackkav commented on packages/insomnia-smoke-test/README.md
> -When raising a PR, paste a screenshot of the test results showing at least 20 successful iterations.
ah the inso CLI doc delete was a mistake, thanks for the catch.
I don't agree that this 20 times process is desirable. If anything it warns contributors away from contributing smoke tests, which playwright aims to encourage.

2021-12-16 12:42 UTC, jackkav commented on packages/insomnia-smoke-test/playwright.config.ts
> +  },
Sure is, haven't figured out how to show the logs for it yet though. Haven't needed to yet.

2021-12-16 12:44 UTC, jackkav commented on packages/insomnia-smoke-test/playwright.config.ts
> +  testDir: 'specs',
sure thing

2021-12-16 13:08 UTC, jackkav commented
Thank you for your thoughts and concerns I hear you and hope to address them to your satisfaction.

> I know you've chosen to descope writing utilities/page objects from this PR. In theory that's fine, it's a work in progress, but we're deleting a lot of valuable code and if we slightly alter the approach we can take a step up from Spectron instead of start from scratch. Note that what we are changing is the test framework, and from what I've seen in this PR that doesn't need to involve writing things from scratch.

Playwright and Spectron are not a 1:1 API match, there are new playwright specific conventions to learn and adapt, and it is unwise to learn and adapt to them as one contributor in a single PR.

> The existing page object approach of writing an e2e test is agnostic of the framework being used. If you look at the overall functions - click a request, click send, click a tab, open a dropdown - and how they are parameterized, they describe user actions, and the implementation describes how the test framework should handle those user actions.

The reason this code uses playwright recordings for its runs are to separate any of my personal opinions about test structuring from the replacement effort, while creating an opportunity to revisit existing conventions, I agree the modules were very useful in making readable spectron tests possible, and we will certainly want to pull in some of the ideas with playwright. However I strongly believe the introduction of abstractions over test structure should happen carefully as these tests have a huge impact on the contribution experience, so we have a duty to keep them as lean and fast as possible to maximise return on investment.

> We've changed our test framework from Spectron to Playwright. Updating the page object implementations to work with Playwright's API will allow us to keep the existing tests (which are much more readable than the what I'm reviewing in this PR) and continue from there.

Readability is subjective and not something I aim to improve in this PR, only to provide us with a starting point to build confidence in our e2e testing.

> I have a strong opinion that it is not necessary to delete all of the existing tests and page objects and start again. This is feedback about the overall approach, please don't take it as a request to increase the scope of this PR. How can we help ourselves build on top of what's already written, instead of writing from scratch?

We can build on top by writing new tests ourselves on top of this minimal safety net, to show the value of required abstractions.

My goal is to eliminate barriers to contribution, to me this means making it intuitive, easy to change and with as little indirection as possible.

2021-12-16 14:48 UTC, filfreire approved these changes
Marking this as approved, seems to work ok, just some minor comments:
- Tests were passing earlier now are failing, I suspect due to a missing click on the `can send requests` scenario
- Left some notes of stuff we might want to look at in the future - like spinning up gRPC and Websocket test servers like you did for http, and also we might want to explore tests where we purposely import insomnia data folder that are in a weird state.

2021-12-16 14:48 UTC, filfreire commented on packages/insomnia-smoke-test/specs/app.spec.ts
> -  await page.click('text=Smoke tests');
@jackkav by removing this the tests seem to be failing now, since playwright can't open the collection to try and issue the requests.
<img width="810" alt="Screenshot 2021-12-16 at 14 29 45" src="https://user-images.githubusercontent.com/11976836/146390536-9f3cb208-9f31-4838-b529-de47ee423b81.png">

2021-12-16 14:48 UTC, filfreire commented on .github/workflows/test.yml
> +        run: npm run app-build:smoke
To pick on something @dimitropoulos had mentioned a while back, I think we could just try and also change the commands both here and in the `package.json` to something that is more readable and simpler.
Related to this ticket: https://linear.app/insomnia/issue/INS-1276/improve-npm-script-experience

Perhaps reducing all our smoke commands to just 2, something like `npm run smoke:build` and `npm run smoke:test`? (Not sure about the naming though)

2021-12-16 14:48 UTC, filfreire commented on packages/insomnia-smoke-test/playwright.config.ts
> +  webServer: {
Same opinion as @develohpanda on this, this is awesome. There's probably a way for us to mimic this and add one for gRPC, and later on websockets , etc. Really cool stuff 👍

2021-12-16 14:48 UTC, filfreire commented on packages/insomnia-smoke-test/tests/app.test.ts
> +  const options = { INSOMNIA_DATA_PATH: randomDataPath() };
This is giving me an idea - let's say we get a bug that is only reproducible with someone's backup of a data folder, we could make it so folks can point to a data path for the test they want to run - which we would fetch locally or maybe download from S3 bucket where we store weird data folder backups.

2021-12-16 14:48 UTC, filfreire commented on packages/insomnia-smoke-test/tests/app.test.ts
> +  await page.click('button:has-text("GETsend JSON request")');
I'm not sure if my other comment will be visible, but here we're missing the step before this one where we click to open the collection after importing.

2021-12-16 16:45 UTC, DMarby approved these changes
Awesome 👍 

Found two remaining references to Spectron, not sure if we have the same issue with the `tsconfig` with Playwright as we did for Spectron?
https://github.com/Kong/insomnia/blob/b2c94ebbdbcc72750d1cb415f058d49a57ca5676/packages/insomnia-smoke-test/tsconfig.build.json#L9
https://github.com/Kong/insomnia/blob/b2c94ebbdbcc72750d1cb415f058d49a57ca5676/DEVELOPMENT.md?plain=1#L60

2021-12-16 16:45 UTC, DMarby commented on packages/insomnia-smoke-test/README.md
> +| `/specs`    | tests for Insomnia                |
```suggestion
| `/tests`    | tests for Insomnia                |
```

2021-12-16 16:46 UTC, DMarby commented on packages/insomnia-smoke-test/specs/app.spec.ts
> -  await page.click('text=Smoke tests');
Can confirm this locally as well, adding this line back in makes the test pass for me

2021-12-16 17:25 UTC, jackkav commented on .github/workflows/test.yml
> +        run: npm run app-build:smoke
I like it!

2021-12-16 17:33 UTC, DMarby commented on packages/insomnia-smoke-test/tests/app.test.ts
> +  const options = { INSOMNIA_DATA_PATH: randomDataPath() };
I think we need to pass `DESIGNER_DATA_PATH` for all tests by default to a directory that does not exist, as otherwise the app will pick up the local designer directory if there is one and attempt to migrate (this breaks the tests for me locally since I have an old Insomnia Designer install present)

I believe we used to use the same approach for Spectron: https://github.com/Kong/insomnia/blob/b2c94ebbdbcc72750d1cb415f058d49a57ca5676/packages/insomnia-smoke-test/modules/application.ts#L19

2021-12-16 18:24 UTC, jackkav commented on .github/workflows/test.yml
> +        run: npm run app-build:smoke
It's in so many places in the code base and meant to exist alongside many other contexts so I'll scope it out for now, but worth a later PR to look for ways to clarify the wording of `app-build:smoke` and `test:smoke:build`

2021-12-16 18:25 UTC, jackkav commented on packages/insomnia-smoke-test/specs/app.spec.ts
> -  await page.click('text=Smoke tests');
I was seeing import for clipboard go straight to the send request view, so I assumed it had been changed in a recent PR after rebase. Not sure though.

2021-12-16 18:26 UTC, jackkav commented on packages/insomnia-smoke-test/tests/app.test.ts
> +  const options = { INSOMNIA_DATA_PATH: randomDataPath() };
done, thanks for the catch! I added a note too for if we remove migration

2021-12-16 20:17 UTC, develohpanda commented on packages/insomnia-smoke-test/README.md
> -When raising a PR, paste a screenshot of the test results showing at least 20 successful iterations.
Ah that's all good, we can drop the 20 times thing. We can bring it back if the need arises!

2021-12-16 20:22 UTC, develohpanda commented on .github/workflows/test.yml
> +        run: npm run app-build:smoke
I agree with this to try and increase clarity! There are a few variations hence the confusion:

* build the app
* build the app for smoke tests
* package the app
* package the app for smoke tests
* run smoke tests against build artifacts
* run smoke tests against the packaged binaries

Building the app is faster than packaging the app. But certain things (such as testing plugin installation) requires the test to be run against a packaged binary instead of build artifacts. Testing against the packaged app is also more realistic, so it's just weighing up the pros and cons.

Additionally, the first four bulletpoints can become _two_ bulletpoints if we can remove/address the requirement for a gitref in the build script: https://github.com/Kong/insomnia/blob/5f4c19da35e90ffa2f3ae27e9b309ee48f9d4e16/packages/insomnia-app/scripts/getBuildContext.ts#L38-L51

2021-12-16 20:26 UTC, develohpanda commented on packages/insomnia-smoke-test/tests/app.test.ts
> +  const options = { INSOMNIA_DATA_PATH: randomDataPath() };
Nice catch 🔥

2021-12-16 20:49 UTC, develohpanda approved these changes
Thanks for your thoughts as well! Readability _is_ subjective but readability helps with code reviews, and while the contribution experience is important, maintainability is also important when tests break and someone goes in with fresh eyes, and over time I hope we can reach a balance between all of these factors.

One action item: could you please make follow-up tasks to go to the existing smoke tests and migrate many of the assertions across?

For example, the PDF viewer assertion, or the XML filter assertion are both regression tests and we shouldn't lose those learnings. https://github.com/Kong/insomnia/blob/b2c94ebbdbcc72750d1cb415f058d49a57ca5676/packages/insomnia-smoke-test/core/app.test.ts#L81-L94.

Another example is the Basic Auth test. Instead of simply testing basic auth works through a header, it's purpose is to use the Auth tab within Insomnia to simulate a user typing into the fields, enabling and disabling auth and verifying the expected response.

tl;dr through this PR we lose a lot of coverage, and we should make an effort to bring across the existing tests once this has merged to reinstate that coverage, hence follow-up tasks.

2021-12-17 12:05 UTC, merged