Chore/consolidate request libs
getinsomnia/insomnia pull request #4308
Opened 2021-12-15 14:46 UTC by jackkav

Problem: There are 4 ways to send a request in insomnia today and not all respect user preferences.

- whatwg-fetch: feat/sync to insomnia backend
- axios: feat/git-sync, segment analytics and deploy to dev portal
- electron.net.request: google analytics and plugin install
- node-libcurl: normal user requests, including oauth2 and graphql introspection

Solution: Remove 2 of them

- node-libcurl: normal user requests, including oauth2 and graphql introspection
- axios: everything else

Closes INS-1302

2021-12-15 15:18 UTC, DMarby requested changes
This PR is great!

For accounts/sync however, I think we need might need a separate axios instance or request config, as we should not allow disabling SSL verification. We might also want to do the same for the plugin install, given that it fetches and executes code from NPM?

I do think it makes sense to allow use the configured application proxy like we do now however.

2021-12-15 15:55 UTC, jackkav commented
I agree, I'm thinking ssl verification should not be configurable for any internal app requests, only curl requests made with the send button. Thanks for the reminder!

Follow up: We may also want to prevent SSL verification from being disabled on OAuth2 flows login step.

2021-12-15 17:18 UTC, gatzjames reviewed
👏 Nice!

Some notes/questions that came to mind:
- What happens to plugins expecting the validateSSL setting to be respected?
- In a couple of places we do `try { let response = await axiosRequest(...) } catch (e) { response.error = e }`. Since axios provides us with a promise/stream based api we could handle these cases better now.

2021-12-15 17:18 UTC, gatzjames commented on packages/insomnia-app/app/plugins/install.ts
> +        request.error = err;
Seems like we can remove the `.error` property from the request and directly throw here:

```suggestion
        reject(new Error(`Failed to make plugin request ${info?.dist.tarball}: ${err.message}`));
```

2021-12-15 20:21 UTC, jackkav commented on packages/insomnia-app/app/plugins/install.ts
> +        request.error = err;
thanks

2021-12-15 20:23 UTC, jackkav commented on packages/insomnia-app/app/network/axios-request.ts
> +export const axiosRequestWithOptionalSSLVerify = async (config: AxiosRequestConfig) => {
This could use a better name

2022-01-24 07:26 UTC, jackkav commented
@DMarby in order to give this PR a better chance of being a no-op, I have matched non-axios request libraries to axios with default rather than overriding proxy or cert settings with user preferences. This should ensure no current use cases are impacted. Thanks.

- whatwg-fetch: feat/sync to insomnia backend -> axiosRequest
- axios: feat/git-sync, segment analytics and deploy to dev portal -> axiosRequestWithUserDefinedProxy
- electron.net.request: google analytics and plugin install -> axiosRequest

2022-01-24 11:31 UTC, gatzjames commented on packages/insomnia-app/app/account/fetch.ts
> +    method: Method | undefined;
```suggestion
    method?: Method;
```

2022-01-24 11:31 UTC, gatzjames commented on packages/insomnia-app/app/common/analytics.ts
> -        for (const result of hitParsingResult || []) {
🤔 Looks like the hitParsingResult was treated as an object above and as an array of objects bellow.
I googled the google api and found this https://developers.google.com/analytics/devguides/collection/protocol/v1/validating-hits which appears to return a list 😂

2022-01-24 17:46 UTC, jackkav commented
Closing because migrating the what-wg fetch api to axios makes less sense now we are evaluating `got`(based on fetch api), and we are planning to remove google analytics.

2022-01-24 17:46 UTC, closed without merging