Cleanup extra 'v' in version of the document card
getinsomnia/insomnia pull request #4319
Opened 2021-12-16 23:07 UTC by wdawson

Took the quick fix path for this issue for now. As noted in the issue, we want to improve this eventually to more clearly show that it's metadata and pull the value directly. But this is the solution we want for now.

https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.yaml

Resolves INS-1277

2021-12-16 23:09 UTC, wdawson commented
I couldn't easily find anywhere to add a test. Is there anything I can add to?

2021-12-17 13:24 UTC, filfreire requested changes

2021-12-17 13:24 UTC, filfreire commented on packages/insomnia-app/app/ui/components/workspace-card.tsx
> +  if (version.length > 0 && !version.startsWith('v')) {
Tested locally, this seems ok for strings like `v1.0` or `1.0`.

This would still have a problem with version names where folks decide to start with other letters, e.g. `alpha-1.0` or `something`. We could probably also check if it starts with any non digit character (a-zA-Z).

![Screenshot 2021-12-17 at 13 22 16](https://user-images.githubusercontent.com/11976836/146551033-5088d88b-8f6c-4ff5-b05d-a43997acfefb.png)

2021-12-17 15:35 UTC, wdawson commented on packages/insomnia-app/app/ui/components/workspace-card.tsx
> +  if (version.length > 0 && !version.startsWith('v')) {
As per the approach in the ticket, we don't want to do that for now. Without additional context for what the string is, we want to keep some indication that it's a version. Perhaps we can add a space or something to make it clearer and look less like a mistake. 

We'll still have issues, per the current implementation, if the string starts with a `v` though.

2021-12-17 15:42 UTC, wdawson commented on packages/insomnia-app/app/ui/components/workspace-card.tsx
> +  if (version.length > 0 && !version.startsWith('v')) {
I may be the only one concerned about the lack of context, however. In which case, we could drop the `v` entirely.

2021-12-21 21:54 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/workspace-card.tsx
> +  if (version.length > 0 && !version.startsWith('v')) {
<discussed in standup that since we all agree that what's in this PR is at least _better_ than what we have right now, we're going to merge as is and keep an eye open for the future on making this even better>

2021-12-21 21:54 UTC, dimitropoulos approved these changes

2021-12-21 21:58 UTC, wdawson commented
@filfreire , seems like the team is aligned that this is better than what we have and we will follow up later with additional improvements. Does that sound good to you?

2021-12-22 16:26 UTC, dimitropoulos commented
<discussed and the team agreed in standup that since we all agree that what's in this PR is at least better than what we have right now, we're going to merge as is and keep an eye open for the future on making this even better>

2021-12-22 18:25 UTC, wdawson commented
Thanks for the tests @dimitropoulos !

2021-12-22 18:28 UTC, merged