Fix/CVE-2021-3777
getinsomnia/insomnia pull request #4335
Opened 2022-01-03 19:45 UTC by iPedreroIBM

Scanned using WhiteSource.:

nodejs-tmpl is vulnerable to Inefficient Regular Expression Complexity

Updated from 1.0.4 to 1.0.5.

URL: https://vuln.whitesourcesoftware.com/vulnerability/CVE-2021-3777

(Also removed local GitHub action that automatically updates the fork and whitesource config)

2022-01-04 12:52 UTC, gatzjames approved these changes

2022-01-14 18:09 UTC, dimitropoulos approved these changes

2022-01-14 18:28 UTC, dimitropoulos requested changes
I'd love to get this merged soon, but I've just noticed there's a problem: the integrity fields were not updated.  That means that if we ran `npm install` after this PR that it will simply bump it right back to `1.0.4`.

I don't actually know what the right way is to do this, but here's an example of dependabot doing it: https://github.com/Kong/insomnia/pull/4359/files#diff-d75077b306a489aef01200210f58d2b45ea25bb4f106ec120db4446fa7125dc1L25020-R26095

2022-04-20 19:03 UTC, johnwchadwick commented
Closing in favor of #4716 which has the integrity fields updated properly.

2022-04-20 19:03 UTC, closed without merging