zero state replacement for body editor
getinsomnia/insomnia pull request #4342
Opened 2022-01-05 21:27 UTC by dimitropoulos

This PR implements the new behavior for the request pane help text.

non gRPC requests:
| BEFORE | AFTER |
| - | - |
| ![Screenshot_20220105_162556](https://user-images.githubusercontent.com/15232461/148291706-69e9d72f-2362-4386-9be2-707d8b28c7ed.png) | ![Screenshot_20220105_162304](https://user-images.githubusercontent.com/15232461/148291428-9aa6a3e0-5b54-49af-81c1-1db72b0acf2a.png) |

gRPC requests:
| BEFORE | AFTER |
| - | - |
| ![Screenshot_20220105_162543](https://user-images.githubusercontent.com/15232461/148291680-2556e97c-b439-4003-b80f-1bbf70389835.png) | ![Screenshot_20220105_162258](https://user-images.githubusercontent.com/15232461/148291414-7d8f2233-0944-49c3-8c6b-3832b5ab2012.png) |

2022-01-06 14:16 UTC, gatzjames requested changes
Nice one! Left some comments for naming and I believe the styles could stay on the component file!

2022-01-06 14:16 UTC, gatzjames commented on packages/insomnia-app/app/ui/components/panes/zero-state-pane.tsx
> +          {map(({ title, url }) => (
Could we replace this with the native array.map? Seems like we don't need the extra abstraction cost.

2022-01-06 14:16 UTC, gatzjames commented on packages/insomnia-app/app/ui/css/css-in-js.ts
> +export const faint = {
Since these styles are only used by the empty state pane they could live in that file.
I'd also try to improve the names to be a bit more intuitive 😅

2022-01-06 14:16 UTC, gatzjames commented on packages/insomnia-app/app/ui/components/panes/zero-state-pane.tsx
> +export const ZeroStatePane: FC<{
Not sure what zero state means? Could we rename this to EmptyStatePane instead? Afaik it's widely used naming for when there's nothing to display on the screen.

2022-01-06 14:55 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/css/css-in-js.ts
> +export const faint = {
sorry, for the lack of context.  they are direct copies of the utility files we use throughout the project https://github.com/Kong/insomnia/blob/develop/packages/insomnia-app/app/ui/css/layout/base.less#L356

That's also why I put them here.  We've done a bit of copying this stuff around in the past (or, just not using the utilities) and at this point I think I want to stop copying around as much.

This is absolutely _not_ "CSS-in-JS done right", in my opinion, but it's the least friction necessary to get us off of the .less stuff and keep things familiar until we have an actual theme system like a mature ui library might.

2022-01-06 14:56 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/css/css-in-js.ts
> +export const faint = {
Notice, too, that the prior implementation uses the `faint` class.  That's really where this ultimately comes from.

2022-01-06 14:58 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/panes/zero-state-pane.tsx
> +          {map(({ title, url }) => (
absolutely :)

apologies for my muscle memory -> a8f7ef591d7819f3fe02bf395d0de28f7127b37f

2022-01-06 14:58 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/panes/zero-state-pane.tsx
> +export const ZeroStatePane: FC<{
I originally called it that, but I changed it to ZeroState because that's the name of the feature and how we're referring to it.  let's chat about this.  I'm 100% cool with whatever.

2022-01-06 15:14 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/components/panes/zero-state-pane.tsx
> +export const ZeroStatePane: FC<{
upon chatting we agree that "empty state" is much more common for developers, so, even if product people / designers / whoever are using different terms, we don't really need to diverge from the most common terminology on the code.

15e528fa69dc854314f2a4b868606426ce10c0cf

2022-01-07 13:52 UTC, gatzjames commented on packages/insomnia-app/app/ui/components/panes/empty-state-pane.tsx
> +  ...superFaint,
I think we should in-line these since they aren't used anywhere else and the naming is not clear. Not sure what the benefit of a separate file is 🤔

2022-01-07 14:36 UTC, gatzjames commented on packages/insomnia-app/app/ui/components/panes/empty-state-pane.tsx
> +  ...superFaint,
This file is used in order to keep parity with the css classnames for now.
Something to look into when updating the styles/theming of the app since the current solution doesn't scale.

2022-01-07 14:37 UTC, gatzjames approved these changes

2022-01-07 14:37 UTC, merged