updates support.insomnia.rest to docs.insomnia.rest
getinsomnia/insomnia pull request #4351
Opened 2022-01-11 15:40 UTC by dimitropoulos

It appears that this URL was updated, so we can point all links in the app to the right thing by just changing the factory.

2022-01-13 05:27 UTC, develohpanda requested changes

2022-01-13 05:27 UTC, develohpanda commented on packages/insomnia-app/app/common/documentation.ts
>  export const docsGitSync = insomniaDocs('/article/193-git-sync');
We should also update the docs links to be correct. The redirects are defined [here](https://github.com/Kong/insomnia-docs/blob/main/docs/vercel.json). This line for example, would become

```suggestion
export const docsGitSync = insomniaDocs('/insomnia/git-sync');
```

2022-01-13 14:08 UTC, dimitropoulos commented on packages/insomnia-app/app/common/documentation.ts
>  export const docsGitSync = insomniaDocs('/article/193-git-sync');
good catch!  @falondarville could you go through them? if not lemme know

2022-01-13 19:49 UTC, falondarville commented on packages/insomnia-app/app/common/documentation.ts
>  export const docsGitSync = insomniaDocs('/article/193-git-sync');
Yep, I can pull this work and go through all of these!

2022-01-13 23:30 UTC, falondarville commented on packages/insomnia-app/app/common/documentation.ts
>  export const docsGitSync = insomniaDocs('/article/193-git-sync');
@dimitropoulos permission denied to push to your fork. Adding the fixes here til we can resolve permission issues:

```
export const docsBase = insomniaDocs('/');
export const docsGitSync = insomniaDocs('/insomnia/git-sync');
export const docsTemplateTags = insomniaDocs('/insomnia/template-tags');
export const docsVersionControl = insomniaDocs('/insomnia/version-control-sync');
export const docsPlugins = insomniaDocs('/insomnia/introduction-to-plugins');
export const docsImportExport = insomniaDocs('/insomnia/import-export-data');
export const docsKeyMaps = insomniaDocs('/insomnia/key-maps');
export const docsIntroductionInsomnia = insomniaDocs('/insomnia/get-started');
export const docsWorkingWithDesignDocs = insomniaDocs('/insomnia/design-documents');
```

2022-01-14 00:09 UTC, falondarville approved these changes
LGTM!

2022-01-14 00:09 UTC, dimitropoulos commented on packages/insomnia-app/app/common/documentation.ts
>  export const docsGitSync = insomniaDocs('/article/193-git-sync');
(update: got it sorted out)

2022-01-14 00:14 UTC, develohpanda approved these changes
Woohoo TY!

2022-01-14 00:29 UTC, merged