Empty State for Test Tab
getinsomnia/insomnia pull request #4362
Opened 2022-01-13 15:24 UTC by dimitropoulos

This PR adds an Empty State for the Test Tab:

| BEFORE | AFTER |
| - | - |
| ![Screenshot_20220113_102252](https://user-images.githubusercontent.com/15232461/149358099-0ec7113b-e203-4042-a371-75b1b772826a.png) | ![Screenshot_20220113_102148](https://user-images.githubusercontent.com/15232461/149357929-17007c47-9281-48a3-87b5-1f6f6d315005.png) |

And also creates an example test suite upon first launch.  Note that you can easily test this by using the new stats.launches helper added in https://github.com/Kong/insomnia/pull/4350

2022-01-17 04:07 UTC, develohpanda requested changes
This PR seems incomplete according to what I read in the title and description. If there's no test suite, there's no empty state. Ie. this PR only adds an empty state for when a suite is selected and has no tests.

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/4312346/149705908-781dc3a7-7747-4807-b22b-15a0b703cc30.png">

Are there future tasks to add/update the empty states for where there is no request selected, or no unit test suite?

### QA

<details>
<summary>🟢 Creates expected data on initial launch</summary>

https://www.loom.com/share/929c5e4a7ba7434bafa6fbf1d9205236

</details>

<details>
<summary>🔴 Base state for a new document looks different to what I saw during onboarding</summary>

https://www.loom.com/share/05d09ecb2ef94141b9934beea4fdd7b6

</details>

<details>
<summary>🔴 Overflow issue in test tab centre pane</summary>

https://www.loom.com/share/05b49ff937b34b629e8fdd3b7c155df3

</details>

2022-01-17 04:07 UTC, develohpanda commented on packages/insomnia-app/app/common/documentation.ts
> +    url: docsUnitTesting,
Having the `docsUnitTesting` variable seems a bit verbose, why not just `url: insomniaDocs('/inso-cli/introduction')`? 😅

2022-01-17 04:07 UTC, develohpanda commented on packages/insomnia-app/app/ui/redux/modules/global.tsx
>    });
There's a lot of stuff we expect to happen during first launch as defined in `initFirstLaunch`. It would be nice to add a unit test specifically for this action creator, to make sure the expected data is being created and code path reached. Any changes here that are not caught by a test and reliant on manual testing would have a detrimental effect on the onboarding UX.

2022-01-18 14:04 UTC, dimitropoulos commented on packages/insomnia-app/app/common/documentation.ts
> +    url: docsUnitTesting,
to stay consistent with all other links, which all have their own URLs.  also, to avoid potential duplication in the future if someone is looking for that link and doesn't see it in our existing list.

2022-01-18 18:02 UTC, dimitropoulos commented
@develohpanda 313ad0c2e73a292098d0fb02efa6e2a4c14f02f7 fixes the overflow issue.  it's been tricky to do without diverging too far from the other Pane usages, but thankfully this solution seems to work in all the situations:

![Screenshot_20220118_125438](https://user-images.githubusercontent.com/15232461/149993114-43e0ada8-7046-4033-83fd-9a7bece30fa8.png)
![Screenshot_20220118_125459](https://user-images.githubusercontent.com/15232461/149993117-0eba85b3-d6d0-4587-a151-190e9bc4c216.png)
![Screenshot_20220118_125534](https://user-images.githubusercontent.com/15232461/149993119-3eea38cc-e7dc-40a2-ac0b-ee821afdc207.png)

2022-01-18 21:30 UTC, develohpanda approved these changes
Looks like overflow is fixed up now, thank you!

2022-01-18 22:00 UTC, dimitropoulos commented
Although this PR didn't do 90% of `initFirstLaunch`, I agree that it's time to have tests for it, and I'd like me/us to be accountable to that.  So, I created INS-1368, which will be a follow-up to all this.

2022-01-18 22:09 UTC, dimitropoulos commented on packages/insomnia-app/app/ui/redux/modules/global.tsx
>    });
totally agree: https://github.com/Kong/insomnia/pull/4362#issuecomment-1015873136

2022-01-18 22:21 UTC, merged