improve smoke test docs
getinsomnia/insomnia pull request #4421
Opened 2022-01-28 15:12 UTC by jackkav

Trying to make it easier to follow the smoke test docs

2022-02-01 17:41 UTC, dimitropoulos commented on packages/insomnia-smoke-test/README.md
> +PWDEBUG=1 npm run test:smoke:dev
the way these are presented, it's always confusing at first when I look at them because it's like it's suggesting to me to run them all at once.  if they were split into separate codeblocks it might read easier and would allow you to comment outside of the script

2022-02-01 17:43 UTC, dimitropoulos commented on packages/insomnia-smoke-test/README.md
> +PWDEBUG=1 npm run test:smoke:dev
Run tests

```shell
npm run test:smoke:dev
```

Debug tests with verbose output

```shell
DEBUG=pw:browser,pw:api npm run test:smoke:dev
```

Step through tests with playwright inspector

```shell
PWDEBUG=1 npm run test:smoke:dev
```

2022-02-02 08:19 UTC, jackkav commented on packages/insomnia-smoke-test/README.md
> +PWDEBUG=1 npm run test:smoke:dev
I started with that but saw inconsistencies elsewhere but I don't mind changing it back

2022-02-03 16:59 UTC, dimitropoulos commented on packages/insomnia-smoke-test/README.md
> +PWDEBUG=1 npm run test:smoke:dev
whatever you want to do is cool with me.

2022-02-03 17:04 UTC, filfreire requested changes
@jackkav added some minor code suggestions.

2022-02-03 17:04 UTC, filfreire commented on packages/insomnia-smoke-test/README.md
> +npm run app-start-playwright    # Run watcher
Watcher would no longer be `app-start-playwright` after this PR, but `watch:app`
```suggestion
npm run watch:app   # Run watcher
```

2022-02-03 17:04 UTC, filfreire commented on packages/insomnia-smoke-test/README.md
> +Package = executable binary `.dmg` or `.exe`
```suggestion
It's possible to run the smoke tests for:
- A `build`, the JS bundle that is loaded into an electron client;
- A `package`, the executable binary (e.g. `.dmg` or `.exe`);
```

2022-02-03 17:04 UTC, filfreire commented on packages/insomnia-smoke-test/README.md
> +
```suggestion
For `build`:
```

2022-02-03 17:04 UTC, filfreire commented on packages/insomnia-smoke-test/README.md
> +npm run test:smoke:package          # Run tests
There's a typo here, you probably mean `build` instead of `package`:
```suggestion
npm run test:smoke:build          # Run tests
```

2022-02-03 17:04 UTC, filfreire commented on packages/insomnia-smoke-test/README.md
>  ```shell
```suggestion
For `package`:
```shell
```

2022-02-03 17:05 UTC, dimitropoulos approved these changes

2022-02-04 12:05 UTC, filfreire commented on packages/insomnia-smoke-test/README.md
>  ```shell
@jackkav  this should fix the lint errors:
```suggestion
It's possible to run the smoke tests for:

- A `build`, the JS bundle that is loaded into an electron client;
- A `package`, the executable binary (e.g. `.dmg` or `.exe`);

For `build`:

```shell
npm run app-build:smoke         # Transpile js bundle
npm run test:smoke:build          # Run tests
```

For `package`:

```shell
```

2022-02-04 12:07 UTC, filfreire approved these changes
@jackkav these should fix the Github actions `lint` errors.

2022-02-04 12:07 UTC, filfreire commented on packages/insomnia-smoke-test/README.md
> +- A `build`, the JS bundle that is loaded into an electron client;
```suggestion

- A `build`, the JS bundle that is loaded into an electron client;
```

2022-02-04 12:07 UTC, filfreire commented on packages/insomnia-smoke-test/README.md
> +For `build`:
```suggestion

For `build`:

```

2022-02-04 12:07 UTC, filfreire commented on packages/insomnia-smoke-test/README.md
> +For `package`:
```suggestion
For `package`:

```

2022-02-18 12:47 UTC, merged