Implement Hawk Authentication
getinsomnia/insomnia pull request #446
Opened 2017-08-17 20:41 UTC by jgiovaresco

Closes #437 

This implementation is enough for my needs. I've not read the entire spec to handle all specific cases.

What do you think about this ?

2017-08-18 00:35 UTC, gschier commented
I took a look at the [HAWK authentication library](https://github.com/hueniverse/hawk) and it looks like you implemented everything needed for the most common use case. The only thing I might add is the ability to specify the algorithm (`sha256` or `sha1`). 

There is also a `bewit` authentication type but it doesn't seem like that would be a very popular use case, and I don't think it's necessary to implement response validation.

I will give an official code review tomorrow with some comments around naming and style, but I think it looks good overall. Nice work!

2017-08-18 04:03 UTC, gschier requested changes
A couple comments @jgiovaresco. All minor things. It's looking great!

Also, can you post a screenshot of the auth UI?

2017-08-18 04:03 UTC, gschier commented on app/common/constants.js
> +  [AUTH_HAWK]: ['Hawk', 'Hawk Authentication'],
The word "Authentication" is pretty redundant here. Could probably just be `['Hawk', 'Hawk']`.

2017-08-18 04:03 UTC, gschier commented on app/common/har.js
> +      renderedRequest.url,
The URL here should actually be the value of what is on line 48. Should pull that into a variable and use it in both places.

2017-08-18 04:03 UTC, gschier commented on app/network/authentication.js
> +export async function getAuthHeader (requestId, requestUrl, requestMethod, authentication) {
These params can just be called `url` and `method`.

2017-08-18 04:03 UTC, gschier commented on app/network/network.js
> +            renderedRequest.url,
This should actually be using `finalUrl` instead of `renderedRequest.url`.

2017-08-18 04:03 UTC, gschier commented on app/ui/components/dropdowns/auth-dropdown.js
> +        {this.renderAuthType(AUTH_HAWK)}
Also need to add a default object to `models/request.js` `newAuth()` function.

2017-08-18 04:03 UTC, gschier commented on app/network/authentication.js
> +    const {hawkAuthId, hawkAuthKey, algorithm} = authentication;
Can you rename these to `id`, `key`, `algorithm` to match the Hawk names? Since the authentication type is Hawk, there is no need to prefix the keys.

2017-08-18 07:28 UTC, jgiovaresco commented
@gschier I let you take a look at the 2 new commits. All changes should be done.

2017-08-21 17:43 UTC, gschier approved these changes
Might make a few minor tweaks after merging, but looks good! Thanks for the PR 😄

2017-08-21 17:43 UTC, merged