[Draft] rename insomnia-app/app to insomnia-app/src like all other packages
getinsomnia/insomnia pull request #4491
Opened 2022-02-14 16:49 UTC by dimitropoulos

As the title states, this PR has a very very tiny scope (despite the number of lines touched).  The first commit renames the directory and absolutely literally nothing else.

The second commit just handles all the places where the location was hardcoded.

The motivation for this PR is to bring some long-overdue consistency to simplify the building of this one package in relation to all other packages.  We have a quite consistent build process (with respect to project structure) _EXCEPT_ for this.

And, if you're wondering:
> why was it /app and not /src in the first place?

The answer is simple: because this convention predates the monorepo.  We changed all other packages during the TypeScript conversion but fell short of renaming them all to defer this particular PR's scope.

2022-03-23 12:46 UTC, DMarby commented on packages/insomnia-smoke-test/playwright/paths.ts
> +// NOTE: main.min.js is built by app-build:smoke in insomnia-app/build and also by the watcher in insomnia-app/app
```suggestion
// NOTE: main.min.js is built by app-build:smoke in insomnia-app/build and also by the watcher in insomnia-app/src
```

2022-04-20 15:58 UTC, filfreire approved these changes

2022-04-20 16:49 UTC, marckong approved these changes
I ran some smoke tests on this branch, and build. I could run successfully the following scripts:
- app-run
- app-package
- app-build
- type-check

I wonder how this would impact [this effort](https://github.com/Kong/insomnia/pull/4713), so do you think we may wait until that PR gets merged?

2022-04-20 17:00 UTC, DMarby requested changes

2022-04-20 17:00 UTC, DMarby commented on lerna.json
> +    "packages/insomnia/build"
This no longer exists since we merged the packedDependencies removal PR
```suggestion
```

2022-04-20 17:00 UTC, DMarby commented on packages/insomnia-inso/src/jest/setup.ts
> +process.env.DEFAULT_APP_NAME = process.env.DEFAULT_APP_NAME || 'insomnia';
This should not be changed, it refers to the user data directory on disk, not the package name.

```suggestion
process.env.DEFAULT_APP_NAME = process.env.DEFAULT_APP_NAME || 'insomnia-app';
```

2022-04-20 17:00 UTC, DMarby commented on packages/insomnia-inso/webpack/webpack.config.development.js
> +      'process.env.DEFAULT_APP_NAME': JSON.stringify('insomnia'),
This should not be changed, it refers to the user data directory on disk, not the package name.
```suggestion
      'process.env.DEFAULT_APP_NAME': JSON.stringify('insomnia-app'),
```

2022-04-20 17:06 UTC, DMarby commented on packages/insomnia/src/main.development.ts
> +  const newPath = path.join(defaultPath, '../', isDevelopment() ? 'insomnia' : appConfig.userDataFolder);
```suggestion
  const newPath = path.join(defaultPath, '../', isDevelopment() ? 'insomnia-app' : appConfig.userDataFolder);
```

2022-04-20 17:22 UTC, dimitropoulos commented on lerna.json
> +    "packages/insomnia/build"
ahhhhhhh I thought it was the other way around.  good catch: e0d1ebd665e6cadc940ef5f0e406f1414907dcfd

2022-04-20 17:22 UTC, dimitropoulos commented on packages/insomnia-inso/src/jest/setup.ts
> +process.env.DEFAULT_APP_NAME = process.env.DEFAULT_APP_NAME || 'insomnia';
!!!!!!!!!!!!!! HOLY CRAP GOOD FIND 3eead72366259b84a03082623378d956db6a1560

2022-04-20 17:22 UTC, dimitropoulos commented on packages/insomnia/src/main.development.ts
> +  const newPath = path.join(defaultPath, '../', isDevelopment() ? 'insomnia' : appConfig.userDataFolder);
3eead72366259b84a03082623378d956db6a1560

2022-04-20 17:22 UTC, dimitropoulos commented on packages/insomnia-inso/webpack/webpack.config.development.js
> +      'process.env.DEFAULT_APP_NAME': JSON.stringify('insomnia'),
3eead72366259b84a03082623378d956db6a1560

2022-04-20 17:28 UTC, DMarby approved these changes

2022-04-20 17:42 UTC, merged