Allow use of ctrl+p/ctrl+n to navigate request switcher
getinsomnia/insomnia pull request #4520
Opened 2022-02-24 15:59 UTC by akivajgordon

On macOS, native lists or multi-line text fields, as well as the command line allow for using <kbd>ctrl</kbd>+<kbd>p</kbd> or <kbd>ctrl</kbd>+<kbd>n</kbd> to navigate up and down respectively.

This is a learned habit from the equivalent emacs keys, and for people that know about it and use it, it's the preferred way of navigating lists so that we don't have to move our hands from the main keyboard area.

This change allows for this functionality.

**Note**: I have tested this only on macOS and I am aware that Windows/Linux have different semantics such that this might not fit. Perhaps this key combination needs to be specifically limited to macOS, which I haven't researched what the appropriate way to do that for this project would be. If there is already semantics for that, feel free to point me in that direction and I can give that a shot.

I'm not familiar with other areas of the app to know if there are other lists in which this kind of functionality would be usable, but that would be ideal if it was more globally accessible that way.

2022-03-01 21:00 UTC, dimitropoulos approved these changes

2022-05-03 16:05 UTC, dimitropoulos requested changes
on second thought, maybe it'd be best to find some other package that does this job (validation) so we don't maintain it at all, rather than furthering our own abstraction for something that already exists (KeyboardEvent.code).

2022-05-05 14:28 UTC, dimitropoulos approved these changes

2022-05-05 14:29 UTC, dimitropoulos approved these changes
ok, after looking at it again I found a simpler way (that didn't involve hardcoded duplication of the keys or using `any`) to solve the same problem.  let's wait for @jackkav @gatzjames or @marckong to take a look before merging.

2022-05-10 13:12 UTC, filfreire approved these changes
Tested it locally, seems to be working ok 👍

2022-05-10 13:23 UTC, marckong approved these changes

2022-05-10 13:59 UTC, merged