add gitlab oauth provider and ui
getinsomnia/insomnia pull request #4727
Opened 2022-04-26 08:02 UTC by gatzjames

TODO
- [ ] Add client secret once we create the GitLab app
- [ ] e2e tests
- [ ] Decide on client_id handling (e.g. keep it in the app vs load it from an api)
- [ ] Security Audit

2022-04-26 08:30 UTC, jackkav commented on packages/insomnia/src/ui/components/modals/git-repository-settings-modal/gitlab-repository-settings-form-group.tsx
> +                command(dispatch);
would be great to avoid this indirection in git sync flows, curious what it would take to achieve?

2022-04-26 08:30 UTC, jackkav commented on packages/insomnia/src/sync/git/gitlab-oauth-provider.ts
> +import { createHash, randomBytes } from 'crypto';
It is worth considering running this in main context so as to ensure it is helping work toward disabling nodeIntegration, then perhaps it could use the confusingly named LocalStorage overload to write the token to disk.
Alternatively this method could use `crypto-browserify` and call axios over ipc.

2022-04-28 09:02 UTC, gatzjames commented on packages/insomnia/src/sync/git/gitlab-oauth-provider.ts
> +import { createHash, randomBytes } from 'crypto';
I'd say both gitlab and GitHub providers can be moved to main and exposed as apis through preload! Feel free to give it a shot! 🙏

2022-04-28 09:08 UTC, gatzjames commented on packages/insomnia/src/ui/components/modals/git-repository-settings-modal/gitlab-repository-settings-form-group.tsx
> +                command(dispatch);
This one is a big thread of state management! Since we use redux to capture the events it's a bit more complicated to move this out of the renderer. Also localStorage is not a requirement and since we upgraded to latest electron we could spike safeStorage instead!
One thing to look out for safeStorage is that it might not be available in all OSes so we need to make sure we have a fallback mechanism for storing tokens (e.g. localStorage 🥲)
Not sure if we should do it in this PR though.

2022-05-04 18:04 UTC, DMarby commented on packages/insomnia/src/sync/git/gitlab-oauth-provider.ts
> +  const scopes = ['api', 'read_user', 'write_repository', 'email'];
Just adding this to remind myself that we should go over these scopes to make sure if we need all of `api` or if we can get away with `read_api` or similar.

2022-05-06 17:59 UTC, marckong commented on packages/insomnia/src/sync/git/gitlab-oauth-provider.ts
> +  const scopes = ['api', 'read_user', 'write_repository', 'email'];
i can experiment this and get back to you

2022-05-12 19:05 UTC, marckong commented on packages/insomnia/src/sync/git/gitlab-oauth-provider.ts
> +  const scopes = ['api', 'read_user', 'write_repository', 'email'];
experiments;
- ['read_api'] throws 403 when you push
- ['api'] works fine, but it seems obvious this gives too much power
- ['read_repository', 'write_repository', 'profile'] works just fine in pulling, pushing.

2022-05-13 10:42 UTC, jackkav commented on packages/insomnia-smoke-test/server/gitlab-api/gitlab-api.mock.ts
> +export const gitrepo = {
how could this better communicate intent? perhaps link to where it came from?

2022-05-18 16:46 UTC, DMarby requested changes

2022-05-18 16:46 UTC, DMarby commented on packages/insomnia/config/config.json
> +      "redirectUri": "https://insomnia.rest/oauth/gitlab/callback"
This is the wrong URL
```suggestion
      "redirectUri": "https://app.insomnia.rest/oauth/gitlab/callback"
```

2022-05-18 16:46 UTC, DMarby commented on packages/insomnia/src/common/constants.ts
> +export const isStaging = () => getAppEnvironment() === 'staging';
This is a pretty risky change that I don't think is desirable (at least not in this PR) for two reasons:
- A lot of the app uses the logic of `!isDevelopment()` to gate things for production. This means that *any* other value of `INSOMNIA_ENV` then `development` is considered `production`, changing this to have strict value matching could have unintended consequences, so it should probably not be done in a feature PR.

- The app environment does not and should not match service/api environments, as it's completely valid use-case to eg run a development build of the app against the production services, or test the production app against staging/development to reproduce fixes of issues. This is why eg `INSOMNIA_API_URL` is completely separate from `INSOMNIA_ENV`.
If we want to have a shorthand environment toggle for gitlab rather then individual environment variables as with github/the api, this should probably be a separate variable instead (eg INSOMNIA_GITLAB_ENV), but I would personally prefer to just have the default be production and have the individually overridable environment variables as you do below already.

2022-05-18 16:46 UTC, DMarby commented on packages/insomnia/config/config.json
> +      "redirectUri": "https://insomnia.moe/oauth/gitlab/callback"
Incorrect URL here as well
```suggestion
      "redirectUri": "https://app.insomnia.moe/oauth/gitlab/callback"
```

2022-05-18 16:46 UTC, DMarby commented on packages/insomnia/src/sync/git/gitlab-oauth-provider.ts
> +  const scopes = ['api', 'read_user', 'write_repository', 'email'];
@marckong @gatzjames Just following up here, so did we conclude that this could be changed to `read_user`, `read_repository`, `write_repository`, `email`, `profile` or something else here then? 

Let me know and I can make the changes needed on the Gitlab end, but would really like to see this be less broad before we merge this if possible.

2022-05-18 16:46 UTC, DMarby commented on packages/insomnia/src/ui/components/modals/git-repository-settings-modal/gitlab-repository-settings-form-group.tsx
> +        .then(({ data, errors }) => {
Do we need to handle expiry/refreshing of the token here as well @gatzjames?

2022-05-18 16:46 UTC, DMarby commented on packages/insomnia/src/sync/git/gitlab-oauth-provider.ts
> +const verifier = base64URLEncode(randomBytes(32));
This needs to be rotated on every token request cycle

2022-05-18 16:49 UTC, marckong commented on packages/insomnia/src/sync/git/gitlab-oauth-provider.ts
> +  const scopes = ['api', 'read_user', 'write_repository', 'email'];
@gatzjames would 'read_repository', 'write_repository', 'profile' be sufficient?

2022-05-18 20:53 UTC, jackkav commented on packages/insomnia/src/ui/components/modals/git-repository-settings-modal/gitlab-repository-settings-form-group.tsx
> +                command(dispatch);
There's another ticket to address the particulars of git sync architecture, cool to scope it out.

2022-05-24 11:59 UTC, gatzjames commented on packages/insomnia/src/sync/git/gitlab-oauth-provider.ts
> +  const scopes = ['api', 'read_user', 'write_repository', 'email'];
By using the /user REST api of GitLab we only need 'write_repository' and 'read_user'

2022-05-24 12:01 UTC, gatzjames commented on packages/insomnia/src/common/constants.ts
> +export const isStaging = () => getAppEnvironment() === 'staging';
Great catch. We need to improve the api of our environment variables (e.g. dev is used to decide many more things than what it's main purpose imo).
Resolving since we use the config api.

2022-05-24 12:02 UTC, gatzjames commented on packages/insomnia/src/ui/components/modals/git-repository-settings-modal/gitlab-repository-settings-form-group.tsx
> +        .then(({ data, errors }) => {
Indeed. Great catch!

2022-05-24 12:03 UTC, gatzjames commented on packages/insomnia/src/sync/git/gitlab-oauth-provider.ts
> +const verifier = base64URLEncode(randomBytes(32));
👏🙏 Fixed. We now use a new verifier associated with the state of that session.

2022-05-24 12:05 UTC, gatzjames commented on packages/insomnia/src/sync/git/gitlab-oauth-provider.ts
> +import { createHash, randomBytes } from 'crypto';
After spiking this resolving this as out of scope for now

2022-05-24 12:06 UTC, gatzjames commented on packages/insomnia/config/config.json
> +      "redirectUri": "https://insomnia.rest/oauth/gitlab/callback"
Resolving as it's replaced by the config api

2022-05-24 12:07 UTC, gatzjames commented on packages/insomnia/config/config.json
> +      "redirectUri": "https://insomnia.moe/oauth/gitlab/callback"
Resolving as it's replaced by the config api

2022-05-24 16:56 UTC, filfreire approved these changes

2022-05-25 11:55 UTC, jackkav approved these changes
Tested with slow internet and unaccepted gitlab T&Cs. Not tested without internet.

2022-05-25 12:05 UTC, DMarby commented on packages/insomnia/src/sync/git/gitlab-oauth-provider.ts
> +export const getGitLabRedirectURI = async () =>
Since `getGitLabConfig` already returns `INSOMNIA_GITLAB_REDIRECT_URI`/`INSOMNIA_GITLAB_CLIENT_ID` from env if set, let's just use `getGitLabConfig` directly below instead of having these utility methods, to avoid multiple API calls every time we do the oauth flow?

2022-05-25 16:46 UTC, gatzjames commented on packages/insomnia/src/sync/git/gitlab-oauth-provider.ts
> +export const getGitLabRedirectURI = async () =>
Good one! Also no need to export it since no other module needs these values anymore

2022-05-26 13:25 UTC, filfreire approved these changes

2022-05-31 17:38 UTC, DMarby approved these changes

2022-05-31 18:10 UTC, marckong commented on packages/insomnia/src/ui/components/modals/git-repository-settings-modal/gitlab-repository-settings-form-group.tsx
> +    img.src = src;
I wonder if src should be added in the deps array of the useEffect.

2022-05-31 18:12 UTC, marckong commented on packages/insomnia/src/ui/components/modals/git-repository-settings-modal/gitlab-repository-settings-form-group.tsx
> +          onClick={e => {
nit pick: I wonder if we can move this into its own handler method instead of inline code block

2022-05-31 18:13 UTC, marckong approved these changes
LGTM. I left very few minor comments but they are not blockers.

2022-06-01 08:19 UTC, gatzjames commented on packages/insomnia/src/ui/components/modals/git-repository-settings-modal/gitlab-repository-settings-form-group.tsx
> +          onClick={e => {
Not sure 🤔.  I'd leave it as is unless there is a perf issue. Resolving this to merge but we can add useCallbacks later if we decide to.

2022-06-01 08:39 UTC, merged