remove unused deps
getinsomnia/insomnia pull request #4730
Opened 2022-04-26 17:56 UTC by jackkav

- ran npx depcheck in root

2022-04-27 14:48 UTC, dimitropoulos commented on package.json
> -    "immer": "^9.0.6"
please see the git blame on why this is necessary

2022-04-27 14:50 UTC, DMarby requested changes
This seems to have a lot of work left before it can be reviewed/merged, amongst other things it's removing dependencies used by scripts in package.json (eg `concurrently`).

Please revisit all these changes before requesting further review.

2022-04-27 14:50 UTC, DMarby commented on package.json
> -    "svg-text-to-path": "^1.1.2",
This is used by the changelog image generator

2022-04-27 14:50 UTC, DMarby commented on packages/insomnia/package.json
> -    "electron-builder-squirrel-windows": "23.0.3",
This is used implicitly by electron-builder

2022-04-27 14:50 UTC, DMarby commented on package.json
> -    "immer": "^9.0.6"
This is used to explicitly specify a version of immer to fix a security vulnerability, which is used by Spectral

2022-04-27 17:29 UTC, jackkav commented on package.json
> -    "immer": "^9.0.6"
seems like a can of worms better left unopened, thanks

2022-04-27 17:38 UTC, jackkav commented on packages/insomnia/package.json
> -    "electron-builder-squirrel-windows": "23.0.3",
thanks for the catch, i was kinda hoping the windows package step would fail :shrug:

2022-04-27 17:39 UTC, jackkav commented on package.json
> -    "svg-text-to-path": "^1.1.2",
thanks, must have missed that one when I was searching

2022-04-28 10:05 UTC, DMarby approved these changes

2022-04-28 12:36 UTC, merged