reduce npm script indirection and surface area
getinsomnia/insomnia pull request #4731
Opened 2022-04-26 19:58 UTC by jackkav

a somewhat aggressive approach to shaving off some of the indirection and complexity of working with packages in the monorepo.

goals
- eliminate anything that isn't documented, meta flows can be documented seperately if they are generally useful.
-

2022-04-27 08:27 UTC, filfreire reviewed
https://www.youtube.com/watch?v=T-v20t_puwE

2022-04-27 14:56 UTC, dimitropoulos commented on packages/insomnia-inso/webpack/webpack.config.development.js
> +      'process.env.DEFAULT_APP_NAME': JSON.stringify('insomnia'),
this will break inso

2022-04-27 14:56 UTC, dimitropoulos commented on packages/insomnia-inso/src/jest/setup.ts
> +process.env.DEFAULT_APP_NAME = process.env.DEFAULT_APP_NAME || 'insomnia';
this seems unintentional

2022-04-27 15:01 UTC, jackkav commented on packages/insomnia-inso/webpack/webpack.config.development.js
> +      'process.env.DEFAULT_APP_NAME': JSON.stringify('insomnia'),
thanks

2022-04-27 18:00 UTC, DMarby requested changes
I think there's a bigger team discussion to be had here around what we want out of our `package.json` scripts, as well as duplication of commands in eg CI files, before making any changes like these.

There are also some fairly bad practices being introduced here, eg relying on `ts-node` being installed globally, and directly referencing `node_modules/.bin` instead of using `npx`.

The NPM hook removal (pre/post scripts) also likely need further work, as a lot of the packaging relies on it when publishing to NPM, which would need to be handled in the publish flow instead if removed or by using more specific hooks like `prepublishOnly`.

2022-04-27 21:40 UTC, jackkav commented
> I think there's a bigger team discussion to be had here around what we want out of our `package.json` scripts, as well as duplication of commands in eg CI files, before making any changes like these.

Agreed :handshake: 

> There are also some fairly bad practices being introduced here, eg relying on ts-node being installed globally, and directly referencing node_modules/.bin instead of using npx.

I'd considered using npx rather than node_modules/.bin thanks for the encouragement!
I'd argue relying on a top-level package like ts-node is a good workspace practice that allows us to avoid needing a duplicated devDep.
Unfortunately we have some big boulders to move to get full workspaces going with plugins, packages and the inso abstraction. Although a gradual migration to workspaces seems possible from a recent spike.

> The NPM hook removal (pre/post scripts) also likely need further work, as a lot of the packaging relies on it when publishing to NPM, which would need to be handled in the publish flow instead if removed or by using more specific hooks like prepublishOnly.

You're spot on with your concerns here lets to discuss further synchronously.

2022-04-29 11:38 UTC, filfreire commented on packages/insomnia/package.json
> +    "build:sr": "esr esbuild.sr.ts",
These are still a bit "cryptic" and I think we should take one more step and rename them to something that better explains the command.

It's also a bit confusing that we have elsewhere `build:production` and here `build:prod`.

If what they do is "build and bundle / transpile stuff" I think we should name them `bundle:<something>` instead of `build:<something>`.

2022-04-29 11:38 UTC, filfreire commented on packages/insomnia-inso/package.json
>      "prepackage": "npm run build:production",
@DMarby I wonder if in here we could completely scrap the `build:production` entry above and call the webpack command in this line?

2022-04-29 11:38 UTC, filfreire commented on package.json
> +    "bootstrap": "npm install && lerna bootstrap && lerna run bootstrap --stream",
I wonder if we should go the extra mile - and rename `bootstrap` to `build`... thoughts?

2022-04-29 11:38 UTC, filfreire commented on packages/insomnia-smoke-test/README.md
> +npm run test:dev --prefix packages/insomnia-smoke-test
I'm split on this one and the "bake -> smoke test" flow.

We don't have playwright anywhere else so I think we could (and should) simplify this a bit further and remove surprises, making the developer experience more accessible.

Running smoke tests locally could be simpler:
```shell
# we check for the user which is latest - dev, build or package.
npm run test:smoke

# or folks can force the target (-t / --target)
npm run test:smoke -t build
npm run test:smoke -t bundle
npm run test:smoke -t package
```

and everything else we would figure out for the developer.


The commands needed like `build:main`, `start:dev-server` or `build:prod` - they could also be simpler.

We could shoot for a logic like:
If you run: 
```
npm run build    # Our old bootstrap
npm run bundle   # transpile JS bundles
npm run package    # artifacts/binaries
```

You know you can just run:
```
npm run test:smoke -t build
npm run test:smoke -t bundle
npm run test:smoke -t package
```

2022-05-01 22:19 UTC, jackkav commented
after discussion with @DMarby and @filfreire we are going to split this PR into a few passes
1. bootstrap -> build
1. make clean+build consistent between packages, eliminate npm hooks in packages
1. prefix build only scripts with CI when context is needed (ts-node ./something.js) otherwise use --prefix to set context
1. playwright test naming and dx need work
1. only one cli test needs the express server, elimate the with-mock and concurrently

2022-05-11 15:45 UTC, jackkav commented
Closing spike, Thanks @DMarby and @filfreire for your thoughts.

2022-05-11 15:45 UTC, closed without merging