remove bootstrap duplicated chain
getinsomnia/insomnia pull request #4744
Opened 2022-05-02 04:24 UTC by jackkav

bootstrap was calling build inconsistently making chained scripts hard to follow.

2022-05-03 16:11 UTC, filfreire approved these changes

2022-05-03 16:16 UTC, DMarby approved these changes
:shipit:

2022-05-03 16:16 UTC, DMarby commented on packages/insomnia-config/package.json
> +    "build": "tsc --build tsconfig.build.json && ts-node ./src/generated/generate.ts"
Just double checking whether the order of this matters? Assuming not

2022-05-03 18:08 UTC, dimitropoulos commented on packages/insomnia-config/package.json
> -    "bootstrap": "npm run generate",
this is a pretty significant change, no? because before it would _not_ build, but now it does.

2022-05-03 18:10 UTC, dimitropoulos commented on packages/insomnia-config/package.json
> +    "build": "tsc --build tsconfig.build.json && ts-node ./src/generated/generate.ts"
it matters: build first, then generate schema from those built types

2022-05-03 18:10 UTC, dimitropoulos requested changes

2022-05-03 18:10 UTC, dimitropoulos commented on packages/insomnia-config/package.json
> +    "build": "tsc --build tsconfig.build.json && ts-node ./src/generated/generate.ts"
I think we should be careful about doing this because it's a side effect of the build that we almost definitely do not want to constantly rerun and could also take up lots of unnecessary time in bootstrap

2022-05-03 18:11 UTC, dimitropoulos commented on packages/insomnia/package.json
> -    "bootstrap": "npm run build:sr",
ok, so then when does send request get built?  or did you say today that something changed such that this isn't required anymore?

2022-05-04 08:17 UTC, jackkav commented on packages/insomnia-config/package.json
> -    "bootstrap": "npm run generate",
The npm hooks sure are confusing.
`"pregenerate": "npm run build",`

2022-05-04 08:22 UTC, jackkav commented on packages/insomnia/package.json
> -    "bootstrap": "npm run build:sr",
send request is built in CI. This isn't required.

2022-05-04 08:23 UTC, jackkav commented on packages/insomnia-config/package.json
> +    "build": "tsc --build tsconfig.build.json && ts-node ./src/generated/generate.ts"
It was already running in bootstrap. I'm just making it more obvious.

2022-05-05 11:07 UTC, jackkav commented on packages/insomnia/package.json
> -    "bootstrap": "npm run build:sr",
Upon closer inspection I had missed updating the doc, and how app build would work thanks for the catch!

2022-05-05 12:36 UTC, jackkav commented on packages/insomnia/package.json
> -    "bootstrap": "npm run build:sr",
I've made the assertion in [314b7d7](https://github.com/Kong/insomnia/pull/4744/commits/314b7d7fb34866927a061ac5eb419e7a225915a7) that all dx flows start with npm run bootstrap therefore ca-cert prep can happen in just one place

2022-05-05 12:41 UTC, dimitropoulos commented on packages/insomnia-config/package.json
> -    "bootstrap": "npm run generate",
sweet.

2022-05-05 12:43 UTC, dimitropoulos commented on packages/insomnia-config/package.json
> +    "build": "tsc --build tsconfig.build.json && ts-node ./src/generated/generate.ts"
```suggestion
    "build": "tsc --build tsconfig.build.json && npm run generate"
```

let's reduce the margin for error here, at least, then.

2022-05-05 12:45 UTC, dimitropoulos commented on packages/insomnia/package.json
> +    "build": "npm run generate:ca-certs",
I find it hard to understand how the `build` command in the `insomnia` package doesn't actually build insomnia, but instead only generates ca-certs??  This is a pretty tough sell on developer experience for me.

2022-05-05 13:07 UTC, jackkav commented on packages/insomnia/package.json
> +    "build": "npm run generate:ca-certs",
open to suggestions

2022-05-05 13:09 UTC, jackkav commented on packages/insomnia-config/package.json
> +    "build": "tsc --build tsconfig.build.json && ts-node ./src/generated/generate.ts"
that would create a loop since generate will pregenerate the build step again.

2022-05-05 13:40 UTC, dimitropoulos commented on packages/insomnia/package.json
> +    "build": "npm run generate:ca-certs",
I suggest all `build` scripts build the package they belong to (as it did before this PR).  Whatever `build` means for that package can vary (as it does here).

also, it has a strange indirection here now because `prebuild` will clean things that weren't done during the `build`

2022-05-05 13:41 UTC, dimitropoulos commented on packages/insomnia-config/package.json
> +    "build": "tsc --build tsconfig.build.json && ts-node ./src/generated/generate.ts"
ok, so then we remove the "pregenerate"?

2022-05-11 16:30 UTC, jackkav commented
Since "build" terminology exists for the app, inso, packages and plugins and the meaning is not consistent. Therefore this PR does not entirely solve the problem. A name change may be in order. Abandoning.

2022-05-11 16:30 UTC, closed without merging