chore: add metrics tracking for design preview button
getinsomnia/insomnia pull request #4761
Opened 2022-05-05 16:22 UTC by marckong

We would like to make better designs with more metrics about the product. We need to add tracking logic to this button click event.

2022-05-05 17:51 UTC, wdawson requested changes

2022-05-05 17:51 UTC, wdawson commented on packages/insomnia/src/common/analytics.ts
> +  designOutputPreviewToggle = 'Design Output Preview Toggled',
I don't think we want a specific event for this particular toggle. We probably want a "Button Clicked" event with a type and/or location parameter. The reasoning is that there are often limits on the number of event names you can have.

2022-05-05 20:22 UTC, marckong commented on packages/insomnia/src/ui/components/wrapper-design.tsx
> +        type: 'user_event',
maybe adding/defining segment event payload type would be a good idea?

2022-05-05 20:51 UTC, dimitropoulos commented on packages/insomnia/src/ui/components/wrapper-design.tsx
> +        location: 'wrapper-design',
```suggestion
```

We definitely do not want to associate name of a code component to the analytics.  also, if we ever change the name of this component (which, I am actually planning on in this case) this would likely fall out of sync.

2022-05-05 20:51 UTC, dimitropoulos commented on packages/insomnia/src/ui/components/wrapper-design.tsx
> +        location: 'wrapper-design',
I tried to look for where `location` came from, but I don't see it elsewhere in the code and I don't see it in segment's docs.

2022-05-05 21:23 UTC, wdawson requested changes

2022-05-05 21:23 UTC, wdawson commented on packages/insomnia/src/ui/components/wrapper-design.tsx
> +        type: 'user_event',
Sorry, I should have been more prescriptive in my suggestion. Here's the extra properties I think we should go with:

```js
{
  type: 'design preview toggle'
  action: 'show | hide' // should be `show` or `hide` depending on which toggle state occurs as a result of the click
}
```

This will reuse the properties we already have and remain human readable (that's the goal here, not machine readable).

2022-05-05 21:23 UTC, wdawson commented on packages/insomnia/src/ui/components/wrapper-design.tsx
> +        location: 'wrapper-design',
Yeah, this was my bad from my previous suggestion. I wasn't clear.

@marckong it might be worth adding something like [this](https://github.com/Kong/insomnia/blob/develop/packages/insomnia/src/common/analytics.ts#L80) but for button click properties:
```js
export function buttonClickSegmentEventProperties
```

2022-05-05 22:12 UTC, marckong commented on packages/insomnia/src/ui/components/wrapper-design.tsx
> +        location: 'wrapper-design',
I think the confusion for my end came from lack of documentation or explanation about the interface for Segment Event Properties and how we are using it. I observed there are several formats. I wonder if we need to consolidate it into an interface like this:
```ts
interface SegmentEventProperties {
  /**
   * type - TODO: good to describe - what do we exactly mean by type? is this actually event type? and the SegmentEvent enum represents the event name?
   * */
  type: string;

  /**
   * description of action - TODO: good to describe - what do we mean by action? Maybe we are confusing between "event type", "event name", "user action"?
   * */
  action: string;

  /**
   * error message - TODO: good to describe - why do we need this? where is it coming from?
   * */
  error?: string;
}
```

2022-05-05 22:18 UTC, wdawson commented on packages/insomnia/src/ui/components/wrapper-design.tsx
> +        location: 'wrapper-design',
Could be helpful to type it if we want. I think we hadn't gone that far yet because we weren't sure if these properties were going to work or not as we expand the data collection that we do, so wanted a bit more flexibility for now. But I'm good either way.

2022-05-05 22:24 UTC, marckong commented on packages/insomnia/src/ui/components/wrapper-design.tsx
> +        location: 'wrapper-design',
Would this be suitable for now?

analytics.track({
  anonymousId: '',
  event: 'Button Clicked',
  properties: {
    action: 'hide',
    type: 'design preview toggle'
  }
});

2022-05-05 22:33 UTC, marckong commented on packages/insomnia/src/common/analytics.ts
> +export function buildEventProperties<T extends string>(
This function may not serve a good purpose other than type checking in the dev time.

2022-05-05 22:33 UTC, wdawson commented on packages/insomnia/src/ui/components/wrapper-design.tsx
> +        location: 'wrapper-design',
Uh... no I think we want to have all the other data in there. You should use [this function](https://github.com/Kong/insomnia/blob/develop/packages/insomnia/src/common/analytics.ts#L131) in a similar way to other places in the app.

2022-05-05 22:35 UTC, marckong commented on packages/insomnia/src/common/analytics.ts
> +   * TODO: what do we mean by type?
Let's take time to define what these actually mean.

2022-05-05 22:51 UTC, marckong commented on packages/insomnia/src/ui/components/wrapper-design.tsx
> +        location: 'wrapper-design',
Just to clarify, i deleted ids on purpose and this is the same way vcs tracking method executes the segment tracking API, so in terms of what are captured, they are same kinds. I could be wrong.

2022-05-06 15:12 UTC, wdawson approved these changes
LGTM from the product side. I'll let the devs also comment of the code etc.

2022-05-10 13:09 UTC, dimitropoulos reviewed
I'm sorry.  I'm confused.  Why can't we just add this single line to wrapper-design:

```ts
    trackSegmentEvent(SegmentEvent.buttonClick, {
      type: 'design toggle preview',
      action: previewHidden ? 'show' : 'hide',
    });
```

2022-05-10 13:10 UTC, dimitropoulos commented on packages/insomnia/src/common/analytics.ts
> +  return { type, action, error };
this code will always send an `error` property, even when there is none.  not sure if that's the best thing to do.  I see that this helper function did this before, but at least we weren't calling it everywhere, you know?

2022-05-10 13:48 UTC, filfreire approved these changes

2022-05-10 18:04 UTC, dimitropoulos commented on packages/insomnia/src/common/analytics.ts
> + * to understand what 'event properties' is for.
```suggestion
 * You may refer to this Segment API Document - https://segment.com/docs/connections/spec/track/#properties to understand what 'event properties' is for.
```

2022-05-10 18:04 UTC, dimitropoulos commented on packages/insomnia/src/common/analytics.ts
> + * ourselves to make product decisions
```suggestion
 * The following properties are custom defined attributes for our own metrics purpose to help ourselves to make product decisions
```

no need to introduce arbitrary line wraps

2022-05-10 18:05 UTC, dimitropoulos approved these changes

2022-05-10 22:10 UTC, merged