refactor: rename the git sync submission label
getinsomnia/insomnia pull request #4781
Opened 2022-05-13 14:17 UTC by marckong

## Description
Currently, the Git Repository Settings Modal renders its submission button with "Done" label, which misleads its intention; closing the modal as its  complete or closing it as a dismissal.

After some discussion, instead of disabling the Done button when form is invalid and changing the label to "Sync", we just decided to move ahead with renaming the label only at this time until we refactor modal and form pattern.

2022-05-17 18:49 UTC, dimitropoulos commented on packages/insomnia-smoke-test/tests/git-sync.test.ts
> +  await page.locator('button[name="git-sync-done"]').click();
please use `data-testid` for this kind of thing.  it's a common pattern, but you can read about it a little more here https://testing-library.com/docs/queries/bytestid/

2022-05-17 18:49 UTC, dimitropoulos commented on packages/insomnia-smoke-test/tests/git-sync.test.ts
> +  await page.locator('button[name="git-sync-done"]').click();
and for playwright, here https://playwright.dev/docs/selectors#id-data-testid-data-test-id-data-test-selectors

2022-05-17 18:50 UTC, dimitropoulos requested changes
please use `data-testid` for test ids, see comment

2022-05-17 18:54 UTC, marckong commented on packages/insomnia-smoke-test/tests/git-sync.test.ts
> +  await page.locator('button[name="git-sync-done"]').click();
Do we rip off data-testid for the production build in the babel setup or this gets included? It was recommended to avoid over-using data-testid attribute at my previous organization. Instead, use of accessibility attributes was strongly recommended.

2022-05-17 18:58 UTC, marckong commented on packages/insomnia-smoke-test/tests/git-sync.test.ts
> +  await page.locator('button[name="git-sync-done"]').click();
Our e2e test doesn't happen in the browser, so not sure keeping the data-testid in the production build makes sense if we want to rely on data-testid for selecting components. I generally think it's good to have accessibility attributes used for components and selecting them in tests. However, I have no issue using data-testid as long as we strip it off.

2022-05-18 18:53 UTC, dimitropoulos approved these changes

2022-05-19 14:17 UTC, merged