Allow for the toggleComment call to be configurable on hotkeys
getinsomnia/insomnia pull request #4786
Opened 2022-05-16 11:16 UTC by filfreire

Follow-up to #1694 and to [this slack thread](https://getinsomnia.slack.com/archives/C5BKWBAMN/p1652475869314609)

This PR adds the ability for folks to edit or add their own custom hot key to trigger the `toggleComment` functionality of CodeMirror. Up until now we have it hard-coded to `Ctrl+/` or `Cmd+/` which isn't available as a working command for all kind of keyboard layouts, not allowing folks, for example, to comment out sections of a GraphQL query they're building.

I'm split on this change: 
- it opens a small precedent for exposing keyboard shortcuts specifically to deal with Code Editor functionality, where-as up until now we only had the `Beautify Active Code Editors` option exposed and that was it. 
- On the other hand it helps unblock folks that want to have better interaction with the code editors views we have but can't due keyboard layout differences, and the fact we hardcode several `extraKeys` combos.

Let me know what you think and if it's worth to merge this, or it's opening a can of worms 😅 

![Screenshot 2022-05-16 at 12 10 06](https://user-images.githubusercontent.com/11976836/168580172-9b1dd648-dcc8-4b5b-8a21-735e71914008.png)

https://user-images.githubusercontent.com/11976836/168580191-f05533ff-15ed-47e5-960f-a577ffec2a8e.mp4

2022-05-18 10:04 UTC, gatzjames approved these changes
Works nice!
I think it's a common pattern to have editor shortcuts exposed to the app's shortcut config.
As a user I would expect that to be the case and it can open up the use-cases you mentioned!

2022-05-18 13:22 UTC, marckong approved these changes
this looks good to me! It wouldn't hurt to add a playwright test though it's understandable that it's hard to do this now. I am also making some changes in this area and it's challenging :(

2022-05-18 13:30 UTC, dimitropoulos commented on packages/insomnia/src/common/hotkeys.ts
> +    keyComb(true, false, false, false, keyboardKeys.semicolon.keyCode),
does this change the standard keyboard shortcut for this?  for me it's not semicolon, but rather `/`

2022-05-18 13:31 UTC, dimitropoulos commented on packages/insomnia/src/common/hotkeys.ts
> +    keyComb(true, false, false, false, keyboardKeys.semicolon.keyCode),
if so, I am not OK with us removing this very very standard shortcut.  VSCode, for example, uses this.  how do they accomplish it if it has remapping problems with operating systems?

2022-05-18 13:35 UTC, dimitropoulos requested changes
see my comment

2022-05-19 08:31 UTC, filfreire commented on packages/insomnia/src/common/hotkeys.ts
> +    keyComb(true, false, false, false, keyboardKeys.semicolon.keyCode),
Hi @dimitropoulos 👋 

1) This doesn't change the standard one, it adds an extra one which folks can configure, besides `Ctrl+/`.

2) In VSCode they allow folks with a non US keyboard to change the default one, like from using `/` to using `;`, or `ç`, ... because we don't generally have the `/` available with a single keypress.


I wasn't sure how to propagate the change from and to the CodeMirror `extraKeys.toggleComment` variable that is hardcoded when the app starts, so I went ahead and create an alternate key combination (e.g. using `;`).

There's a side effect I didn't mention in the initial PR description: if we put the key combination here the same as CodeMirror `extraKeys.toggleComment` variable, which makes it so toggleComment is triggered twice in a row, basically doing and undoing the commented code in one go.

2022-05-20 11:14 UTC, dimitropoulos commented on packages/insomnia/src/common/hotkeys.ts
> +    keyComb(true, false, false, false, keyboardKeys.semicolon.keyCode),
I hate to rain on the parade but if we're going to do this we need to do it right.  I'm glad you clarified that the double-triggering with codemirror is the rationale for the approach you selected because there is where the problem is.

Also, I don't think it's an acceptable UX to have two shortcuts for the same thing, one that may overlap with system shortcuts but is not configurable and another that is.  Not that I have a problem with multiple shortcuts for the same thing in general, but it seems like we're not really approaching this with the UX in top of mind.


Here's what I'd suggest:
1. configure the app with the native shortcut (`Ctrl`/`Cmd`+`/`) by default, just like it is now
1. configure CodeMirror to use this shortcut
1. ensure that changing the shortcut in Insomnia will change CodeMirror mapping as well (with the original shortcut it is today no longer functional)

2022-06-15 08:31 UTC, closed without merging

2022-06-15 08:32 UTC, filfreire commented
Closing this for now, will revisit it if there's time in the future.