Feature/ins-1518-improve-create-request-dropdownmodal
getinsomnia/insomnia pull request #4812
Opened 2022-05-23 18:40 UTC by jackkav

Request shortcuts in new request/folder dropdown

2022-05-25 00:20 UTC, dimitropoulos commented on packages/insomnia/src/common/hotkeys.ts
> -  [hotKeyRefs.REQUEST_QUICK_CREATE.id]: keyBinds(
Why was this removed?  I use it all the time.  was it moved somewhere else maybe?

2022-05-25 08:02 UTC, jackkav commented on packages/insomnia/src/common/hotkeys.ts
> -  [hotKeyRefs.REQUEST_QUICK_CREATE.id]: keyBinds(
Thanks for the early review! Forgot to add that to the PR description. I've renamed them both to point at REQUEST_CREATE_HTTP.

2022-05-25 13:43 UTC, jackkav commented on packages/insomnia/src/common/hotkeys.ts
> -  [hotKeyRefs.REQUEST_QUICK_CREATE.id]: keyBinds(
I merged them.

2022-05-26 13:25 UTC, filfreire approved these changes

2022-05-26 20:37 UTC, dimitropoulos requested changes
hey: reminder that we want analytics events for stuff like this

2022-05-31 12:09 UTC, gatzjames approved these changes
Seems that most of the friction points have been moved to new issues 👏
Imo migrating the dropdown seems like a big task for this PR so we could keep it out of scope for now.
Tested and it works great! 🚀

2022-06-01 14:53 UTC, jackkav commented
Tested analytics from new request in folder, add button and empty state. All send successfully @dimitropoulos

2022-06-01 20:50 UTC, dimitropoulos requested changes, later dismissed
I know I know we're trying to get this PR over the line and I hate having to ask this.. but what's the story with the request group menu not having the graphql and grpc items anymore in the last commit?  Apologies if I missed it somewhere.

<img width="50%" src="https://user-images.githubusercontent.com/15232461/171497603-e1f1c829-5560-4e5d-bf12-8404b683a01e.png" />

___

Also, independent of that, the change to put unbound functions in callbacks (e.g. `onClick={() => someThing()}}`) has pretty sever performance problems it presents (over time, especially).

___

I did, however, confirm that the segment events area all working now, so that's good at least.

2022-06-01 21:49 UTC, jackkav commented
It wasn't in the ticket, so I thought to add it if it was straightforward. However once I did the number of new decisions to make increased the scope too much for a single PR.

2022-06-01 22:08 UTC, marckong approved these changes

2022-06-02 07:31 UTC, merged