fix: use of replacer to fix the circular ref issue with .stringify()
getinsomnia/insomnia pull request #4832
Opened 2022-06-02 20:59 UTC by marckong

The issue is that parsing the swagger schema object can take a lot of circular references in certain cases. Then we are stringifying it in openapi-to-kong plugin. However, JSON does not support circular reference (see [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cyclic_object_value#examples)). The MDN suggests a simple arrow function to track the reference of what's already read as a replacer function to be passed in JSON.stringify() method. I attempted to use it, and this fixed the issue.

It's probably fine to use the WeakSet way suggested by MDN for now unless we want to find a specific library to stringify that handles circular dependency.

Before this fix:
![image](https://user-images.githubusercontent.com/103070941/171737083-bda2e8e6-b702-4958-a110-0df6bc5ccc28.png)

After this fix:
![image](https://user-images.githubusercontent.com/103070941/171737297-3afe0fd2-f727-4f03-974f-ef8dca4afae4.png)

2022-06-02 21:01 UTC, marckong commented
Will add unit test to cover this case shortly

2022-06-03 11:35 UTC, filfreire approved these changes
LGTM

Before:
<img width="1243" alt="Screen Shot 2022-06-03 at 12 33 50" src="https://user-images.githubusercontent.com/11976836/171846192-437aeff0-f262-4793-bf8c-e8b32bcd9290.png">


After:
<img width="1413" alt="Screen Shot 2022-06-03 at 12 34 04" src="https://user-images.githubusercontent.com/11976836/171846210-6f02d462-2072-4270-91f1-96fae51e4585.png">



There's some weird errors when importing the example yaml file in the FTI-3186, but they are also reproducible before in `2022.3.0`, unrelated to this change.

<img width="773" alt="Screen Shot 2022-06-03 at 12 03 38" src="https://user-images.githubusercontent.com/11976836/171846235-106026a8-5c88-443c-9b57-effca0a3aca7.png">
<img width="305" alt="Screen Shot 2022-06-03 at 12 05 43" src="https://user-images.githubusercontent.com/11976836/171846243-b182545a-db73-4a4e-9e01-a9dfaa071852.png">

2022-06-03 12:30 UTC, jackkav commented
If I'm understanding this correctly it is removing circular references in order to support rendering documents that contain them.
If we are altering the users spec in order to support for transformation or rendering we should consider providing a warning that there is a mutation happening in order to export as json and render. Otherwise it may come as a surprise to a user transforming a long OAS that some things are missing.
> The snippet below illustrates how to find and filter (thus causing data loss) a cyclic reference by using the replacer parameter of [JSON.stringify()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify):

2022-06-03 12:33 UTC, jackkav commented on packages/openapi-2-kong/src/declarative-config/plugins.ts
> + * This is what MDN Doc suggests as a solution for circular dependency as JSON does not support it.
```suggestion
 * This is what MDN Doc suggests to remove circular dependencies, in order to support JSON format.
```

2022-06-03 19:34 UTC, dimitropoulos commented on packages/openapi-2-kong/src/declarative-config/plugins.ts
> +  console.log(operation);
```suggestion
```

2022-06-03 19:35 UTC, dimitropoulos requested changes
please see https://github.com/Kong/insomnia/blob/29f530e19c7c976eb4535467233b45b3091f020d/packages/insomnia-importers/src/importers/openapi-3.ts#L714 and https://github.com/Kong/insomnia/pull/4015

If we need to parse an openapi spec and handle circular deps, we should use the swagger parser as shown above and not write or maintain this code ourselves.

2022-06-06 09:36 UTC, Tieske requested changes
This needs a test case with a recursive JSON schema. And the expected output for the generated Kong configuration.

2022-06-06 13:41 UTC, marckong commented
@dimitropoulos this is a case that is stringifying what's parsed. 'ignore' was added to actually skip the circular reference check.

Swagger doc also suggests to use a custom replacer function [when serializing a dereferenced api as JSON](https://apitools.dev/swagger-parser/docs/#circular-refs).
![image](https://user-images.githubusercontent.com/103070941/172167410-4e376623-c3e6-44cf-8660-d1b062e18d54.png)

The use of bundle method instead of validate method is also suggested, but this will attach all the internal references and seems it may need a bigger scope.

Now, we can possibly look for a library as I mentioned in the PR description. 

> It's probably fine to use the WeakSet way suggested by MDN for now unless we want to find a specific library to stringify that handles circular dependency.

I would be fine looking for a library now to stringify with circular reference support. Please feel free to leave any suggestion.

@Tieske I am not sure if this needs test coverage on the Kong configuration as the code usage seems to be limited to the declarative configuration. Please feel free to educate me where it is used for Kong configuration since I am still new to the codebase. Test case is in progress.

2022-06-06 14:48 UTC, marckong commented
After investigation, these two libraries seem to be good candidates if we really want to pick a library for it. However, one still requires "replacer" function and the other is bigger than what we need. I am not sure if this is necessary. I would be keen to look at any suggestion.

https://github.com/davidmarkclements/fast-safe-stringify
https://github.com/WebReflection/flatted

2022-06-07 07:42 UTC, Tieske commented
> @Tieske I am not sure if this needs test coverage on the Kong configuration (if you meant for Kong for Kubernetes) as the code usage seems to be limited to the declarative configuration. Please feel free to educate me where it is used for Kong configuration since I am still new to the codebase. Test case is in progress as I mentioned.

The typical circular reference is in the JSON schema. These schemas will be passed on when the Kong request-validator is configured. So the output should also get the circular references for the validator to do its job. So imo; yes, it will need a test case.

To enable that Kong plugin add `x-kong-plugin-request-validator: {}` to the root of the document, see https://github.com/Kong/openapi2kong/blob/master/examples/learnservice_oas.yaml#L55 (that repo is deprecated, but the example is still valid)

2022-06-13 15:02 UTC, Tieske commented on packages/openapi-2-kong/src/declarative-config/fixtures/test-circular.expected.json
> +								"body_schema": "{\"description\":\"desc\",\"allOf\":[{\"description\":\"desc\",\"type\":\"object\",\"properties\":{\"entity1Prop1\":{\"description\":\"desc\",\"oneOf\":[{\"description\":\"des
This is (reformatted):
```json
{
  "description": "desc",
  "allOf": [
    {
      "description": "desc",
      "type": "object",
      "properties": {
        "entity1Prop1": {
          "description": "desc",
          "oneOf": [
            {
              "description": "desc",
              "allOf": [
                {
                  "description": "desc",
                  "type": "string"
                },
                {
                  "description": "desc",
                  "type": "string",
                  "properties": {
                    "owners": {
                      "type": "array",
                      "description": "desc",
                      "items": {
                        "description": "desc",
                        "type": "object",
                        "required": [
                          "entity5"
                        ],
                        "properties": {
                          "entity5": {
                            "description": "desc",
                            "oneOf": [
                              {
                                "description": "desc",
                                "allOf": [
                                  {
                                    "description": "desc",
                                    "allOf": [
                                      null,
                                      null
                                    ]
                                  }
                                ]
                              }
                            ],
                            "discriminator": {
                              "propertyName": "entity5Type",
                              "mapping": {
                                "ENTITY_3": "#/components/schemas/Entity3AsOwner"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          ],
          "discriminator": {
            "propertyName": "entity5Type",
            "mapping": {
              "ENTITY_CIRCULAR_START": "#/components/schemas/EntityCircularStart"
            }
          }
        }
      }
    }
  ]
}```

It still contains references;
```
"ENTITY_CIRCULAR_START": "#/components/schemas/EntityCircularStart"
```
but they are no longer valid, since their targets are not included.

2022-07-01 16:42 UTC, closed without merging