prevent focus loss
getinsomnia/insomnia pull request #4925
Opened 2022-07-01 12:17 UTC by jackkav

during development, when modifying a class component hmr triggers a full-reload event on the ws connection. This event is picked up by the browserwindow will-navigate and causes chrome to steal focus. This change corrects that behaviour.

2022-07-01 14:59 UTC, dimitropoulos commented
can you please share some reproduction steps?  Is `ws connection` workspace?

2022-07-01 16:29 UTC, jackkav commented
> can you please share some reproduction steps?  Is `ws connection` workspace?

Sure if you modify ui/index.tsx you will see a full-reload event in the websocket dev tool view. In normal cases the reload will happen as usual and get a rerender but if you leave your dev env running for a while the hmr stops working and full-reload causes the will-navigate event to receive a url with an anchor # on the end which causes the handler to misinterpret it as an outside url click. This change makes the handler ignore local dev vite full-reload events.

2022-07-01 16:42 UTC, marckong approved these changes

2022-07-01 20:23 UTC, dimitropoulos requested changes, later dismissed
@jackkav in that case can you please document this in the code?  this is a pretty tough-to-discern edge-case just from looking at the code and we'd benefit a lot from including it (down the road, when we start wondering why it was using `startsWith`).  you could pretty much take what you already wrote verbatim

2022-07-04 10:22 UTC, filfreire approved these changes
Tested locally and seems to be working as intended.

Before - every change to the `ui/index.tsx` file and other files that would cause Insomnia to reload would open a `localhost` related browser tab:
![Screenshot 2022-07-04 at 10 59 16](https://user-images.githubusercontent.com/11976836/177135346-8b9ad79c-f7cb-4b08-b06c-ef832e496131.png)

After - local changes no longer open browser tabs:

![Screenshot 2022-07-04 at 11 16 06](https://user-images.githubusercontent.com/11976836/177135363-43f6a68a-b464-4cbc-9243-973e2064b0f3.png)

2022-07-04 10:22 UTC, filfreire commented on packages/insomnia/src/main/window-utils.ts
> +    if (url.startsWith(appUrl)) {
```suggestion
    // Prevents local dev full-reload events from opening browser window, see https://github.com/Kong/insomnia/pull/4925
    if (url.startsWith(appUrl)) {
```

2022-07-04 10:36 UTC, jackkav commented
I'm not sure exactly what puts the hash on the end of the url after a certain amount of time, but I have a hacky repro.
1. set the window location `window.location='http://localhost:3334/index.html#'` in chrome devtools. 
2. Make a change to a react function component. 

Before HMR would open a browser tab.
After HMR would reload only the changed function component.

2022-07-04 11:35 UTC, merged