Move login flow to accounts website.
getinsomnia/insomnia pull request #4964
Opened 2022-07-13 20:09 UTC by johnwchadwick

Our intent with this PR is to unify the SRP handshake and key derivation in one place. To spell it out explicitly, the intent of this PR is not to obfuscate the login process from the public, but just to make the app more flexible so that we can implement additional features to login without needing to duplicate it between the app and the accounts website.

The security model of this new login process has some implications. The general flow works like this:

1. On app startup, an X25519 keypair is generated for login delegation purposes.
2. When the login modal is opened, a new URL is opened linking into the accounts website, containing the public key.
3. The login process is continued in the browser, including SRP and key derivation. The accounts website always requires a password, even if the user is already logged in.
4. The accounts website running in the browser invokes an `insomnia://` deep-link containing a [sealed box](https://libsodium.gitbook.io/doc/public-key_cryptography/sealed_boxes) with the derived key and session token.
5. The app grabs the account keys and uses the derived key to decrypt them.

Though this removes both SRP and key derivation from the app side of the login flow, some code in the app still needs to deal with SRP and the key derivation process for the time being; this will be dealt with in the future, allowing us to remove a significant amount of code and some dependencies. For now, the remainder of session code is unchanged.

There are a few assumptions:

1. The end user device is trusted and not compromised; if it were not trusted, the current login flow would still be insecure, as it could be defeated with a simple key logger.
2. The app is not compromised; if the app were compromised, the existing login flow would also be unsafe, since either the raw credentials or the long-term session could be stolen.
3. The browser is trusted and not compromised; **This is a new assumption from this PR**. However, if the browser _was_ compromised, many other account-related actions would be insecure, as they can only be performed in the browser.

This login flow is assumed to be secure with those assumptions.

Here are some example scenarios:

- Phishing/token theft: An attacker (e.g. running in another browser tab) could try to start the app authentication flow and get the token from it somehow. The following mitigations apply:
    - Deep links: An attacker would need to register the `insomnia://` protocol to be able to steal the tokens directly out of the automatic flow. This is unlikely in cases where the computer is not compromised. (They could still try to convince the user to copy and paste the token into an attacker-controlled input.)
    - Password requirement: Other security issues require the user to explicitly input their password to finish the login process. Because of this, the login flow itself could never facilitate an automated attack, even in the case where the computer is compromised.
    - We could also improve this by implementing the login token as a one-time exchangeable token where the API call to exchange the token is inaccessible via browsers as a result of Same-Origin policy. This would increase the complexity of a phishing attack and make it easier to detect.
- Keymatter/ciphertext leakage: An attacker could try to intercept the public key or authentication box somehow.
    - The public key and cipher text are both useless without the private key, which never leaves the app's memory. Assuming the app is not compromised, this flow is already very secure in this regard.
    - We could still improve it by implementing the one-time token mechanism discussed above: then, the session token in the box would become useless after it is used.
- Accounts website XSS: An attacker could gain (possibly persistent) code execution on the accounts website, allowing the attacker to directly exercise code in the context of app authentication.
    - Due to the requirement to enter a password to create the app session, we are happily not introducing additional risk here.
    - If an attacker has code execution on the accounts website, they can potentially steal the derived key, OR they can potentially read the user's credentials as they are typing them. With regards to app authentication, while the attacker could now steal a long-term token out of the app auth flow, this is effectively not different from stealing the momentarily entered credentials/passphrase. And since the app authentication requires the credentials on the API side, there's no additional risk here.
    - Again, this can be improved by implementing a one-time token exchange mechanism, as it would make it impossible to get the token from the browser context alone.

Note that the accounts website changes are not in production yet. This PR shall remain a draft until it is.

2022-07-13 20:11 UTC, johnwchadwick commented on packages/insomnia/src/index.html
> +      content="font-src 'self' data:; connect-src * data:; default-src * insomnia://*; img-src blob: data: * insomnia://*; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src
Note: This is to allow for fast ArrayBuffer base64 computation via `fetch` and blob. It is a bit of a hack, but the approach is very fast in both Electron and the browser. I sincerely believe there is no security implication of adding `data:` to connect-src`, but I am not 100% certain of this.

2022-07-13 20:55 UTC, dimitropoulos commented
(oh, sorry, I didn't realize this was still in draft: well all the same added a super minor commit 624aa5002bdf0ee8158842bcaa0d1ab34746887e to reflect what we do all other places in the app.  the goal is to get onto jsx-transform (https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) at which point we'd have no need for the default `React` thingy at all except for cases where there are collisions (such as React.MouseEvent vs MouseEvent from lib.dom.  generally we aim to treat the react npm imports like any other npm.)

2022-07-14 13:56 UTC, johnwchadwick commented
> (oh, sorry, I didn't realize this was still in draft: well all the same added a super minor commit [624aa50](https://github.com/Kong/insomnia/commit/624aa5002bdf0ee8158842bcaa0d1ab34746887e) to reflect what we do all other places in the app. the goal is to get onto jsx-transform (https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) at which point we'd have no need for the default `React` thingy at all except for cases where there are collisions (such as React.MouseEvent vs MouseEvent from lib.dom. generally we aim to treat the react npm imports like any other npm.)

It actually *is* like any other import; namespaces and default imports are valid ES and not a special case. We use default imports and namespace imports in other places.

I don't understand how this is an improvement.

2022-07-19 10:49 UTC, DMarby requested changes

2022-07-19 10:49 UTC, DMarby commented on packages/insomnia/src/ui/redux/modules/global.tsx
> +      if (submitAuthCode) {
This should be `currentLoginModalHandle?.submitAuthCode` or similar I think?
Currently doesn't work, tested by changing the protocol handler in the website to `insomniadev://` as that's what the app registers when in dev mode.

2022-07-19 10:49 UTC, DMarby commented on packages/insomnia/src/ui/components/modals/login-modal.tsx
> +export const showLoginModal = () => showModal(LoginModalHandle);
Seems like all calls to `showModal(LoginModal)` are now broken, not sure if they need to be switched out to reference this instead or something?

This seems to break the protocol handler for `COMMAND_LOGIN`, as well as opening the login modal from Settings -> Account -> Log In

2022-07-19 10:49 UTC, DMarby commented on packages/insomnia/src/ui/components/modals/login-modal.tsx
> +      session.absorbKey(box.token, box.key);
This should probably be awaited since does a `_whoami` call, in-case it errors or such?

2022-07-19 10:49 UTC, DMarby commented on packages/insomnia/src/ui/components/modals/login-modal.tsx
> +    } catch (e) {
Maybe worth logging the full error here, and/or pass it to Sentry, to aid in debugging if something breaks for a user?

2022-07-19 10:49 UTC, DMarby commented on packages/insomnia/src/ui/components/modals/login-modal.tsx
> +      this.setState({ ...this.stateRef.current, state: 'done' });
Seems like something causes this to momentarily flash and the entire modal to disappear upon sign-in, which is a fairly confusing experience. Might have to do with the hooks in `absorbKey` causing a re-render somewhere up the tree?

2022-07-19 14:22 UTC, johnwchadwick commented on packages/insomnia/src/ui/redux/modules/global.tsx
> +      if (submitAuthCode) {
It was meant to be `currentLoginModalHandle`... I'm not sure how that happened.

I don't currently have a way to test this because, as it turns out, the Electron function to register the protocol handler doesn't do anything on Linux.

2022-07-19 14:54 UTC, johnwchadwick commented on packages/insomnia/src/ui/components/modals/login-modal.tsx
> +export const showLoginModal = () => showModal(LoginModalHandle);
Fixed. (I was aware of this one, but I hadn't fixed it yet. I didn't expect this PR to be the first one to be reviewed.)

2022-07-19 14:57 UTC, johnwchadwick commented on packages/insomnia/src/ui/redux/modules/global.tsx
> +      if (submitAuthCode) {
(Should be fixed, but not tested.)

2022-07-19 14:58 UTC, johnwchadwick commented on packages/insomnia/src/ui/components/modals/login-modal.tsx
> +      session.absorbKey(box.token, box.key);
Done.

2022-07-19 14:58 UTC, johnwchadwick commented on packages/insomnia/src/ui/components/modals/login-modal.tsx
> +    } catch (e) {
Added Sentry.captureException.

2022-07-19 15:02 UTC, johnwchadwick commented on packages/insomnia/src/ui/components/modals/login-modal.tsx
> +      this.setState({ ...this.stateRef.current, state: 'done' });
Fair enough; I just got rid of the done state, since the old login modal didn't have it anyway.

2022-07-19 15:36 UTC, DMarby commented on packages/insomnia/src/ui/redux/modules/global.tsx
> +      if (submitAuthCode) {
Works like a charm :shipit:

2022-07-19 15:38 UTC, DMarby commented on packages/insomnia/src/ui/components/modals/login-modal.tsx
> +    clickLink(url);
Not sure what to do about/whether to do anything about this yet UX wise, but leaving it as a note so I don't forget:

The fact that we automatically open this in the browser becomes a bit weird in certain situations, eg when this modal is automatically opened every time a sync action is done and you're not authenticated (including listing projects on the dashboard)

2022-07-19 15:40 UTC, DMarby commented on packages/insomnia/src/ui/redux/modules/global.tsx
> +      }
nit: Should probably add a break here, lest we accidentally fall-through to the next command added in the future

2022-07-19 16:42 UTC, johnwchadwick commented on packages/insomnia/src/ui/components/modals/login-modal.tsx
> +    clickLink(url);
You know, I thought about this one. Maybe we should make it explicit only in those cases? I could add another step for that.

We should probably improve the 'broken session' UX at some point, as it's currently extremely annoying. (A great start would be having a 'log out' option in the modal when you come from one of these cases.)

2022-07-19 19:55 UTC, DMarby commented on packages/insomnia/src/ui/components/modals/login-modal.tsx
> +    clickLink(url);
I think making it explicit only for those cases probably makes sense, yeah.

Agreed that we definitely need to do something about the invalid session ux in general, log out option in the modal does sound reasonable to me as a start as well

2022-07-26 19:26 UTC, johnwchadwick commented on packages/insomnia/src/ui/redux/modules/global.tsx
> +      }
Done.

2022-07-26 19:30 UTC, johnwchadwick commented on packages/insomnia/src/ui/components/modals/login-modal.tsx
> +    clickLink(url);
I've fixed it now, and also added a Log Out button that displays on the left side. So now it should be less annoying.

2022-07-27 15:09 UTC, wdawson commented
Does the session expiration flow still say "...continue using Insomnia Plus"? If so, "Insomnia Plus" isn't a thing anymore so we should figure out different language.

2022-07-27 15:16 UTC, johnwchadwick commented
> Does the session expiration flow still say "...continue using Insomnia Plus"? If so, "Insomnia Plus" isn't a thing anymore so we should figure out different language.

This is from the API, not this PR, so it will be fixed whenever the change is deployed in the backend.

2022-07-27 15:34 UTC, wdawson approved these changes
LGTM

2022-07-27 17:56 UTC, DMarby approved these changes

2022-07-27 18:30 UTC, dimitropoulos commented on packages/insomnia/src/ui/components/modals/login-modal.tsx
> +  }, []);
issue: this implementation of copying broke for me when I tried it, causing me to not be able to log in.

he below fixes it (including the `import { clipboard } from 'electron'`):


```suggestion
  const copyUrl = useCallback(() => {
    clipboard.writeText(state.url);
  }, [state.url]);
```


My reproduction steps were:
- clicked `Log In` in the Account dropdown
- it redirects to a new open tab in a Chrome workspace that I didn't want it to (i.e. one that I don't have access to my insomnia password anyway)
- so I went back and clicked "Copy URL" and it did not copy anything

Also, document.execCommand is [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) anyway.  Check out `copy-button.tsx` to see us using the clipboard export from electron in the same way.

Also, this implementation is dependent on the selection, whereas the suggested fix is not.  When first trying to figure out what was broken I tried selecting from the input, but it kept just copying `loginKey` to my clipboard.  Later I realized when I looked at the implementation that it was because of the selection being used, rather than the url.

2022-07-27 18:35 UTC, dimitropoulos commented on packages/insomnia/src/ui/components/modals/login-modal.tsx
> +  const [state, setState] = useState<State & Options>({
question: could you share your motivations for using a state object like this?

We don't use this pattern anywhere else in the app, and it's not very common in react codebases for useState hooks.  I don't know the full implications of doing this in the future as we move to react 18 with batching and whatnot.  I am aware that at least [some people](https://dev.to/thoughtspile/are-many-usestates-better-than-usestateobject-j3l) have experimented with this approach and I wanted to get your take first.

2022-07-27 21:41 UTC, johnwchadwick commented on packages/insomnia/src/ui/components/modals/login-modal.tsx
> +  const [state, setState] = useState<State & Options>({
It's just following the same state paradigm as the component it replaces. Truth be told, there's really no reason it *has* to be done this way, but it really does seem like an unnecessary PITA to do it any other way, and I just can't see it as an improvement over what I have here. As an example, having multiple different setState functions would make it more difficult to deal with the modal handle kerfuffle, since I need to plumb those. Are you aware of any downsides to this approach? If not, I think I'm just going to favor merging with this. Obviously, it can be refactored later, as it's basically just a simpler and lower boilerplate equivalent to splitting the object up into individual useStates.

2022-07-27 21:47 UTC, johnwchadwick commented on packages/insomnia/src/ui/components/modals/login-modal.tsx
> +  }, []);
Thanks, but: you didn't need to write all of this; It was only a mistake. I copied the same code from the browser portion, which has no choice but to do this, because browsers have intentionally limited clipboard APIs.

2022-07-27 21:47 UTC, johnwchadwick commented on packages/insomnia/src/ui/components/modals/login-modal.tsx
> +  }, []);
(also fixed)

2022-07-28 00:51 UTC, dimitropoulos commented on packages/insomnia/src/ui/components/modals/login-modal.tsx
> +  const [state, setState] = useState<State & Options>({
ok, maybe we'll revisit later then.  thanks for the explanation.

2022-07-28 00:52 UTC, dimitropoulos approved these changes

2022-07-28 00:55 UTC, johnwchadwick commented
OK, I could probably get more reviews to be safe, but I actually feel pretty confident with the state we got it in, so I'm going to just go for the merge. Thanks everyone.

2022-07-28 00:55 UTC, merged