INS-2627: sanitize path-variable name regex capture for kong 3.x
getinsomnia/insomnia pull request #5958
Opened 2023-05-12 13:22 UTC by filfreire

2023-05-12 15:43 UTC, Tieske requested changes

2023-05-12 15:43 UTC, Tieske commented on packages/openapi-2-kong/src/common.ts
> +  }
Can we externalize this in to its own function? that function can then be called from here, as well as from the validation-generator, to ensure both will have the same name, and the user doesn't have to manually update his/her OAS spec

here's the Go-function; https://github.com/Kong/go-apiops/blob/8842f7b0ecf3654f62f8e0bd867b5b67766794c9/convertoas3/oas3.go#L47-L57

called when generating the regex: https://github.com/Kong/go-apiops/blob/8842f7b0ecf3654f62f8e0bd867b5b67766794c9/convertoas3/oas3.go#L819

called when generating the validation: https://github.com/Kong/go-apiops/blob/8842f7b0ecf3654f62f8e0bd867b5b67766794c9/convertoas3/validator.go#L60-L64

2023-05-12 15:43 UTC, Tieske commented on packages/openapi-2-kong/src/common.ts
> +    result = result.replace(/-/g, '_');
To do this properly, use some slugification (to fix non-ascii chars), and then reduce to [A-Za-z0-9_] whilst starting with [A-Za-z].

2023-05-12 15:45 UTC, Tieske commented on packages/openapi-2-kong/src/common.ts
> +    result = result.replace(/-/g, '_');
from: https://www.pcre.org/current/doc/html/pcre2pattern.html#SEC16

> When PCRE2_UTF is not set, they may contain only ASCII alphanumeric characters and underscores, but must start with a non-digit.

I don't know if PCRE2_UTF is set in our implementation, but better safe than sorry I guess.

2023-05-15 10:28 UTC, filfreire commented on packages/openapi-2-kong/src/common.ts
> +  }
Done, move it into it's own function, and has the same name 👍

2023-05-15 10:31 UTC, filfreire commented on packages/openapi-2-kong/src/common.ts
> +    result = result.replace(/-/g, '_');
Added slugification is done ✅ 

The PCRE2_UTF part not sure how to do it though, but should be fine as is.

2023-05-15 13:57 UTC, jackkav approved these changes

2023-05-15 14:11 UTC, Tieske approved these changes

2023-05-15 14:13 UTC, merged

2023-05-15 14:14 UTC, Tieske commented on packages/openapi-2-kong/src/common.ts
> +    result = result.replace(/-/g, '_');
what I meant mostly was removing accents etc from characters; eg. reduce `èëé` into `eee`