feat: configure response threshold
getinsomnia/insomnia pull request #6520
Opened 2023-09-17 20:02 UTC by ThalisonCosta

Closes [#3115](https://github.com/Kong/insomnia/issues/3115)

This PR makes it possible to the user configure the threshold size of the response, the default value still being 5MB but now isn't hard-coded and its more flexible because values can be set in KB

![Screenshot from 2023-09-17 15-36-04](https://github.com/Kong/insomnia/assets/80794311/53cd78e8-22a3-43d8-a0fd-d689d3fc1caf)

![Screenshot from 2023-09-17 14-27-33](https://github.com/Kong/insomnia/assets/80794311/d692c647-b401-4a35-a248-ee21b5015467)

2023-11-23 13:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/insomnia?pullRequest=6520) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/insomnia?pullRequest=6520) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/insomnia?pullRequest=6520) it.</sub>

2024-07-02 06:06 UTC, ThalisonCosta commented
Hi @jackkav @filfreire @CurryYangxx @ihexxa, I've pushed this PR that implements a new feature. Any feedback or final touches needed before we can close it out?

2024-07-08 09:14 UTC, jackkav requested changes

2024-07-08 09:14 UTC, jackkav commented on packages/insomnia/src/common/constants.ts
> -export const LARGE_RESPONSE_MB = 5;
Thanks for you PR, unfortunately this is not a trivial ask.
Part of the implicit behavior of a flat 5mb limit is that we need to ensure the app and response viewers and usable with files up to that size. If we allow changes to this limit we also need to ensure the app performance doesn't degrade over than size.

Therefore in order to move this forward we would need to set a reasonable higher limit and ensure the app can handle rendering a response of that size without crashing or degrading interactivity.

For reference vscode has limits of 20MB or 300k lines, and has a UX for files over than size, like turning off tokenization and wordwrapping.

Its hard to gauge the performance of the app on older machines. Misconfiguration of this setting can leave the app in a state where it will crash when visiting a request. 

These are my concerns.

2024-07-12 11:47 UTC, gatzjames commented
Closing as increasing the size would create other issues

2024-07-12 11:47 UTC, closed without merging