fix: only prettify if is a valid JSON #2506
getinsomnia/insomnia pull request #6661
Opened 2023-10-06 13:06 UTC by jacksjm

It was checked whether the return is a valid JSON, if so, it maintains the embellishment, if not, it directly returns the value obtained.

Following @johanhammar suggestion

Closes #2506

2023-10-06 13:37 UTC, jackkav requested changes

2023-10-06 13:37 UTC, jackkav commented on packages/insomnia/src/ui/components/codemirror/code-editor.tsx
> +        JSON.parse(jsonString);
The idea behind [jsonPrettify](https://github.com/jackkav/insomnia/blob/05d98968f972cee0968b72f0a143f3f95ab477c7/packages/insomnia/src/utils/prettify/json.ts#L30) is for it to work without parsing it into javascript, if we JSON parse it here, there would be no reason to use this jsonPrettify function. and this would serve us better. `JSON.stringify(jsonString,null,2)`

Another approach would be to add a case to the jsonPrettify function rather than throwing an error.

2023-10-06 16:49 UTC, jacksjm commented on packages/insomnia/src/ui/components/codemirror/code-editor.tsx
> +        JSON.parse(jsonString);
I really appreciate the feedback!
Do you believe the test case in jsonPrettify could use parsing in js?
I'm thinking about inserting the same validation into jsonPreffity after checking that the json is not empty, but I'm not sure if this is the best way. If you agree, I'll do it like this :smile: 
In order, to test the feature, I used a mocking REST (unfortunately via beeceptor: "https://test-mock-text.free.beeceptor.com", as mockbin does not allow this action) that returns a string without quotes. This way, when performing a GET on this service, the response in the Preview and SourceCode views are presented without space:
![image](https://github.com/Kong/insomnia/assets/23451875/b2440e16-be50-451e-9f73-93b09d7e5265)
After the fixes:
![image](https://github.com/Kong/insomnia/assets/23451875/22ba0a43-22a5-4af4-a07b-c1df5e36e5cc)

2023-10-06 18:43 UTC, jacksjm commented on packages/insomnia/src/ui/components/codemirror/code-editor.tsx
> +        JSON.parse(jsonString);
@jackkav I had a different idea, I checked if the structure starts or ends on a String or JSON base.
If not, use JSON.stringify to convert to an understanding codification.
Please, review again if is a satisfactory solution.

Tests with GET endpoints:
![image](https://github.com/Kong/insomnia/assets/23451875/b570f893-8462-4e5d-8440-b3bdef68941f)
![image](https://github.com/Kong/insomnia/assets/23451875/53b75aaf-d1a0-47c9-bf44-d458fb4eafa1)
![image](https://github.com/Kong/insomnia/assets/23451875/4b2b9191-881b-4d04-8efe-6f532e44f7ea)

2023-10-09 08:23 UTC, jackkav commented
Thanks @jacksjm I've pushed a commit that changes the underlying function and added a test. What do you think? @gatzjames

2023-10-09 14:06 UTC, jackkav approved these changes

2023-10-10 09:58 UTC, merged

2023-10-13 15:11 UTC, filfreire commented
@jacksjm you can claim a free tshirt for this PR contribution - find more at https://konghq.com/community/open-source-contribution