chore: clean up pre-request script sdk objects
getinsomnia/insomnia pull request #7172
Opened 2024-03-13 06:39 UTC by ihexxa

- [x] enable `eval()`
- [x] clean up auth param transforming
- [x] add more tests 
- [x] enable requiring node.js modules
- [x] make `console.log` outputs more friendly

2024-03-18 03:32 UTC, ihexxa commented on packages/insomnia/src/hidden-window.ts
> +    const result = eval(script);
As current scripts heavily rely on this so it is introduced for compatibility.
In the long term, a better mechanism should be introduce for cover its usage.

2024-03-19 08:38 UTC, jackkav commented on packages/insomnia/package.json
> +    "@types/xml2js": "^0.4.14",
added packages should be done in a different PR with a rationale.

2024-03-19 14:12 UTC, gatzjames requested changes
For exposing node specific modules:
- We need to document those alongside the node version that we support. This has the potential to block us from upgrading electron and node because of breaking changes to pre-request scripts

For exposing installed modules from npm:
- Similar to node but with greater risk of breaking changes. We should add these one by one once we figure out the API documentation story and how to communicate breaking changes. e.g. what happens when a version of a package we expose has a vulnerability or some reason to be updated but it contains breaking changes?

2024-03-19 14:12 UTC, gatzjames commented on packages/insomnia/src/hidden-window-preload.ts
> +        'crypto-js',
Do we want to provide all these node_modules?
One really big issue here will be upgrading and documenting the supported versions and APIs.
- Lodash seems redundant
- Moment can be replaced by date-fns since it is already installed
- uuid can be replaced by crypto.randomUUID()
- Also a large number of crypto APIs are available in node/browser crypto.

I'd suggest adding these packages in separate PRs one by one and really thinking how it's going to affect maintenance down the road.

2024-03-19 14:12 UTC, gatzjames commented on packages/insomnia/src/hidden-window-preload.ts
> +        'punycode',
This one is deprecated

2024-03-20 08:20 UTC, ihexxa commented on packages/insomnia/src/hidden-window-preload.ts
> +        'crypto-js',
Sounds reasonable 👍 , we definitely should avoid introducing unexpected breaking changes. Let me try to summary some points which could help us to understand and manage this case:

- Currently the main target is to provide consistent interface with existing ones, so that `punnycode` is also included.. (here is one [example](https://github.com/Kong/insomnia/discussions/3806#discussioncomment-8746286)) 
- For managing vulnerabilities and breaking changes, I would propose several ways to manage them:
  - install the latest version and don't upgrade them if needed, actually no claim has been made those module versions are fixed.. ([link](https://learning.postman.com/docs/writing-scripts/script-references/postman-sandbox-api-reference/#using-external-libraries)) 
  - it should be ok if we don't explicitly upgrade the major version of dependencies
  - in the short term, we can add some tests for detecting interface changes
  - in the long term, we can make the pre-request window as a separated sub-package so that we can totally manage its dependencies. 
  - in the long term, we could introduce better alternatives and deprecate old ones
  - improve the hidden window isolation, so that it would greatly reduces the affection of module vulnerabilities, also the security of script execution.
 
Please let me know what do you think and let's have a sync later.

2024-03-20 11:33 UTC, subnetmarco commented on packages/insomnia/src/hidden-window-preload.ts
> +        'crypto-js',
We are providing backwards compatibility with Postman so we need all the modules they also have.

2024-03-21 08:42 UTC, ihexxa commented on packages/insomnia/src/hidden-window-preload.ts
> +        'crypto-js',
I checked modules mentioned:
- lodash is removed
- data-fns's interface seems different from Moment's
- uuid provides generating ids for v1 - v5, while `crypto.randomUUID()` only supports v4
- mapping node/browser crypto to crypto-js interface seems not trivial, its maintenance seems more difficult
Please let me know if there is any other concern.

2024-03-21 08:43 UTC, ihexxa commented on packages/insomnia/src/hidden-window-preload.ts
> +        'punycode',
As mentioned above, `punycode` is required for compatiblity.

2024-03-21 11:23 UTC, gatzjames commented
Let's remove the external npm modules from this PR (lodash, moment etc) and merge the changes.
We can introduce those in another PR to have a conversation about external npm modules, bundling them and avoiding installing them in the app (shouldn't be accessible by renderer/main code)

2024-03-22 07:50 UTC, ihexxa commented
The external modules have been removed and I will set up another PR for external modules and then lets focus on it.

2024-03-22 11:23 UTC, marckong approved these changes, later dismissed
Giving a thumbs up for now to ship this feature, but I would say we should explore a path that uses packages installed in the user's operating system instead of shipping these modules in the Insomnia's executable package.

The reason is we cannot support all new modules with different versions that users request. We should probably allow them to select node runtime version and load the packages that are installed, so the Insomnia client is literally a shell that runs these javascript "files" instead. However, I understand this is quite difficult challenge to be tackled

2024-03-22 11:25 UTC, marckong commented
I am also still learning the context of pre-request feature implementation, so please consider this approval as a half.

2024-03-22 11:33 UTC, marckong commented on packages/insomnia-smoke-test/tests/smoke/pre-request-script-features.test.ts
> +        //         {
are these commented out for a reason?

2024-03-22 11:34 UTC, marckong commented on packages/insomnia-smoke-test/tests/smoke/pre-request-script-features.test.ts
> +            name: 'require the url module',
nit:

I am not a huge fan of table driven tests. They are not very explicit, and become hard to understand as it tends to create more abstraction. I'd rather have repetition on the tests and be very explicit.

2024-03-22 11:48 UTC, ihexxa commented on packages/insomnia-smoke-test/tests/smoke/pre-request-script-features.test.ts
> +            name: 'require the url module',
Updated

2024-03-22 11:48 UTC, gatzjames approved these changes

2024-03-22 12:02 UTC, merged

2024-03-22 13:29 UTC, ihexxa commented
The new PR has been create at: https://github.com/Kong/insomnia/pull/7198